### ISSUE TITLE
Metadata elements for chant fragments

### ISSUE THREAD

**Issue by mfeustle** [music-encoding/music-encoding#1041]
The immediate application I envision for the features proposed below would be their potential to link separated chant fragments, but broader applications seem possible. 

Texts in chant fragments are generally standardized enough to be recognizable, as a result of their specific liturgical function. It is therefore possible to determine what text would precede or follow what is present on a fragment with a great deal of confidence. 

The current options under the otherChar element, "follows" and "precedes," provide half of what is needed for automating the match of potential adjacent pages.

I'd like to propose the addition of four items, either as elements, or as attributes of the existing otherChar element:

begins-with
ends-with
follows-from
followed-by

These would identify a match when "begins with" matches "followed-by" or when "ends-with" matches "follows from."

For example, suppose we had a fragment from Vespers that cuts off in the middle of the singing of the Magnificat. Since the Latin text is standardized, we know that the words that conclude our hypothetical page, "Fecit potentiam in bracchio suo," will be followed on the next page by "Dispersit superbos mente cordis sui." 

Therefore, our page would have an "ends-with" of "Fecit potentiam in bracchio suo" and a "followed-by" that is "Dispersit superbos mente cordis sui."

Somewhere out there, there is a page that begins with "Dispersit superbos mente cordis sui," which follows from "Fecit potentiam in bracchio suo."

If we structure this data, we can isolate potential matches when "ends-with" matches "follows-from" or when "begins-with" matches "followed-by."

One variable that could be addressed by common practice is the length of these text samples. In the example above, five words suffice to set up a virtual "handshake" between disconnected, once-adjacent pages. 

I appreciate the consideration of this new feature request, and I hope it is useful in advancing discoverability of chant fragments.

**Comment by ahankinson** [comment]
Hi @mfeustle would you mind if I converted this to a [discussion](https://github.com/music-encoding/music-encoding/discussions)? I think it is worthwhile to discuss your approach and needs prior to making it an issue.

**Comment by mfeustle** [comment]
Sure, thanks!
