### ISSUE TITLE
Guidelines: outdated neumes documentation

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1049]
The [Guidelines](https://music-encoding.org/guidelines/v4/content/neumes.html#neumesNotation) still contain references to `ineume` and `uneume` elements although these were removed in MEI4.

**Comment by ahankinson** [comment]
I think the paragraph is supposed to reference the previous method and terminology (interrupted / uninterrupted) vs. the new (gapped / ungapped), since there is a reference to MEI 3 in there. So it's not necessarily outdated, but it can definitely be made clearer.

**Comment by fujinaga** [comment]
How about changing:
"... Morent 2011; MEI Guidelines, 6: Neume Notation, version 3.0), and now as gapped or not gapped (Behrendt, Bain, & Helsen 2017; MEI Guidelines, 6: Neume Notation, version 4.0)..."
to:
"...Morent 2011; MEI Guidelines 3, 6: Neume Notation), and now as gapped or not gapped (Behrendt, Bain, & Helsen 2017; MEI Guidelines 4, 6: Neume Notation)..."
