### ISSUE TITLE
Deployment of css

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1059]
It seems the guidelines lose the css file when being deployed. All the rules for `attributeUsage`, `attributeDesc`, etc. from the local build are missing online.

**Comment by musicEnfanthen** [comment]
Related to #959 

Will be (hopefully) fixed with the refactored build process.

**Comment by musicEnfanthen** [comment]
Just double-checked again on the website, and it seems that rules for `.specPage .attributeDef .attribute...` are applied in the online guidelines.

![Screenshot 2023-05-05 174601](https://user-images.githubusercontent.com/21059419/236505516-79480e85-80ac-4c5c-a32d-2410214bc898.jpg)

@rettinghaus Can you please check if this is still an open issue and if so, provide an example where the CSS is missing?

**Comment by rettinghaus** [comment]
Everything seems to be fine now. Maybe this was just an hiccup in the process …

**Comment by musicEnfanthen** [comment]
Great, thanks!
