### ISSUE TITLE
/addDef with `@ns="http://www.tei-c.org/ns/1.0"` in MEI basic

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#1067]
Two attribute definition (`xml:lang` and `curvedir`) in MEI basic have a `@ns="http://www.tei-c.org/ns/1.0"`, but no other one.

https://github.com/music-encoding/music-encoding/blob/1a62535e05a74ed781ace12d8f9d7760e4203c36/customizations/mei-basic.xml#L605

https://github.com/music-encoding/music-encoding/blob/1a62535e05a74ed781ace12d8f9d7760e4203c36/customizations/mei-basic.xml#L378

 Could somebody explain what their purpose is? Thanks

**Comment by rettinghaus** [comment]
Seems to be something coming from Oxygen (or another XML editor). It's just a redefinition of the root ns and should be deleted.

**Comment by bwbohl** [comment]
not exactly, because actually it adds the attributes with the tei-namespace but I agree that they should be removed.
