### ISSUE TITLE
Model of `<acquisition>`

### ISSUE THREAD

**Issue by doerners** [music-encoding/music-encoding#1072]
Recently I noticed that the model of `<acquisition>` is different from all other "history-like" elements now that #911 has been merged. In particular, `<acquisition>` is now the only element in this series that does not allow `<eventList>` as a child element, even though its model is based on the TEI [acquisition](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-acquisition.html) element which allows a TEI `<listEvent>` element. 

Is there an important reason for this that I am missing? 
Otherwise, I would suggest to just remodel `<acquisition>` after provenence.

**Comment by ahankinson** [comment]
> Otherwise, I would suggest to just remodel <acquisition> after provenence.

I think this sounds OK with me!
