### ISSUE TITLE
Change parsing instructions in Guidelines for note attributes

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#1079]
Referencing discussion #1071 , this statement in [Section 4.2.5.1.1](https://music-encoding.org/guidelines/dev/content/cmn.html#cmnNotesBasic) seems to be causing some confusion about how certain attributes are to be parsed and inherited.

"Because these attributes may not be required in all situations (such as `@dur` for the notes of a chord), processing software should anticipate retrieving the information that would have been provided by missing attributes from a preceding `<note>` or `<chord>` parent in the same `<layer>`. Only information from `@pname`, `@oct` and `@dur` attributes can be gathered in this fashion. No other attributes can be treated this way."

I propose that we simply delete this paragraph altogether, since it's pretty clear that inheriting these attributes from previous (peer) notes is highly problematic. 

The case for inheriting `@dur` on `<chord>` is made later in [Section 4.2.5.2.1](https://music-encoding.org/guidelines/dev/content/cmn.html#cmnChordsBasic) so I don't think we need to replace this.

**Comment by craigsapp** [comment]
That sounds good.

It may be useful to explain somewhere how such information could otherwise be linked  to previous elements, such as via `@corresp`.

**Comment by ahankinson** [comment]
Thanks @craigsapp !  I think this is probably covered [here](https://music-encoding.org/guidelines/dev/content/analysisharm.html#analysisDescribingRelationships)
