### ISSUE TITLE
build: improve classpath handling

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1084]
With the new v7.54.0 Release of the TEI Stylesheets, `classpath` can now be submitted to the ant-calls. This should be fixed as described in https://github.com/TEIC/Stylesheets/issues/544

**Comment by bwbohl** [comment]
also: the mei.classpath should be populated dynamically

**Comment by musicEnfanthen** [comment]
Fixed in 71beeb0 on pdf-guidelines-test branch
