### ISSUE TITLE
build: upgrade oxygen-patched-xerces

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1085]
oxygen-patched-xerces is now available in v25.0.0.0

**Comment by bwbohl** [comment]
as the versions of external dependencies occur at multiple locations in the ant file the version numbers could be provided as properties for central configuration capabilities.

**Comment by musicEnfanthen** [comment]
Yes, this is already implemented in the updated build process on the pdf-guidelines-test branch, isn't it?

**Comment by bwbohl** [comment]
Yes, you're right!
Makes me wonder whether we should merge that branch ASAP?

**Comment by musicEnfanthen** [comment]
Superseded by #1111
