### ISSUE TITLE
dynam not a member of att.color

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#1086]
I noticed that `<dynam>` has no `@color`. Any reason for not adding it?

**Comment by bwbohl** [comment]
As `@color` does not seem to be restricted to, e.g., transcriptional matters, I don't see a reason not to add it. Consequently, I wonder if there is a reason not to make `@color` globally available instead of confining its use to a selected set of elements. Following that path, Wouldn't it be desirable to capture all general aspects of rendition in the same place, i.e. the same attribute, for example, `@rend`.
I know `@rend` is also only available at a very few elements (`rend`, `del`) and derived from the allowed places of occurrence and available values, designed for encoding information on how text is being rendered. Nevertheless, its definition is not that restrictive: 

att.textRendition
>Attributes that record renditional characteristics.

rend Attribute
>Captures the appearance of the element’s contents using MEI-defined descriptors.

Ok, yes, the attribute class is att. **text** Rendition, but what is text anyway ;-)

So maybe allowing `color` on `dynam`, for now, could just be one first step towards a bigger change that has yet to be conceptualised?

**Comment by ahankinson** [comment]
If you look at [the values](https://music-encoding.org/guidelines/dev/data-types/data.TEXTRENDITIONLIST.html) for `@rend` it doesn't really make a whole lot of sense for non-text content -- What is a "small caps" dynamic marking, for example? :-D

+1 to `@color` on `<dynam>`.

**Comment by rettinghaus** [comment]
Essentially `@color` is not allowed on textual elements, because you can use `rend@color`. AFAICS the only inconsistency here is with `<reh>`, which allows `rend` children _and_ `@color`. So I'd rather remove it there than add it (only) to `dynam`.

-1 to `@color` on `<dynam>`.

**Comment by lpugin** [comment]
> AFAICS the only inconsistency here is with `<reh>`

No, there are others. For example `ornam`, or `octave`. It is also available on `verse`, which does not really makes sense if we follow your reasoning since then one would argue that you should use a `verse/syl/rend@color`.

> Essentially `@color` is not allowed on textual elements

Unless we allow it, as it is already in some cases ;-)

**Comment by craigsapp** [comment]
> `<reh>`, which allows rend children and `@color`

I presume that `reh@color` controls the color of the enclosure, while `reh/rend@color` controls the color of the contents inside the enclosure.

**Comment by rettinghaus** [comment]
The elements you listed are not textual elements, because they all can't contain rend elements.

**Comment by rettinghaus** [comment]
> I presume that reh@color controls the color of the enclosure, while reh/rend@color controls the color of the contents inside the enclosure.

rend@rend controls the enclosure.

**Comment by craigsapp** [comment]
I thought you were going to say something like that 😉  But checking with verovio, it is doing what I was thinking it does:

<img width="437" alt="Screenshot 2023-03-08 at 12 00 06 PM" src="https://user-images.githubusercontent.com/3487289/223834083-d94feb75-535f-4be6-adfe-19fcc44ea496.png">

The box around the text is specified by `rend@rend` as you say, but `rend@color` applies only to the text content, while `reh@color` controls the enclosure color:

```xml
<reh color="royalblue" staff="1" tstamp="0">
   <rend color="red" rend="box">A</rend>
</reh>
```


<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-03-08T11:59:29" version="3.16.0-dev-9aae300">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m2u0tju">
    <score xml:id="s1qr2p1n">
     <scoreDef xml:id="svl3vqu" midi.bpm="400.000000">
      <staffGrp xml:id="s178j2qr">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="c20ewme" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L5" right="end" n="2">
       <staff xml:id="staff-L5F1N1" n="1">
        <layer xml:id="layer-L5F1N1" n="1">
         <note xml:id="note-L6F1" dur="1" oct="4" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <reh color="royalblue" xml:id="ryoxxg3" staff="1" tstamp="0.000000">
        <rend xml:id="r1obq93d" color="red" rend="box">A</rend>
       </reh>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</detail>

**Comment by pe-ro** [comment]
`reh/@color` should control the color of the entire rehearsal mark, the enclosure as well as its content.  However, the `<rend>` element overrides this for its content.  In other words, if the `@color` attribute on `<rend>` element wasn't there, the "A" would be blue too.

**Comment by lpugin** [comment]
> The elements you listed are not textual elements, because they all can't contain rend elements.

They can contain text, so I would consider them textual elements. Unless there is a definition somewhere else?

**Comment by bwbohl** [comment]
I was rather thinking in the direction of:
* getting rid of `@color` everywhere
* making `@rend` or another attribute capturing such information globally available and extending its data model to be more like, e.g., https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.rendition.html. That is, to allow the encoding of appearance in some formal syntax, such as CSS.

**Comment by bwbohl** [comment]
Or even introduce something like `tei:rendition` that is used to define a rendition style centrally and is referenced with `@rendition` where applicable.

**Comment by pe-ro** [comment]
XML-based styling, as opposed to CSS, is something that's been brewing for a while now.  Something CSS-like would require parsing and enforcing a new syntax.  When the time is right; that is, when there's time and money to implement it, MEI style can move forward.  In the meantime, it's best not to make sweeping changes to `@color`, `@rend`, etc.

Returning to the comment that started this thread, `<dynam>` allows `<rend>`.  This is powerful mechanism that permits fine control over the color of a dynamic marking. For instance, different parts of a marking can be different colors.

```
<dynam>
  <rend color="red">m</rend>
  <rend color="blue">f</rend>
</dynam>
```
`@color` can be added to `<dynam>`, however, to control the color when the use of `<rend>` children is overkill.  `@color` on `<dynam>` would function the same as it does on `<reh>` (see my comment above.)

**Comment by bwbohl** [comment]
Can we agree on @pe-ro's proposal?

**Comment by rettinghaus** [comment]
Wouldn't that bring in another inconsistency? 
Allowing color on `dynam`, and not on `dir` and `tempo` seems to be a bad idea. But allowing it on every element is also not convincing.

**Comment by lpugin** [comment]
`dynam` is certainly different from other control events in the sense that it tacitly implies SMuFL font rendering. For example, `<dynam>pp</dynam>` is understood (and accepted) to be a shortcut for `<dynam><rend glyph.auth"smufl">pp</rend></dynam>`, and `<dynam>sempre pp</dynam>` a shortcut for `<dynam>sempre <rend glyph.auth"smufl">pp</rend></dynam>`

So looking down at complete consistency is not really meaningful in my opinion. I would find it clearer to allow `<dynam color="red">pp</dynam>` because if you do `<dynam><rend color="red">pp</rend></dynam>` then the SMuFL implied font rendering becomes less straightforward to understand and to process.

So I don't think adding `@color` to `dynam` is as much of a bad idea, and +1 on @pe-ro 's proposal.

**Comment by pe-ro** [comment]
Members of `att.event` and `att.controlEvent` don't get their color attribute from membership in these classes due to the fact that `@color` on some elements, such as `<space>`, would be nonsensical.  Members of these classes get their `@color` attribute from their own `att.[element name].vis` class.

So I suggest adding membership in `att.color` to `att.dynam.vis` along with a survey of all the other members of `model.event` and `model.controlEvent` to make sure `@color` is available wherever it makes sense.
