### ISSUE TITLE
Guidelines: neumes chapter contains escaped XML comment

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1088]
The guidelines chapter on neumes contains an escaped XML comment around the following `tei:gi` and graphic. I don't know if this actually should be commented out or if the `&lt;!--` and `--&gt;` can actually be deleted.

https://github.com/music-encoding/music-encoding/blob/1115f51d626b64fa30691e2f6850731e166b7fa9/source/docs/06-neumes.xml#L328-L331

**Comment by bwbohl** [comment]
@music-encoding/ig-neumes could anyone of you have a closer look, please?

**Comment by musicEnfanthen** [comment]
@fujinaga Do you accidentally know more about the purpose of these escaped comments?

**Comment by fujinaga** [comment]
The comment things \ can be removed.

**Comment by musicEnfanthen** [comment]
Thank you @fujinaga for the clarification.
