### ISSUE TITLE
Make invisibility attributes for clef and meterSig uniform

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#1096]
Currently `clef@visible` is defined, but `meterSig@visible` is not.  In verovio, to create an invisible time signature `meterSig@form="invis"` is currently being used.  It would be better to add `meterSig@visible` to make the attributes between the two elements uniform.

See https://github.com/rism-digital/verovio/issues/3365

**Comment by ahankinson** [comment]
We would also need to probably remove the `form="invis"` option, since it's not clear what "visible=True / form=invis" would mean.

**Comment by ahankinson** [comment]
Related to #987, #334 

In #987 @rettinghaus makes a case that both form and visible are necessary, but I don't really follow his reasoning. Perhaps he can explain more.

**Comment by craigsapp** [comment]
There are two types of invisibility in HTML/CSS: `display` and `visibility`.   MEI `clef@visible` is similar to CSS `display` and CSS `visibility` is less needed in MEI and can be handled in SVG renderings of MEI data.

**Comment by rettinghaus** [comment]
@ahankinson In #987 I talked about the separator sign in `meterSigGrp`, then `@form="invis"` would specify an invisible separator and `meterSigGrp@visible` would mark the whole thing. 

When having `meterSig@visible` we most likely don't need `form="invis"` anymore for `meterSig`.
