### ISSUE TITLE
Guidelines: neumes chapter still contains markdown syntax in bibliography

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1104]
In the bibliographic section of the "Neumes" chapter of the Guidelines, titles that should be italicized are still given in markdown, e.g. 

`Behrendt, Inga, Jennifer Bain, and Kate Helsen. 2017. “MEI Kodierung der frühesten Notation in linienlosen Neumen.” _Kodikologie und Paläographie im Digitalen Zeitalter 4 / Codicology and Palaeography in the Digital Age_. Vol. 4. `

This should be replaced by `<hi rend="italic">...</hi>`.

Also, the bibliographic references are placed as point `6.4.12` under `6.4 Samples of MEI encodings`. Would it make sense to move them to the top level as `6.5 Bibliographic references`? @fujinaga

**Comment by fujinaga** [comment]
Can you fix the italic issue, as I'm not sure the proper procedure for making the changes?
Yes, please move the references in 6.4.12 to 6.5. Thank you.

**Comment by musicEnfanthen** [comment]
Great, thanks. Yes, I can fix it, no problem!
