### ISSUE TITLE
build: upgrade ant library to Xerces 25.1.0.1

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1111]
https://github.com/music-encoding/music-encoding/blob/acb824ad8a50cbae0998a9ecd2dd8bbf1bcfb33e/build.xml#L53

**Comment by musicEnfanthen** [comment]
@bwbohl Yes, agree (since the docker file uses v25 as well). Do you want me to implement it in the build.xml?

**Comment by musicEnfanthen** [comment]
Related to #1085
