### ISSUE TITLE
add @unit to <surface>?

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#113]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on September 18, 2012 15:20:31_

Currently, it's possible to specify the coordinate space for <surface>, but no way to say what units this space is measured in.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=113_

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on June 12, 2014 14:18:10_

**Labels:** -Priority-Medium Priority-Low

**Comment by pe-ro** [comment]
The dimensions of the members of att.coordinated (surface, symbolDef, and zone) are _abstract_; that is, they are agnostic about their real-life dimensions.  Therefore, no unit attribute is necessary.
