### ISSUE TITLE
Update copyright / license dates

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#1144]
Most of the copyright and license dates currently say 2017 / 2018, etc. Before the 5.0.0 release we should update these dates.

**Comment by bwbohl** [comment]
Do you have an overview of whether there are copyright and license statements in all our files? From my point of view, we should have this, at least in the released version. This could be done on build with ant, which would require a template license with a year placeholder that can be automatically replaced by the current year / date. Afterwards and could automatically insert it at the top of the files. Not too complicate, done this before ;-)

**Comment by rettinghaus** [comment]
TEI keeps in every file this small statement:

```xml
<!--
Copyright TEI Consortium. 
Dual-licensed under CC-by and BSD2 licences 
See the file COPYING.txt for details.
$Date$
$Id$
-->
```

Maybe we could do something similar?

Also note that our guideline files are missing the XML declaration.

**Comment by ahankinson** [comment]
I've added the notice manually for now in #1163; we may add the template later, but this is probably a prerequisite to that.
