### ISSUE TITLE
Warnings from Verovio and Prince on live rendered example file

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1146]
The file `source/examples/verovio/tempo-01.mei` ([line 46](https://github.com/music-encoding/music-encoding/blob/develop/source/examples/verovio/tempo-01.mei#L46)) triggers a warning when rendered with Verovio to be included in the guidelines during the build process:

`[Warning] Using rend@fontname with 'VerovioText' is deprecated. Use 'rend@fontfam="smufl"' instead`

Would simple replacement be sufficient, or would we need to add the font-family "smufl" to the [source/assets/css/print/fonts.css](https://github.com/music-encoding/music-encoding/blob/develop/source/assets/css/print/fonts.css) as well, @kepper?

The same file and line are triggering another warning in Prince, since the used unicode for the half note in the tempo indication is not correctly resolved. Is there a better way to do it with SMuFL, @lpugin ?

**Comment by bwbohl** [comment]
So we should fix our examples in the guidelines to use `rend/@glyph.auth`, cf. #1142
