### ISSUE TITLE
Change "isoschematron" to "schematron"

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#1158]
Currently the value of "isoschematron" gives us validation errors in our source since it has been changed in the TEI stylesheets. So we should update our source files to change all values of "isoschematron" to "schematron".

**Comment by ahankinson** [comment]
Looking at this more: In the source code we have the following declaration: 

```xml
<?xml-model href="../validation/mei_odds.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

That is, we point to our own `mei_odds.rng` file, which doesn't flag `isoschematron` as wrong. But in the customizations we use:

```xml
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

Where we point to the TEI's definition for schematron, which raises the value of `isoschematron` as an error.

So which of these two should we use? @bwbohl ?

(Using the TEI version also flags several other things as wrong in the source as well...)

**Comment by bwbohl** [comment]
Please pick the mei_odds as this is pre-pure-odd. A pure-odd transition should be tackled by MEI but that needs more time than we have before the planned release.
