### ISSUE TITLE
build: describe the available ant targets

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1166]
The BUILD_COMMANDLINE.md should describe the available ant targets that can be used to build any of the MEI artifacts. Users should not have to look up the targets from the build.xml file.

**Comment by bwbohl** [comment]
probably we should use `@description` on the targets which will be printed to the terminal as a list when you run `ant -p`?

**Comment by musicEnfanthen** [comment]
@bwbohl Thanks.

Yes, that could be helpful. Can you open another issue for that, please?
