### ISSUE TITLE
Inconsistency in data type nomenclature

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1173]
By reviewing #1157 , it appeared that there are different styles of nomenclature for the data types. We have:

- [data.ACCIDENTAL.GESTURAL](https://music-encoding.org/guidelines/dev/data-types/data.ACCIDENTAL.GESTURAL.html) (plus[data.ACCIDENTAL.GESTURAL.basic](https://music-encoding.org/guidelines/dev/data-types/data.ACCIDENTAL.GESTURAL.basic.html) and [data.ACCIDENTAL.GESTURAL.extended](https://music-encoding.org/guidelines/dev/data-types/data.ACCIDENTAL.GESTURAL.extended.html))
- [data.DURATION.gestural](https://music-encoding.org/guidelines/dev/data-types/data.DURATION.gestural.html)
- [data.PITCHNAME.GES](https://music-encoding.org/guidelines/dev/data-types/data.PITCHNAME.GES.html)

While there is nothing wrong with it in the sense that it works, we should consider consolidating those names some day.

**Comment by bwbohl** [comment]
While #1181 proposes to fix all variants of gestural datatypes to `.GESTURAL` I wonder if some other suffixes (`.cmn`, `.mensural`, `.pat` etc.) should also be ’fixed’?

**Comment by rettinghaus** [comment]
@bwbohl Could you propose a scheme? Should everything be `data.UPPER.UPPER.UPPER`? Or just "official" customization/module names like `CMN`?

**Comment by ahankinson** [comment]
Hm. I moved this to the v5 milestone because I thought it would be addressed with #1181. Renaming all the data classes sounds like a post-v5 task, so I would suggest @bwbohl 's comment (and following discussion) be filed as a separate issue.

**Comment by bwbohl** [comment]
We can go that way and make that a v6 issue, or we can fix it for v5

**Comment by bwbohl** [comment]
@pe-ro & @kepper has there been an "official" naming-scheme in the past?

**Comment by pe-ro** [comment]
The general pattern for datatypes is data.UPPERCASE.lowercase.  The 3rd part of the name functions as a qualifier, sometimes by repertoire, sometimes signifying membership in a higher order class, sometimes for distinction between two similarly named datatypes that couldn't be differentiated by name alone.

The exceptions to this that I could find with a quick visual scan are data.OCTAVE.DIS, which I would rename to data.OCTAVEDIS, and data.PERCENT.LIMITED and data.PERCENT.LIMITED.SIGNED, which can be renamed to data.PERCENT.limited and data.PERCENT.limited.signed (or data.PERCENT.limitedsigned), respectively.  It would be good to search for other exceptions with a regex.

In the case of note head modifier datatypes, data.NOTEHEADMODIFIER.list can be renamed as data.NOTEHEADMODIFIERLIST, and data.NOTHEADMODIFIER.pat can be renamed to data.NOTHEADMODIFIERPATTERN with no ill effects.

**Comment by rettinghaus** [comment]
Closing this one as the specific issue has been solved. @bwbohl Please open a new one for post-v5.

**Comment by bwbohl** [comment]
> The general pattern for datatypes is data.UPPERCASE.lowercase. The 3rd part of the name functions as a qualifier, sometimes by repertoire, sometimes signifying membership in a higher order class, sometimes for distinction between two similarly named datatypes that couldn't be differentiated by name alone.

@pe-ro :
So for absolute consistency, it shoud be:

data.ACCIDENTAL.mensural
data.ACCIDENTAL.mensural.basic

etc. right?

Nevertheless, we have a local consistency with #1181 now. Thx @rettinghaus !
As there is no sense in fixing the others in a rush, I added the new issue #1194 to the [MEI 6  Milesonte](https://github.com/music-encoding/music-encoding/milestone/16)

**Comment by pe-ro** [comment]
@bwbohl, 

> So for absolute consistency, it shoud be:
> 
> data.ACCIDENTAL.mensural
> data.ACCIDENTAL.mensural.basic
> 
> etc. right?

that's correct.
