### ISSUE TITLE
XML snippets throw java errors

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1175]
We parse coding examples as `text`, so brackets are converted to HTML name encodings (`&lt;` `&gt;`) in the canonicalized xm. What follows are endless java errors:

`ERROR: Unable to parse the following XML snippet, which is apparently not well-formed:`

Parsing them as `xml` doesn't work, because the snippets are actually not well-formed. Any ideas?

**Comment by musicEnfanthen** [comment]
I recognized this behaviour the first time with the changes in https://github.com/music-encoding/music-encoding/pull/1148#issuecomment-1563276012. 

Beside the other changes that removed the warnings from the Verovio image generation step, it introduced these Java errors. Maybe the XML declaration added to the beginning of the files causes this?

`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by musicEnfanthen** [comment]
OK, when I remove the XML declaration, all the parsing errors are gone.

What's left is a warning: `WARNING: Unable to retrieve definition of element rend&gt;. No link created. Please check spelling?`

Not sure though where this rend is coming from?

**Comment by musicEnfanthen** [comment]
Furthermore, the code snippets are rendered correctly again, cf. #1177. Preparing a PR that removes the declarations.

**Comment by musicEnfanthen** [comment]
Found the reason for the `rend&gt;` warning above. Preparing another PR.
