### ISSUE TITLE
Code rendering is broken in the Guidelines

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#1177]
For example: https://music-encoding.org/guidelines/dev/content/shared.html#sharedAccidentalsArticulations

The code examples are being rendered as text, not as XML. Maybe this is connected with #1175?

**Comment by kepper** [comment]
Scrolling around that page, this seems to affect only those examples that are to be rendered with Verovio, not the other examples on the same page.

**Comment by musicEnfanthen** [comment]
Yes, that is obviously connected to #1175. Following on there.
