### ISSUE TITLE
Add description to ant targets

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1187]
The ant target offer documentation via `@description`. We should properly document the targets there

**Comment by rettinghaus** [comment]
@bwbohl Looks like most targets have a `@description` already. Please specify if you expect _every_ target to have one or what else would be sufficient.

**Comment by bwbohl** [comment]
We can decide this after the MEI 5.0. targets with a description attribute are considered main targets in an ANT project, so no, not every target should have one. But we should have a closer look at this, and on how targets can get documentation if they are not considered main targets.
