### ISSUE TITLE
build: only run prince if command found

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1201]
When running the `dist` target locally without having Prince XML installed, the build-guidelines-pdf subtask fails. Maybe this should fail more gently, e.g., by adding console feedback or adding a text file describing the reason. Or maybe the dist, or init targets should precheck for Prince XML, too?

**Comment by rettinghaus** [comment]
Do we want the PDF to be build always locally? I'm less in favor of a precheck, just skip the step if Prince XML isn't there.

**Comment by bwbohl** [comment]
that's exactly what this ticket is for. At the moment prince will always be called and consequently, if not present on the host system the build will fail. the PR is almost ready.
