### ISSUE TITLE
Ampersands indicating attributes missing in PDF

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1227]
Within the main text all attributes lost their ampersand.
  
![Bildschirmfoto 2023-06-16 um 16 22 04](https://github.com/music-encoding/music-encoding/assets/7693447/fdbb291a-a3fe-494e-a23e-047dced53414)

**Comment by musicEnfanthen** [comment]
@rettinghaus You mean the @ symbol, right?

PR is on the way, a css rule was missing.
