### ISSUE TITLE
tidy repository

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1240]
Merged branches keep piling up and nobody seems to care. @music-encoding/technical-team-co-chairs please delete merged/outdated branches from the repo. 

GitHub may help with this if you turn on the feature in the settings:

![image](https://github.com/music-encoding/music-encoding/assets/7693447/21fd22d4-f1f4-47b6-8da1-f350f281e9c3)

**Comment by musicEnfanthen** [comment]
Thanks @rettinghaus, valid point. During the release preparation we are trying to avoid automatic deletion but it is something we should consider after the release. We are checking manually for some branches that can be safely deleted (as we did before, so yes, we care ;)  ).

Please note that we have between 25 and 35 open PRs at the moment which quite increases the number of branches.

**Comment by rettinghaus** [comment]
Yes, but 10 from @lpugin and myself, and we properly forked it. ;-)

**Comment by ahankinson** [comment]
Can this be closed now?
