### ISSUE TITLE
generated schemata invalid due to duplicate attributes

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1260]
in all schemata `@func` on elements:
* pgHead
* pgFoot

in mei basic `stem.dir` on element:

* chord

**Comment by musicEnfanthen** [comment]
pinging @lpugin

**Comment by bwbohl** [comment]
The `@func` was unintentionally reintroduced with the merge of #1157 .

**Comment by bwbohl** [comment]
The duplicate `@stem.dir`on `<chord>` in the mei-basic customization is due to the direct membership of `<chord>` in `att.stems` and the inherited membership to it through membership in `att.chord.vis`.

**Comment by bwbohl** [comment]
I will prepare a fix for both de-duplications.
