### ISSUE TITLE
<application> should be allowed in in-line text

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#127]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on October 08, 2012 19:25:23_

It is often useful to markup the name of an application in text.

<application> should be placed in the shared module since it is used in  meiHead and in text.  It should also be added to the model.nameLike class.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=127_

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on June 11, 2014 13:28:41_

**Labels:** -Priority-Medium Priority-Low

**Comment by pe-ro** [comment]
In the latest schema, `<name>` provides suggestions for `@type`, one of which is "process", which can be applied to software application names.
