### ISSUE TITLE
`@lform` and `lwidth` removed from `ending` in MEI Basic

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#1273]
It seems that [this](https://github.com/music-encoding/music-encoding/pull/1157) PR removed the attributes in MEI-Basic.

I tried to understand what happened but narrowing down to which PR caused the change is all I could do.

Any thoughts?

**Comment by musicEnfanthen** [comment]
Thanks @lpugin for catching this. 

It seems that the commit dd345d25b8c5814486ae34165d476ccf143860b4 in PR #1157 replaced the direct `lform` and `lwidth` attributes in `att.lineRend.base` with membership in `att.curveRend` (which contains those two attributes). In consequence, elements like `ending` could access those attributes only via `att.curveRend` but that class was deleted in MEI basic.
