### ISSUE TITLE
anyStart throws schematron warnings for required ancestor, e.g. `heraldry`, `watermark`, `locus`

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1276]
The `heraldry`, `watermark`, `locus` have Schematron rules testing for an ancestor `physDesc`. While this is true in a complete `meiHead`, it does not make sense in the anyStart schema if a files starts below the `physDesc` (e.g., in the sample-encodings collection).
There might be other elements with parent or ancestor checks in Schematron rules.
There are alternative solutions:
* remove those Schematron checks in the anyStart customisation
* rework them in the customisation to not throw an error but a warning or info
* rework them generally to warning or info level.

Is there no other way for those three elements mentioned to ensure they are only used in `physDesc`?
What would be an easy solution for MEI 5?
Opinions? Especially from @music-encoding/ig-metadata?

**Comment by musicEnfanthen** [comment]
For reference see, e.g., the files in https://github.com/music-encoding/sample-encodings/tree/main/MEI_4.0/Header/Watermark

**Comment by pe-ro** [comment]
Making these elements members of model.msInline and then restricting their presence to physDesc doesn't make sense.  I say we remove the Schematron rules for these elements and rely on encoders to do the right thing.

**Comment by riedde** [comment]
I'm also irritated that, e.g., `<watermark>` appears nearly everywhere and is then restricted to a specific point. Overthinking the model membership could also be a solution.

If a change with minimal impact is preferred I will vote for deleting the schematron rule in the anyStart schema.

**Comment by pe-ro** [comment]
The members of model.msInline have a two-fold function.  They may contain a description (as when they're used in the header) or they can mark the presence of a textual feature (when used inline).  There's no way to predict where in the text the second  function may be invoked, so I prefer to  remove the Schematron rule from all customizations, including mei-all.  The result will be no worse than the situation created by any of the already-existing inline elements.

**Comment by pe-ro** [comment]
I'm inclined to leave in place other Schematron rules that may be violated by the anyStart customization.  Common sense should guide the user to ignore violations that no impact.  The primary function of the anyStart customization is to validate a document tree starting at a node that is not normally a document node.  Obviously, rules that apply to ancestors or siblings will be violated and should be ignored.

**Comment by riedde** [comment]
@pe-ro I understand your point and you are right that people should be able to handle this. But technically it is a bit more difficult. If the schematron rules return an error the validation fails (or could fail, depending on the validation process). However, if the code is valid this shouldn't be counteracted by schematron rules.

**Comment by pe-ro** [comment]
Having reviewed this issue more carefully, I suggest that `<watermark>` be removed from model.msInline.  This will restrict its use to `<physDesc>` (via model.physDescPart) and make the Schematron rules that pertain to it unnecessary.

Just removing the Schematron rules pertaining to the others is the easiest solution.

**Comment by pe-ro** [comment]
Just noticed this issue is closed.  Presumably (I haven't checked), the Schematron rules were dropped.  I'd still propose removing `<watermark>` from model.msInline.

**Comment by riedde** [comment]
I support @pe-ro's suggestion. Because of the fact that `<watermark>` is allowed 'nearly everywhere' made me already thinking of revising some data models. But that will be obsolete, if it is as easy as @pe-ro says.

**Comment by bwbohl** [comment]
I'm inclined to move this back to milestone MEI 5.0 and close the issue because the primary problem described by this issue was solved, and there’s a new issue for remodeling the class memberships of `watermark`. But have you guys also checked the other elements (`heraldry` and `locus`) to see whether changes are necessary there, too?

**Comment by ahankinson** [comment]
Why not keep it at 6?

**Comment by bwbohl** [comment]
> Why not keep it at 6?

The Schematron checks have been removed in v5 the issue is resolved
