### ISSUE TITLE
implement customization-specific version numbers with suffix

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1290]
e.g., mei-basic in the dev version implements `5.0.0-dev+basic` at the moment. This is a good idea, because it definitely tells which customization was used when creating a file, and there might be cases when a customization allows things that would not be valid against mei-all.

**Comment by bwbohl** [comment]
- [ ] 5.0+basic
- [ ] 5.0+neumes
- [ ] 5.0+mensural
- [ ] 5.0+cmn
- [ ] *anyStart:* 5.0+anyStart
- [ ] *all:* 5.0

All should additionally allow `5.0`

**Comment by musicEnfanthen** [comment]
Closed with #1319
