### ISSUE TITLE
Using SMuFL noteheads on MEI

### ISSUE THREAD

**Issue by faelwar** [music-encoding/music-encoding#1312]
I'm not sure if here is the correct place to post this type of question. If not, please let me know.

I'm trying to use the Ornate X notehead (E0AA) on my notation and I can't figure out how to do it. I have try the following ways but I have hadn't any success on this. Can someone please help me?

```
<note oct="5" pname="b" glyph.auth="smufl" glyph.num="#xE0AA" />
<note oct="5" pname="b" glyph.name="noteheadXOrnate" />
```

For testing the rendering I have been using mei-friend (https://mei-friend.mdw.ac.at/)

Thanks for helping me

**Comment by rettinghaus** [comment]
Correct encoding would be: 
`<note oct="5" pname="b" head.auth="smufl" head.shape="#xE0AA" />`

But I guess Verovio isn't supporting this (yet).

**Comment by faelwar** [comment]
Thanks For the explanation! Really Appreciated!
