### ISSUE TITLE
MEI Basic: unclear status of attribute classes

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1314]
The following attribute classes are explicitly added to some elements in the MEI Basic customization, although they are deleted from the schema:

- att.bibl
- att.metadataPointing
- att.measure.log 
- att.measure.vis
- att.responsibility

It needs to be decided wether these should be actually available or not. 
This is a follow up to #1313.

**Comment by bwbohl** [comment]
Good catch @rettinghaus

# att.bibl

## status deleted

## attributes

* `@analog`

## members

* meiHead
* fileDesc
* date
* pubStmt 

# att.metadataPointing

## status

deleted

## attributes

* `@decls`

## members

* measure
* music
* staffGrp

# att.measure.log

## status

included through module MEI.cmn

## attributes

* att.alignment
  * `@when` [N.B. temporal alignment]
* att.meterConformance.bar (customised)
  * `@metcon`

## members

* measure

# att.measure.vis

## status

deleted

## attributes

* att.barring ( deleted – `@bar.len`, `@bar.method`, `@bar.place`)
* att.width (`@width`)

## members

* measure

# att.responsibility

## status

deleted

## attributes

* `@resp`

## members

* meiHead

**Comment by bwbohl** [comment]
@lpugin and @kepper could you have a look, please?

**Comment by lpugin** [comment]
Except for `measure.log` (which does not seem to be deleted?) I think they can be removed from the elements where they are added again.

**Comment by musicEnfanthen** [comment]
Fixed in #1320
