### ISSUE TITLE
Rest positioning in MEI Basic

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1324]
Currently it is only possible to change the vertical position of rests by adding an offset in `@vo`. This feels weird, as the common way to do this in MEI, MusicXML, Humdrum and Lilypond is to add pitch information to the rest. 

As MEI Basic tries to keep ["features, that falls in the range of other encoding formats and thus allows an easier transformation"](https://music-encoding.org/update/2019/05/31/mei-basic-first-draft.html), `att.staffLoc` and `att.staffLoc.pitched` should be available in MEI Basic.

**Comment by ahankinson** [comment]
Basic also “intends to simplify MEI so that every feature can only be expressed in one specific way” so we should agree on a solution doesn’t unnecessarily multiply the ways of encoding this.

**Comment by lpugin** [comment]
From your explanation, it seems that only `att.staffLoc.pitched` would be enough. Could you explain further why you want to have both `att.staffLoc` and `att.staffLoc.pitched`?

**Comment by rettinghaus** [comment]
Both were previously added to `rest`, but I agree that the latter one is sufficient.
