### ISSUE TITLE
build: properly handle element descriptions

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1343]
Currently we loose text of subelements in the [Guidelines](https://music-encoding.org/guidelines/v5/content/metadata.html#headerrespstatement), because we only handle the `text()` in `generatewebsite.xsl`.

<img width="149" alt="image" src="https://github.com/music-encoding/music-encoding/assets/7693447/bb723ad6-81fa-4a41-a41e-177344ce48bc">

**Comment by bwbohl** [comment]
thx for spotting
