### ISSUE TITLE
Add a new `@edtfdate` attribute to the att.datable class

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#1349]
A recent discussion on the TEI mailing list about representing ambiguous dates and date ranges leads me to suggest adding a new `@edtfdate` attribute to the att.datable class.

```
<classSpec ident="att.datable" module="MEI.shared" type="atts">
  <desc xml:lang="en">Attributes using to provide dates.</desc>
  <attList>
    <attDef ident="normal">
      <desc xml:lang="en">Provides the value of a textual date using an Extended Date Time
        Format (EDTF) expression. EDTF is particularly useful for representing ambiguous
        and/or under specified dates, as well as non-consecutive date ranges. For more
        details, see <ref target="https://www.loc.gov/standards/datetime/"
          >https://www.loc.gov/standards/datetime/</ref></desc>
      <datatype>
        <rng:data type="string"/>
      </datatype>
    </attDef>
    <attDef ident="enddate" usage="opt">
      <desc xml:lang="en">Contains the end point of a date range in standard ISO
        form.</desc>
      <datatype>
        <rng:ref name="data.ISODATE"/>
      </datatype>
    </attDef>
    <attDef ident="isodate" usage="opt">
      <desc xml:lang="en">Provides the value of a textual date in standard ISO
        form.</desc>
      <datatype>
        <rng:ref name="data.ISODATE"/>
      </datatype>
    </attDef>
    <attDef ident="notafter" usage="opt">
      <desc xml:lang="en">Contains an upper boundary for an uncertain date in standard ISO
        form.</desc>
      <datatype>
        <rng:ref name="data.ISODATE"/>
      </datatype>
    </attDef>
    <attDef ident="notbefore" usage="opt">
      <desc xml:lang="en">Contains a lower boundary, in standard ISO form, for an
        uncertain date.</desc>
      <datatype>
        <rng:ref name="data.ISODATE"/>
      </datatype>
    </attDef>
    <attDef ident="startdate" usage="opt">
      <desc xml:lang="en">Contains the starting point of a date range in standard ISO
        form.</desc>
      <datatype>
        <rng:ref name="data.ISODATE"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```

**Comment by rettinghaus** [comment]
As you can represent all the attribute values within an EDTF expression, I'm wondering why these should be here. On the other hand: EDTF is part of the ISO standard for some years now, so my expectation would be to extend @isodate to be capable to hold also ISO dates form level 1 and 2. 
See also https://github.com/TEIC/TEI/issues/2249

**Comment by ahankinson** [comment]
+1 to @rettinghaus' suggestion -- an EDTF date is an ISO 8601 format, just with additional syntax, so extending `data.ISODATE` to accommodate EDTF dates will also still work with "plain" 8601 dates.

**Comment by pe-ro** [comment]
I thought about creating a new attribute called "normal" that would allow ISO level 1 and EDTF-style expressions.  The problem is, however, that ISO level 1 values are relatively easy to parse/validate, while EDTF values are not.  I'm unaware of any validators for EDTF other than the one I wrote in Schematron/XSLT.  The problem with that one is that it runs to several thousand lines!

So, I thought it best, at least in the short term, to leave the ISO cluster of attributes intact and just add an extra attribute for EDTF values.

**Comment by ahankinson** [comment]
> I'm unaware of any validators for EDTF other than the one I wrote in Schematron/XSLT. The problem with that one is that it runs to several thousand lines!

I wonder if TEI will run into the same problem and, if so, would they want to work together on a shared data type that can be used by both?

**Comment by ahankinson** [comment]
> So, I thought it best, at least in the short term, to leave the ISO cluster of attributes intact and just add an extra attribute for EDTF values.

Won't we still have the problem that we also can't validate the values in `@edtfdate`?

**Comment by pe-ro** [comment]
Yes, there will still be a validation problem for EDTF, but the ISO level 1 dates won't be affected.

**Comment by ahankinson** [comment]
Given that it seems there's movement on the TEI side to support EDTF dates, I'd be inclined to say we can wait / participate in any efforts there, and add EDTF support to MEI when we can properly support it in both? This seems preferable to adding an attribute that will become redundant later on once our dates are both level 1 and 2 capable.

**Comment by pe-ro** [comment]
OK, it can wait.

**Comment by pe-ro** [comment]
Closing for now.

**Comment by ahankinson** [comment]
I've added a follow-up issue so that we don't lose track of the requirement.
