### ISSUE TITLE
Add "not" to the definition of `@optimize="true"`

### ISSUE THREAD

**Issue by cividini** [music-encoding/music-encoding#1377]
Am I wrong, or is the definition of `@optimize="true"` in the MEI guidelines wrong? According to the MEI guidelines (versions 3, 4 and 5.0 checked): "when the value is 'true', empty staves **are displayed**." But it should be the other way round: "when the value is 'true', empty staves are **not** displayed **[i.e. hidden, 'optimized']**." 

In Verovio it is rendered correctly the other way round (example from W. A. Mozart, String Quartet K. 168/4, empty staves in the cello at the beginning, MEI-code downloadable in: https://dme.mozarteum.at/movi/navigator/168/004/01/nma):

- empty staves (cello from m. 6) are **not** displayed, when `@optimize="true"`:

<img alt="KV_168_04_01_optimize" src="https://github.com/music-encoding/music-encoding/assets/45197272/8c00f16e-b632-4cb2-b400-329f842dd3f3" width="500"/>
//
<img alt="KV_168_04_06_optimize_true" src="https://github.com/music-encoding/music-encoding/assets/45197272/b06e03f6-a1f1-43a1-a019-d016f088861c" width="500"/>

- empty staves (cello from m. 6) are displayed, when `@optimize="false"`:
<img alt="KV_168_04_01_optimize" src="https://github.com/music-encoding/music-encoding/assets/45197272/8c00f16e-b632-4cb2-b400-329f842dd3f3" width="500"/>
//
<img alt="KV_168_04_06_optimize_false" src="https://github.com/music-encoding/music-encoding/assets/45197272/e99ae230-2e55-4c83-8212-7d729370b8db" width="500"/>

I think the word "not" was just left out in the definition...

**Comment by pe-ro** [comment]
I think you're right -- the word "not" is missing from the definition of `@optimize`.

**Comment by bwbohl** [comment]
@cividini many thanks for spotting this ;-)

**Comment by bwbohl** [comment]
MEI v2.1.1
> indicates whether staves without notes, rests, etc. should be displayed. When the value is 'true', empty staves are displayed

MEI v2.0.0
> indicates whether staves without notes, rests, etc. should be displayed. When the value is 'true', empty staves are displayed.

Makes this date back to 2012 at least.
