### ISSUE TITLE
Allow `@vgrp` on `<harm>` and other `<dir>` derivative elements

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#1379]
The `@vgrp` attribute allows one to group individual directive-like elements on their vertical offset without having to specify the exact amount of offset.  For example, when a set of `<dir>` elements is grouped ; that is, they all have the same value for `@vgrp`, then a renderer should place them all at the same height above/below the staff they pertain to.

The current members of att.verticalGroup are: attacca, dir, dynam, hairpin, pedal, repeatMark, and tempo.  Additional members to be added under this proposal are: harm, breath, fermata, fing, and fingGrp.

**Comment by bwbohl** [comment]
I think, it's a good idea to allow `@vgrp` on those elements

**Comment by lpugin** [comment]
Verovio currently aligns `harm` based on their `@n`. It would not be a problem also to support `@vgrp`.

**Comment by pe-ro** [comment]
Addressed in #1472

**Comment by musicEnfanthen** [comment]
Fixed in #1472. Closing.
