### ISSUE TITLE
Wording for attributes with valList type="semi"

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#1382]
From #1381, split into a separate issue for @pe-ro.

[Context: @ahankinson observed that `<line@func>` has the wording "Allowed values" suggesting that this was a closed list, when in fact it was a semi-closed list and can allow any value.]

... using `valList/@type="semi"` to generate the text "Suggested values are:" [in the Guidelines].

_Originally posted by @pe-ro in https://github.com/music-encoding/music-encoding/discussions/1381#discussioncomment-7319849_

**Comment by musicEnfanthen** [comment]
That's nice that you spotted the only semi closed list that we have in the specs :D

Provided a PR to handle this.
