### ISSUE TITLE
Dynamics @place and @staff possible values

### ISSUE THREAD

**Issue by davidrizo** [music-encoding/music-encoding#1411]
The explanation of the `@place` attribute in the `dynam` element is not including the value `between` that is used in the last example of the [section](https://music-encoding.org/guidelines/dev/content/cmn.html#cmnDynam):

```xml
<dynam tstamp="1" tstamp2="2m+1" extender="true" place="between" staff="1 2">dim.</dynam>
```

**Comment by bwbohl** [comment]
thanks for spotting this

**Comment by musicEnfanthen** [comment]
Transfering this issue to the main repo.
