### ISSUE TITLE
Issue with listing 128 at the Guidelines MEI 5.0

### ISSUE THREAD

**Issue by ElGuilles** [music-encoding/music-encoding#1430]
Whole encoding question can be found here  https://github.com/music-encoding/music-encoding/blob/develop/source/examples/verovio/04-score-redefinition.mei (chapter 4.2.4: https://music-encoding.org/guidelines/dev/content/cmn.html#cmnReDef), at listing 128. 

Firstly, the numbering scheme of the measures seems disorganized to me (the first measure is labeled as "1," the second as "4," then after the three rest measures, the next one is labeled as "5"...). Secondly, regarding the accidentals in the first chord, why is C flat? And finally, why is it possible to hold a whole chord in the third measure within a "cut" measure bar? These are examples of cases that happened more than once. I hope you can help me.

Here you have the extract of the code I am refering to, y marked with **these** symbols the examples I talk about above.

<music>
    <body>
      <mdiv>
        <score>
          <?edit-start?>
          <scoreDef keysig="4f" meter.sym="common">
            <staffGrp>
              <staffDef n="1" lines="5" clef.shape="G" clef.line="2" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure right="dbl" n="1">
              <staff n="1">
                <layer n="1">
                  **<chord dur="1">**
                    <note oct="4" pname="a" accid.ges="f" />
                    <note oct="5" pname="c" **accid.ges="f"** />
                    <note oct="5" pname="e" accid.ges="f" />
                  </chord>
                </layer>
              </staff>
            </measure>
            <scoreDef keysig="0" keysig.cancelaccid="none" />
            <measure right="dbl" **n="4"**>
              <staff n="1">
                <layer n="1">
                  <chord dur="1">
                    <note oct="4" pname="a" />
                    <note oct="5" pname="c" />
                    <note oct="5" pname="e" />
                  </chord>
                </layer>
              </staff>
            </measure>
            <scoreDef keysig="2s" keysig.cancelaccid="before" meter.sym=**"cut"** />
            <measure n="2">
              <staff n="1">
                <layer n="1">
                  **<chord dur="1">**
                    <note oct="4" pname="b" />
                    <note oct="5" pname="d" />
                    <note oct="5" pname="f" accid.ges="s" />
                  </chord>
                </layer>
              </staff>
            </measure>
            <measure right="dbl" n="3">
              <staff n="1">
                <layer n="1">
                  <multiRest num="3" />
                </layer>
              </staff>
            </measure>
            <scoreDef keysig.visible="false" keysig="5f" meter.count="4" meter.unit="4" />
            <measure right="dbl" n="5">
              <staff n="1">
                <layer n="1">
                  <chord dur="1">
                    <note oct="4" pname="g" />
                    <note oct="4" pname="b" accid.ges="f" />
                    <note oct="5" pname="d" />
                  </chord>
                </layer>
              </staff>
            </measure>
            <scoreDef keysig="2s" keysig.cancelaccid="before-bar" />
            <measure right="end" n="2">
              <staff n="1">
                <layer n="1">
                  <chord dur="1">
                    <note oct="4" pname="b" />
                    <note oct="5" pname="d" />
                    <note oct="5" pname="f" accid.ges="s" />
                  </chord>
                </layer>
              </staff>
            </measure>
          </section>
          <?edit-end?>
        </score>
      </mdiv>
    </body>
  </music>
</mei>

**Comment by rettinghaus** [comment]
A "cut" measure bar says there are two half notes, which equals a whole, see https://en.wikipedia.org/wiki/Alla_breve.

**Comment by rettinghaus** [comment]
Unfortunately there is now an issue with formatting the listing.

**Comment by musicEnfanthen** [comment]
Strange. 

It seems that the only change in PR #1431 that might have caused this issue could be the added XML processing instruction at the file beginning. None of the other mei examples has such a processing instruction, except for editorial_example.mei which seems to be used nowhere: https://github.com/search?q=repo%3Amusic-encoding%2Fmusic-encoding+editorial_example.mei&type=code

**Comment by rettinghaus** [comment]
The problem was, that 

1. there was an XML declaration
2. inside the processing instructions there were two elements on the same level, leading to a "not well-formed" XML

**Comment by musicEnfanthen** [comment]
@ElGuilles The issue should be fixed now. Please let us know if there is any further feedback. Many thanks.

**Comment by ElGuilles** [comment]
Thank all of you for your support,

Guillermo
