### ISSUE TITLE
reserve @rend and @style for CSS-like renditional information

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#144]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on February 21, 2013 16:05:39_

Current @rend and @style attributes other than those on the <rend> element should be renamed in order to clear the path for generic @rend and @style attributes than can be applied to more elements (not global, but common). @rend will be used to record visual characteristics of the input document, while @style will be used to specify visual characteristics of potential output. CSS may be used in both attributes.  @altrend will allow user-defined values; that is, ones not permitted by @-rend or CSS.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=144_

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on December 10, 2014 12:10:18_

<desc> for del/@rend should be modified thus: 

"contains an indication of how the deletion is rendered in the source document."

del/@rend may be restricted to a subset of the values provided by rend/@rend.  Or not.  :-)

**Comment by pe-ro** [comment]
related task: move attributes in att.beamrend to att.beam.vis and eliminate att.beamrend.
