### ISSUE TITLE
Checkout TEI Stylesheets during build

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1459]
I was wondering what the benefits are for having the TEI Stylesheets as a submodule in the repo and if it would be possible to download them with the ANT task. Right now the tagged version of the stylesheets and those of all other needed components are handled differently. With moving the process for checking out the stylesheets to the ANT init would bring all dependencies into a single file. 
Another benefit would be to clean up the repo a bit further (#873).

**Comment by bwbohl** [comment]
That is an interesting idea; nevertheless, you always have the option not to check out recursively. At the moment I'd rather add saxon as submodule, too, and maybe the other dependencies as well (or move the build to maven ;-)

**Comment by rettinghaus** [comment]
I find it always a bit tricky to properly update submodules.
And although Xerces-J is available on Github, the OXygen Patched Xerces we use isn't. Neither is Prince, which is commercial software. So the problem remains: we leave our dependency management scattered over several files.

**Comment by ahankinson** [comment]
Would this work? 

https://central.sonatype.com/artifact/com.princexml/prince-java-wrapper?smo=true
