### ISSUE TITLE
Mixed-stem direction beam + rest interaction

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#1461]
In the following example encoding, I would like the beam in the second measure to match the one in the first measure:

<img width="315" alt="Screenshot 2024-04-29 at 10 45 08 AM" src="https://github.com/music-encoding/music-encoding/assets/3487289/896a7f91-b3c3-46e7-8d8f-86a93382c08a">

<details>
<summary> Click to view MEI data for above example. </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt>
   </pubStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2024-04-29T10:42:40" version="4.2.0-dev-764d3d2-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
 </meiHead>
 <music decls="#work1_encoded">
  <body>
   <mdiv xml:id="mid4lan">
    <score xml:id="s1nzk847">
     <scoreDef xml:id="s2r15e0" tempo.dist="3.0000vu">
      <staffGrp xml:id="snvnop0" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-L1F2" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
       </staffDef>
       <staffDef xml:id="staffdef-L1F1" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-L1F2" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <space xml:id="space-L3F2" dur="4" />
        </layer>
       </staff>
       <staff xml:id="staff-L1F1" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L3F1-L4F1" beam.with="below">
          <note xml:id="note-L3F1" type="placed" dur="8" oct="3" pname="c" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L4F1" type="placed" dur="8" staff="1" oct="5" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L5" n="2">
       <staff xml:id="staff-L5F2N1" n="1">
        <layer xml:id="layer-L5F2N1" n="1">
         <space xml:id="space-L6F2" dur="4" />
        </layer>
       </staff>
       <staff xml:id="staff-L5F1N1" n="2">
        <layer xml:id="layer-L5F1N1" n="1">
         <beam xml:id="beam-L6F1-L7F1" beam.with="below">
          <note xml:id="note-L6F1" type="placed" dur="8" oct="3" pname="c" stem.dir="up" accid.ges="n" />
          <rest xml:id="rest-L7F1" dur="8" staff="1" ploc="b" oloc="4" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

But this does not currently seem possible.  In verovio, the outer attached notes of a beam (for two-notes beams at least) control identification of whether or not the beam should be displayed as a mix-stem beam.   But in this case one end of the beam is attached to a rest, and rests cannot have `@stem.dir` attributes; thus, verovio cannot be told to generate a mix-stem beam for the case in the second measure of the example.

How can this be done?  It seems that either `rest@stem.dir` should be allowed, or some attribute on `<beam>` would be needed, such as `@place="above-below`" or for the opposite direction `@place="below-above"` (with possibly spaces for hyphens, or no space between such as `abovebelow`).  Or `<beam place="above" place2="below">`, etc.

Here is the real-life source (Scriabin Op. 64) which is related to this case:

![image](https://github.com/music-encoding/music-encoding/assets/3487289/4449fc06-e935-4c08-9a6a-a217e9312b09)

(first beam of example)

**Comment by pe-ro** [comment]
`beam/@place` can currently take 3 values: 'above', 'below', and 'mixed'.  'mixed' is the proper value in this case.  That is, the beam is above some notes/rests/etc and below others.

**Comment by pe-ro** [comment]
Let me know if you're satisfied with my answer, and I'll close the issue.

**Comment by craigsapp** [comment]
Thanks!  That should work for this situation, so you can close (might be a little difficult with rests on both ends, but that can be dealt with in the future if there are any real examples associated with it).

**Comment by rettinghaus** [comment]
@pe-ro you might want to recheck your comments in #690 on place attributes.

**Comment by pe-ro** [comment]
@rettinghaus, good catch.  Clearly, I wasn't thinking about Scriabin. :-)

To be explicit, I'd encode measure 2 with the rest on staff 1 and the note on staff 2:
```
<measure>
  <staff n="1">
    <layer n="1">
      <beam beam.with="below">
        <space dur="8"/>
        <rest xml:id="rest-L7F1" dur="8" staff="1" ploc="b" oloc="4" />    
      </beam>
    </layer>
  </staff>
  <staff n="2">
    <layer n="1">
      <beam beam.with="above">
        <note xml:id="note-L6F1" type="placed" dur="8" oct="3" pname="c" stem.dir="up" accid.ges="n" />
        <space dur="8"/>
      </beam>
    </layer>
  </staff>
</measure>
```
In other words, `@beam.with` appears on 2 staves or layers.  `<rest>`s can take their so-called "stem direction" from `@beam.with`; that is, "down" when `@beam.with` = "below", and "up" when `@beam.with` = "above".

IMO, the current encoding is somewhat non-sensical.  It has only 1 of the `@beam.with` pair.

Another possibility to encode such beams is with stand-off `<beamSpan>` elements.

**Comment by craigsapp** [comment]
The Scriabin example is encoded in Humdrum, with the purpose of preserving the intended melodic line that is implied by the silly mixed beams, so they are kept in the same track (which happens to be attached to the bottom staff).  So in theory the first rest will be two (one for staff 1 and the other for staff 2 which has moved to the same position as the staff 1 rest).
