### ISSUE TITLE
schema: `@rend` should be available on `<q>`

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#1464]
Although `data.TEXTRENDITION` offers the values `quote` (single quotes)  and `quotedbl` (double quotes) they are not consistently usable in the context of text quotation. Of course, on phrase-level the quotation could be surrounded by a `<rend>` with the respective `@rend` value, e.g.:

```xml
<p>The MEI Guidelines state that <rend rend="quotedbl"><q>Often, the quoted
material is typographically distinct from the surrounding text; i.e., surrounded by
so-called ‘quote marks’</q></rend></p>
```
or alternatively also encoding the quoted quotes:

```xml
<rend rend="quotedbl"><p>The MEI Guidelines state that <q>Often, the quoted
material is typographically distinct from the surrounding text; i.e., surrounded by
so-called <rend rend="quote"><q>quote marks</q></rend></q></rend></p>
```

Of course, it is might be good to separate graphical and logical encoding into separate elements (as above with `rend` indicating the graphical component, and `q` the logical – namely the enclosed text being quoted).

But this is not possible with `<quote>`, as it is a block-level element and `<rend>` is not.

```xml
<!-- invalid -->
<p>The MEI Guidelines state:</p>
<rend rend="quotedbl"><quote>Often, the quoted material is typographically distinct from
the surrounding text; i.e., surrounded by so-called <rend rend="quote"><q>quote marks</q></rend></quote></rend>
```

Maybe the definition of `<quote>` – `Contains a paragraph-like block of text` also means that the contents should also be wrapped in a paragraph OR that it should always be wrapped with a paragraph? But neither would help in wrapping it with `<rend>`.

Alternatively, encoding the `<rend>` inside of the `<quote>` – possible with the current MEI 5.0 – but encoding 'quote marks' as part of the quotation just doesn’t seem right. Trying to encode a quotation of multiple paragraphs in this way will utterly fail due to the same phrase- vs block-level problem.

I think the logical consequence is to allow `@rend` (and probably also `@altrend`) on `<q>` and `<quote>` elements.

**Comment by rettinghaus** [comment]
Sounds reasonable (and would follow TEI).

**Comment by pe-ro** [comment]
This may start a cascade of allowing `@rend` on lots of block-level elements -- `<p>` for sure, but also other text-y elements like `<lg>`, `<stageDir>`, `<list>` and all its derivatives, etc. This could even be extended to musical text elements, such as `<dir>` and its derivatives. Proceed with caution.
