### ISSUE TITLE
docs: macroGroups are not resolved correctly

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1481]
As reported on Slack by Clara Byom and Max Rothman, 

> "The docs say that `<availability>` doesn't say it can be contained by `<manifestation>`, but <manifestation> says it can contain `<availability>`.

Further investigation by @ahankinson showed that 

> `<availability>` doesn't have `<manifestation>` in the "Contained by" list:
https://music-encoding.org/guidelines/dev/elements/availability.html
But `<manifestation>` does have `<availability>` in the "May Contain" list:
https://music-encoding.org/guidelines/dev/elements/manifestation.html

Finally, @kepper was "expecting problems from macro groups" and pointed out:

>If you go on https://music-encoding.org/guidelines/dev/elements/manifestation.html and look for the "May Contain" in "by class" mode, there's https://music-encoding.org/guidelines/dev/macro-groups/macro.bibldescPart.html at the bottom, which brings in `<availability>`, `<editionStmt>`,` <physDesc>`, `<physLoc>`, `<pubStmt>`, and `<seriesStmt>`. Manifestation is not in the "Contained By"  section of any of these, so apparently macro groups aren't properly resolved for that section

**Comment by ahankinson** [comment]
Is it because that macro group isn't wrapped in an `<rng:Optional>` or `<rng:zeroOrMore>` tag, like everything else?

**Comment by musicEnfanthen** [comment]
No, I think that there is an issue in the utils xslt. It seems to not retrieve the macroGroups at all when creating the containedByFacet.

**Comment by musicEnfanthen** [comment]
In fact, the [tools:getContainedByFacet](https://github.com/music-encoding/music-encoding/blob/e38db3ffe2fa3135cc0cd50fbbb26bf16469f6ed/utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl#L1051) is mostly commented out, and just delegates to [tools:getParentsByModel($object)](https://github.com/music-encoding/music-encoding/blob/e38db3ffe2fa3135cc0cd50fbbb26bf16469f6ed/utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl#L1126). 

And there the line for retrieving the macro.parents is commented out saying that it creates recursive loops.

https://github.com/music-encoding/music-encoding/blob/e38db3ffe2fa3135cc0cd50fbbb26bf16469f6ed/utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl#L1169-L1170
