### ISSUE TITLE
guidelines: did we loose subchapters from "9.2.8 Names" during back2odd conversion?

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#1499]
Looking at the v4 guidelines, there was a huge chapter on "Names" including a lot of subchapters: https://music-encoding.org/guidelines/v4/content/textencoding.html#sharedNames

In v5, all the subchapters are gone and only the section of the main "Names" chapter 9.2.8 is left: https://music-encoding.org/guidelines/v5/content/textencoding.html#sharedNames

I cannot find any commit in the history of the textencoding.xml (https://github.com/music-encoding/music-encoding/blob/develop/source/docs/09-textencoding.xml) that removed or moved that section. Actually, the first (and only) commit for this chapter is the "[initial draft of reverted sources](https://github.com/music-encoding/music-encoding/commit/901ffde0809ff79262f564484c0ac4542284ed7e)" commit from 4 years ago.

**Comment by bwbohl** [comment]
What an ugly find! Great discovery!

**Comment by musicEnfanthen** [comment]
There was a wrong order of these chapters in v4 which @krHERO fixed in her awesome PR music-encoding/guidelines#206 (cf. https://github.com/music-encoding/guidelines/pull/206/files#diff-fbf3072abfd0eb44ef6e9266e39f132a3bca0078d89c1305d8ea0c268972dd9fR1252). 

I just wanted to double-check if the order is wrong in v5/dev, too. And as it appears, nothing to order anymore 🙈 

So initial credits for discovery go to @krHERO 🎉
