### ISSUE TITLE
Tablature: new attributes staffDef@tab.align and staffDef@tab.anchorline are missing from staffDef's guidelines.

### ISSUE THREAD

**Issue by paul-bayleaf** [music-encoding/music-encoding#1540]
Two new attributes for German lute tablature, tab.align and tab.anchorline, were introduced in PR #1468 and PR #1534 respectively.  These are intended for use with &lt;staffDef&gt; but do not appear in its guidelines as allowed attributes.
https://music-encoding.org/guidelines/dev/elements/staffDef.html

They do, however, appear in the guidelines for &lt;note&gt;, where they are not applicable.
https://music-encoding.org/guidelines/dev/elements/note.html

**Comment by musicEnfanthen** [comment]
Thank you @paul-bayleaf, good catch. 

So it seems that `tab.align` and `tab.anchorline` are promoted via [att.stringtab](https://music-encoding.org/guidelines/dev/attribute-classes/att.stringtab.html) to [att.note.ges](https://music-encoding.org/guidelines/dev/attribute-classes/att.note.ges.html), [att.chordMember.log](https://music-encoding.org/guidelines/dev/attribute-classes/att.chordMember.log.html) and directly to [`<tabDurSym>`](https://music-encoding.org/guidelines/dev/elements/tabDurSym.html). Probably none of this is correct. 

Pinging @music-encoding/ig-tablature, @musicog, @lpugin

**Comment by janjusolja** [comment]
Thank you @paul-bayleaf for spotting this, I hope this will fix the issue!
