### ISSUE TITLE
Development version is wrong

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#1559]
After the last release we updated all MEI examples to version "5.1-dev".
Validating against the development version fails, because it still expects the version "5.0.0-dev".
Even more strange is, when changing it to the latter it still fails to validate.

We should make sure to update the version properly after the next release.

Probably refers to #1347

**Comment by bwbohl** [comment]
@rettinghaus, which examples are you talking about, the sample-encodings repo or those in the music-encoding repo? And which schema are you validating against?

**Comment by rettinghaus** [comment]
@bwbohl It happens with all files from `music-encoding` in the `examples/verovio` folder with the default schema <https://music-encoding.org/schema/dev/mei-all.rng>.

**Comment by bwbohl** [comment]
When I validate those, I only get 19 warnings with the description:

```
At least one element pair (a resp element and a name-like element) is recommended. Alternatively, each name-like element may have a @role attribute.
```

**Comment by rettinghaus** [comment]
Very weird. What are you using for validation? Maybe connected to <https://github.com/music-encoding/music-encoding/issues/970#issuecomment-2503669692>?

Someone's vaidation doesn't seem to work here.

<img width="864" alt="grafik" src="https://github.com/user-attachments/assets/7f06e3b7-16ab-4550-a62f-0983cee20eff">

Validating against my local build (latest dev) works fine for me.

**Comment by musicEnfanthen** [comment]
@rettinghaus What happens if you use https://raw.githubusercontent.com/music-encoding/schema/refs/heads/main/dev/mei-all.rng ?

Update: And what file source is displayed when you hover over "Source: mei-all.rng"? I have the same issue in VSCode, but the Source path points to some "`.lemminx/cache`" folder instead of the online resource....

**Comment by musicEnfanthen** [comment]
@rettinghaus Ok, think I figured it out, seems to be a cache problem in the VSCode XML plugin. Can you please try

`> XML: Restart XML Language Server`

in VSCode?

**Comment by rettinghaus** [comment]
@musicEnfanthen Thanks for help. Unfortunately both approaches didn't resolves this for me.

**Comment by musicEnfanthen** [comment]
@rettinghaus I remember also deleting the .lemminx/cache folder before restarting the language server. Maybe this is also needed?

**Comment by rettinghaus** [comment]
The heck… that worked for whatever reason. Thank you!

**Comment by musicEnfanthen** [comment]
Yeah, it's weird. Probably related:

- https://github.com/redhat-developer/vscode-xml/issues/284
- https://github.com/redhat-developer/vscode-xml/blob/main/docs/Commands.md
- https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#server-cache-path
