### ISSUE TITLE
Clarify element description of <supplied>

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#160]
_From [stadlerp...@yahoo.fr](https://code.google.com/u/104774976997759771329/) on June 24, 2013 10:38:41_

As discussed on MEI-L [1] I propose to rephrase the element description of <supplied> to not only cover the reason "illegible for any reason" but also "not present in the source material". Additionally, this would make it consistent with section 11.4.1 "Omissions, Unclear Readings, Damage, and Supplied Readings".  

[1] https://lists.uni-paderborn.de/pipermail/mei-l/2013/000944.html )

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=160_

**Comment by zolaemil** [comment]
+1
