### ISSUE TITLE
data.COLOR description doesn't fit on the page

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#173]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on August 25, 2013 11:23:52_

In the MEI 2013 Guidelines the data.COLOR regex does not wrap to the page. (Page 682)

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=173_

**Comment by pe-ro** [comment]
This was fixed in the last release.
