### ISSUE TITLE
barLine needs @staff attribute

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#176]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on September 03, 2013 11:41:33_

The `<barLine>` element must have an attribute that indicates which staff/staves it crosses.  This is particularly important for barlines that affect a sub-set of a score.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=176_

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on September 03, 2013 09:03:38_

Isn't this the function of `<staffGrp />`? Since that can group arbitrary staves, and it can have @-barthru, why does the individual `<barLine />` elements need it?

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on September 03, 2013 10:38:10_

This is one of the functions of `<staffGrp>`, but only when the bar lines are "controlling"; that is they "line up" in all the staves.  However, bar lines can be drawn without regard to the staff grouping.  For example, a score may have 3 staves grouped by `<staffGrp>`, yet in spite of the grouping, some barlines may be drawn only across staves 1 and 2 or even across single staves independently; that is, the bar lines don't "line up". This happens often in the case of transcriptions of early music that doesn't easily submit to the "tyranny of the barline".

**Comment by pe-ro** [comment]
Making <barLine> a member of att.staffIdent --

```
<classSpec ident="att.staffIdent" module="MEI.shared" type="atts">
  <desc>Attributes for identifying the staff associated with the current feature.</desc>
  <attList>
    <attDef ident="staff" usage="rec">
      <desc>Signifies the staff on which a notated event occurs or to which a control event applies.
        Mandatory when applicable.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="positiveInteger"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```

would allow markup like --

```
<barLine staff="2 3"/>
```

for those cases where a bar line involves only a sub-set of staves.

The problem is that this presupposes that `<barLine>` is a control event; that is, it occurs outside `<staff>` and `<layer>`.  At present, however, `<barLine>` is a member of model.eventLike, which means it **only occurs** within `<layer>`.  Hmmm, looks like this needs some extra thought.

**Comment by lpugin** [comment]
Needs more real-life examples. Can be re-opened with these.
