### ISSUE TITLE
description of accid.ges

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#205]
_From [zolae...@gmail.com](https://code.google.com/u/104951529460473817913/) on October 09, 2014 04:45:26_

See the description of accid.ges: 

"Records the performed pitch inflection when it differs from the written accidental."

I think this description is slightly inaccurate, because @-accid.ges can describe the performed pitch regardless whether it is the same or not as the written accidental, e.g.:

<note xml:id="d1e157_1" pname="e" oct="5" dur="8"  stem.dir="down" accid.ges="f">
    
    <accid accid="f" func="caution"/>
</note>

(from http://music-encoding.org/sampleCollection/encodings/caution.xml )

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=205_

**Comment by pe-ro** [comment]
This is related to #263, which has been closed.  So I'm closing this one too.
