### ISSUE TITLE
Add "clones" of SVG elements to model.graphicprimitives

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#216]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on January 28, 2015 11:13:09_

MEI already has anchoredText, curve, line, and symbol elements that allow the capture of graphic elements on the score and permit the definition of user-defined symbols. Unlike similar SVG elements, these MEI versions allow relative positioning. It would be helpful to create additional elements, such as circle, ellipse, polygon, polyline, and rectangle), that also mirror their SVG counterparts but add relative positioning capability. This would increase the "drawing" capabilities of MEI and make it easier to translate the data embodied there as SVG.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=216_

**Comment by pe-ro** [comment]
Closing this since SVG is now allowed with symbolDef.
