### ISSUE TITLE
Provide markup examples and illustrations within elementSpec

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#222]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on January 28, 2015 11:32:25_

While some redundancy may occur (swelling the complete Guidelines even more), markup examples and illustrations within elementSpec provide for better quick reference than having to seek out this info in the textual part of the Guidelines.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=222_

**Comment by pe-ro** [comment]
See also #306

**Comment by ahankinson** [comment]
We're going a different direction with the guidelines, so I'll close this one.
