### ISSUE TITLE
Version number of the next release

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#242]
So far the next release is known as MEI 2015. Do we want to use this, or should it be 3.0.0?

**Comment by ahankinson** [comment]
I think we should increment it by a major version, since the next version contains backwards-incompatible changes.

**Comment by pe-ro** [comment]
My vote would be for 3.0 without the 3rd-level division.

**Comment by pe-ro** [comment]
This has some implications for the schema regardless of what the next release is actually called; that is, should the `@version` attribute be dropped and only the `@version.num` attribute retained?  or should `@version` be re-defined to take a more number-like value and `@version.num` dropped?

**Comment by raffazizzi** [comment]
I'd suggest to keep the third level division. We might need it for upcoming releases. Since breaking backwards compatibility is not a huge issue in this release.. I'd drop `@version.num` and redefine `@version`.

**Comment by lpugin** [comment]
Sorry, I am confused. My proposal was 3.0.0. @raffazizzi and @ahankinson : are you suggesting it should be 2.2.0?

**Comment by ahankinson** [comment]
Nope. 3.0.0 is my vote. I imagine "third level division" means "3.0.0" vs. "3.0".

**Comment by lpugin** [comment]
OK, then it will be 3.0.0 and we can close this.
