### ISSUE TITLE
Permanent links to the schema

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#245]
Since the Google Code repository will be dropped, the links to the schema previously hosted on Google Code will need to be changed to the new url. This is actually a pretty bad practice and I think we should avoid it in the future. So we should have a permanent url for the schema that does not rely on a repository system. We can use music-encoding.org and either copy each release there or redirect to GitHub. It would also be good to have the schema without version number referring to the latest version but also each version numbered explicitly for users who want to refer to a specific release. That is, something like:

http://www.music-encoding.org/schema/mei-all.rng
http://www.music-encoding.org/schema/mei-all-3.0.0.rng

 Any thoughts?

**Comment by raffazizzi** [comment]
:+1: Very good idea! I would prefer this format, however:

http://www.music-encoding.org/schema/latest/mei-all.rng
http://www.music-encoding.org/schema/3.0.0/mei-all.rng

**Comment by zolaemil** [comment]
+1

Redirect is possibly the best...

**Comment by lpugin** [comment]
Great. Would http://schema.music-encoding.org/latest/mei-all.rng be OK? Having a sub-domain might make it easier to manage redirections

**Comment by ahankinson** [comment]
My preference would be for a sub-folder, not a sub-domain.

`http://music-encoding.org/schema/...`

I don't really know why, it just seems a bit clearer. I'm don't really care either way, though.

**Comment by lpugin** [comment]
OK, let's see. I proposed the sub-domain since we are using WordPress for the site and redirect might be  more complicated with the sub-folder. We are looking at it.

**Comment by lpugin** [comment]
@kepper is suggesting
http://www.music-encoding.org/schema/current/mei-all.rng in order to match the documentation url (current instead of latest). OK?

**Comment by kepper** [comment]
actually, we can also change the documentation to support both (or just latest). No special preference here…

**Comment by lpugin** [comment]
OK, a trial there
http://www.music-encoding.org/schema/2.1.1/mei-all.rng

However, this is not ideal because the end url is still the GitHub one. We would need another way to redirect, and at this stage I think it would be simpler to just have a copy of the files.

**Comment by ahankinson** [comment]
I believe we've dropped the `www` prefix, so:

`http://music-encoding.org/schema/2.1.1/mei-all.rng`

**Comment by kepper** [comment]
but isn't this exactly the behavior of a 301? It's a permanent redirect, which tells users (and crawlers) that the original resource is now available from the target pointed at. Not sure which consequences it would have to hide this. Oxygen doesn't choke on the redirect (I just tried the schema below), and only if people want to follow the link "manually", they would end up at GitHub. I think that would be fine, wouldn't it?

jo

Am 02.07.2015 um 11:38 schrieb Andrew Hankinson notifications@github.com:

**Comment by lpugin** [comment]
Yes, it is ended the expected behavior. But I would try to avoid to have
the GitHub url visible since it will end up being used.

**Comment by kepper** [comment]
but where is it visible? Not to people using it in the MEI files. So probably it's only visible to people trying to download the file. This could be prevented by referring to it with a "download"-attribute (http://caniuse.com/#feat=download). But you're right, there is no way to ultimately prevent that people use the github URI…

Am 02.07.2015 um 12:00 schrieb Laurent Pugin notifications@github.com:

> Yes, it is ended the expected behavior. But I would try to avoid to have
> the GitHub url visible since it will end up being used.
>

**Comment by ahankinson** [comment]
Since we release infrequently, we can copy the files over -- it might be different if we were releasing every week, but copying files is probably the best and easiest solution that will ensure that all tools can use it. (Will jing or xmllint follow the redirect too? Possibly not.)

**Comment by lpugin** [comment]
I agree, it is clearer and not a significant overhead to copy the files

**Comment by lpugin** [comment]
OK, we do not have all versions, but since we have 2.1.1 and nobody complains about it we can close the issue
