### ISSUE TITLE
Cleanup some old branches

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#246]
Currently we have a bunch of old branches which survived the move from the Google Code repo. While I think we can keep a few of them, there are some that can go away.

Perhaps the following could be scheduled for removal:
- Raffaele@197
- Raffaele
- FeatureRequests
- FeatureRequests@208
- Documents@208

@raffazizzi @pe-ro

**Comment by raffazizzi** [comment]
You can certainly removed the "Raffaele" ones. I think it's some old additions to musicxml2mei XSLTs that would be completely obsolete by now. Or first attempts at moving from rng to ODD

**Comment by ahankinson** [comment]
OK, I've deleted the Raffaele ones. Anyone else have any feeling on this?

**Comment by ahankinson** [comment]
Fixed.
