### ISSUE TITLE
restrict @n to positive integer vallues

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#248]
While most users so far have intuitively avoided it, there can be confusion between `@n` and `@label` if `@n` is allowed to continue to hold text values.  I believe there should be a clear separation in the way these attributes are used -- `@n` for numeric and `@label` for text labels/identifiers/names/whatever.  Restricting `@n` will allow the removal of several Schematron rules that validate the use of `@n` as an integer.  On the surface, this appears to be a backward incompatible change, but I think it actually supports current practice.

**Comment by lpugin** [comment]
I agree that it is essentially a clarification. Maybe we can have somewhere in the release summary a list of them? Likely items for which the change is only in the Schematron rules.

**Comment by zolaemil** [comment]
I think I have come across @n attributes holding strings in the past, but I totally agree, restricting to number could only make things cleaner.

However, positive integer seems to me a bit over restrictive. What about simply integer?

**Comment by pe-ro** [comment]
What does @staff=”0” mean?  Or @staff=”-1”?

**Comment by zolaemil** [comment]
Sure, I probably would never give staff/@n a negative value. But I think it's arguable that a measure/@n="0" could be used for anacrusis. I think it should at least be natural (non-negative) numbers. Do you see any harm in allowing the negative range? If the existing Schematron rules assert for integers, they could still be deprecated safely.

**Comment by pe-ro** [comment]
Oh, yeah.  I’d forgotten about pick up measures.  So, I see the point in non-negative integers, but can’t see any usefulness in negative ones.

**Comment by zolaemil** [comment]
For the sake of argument, consider numbering <zone> elements, so that the one with @n="1" corresponds to page no.1 (you would probably add @label="page_1" too, I guess). In this case, the leading pages, such as table of contents, cover, leading blank pages, etc. would be negative numbers. 

This is clearly bad practice, so I am with you on this one: the first <zone> should either have @n="0" or n@="1". So perhaps you are right, and negatives should just be _banned_! Unless someone can think up some actually meaningful use case...

**Comment by pe-ro** [comment]
Giving this a little more thought, I think we've been trying to apply the stricter standards for `staffDef/@n`, `layerDef/@n`, `staff/@n` and `layer/@n` too broadly.  In fact, I think the datatype defined for `@n` in att.common should be re-defined as “token” so that it can capture the broadest possible definition of “number”.  This provides the flexibility to define "number" (which the documentation will say) very liberally, as is necessary for measure and page numbers, which often aren’t really numbers at all, e.g. `<pb n=”3a (iii)”/>`.  In these cases, the so-called number is really just a label (which the current definition of `@n` recognizes), but it’s too much of an up-hill battle to get folks not to call these “numbers”.  For those situations where a true (I started to say “real”, but that has a special meaning with regard to numbers) value is required; that is, one that can be used to calculate with, then individual elements (such as staffDef, layerDef, staff, layer) can define `@n` as needed.  So that these can be defined as number datatypes, and not simply strings that look like numbers, I propose redefining att.common like so --

``` xml
<!-- add new att.commonPart class -->
<classSpec ident="att.commonPart" module="MEI.shared" type="atts" mode="add">
  <desc>Attributes that form the basis of the att.common class.</desc>
  <classes>
    <memberOf key="att.id"/>
  </classes>
  <attList>
    <attDef ident="label" usage="opt">
      <desc>provides a name or label for an element. The value may be any string.</desc>
      <datatype>
        <rng:data type="string"/>
      </datatype>
    </attDef>
    <attDef ident="xml:base" usage="opt">
      <desc>provides a base URI reference with which applications can resolve relative URI
        references into absolute URI references.</desc>
      <datatype>
        <rng:ref name="data.URI"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>

<!-- re-define @n as "number-like"; elements that require a true numeric value must define @n. -->
<classSpec ident="att.common" module="MEI.shared" type="atts" mode="replace">
  <desc>Attributes common to many elements.</desc>
  <classes>
    <memberOf key="att.commonPart"/>
  </classes>
  <attList>
    <attDef ident="n" usage="opt">
      <desc>provides a number-like designation for an element.</desc>
      <datatype>
        <rng:ref name="token"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```

att.commonPart is a re-usable chunk of attributes which elements that re-define `@n` can use instead of att.common. The `@n` attribute can then be re-defined as a nonNegativeInteger (or whatever) and not just as a string restricted to digits.  Just thinking ahead to schema-aware processing.

## 

p.

**Comment by raffazizzi** [comment]
:+1: I think it's important and very useful to make this distinction. What about `<measure>`? I suppose it should keep the token datatype for things like '1a' or other unpredictable measure numbering. Right?

**Comment by pe-ro** [comment]
Right, `<measure>` and `<pb>` should keep the token datatype.  Are there others?  Conversely, are there other elements besides `<staffDef>`, `<layerDef>`, `<staff>` and `<layer>` where `@n` needs an actual number (=nonNegativeInteger)?
