### ISSUE TITLE
Improve consistency between attributes and equivalent elements

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#250]
In the cases where we can either have an attribute or an element for the same thing, my understanding it that one would use the element when either more detailed information needs to be provided or where there is a need to provide editorial information about it (e.g. having it in an app/rdg). We have quite a few of them in staffDef (clef, key, meter, etc.). So it seems to me that everything that is available at the attribute level should also be provided in the element. 

In `<keySig>`, there is no option to encode it as in `<staffDef> @key.sig`.  Shouldn't we add `@sig` in `<keySig>`?

There are some inconsistencies how attributes are grouped in the ODD, but this is less of an issue. In most cases it could be improved without generating changes in the resulting schema, I think.

**Comment by pe-ro** [comment]
Can you be more specific than "everything that is available at the attribute level" as a target?

The grouping of attributes attached to `<scoreDef>` is addressed in issue #115 and in the 2015 ODD customization.  Several new attribute classes are added: att.endings (ending.rend), att.measurenumbers (mnum.visible), att.notationstyle (music.name, music.size), att.optimization (optimize), att.pages (page.height, .width, .topmar, .botmar, .leftmar, .rightmar, .panels, .scale), att.spacing (spacing.packexp, .packfact, .staff, .system), and att.systems (system.leftline, .leftmar, .rightmar, .topmar). Except for a couple of cases (system.leftline, for instance) this represents a re-arrangement of existing attributes and has no effect on the resulting schema, but it separates the attributes into more manageable and shareable groups.

**Comment by lpugin** [comment]
In `<staffDef>`, you can do clef.line="2" or clef.shape="G" that intuitively translates in `<clef>` to line="2" and shape="G". I could not find the equivalent of key.sig="1f" in `<keySig>`.

**Comment by lpugin** [comment]
Another example: `<staffDef>` has key.sig.showchange attribute for displaying cautionary changes (or not). Here too, I am not sure there is an equivalent in `<keySig>`. So if I want to have encode the key signature within an app and rdg within staffDef, with one showing cautionary changes and the other not, I am not sure I can do it. So, to go back to the issue: I would expect every attribute in staffDef to have their equivalent in promoted element. 

If possible, it would also make it simpler to have the same attribute classe structure: for example, att.keySigDefault.vis that defines 'key.sig.showchange' could be att.keySig.vis and define 'showchange' in keySig. (Mensur - the attributes in staffDef and the element - is not consistent in this regard, to have another example.)

Along the same lines, I would personally be in favor of deprecated all attributes that have been promoted to an element, and eventually drop them. This would make MEI developments much easier in the long run.

**Comment by pe-ro** [comment]
Ever hear that "Consistency is the hobgoblin of small minds"?  :-)

Seriously, I see your point about making the so-called "attribute solution" and the "element solution" more consistent.  And I agree.  It's just that it may take some time to get around to it.  Version 4, perhaps?

I'm less willing to whole-heartedly support deprecating attributes in favor of elements, because each possibility within the "two-state" solution serves a different constituency  -- some want attributes and some want elements.  I think the best way to deal with this is to encourage the use of **one way or the other** but **not both simultaneously**.  To do so, we could provide customizations that enforce one approach or the other or we could add schematron rules (although it would swell the size and complexity of mei-source considerably).

**Comment by lpugin** [comment]
I never heard did. But I know that small minds usually have a bad memory ;-)

I understand that it would take some time, this is not urgent. Only missing features in the elements is more problematic, I think. I might add separate issues for them.

I think the interesting part of the discussion is in the end more the attribute/element thing. I can see many places in MEI where it makes sense to have several possible approaches. For example beam and beamSpan, because here there is a structural difference. Now for keeping attributes where elements are available I cannot see any advantage in the long run, but only overhead and/or incompatibility. Using one or the other is easy to define when you create your own tool for your own project. Just to take the example of SibMEI. It consistently uses accid elements. And consistently dot attributes. Fine (and no criticism here!). But this might be incompatible with another tool that uses attributes for both accid and dots, or reverse. So of course, we can have a customization or schematron rules. But this is not going to fix it. We will need to convert from one to another, presumably with an XSL stylesheet, and somebody will need to write this stylesheet and then run this stylesheet every time. So to me the is a huge overhead and I cannot understand why we would not want to avoid it only because some prefer this and others prefer that. 

They are actually not that many attributes that have a promoted element equivalent (probably mostly in staffDef and in note). I am convinced that deprecating the attribute when a feature is promoted to an element will make MEI much stronger in the long run.

**Comment by th-we** [comment]
Like Zoltan, I'd like to wholeheartedly support Laurent's suggestion of deprecating attributes where elements are available (don't forget `@syl` vs. `<syl>`).

**Comment by lpugin** [comment]
I am not sure Zoltan supports this idea but I am glad you do ;-)

**Comment by zolaemil** [comment]
I can't recall expressing any opinion on the matter, but very happy that is
still matters :)

But then let me stir up this thread once again, with perhaps the most
controversial suggestion. I don't actually see a problem of the two forms
to co-exist within a single MEI file, especially if they are the result of
a processing step, thus making sure that the redundancy is proper (i.e.
there is no conflicts).

For example, we have MEI files with ties encoded as attributes. For
rendering purposes, we convert these into elements, but tie attributes are
still useful for audio processing (generating MIDI), so it makes sense to
keep them both.

For the record, I am all for consistency, as long as it's not "a foolish"
one, as Perry saved us from the cheeky qualifying term from the beginning
of his quote ;)

Zoltan

2015-08-21 11:13 GMT+01:00 Laurent Pugin notifications@github.com:

**Comment by th-we** [comment]
@zolaemil I'm sorry, I guess my telepathy skills need training as I don't see a post where you explicitly expressed the opinion implied by me. I have no idea what association chain made me link your name with that opinion - I can assure you I wasn't under the influence while writing!

**Comment by lpugin** [comment]
Of course it is not a problem to have both attributes and elements. It just increases the complexity and the amount of work. When thinking "encoding", it clearly has no major impact (you can do this, or you can do that). It does when it comes to developing tools, and in particular when creating tools that are mean to "read" MEI - writing it is easy, you just do what you prefer ;-). So this is a community question: are there places where we can deprecate attributes in order to make the exchange of data and tools easier in the long run.

Now ties might be a different issue. But if we take accid, I cannot see the benefit of allowing

```
<note accid="s"/>
```

since there is

```
<note>
  <accid accid="s">
</note>
```

Now let's say, somebody is planning to have an MEI importer into MuseScore (wouldn't this be be great?). Which one should be supported first? Should the person start with the simplest one? Or look around what is most commonly used? Both clearly make sense. One risk here it so have some sort of de facto standardization that is driven by the development of some tools. Another one is to have to develop additional tools to "sanitize" the data (we see this happening elsewhere). I would prefer discussion and deprecation.

**Comment by lpugin** [comment]
Reduced to a more focused issue here #354
