### ISSUE TITLE
Update Sample Encodings to MEI 3.0.0

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#251]
The sample encodings will need to be updated for the upcoming MEI 3.0.0 release.

**Comment by pe-ro** [comment]
I just started on an XSLT stylesheet to convert 2013 files to 3.0.0 (2015).  Where should I put it?

**Comment by ahankinson** [comment]
Great! You can put it in the `tools/` directory, along with the others and then commit it to your `develop-perry` branch.

In your commit message you can add "Refs #251" and GitHub will pick up on that and link the commit with the issue so that we can watch the progress here.

**Comment by ahankinson** [comment]
Also "Refs #243" for that issue as well.

**Comment by pe-ro** [comment]
Sorry, I forgot.

**Comment by ahankinson** [comment]
S'ok.
