### ISSUE TITLE
Create a generic ornament element

### ISSUE THREAD

**Issue by raffazizzi** [music-encoding/music-encoding#253]
As suggested in a [MEI-L discussion](https://lists.uni-paderborn.de/pipermail/mei-l/2015/001612.html), I tried using `<dir>` for encoding ornaments that are not mordents, turns, or trils, but it lacks some attributes that would be quite helpful when encoding ornaments, such as `@accidupper` and `@accidlower`. Would it make sense to consider introducing a generic `<ornament>` element for ornaments that are not mordents, turns, or trills?

I would imagine it would have attributes that all three current supported ornaments share, plus duration attributes to support ornaments that extend like a trill. The `@form` attribute instead could probably be skipped because it wouldn't be possible to pre-define forms of a generic ornament. The `@altsym` attribute could be used to refer to a specific glyph and an expansion should probably be provided in the stream of events like @pe-ro recommended.

For example a Doppelt-Cadence now can be encoded as:

``` xml
<dir tstamp="1">
   <symbol ref="#my_doppel-cadence_symbol"/>
</dir>
```

With a generic ornament it would be encoded very similarly:

``` xml
<ornament altsym="#my_doppel-cadence_symbol" tstamp="1" />
```

But, unlike `<dir>` it would also allow me to add an accidental:

``` xml
<ornament altsym="#my_doppel-cadence_symbol" tstamp="1"  accidupper="s" />
```

Thoughts? Here is a possible ODD definition:

``` xml
<elementSpec ident="ornament" module="MEI.cmnOrnaments">
      <desc>An element indicating an ornament that is not a mordent, turn, or trill.
      </desc>
      <classes>
        <memberOf key="att.common"/>
        <memberOf key="att.facsimile"/>
        <memberOf key="att.ornament.log"/>
        <memberOf key="att.ornament.vis"/>
        <memberOf key="att.ornament.ges"/>
        <memberOf key="att.ornament.anl"/>
        <memberOf key="model.ornamentLike.cmn"/>
      </classes>
      <content>
        <rng:empty/>
      </content>
      <constraintSpec ident="ornament_start-type_attributes_required" scheme="isoschematron">
        <constraint>
          <sch:rule context="mei:ornament">
            <sch:assert test="@startid or @tstamp or @tstamp.ges or @tstamp.real">Must have one of
              the attributes: startid, tstamp, tstamp.ges or tstamp.real</sch:assert>
          </sch:rule>
        </constraint>
      </constraintSpec>
      <remarks>
        <p>The glyph of the ornament may be indicated with the <att>altsym</att> attribute, 
          and it is recommended to provide an expansion of the ornament on the staff content.
          The starting point of the ornament may be indicated by either a <att>startid</att>,
          <att>tstamp</att>, <att>tstamp.ges</att>, or <att>tstamp.real</att> attribute. It is a
          semantic error not to specify one of these attributes.</p>
      </remarks>
    </elementSpec>
```

Here is a full spec with attribute classes for reference: https://gist.github.com/raffazizzi/e92c15a36e6203846fbb

PS I would have written this to the developers' list in the past, but if I understand correctly this is the new place to do this, correct?

**Comment by pe-ro** [comment]
This sounds fine to me, although since it's a generic ornament element, it should be placed in the MEI.shared module, not MEI.cmnOrnaments, and should be a member of model.controleventLike, not model.ornamentLike.cmn. Also, in keeping with upcoming changes, it should be a member of att.typed.

**Comment by pe-ro** [comment]
It's a small thing, but following the principle that often-used elements get abbreviated names, I'd prefer that the new element be called “ornam” rather than “ornament” for a couple of reasons: it’s shorter (just as easy to remember w/o increasing the size of the file) and it matches other uses of the term (for example, in `att.ornam/@ornam`).

**Comment by raffazizzi** [comment]
I have no problem with that. I'll submit a new PR soon

**Comment by pe-ro** [comment]
Grazie

**Comment by ornam** [comment]
Hi guys,

I'm new to Github so forgive my naivety, but am I going to get notifications every time someone calls the @ornam element?

Thanks, 
Orna M.

**Comment by ahankinson** [comment]
Whoops! :) Sorry about that Orna. 

In XML notation, `@ornam` is a common way to refer to an element's attributes. On GitHub, prefixing an `@` with a user name alerts that user that they have been mentioned. 

We can prevent this by escaping it with backticks, so `@ornam` will appear as code and won't alert you. 

Our apologies!

**Comment by ornam** [comment]
No problem!

Thanks for that!!

Orna.
