### ISSUE TITLE
regularised ornament

### ISSUE THREAD

**Issue by zolaemil** [music-encoding/music-encoding#256]
Recent discussion on [MEI-L](https://lists.uni-paderborn.de/pipermail/mei-l/2015/001612.html) concluded that the regularised notation should be encoded as part of the event stream:

```
<layer>
  <orig><!-- written note --></orig>
  <reg><!-- resolution of the ornament (probably multiple notes) --></reg>
</layer>
```

This is in conflict with the Guidelines' recommendation that suggests to encode the regularised notation along with the ornament, _outside_ the staff (see the last example in [8.3.1](http://music-encoding.org/documentation/2.1.1/cmnOrnaments/)):

```
  <staff>
    <layer>
      <orig><!-- written note --></orig>
    </layer>
  </staff>
```

and then  

```
  <choice>
    <orig>
      <!-- ornament -->
    </orig>
    <reg>
      <!-- resolution of the ornament (probably multiple notes) -->
    </reg>
  </choice>
```

I also think that the first first solution is more elegant, and it is conceptually more adequate to encode notes as part of the event stream.

If this is indeed the recommended practice, we should probably update the relevant section in the guidelines.

**Comment by pe-ro** [comment]
I agree that the documentation should be expanded to describe each method and its possible advantages, but I don't think we can recommend one method over the other.  I believe that including the ornament resolution in the event stream is easier for human beings, but more difficult for mechanical processes.

**Comment by zolaemil** [comment]
In my opinion processing (at least certain type of processing, such as substituting the written text with the regularised one) is also more straightforward when they are both contained within the event stream. 

In any case, we could certainly allow both encoding. Regarding recommendation (or encouragement?), I thought that was the Guidelines' primary purpose.

**Comment by pe-ro** [comment]
Of course, recommendations are the purpose of the Guidelines.  I think we just have to be careful about what we recommend.  ☺

Personally, I agree with you, Zoltan, that certain kinds of processing are easier/more straightforward when the written text and the regularized one are both in the event stream.  But, we have to recognize that placing the ornament and its realization (notice I didn’t say “regularization”) alongside each other has value as well.  In fact, it could be helpful to have both the “regularization” of the text and the “realization” available.  In order to avoid double encoding, however, there should be a way to encode one or the other (probably the “regularization”) and then refer to it in the other location.  In other words, this is a good use case for a generic reference/copy mechanism.

But, let’s work on this together – if you’ll revise section 8.3 (leaving out the stuff about referencing/copying for now), I’ll edit and create examples.  Fair enough?

## 

p.

**Comment by zolaemil** [comment]
I guess there's a very fine line between realisation and regularisation. Since we have only one element (<reg>) maybe something like the following passage could make things clearer:

"In other cases it may be more convenient to encode the regularized text within the stream of events, thus providing a realization [perhaps resolution?] of the related ornament.

```
<measure>
  <staff>
    <layer>
      <orig>
        <note dur="4" oct="5" pname="c" stem.dir="down"/>
      </orig>
      <reg>
        <note dur="32" oct="5" pname="d"/>
        <note dur="32" oct="5" pname="c"/>
        <note dur="32" oct="5" pname="d"/>
        <note dur="32" oct="5" pname="c"/>
        <note dur="32" oct="5" pname="d"/>
        <note dots="1" dur="16" oct="5" pname="c"/>
      </reg>
    </layer>
  </staff>
  <choice>
    <orig><trill place="above" staff="1" tstamp="1"/></orig>
    <reg></reg>
  </choice>
</measure>
```

"

**Comment by pe-ro** [comment]
Although I may give the regularization-in-the-event-stream explanation first, your text is fine with me.  I’ll work it into the Guidelines.

Thanks,

## 

p.

**Comment by pe-ro** [comment]
Here's what I've got so far.  Comments appreciated.

```
<p>Another situation that requires disambiguation of an ornament's name and its potential
        rendition is due to the fact that the symbols for trills and mordents have been often used
        interchangeably in the past. The following example, taken from <title>Klavierbüchlein für
          Wilhelm Friedemann Bach</title> (1720), shows a trill (<q>Trillo</q>) identified by the
        symbol associated with a mordent in modern practice. Nonetheless, J.S. Bach's suggested
        resolution should be encoded with a variant of the procedure presented above.</p>
      <p>In the example below, the child elements of <gi scheme="MEI">choice</gi>; that is, <gi
          scheme="MEI">orig</gi> and <gi scheme="MEI">reg</gi>, represent non-exclusive options;
        that is, both may be processed by applications that aim to support both visual and aural
        renditions.</p>
      <figure>
        <head>Trill transcribed from J.S. Bach's <title>Klavierbüchlein für Wilhelm Friedemann
            Bach</title> (1720)</head>
        <graphic url="Images/modules/cmnOrnaments/ex_tr_B.png" height="175px"/>
      </figure>
      <egXML xmlns="http://www.tei-c.org/ns/Examples" xml:space="preserve">
<measure n="1">
  <staff n="1">
    <layer n="1">
      <note dur="4" oct="5" pname="c" stem.dir="down"/>
    </layer>
  </staff>
  <choice>
    <orig>
      <trill staff="1" place="above" tstamp="1"/>
    </orig>
    <reg>
      <note dur="32" oct="5" pname="d"/>
      <note dur="32" oct="5" pname="c"/>
      <note dur="32" oct="5" pname="d"/>
      <note dur="32" oct="5" pname="c"/>
      <note dur="32" oct="5" pname="d"/>
      <note dur="16" oct="5" pname="c" dots="1"/>
    </reg>
  </choice>
</measure>
      </egXML>

      <p>Depending on the purpose of the encoding, it may be more convenient to encode the
        regularized text within the stream of events, along with a corresponding choice with regard
        to the existence of the trill marking, as in the following example:</p>
      <egXML xmlns="http://www.tei-c.org/ns/Examples" xml:space="preserve">
<measure>
  <staff>
    <layer>
      <choice>
        <orig>
          <note dur="4" oct="5" pname="c" stem.dir="down"/>
        </orig>
        <reg>
          <note dur="32" oct="5" pname="d"/>
          <note dur="32" oct="5" pname="c"/>
          <note dur="32" oct="5" pname="d"/>
          <note dur="32" oct="5" pname="c"/>
          <note dur="32" oct="5" pname="d"/>
          <note dots="1" dur="16" oct="5" pname="c"/>
        </reg>
      </choice>
    </layer>
  </staff>
  <choice>
    <orig>
      <trill place="above" staff="1" tstamp="1"/>
    </orig>
    <reg/>
  </choice>
</measure>
      </egXML>
      <p>The <gi scheme="MEI">orig</gi> element contains the single-note-with-trill transcription of
        the original text, while the <gi scheme="MEI">reg</gi> element represents the
        realization-without-trill version.</p>
      <p>This approach facilitates substitution of the realization of the trill for the original
        written note (as well as the opposite procedure) and is therefore the recommended markup for
        applications where exchange of this kind is desirable.</p>
```

**Comment by zolaemil** [comment]
Thanks Perry, this looks good to me!
