### ISSUE TITLE
Various issues with grace notes

### ISSUE THREAD

**Issue by rigaux** [music-encoding/music-encoding#258]
We found several cases where grace notes seem to be incorrectly copied from MusicXML to MEI by the XSLT stylesheet. 
1) http://neuma.huma-num.fr/scorelib/opus?id=methodes:adampiano:091_1, measure 4. The second grace note (c5) is missing in the MEI file.
   http://neuma.huma-num.fr/rest/methodes/adampiano/091_1/score.xml
  http://neuma.huma-num.fr/rest/methodes/adampiano/091_1/mei.xml
2) http://neuma.huma-num.fr/scorelib/opus?id=timbres:ctf:0015, measure 7. Two grace notes are
   represented in the MEI doc, instead of 4
    http://neuma.huma-num.fr/rest/timbres/ctf/0015/score.xml
    http://neuma.huma-num.fr/rest/timbres/ctf/0015/mei.xml

More examples available.

**Comment by ahankinson** [comment]
This issue was moved to music-encoding/encoding-tools#6
