### ISSUE TITLE
Schematron validation in build process

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#264]
Related to #262 

Schematron validation should be integrated into the build process. I'm willing to do this, but would appreciate some guidance (@kepper, @pe-ro, @raffazizzi, @th-we ), especially around getting a command-line (i.e., no oXygen) system for validating.

I've extracted the attached schematron rules (***) from the latest `mei-all.rng` using saxon-he. I can't seem to get it to validate without spitting out a bunch of warnings:

```
Warning: on line 1112
  The attribute axis starting at an attribute node will never select anything
Warning: on line 1112
  The child axis starting at an attribute node will never select anything
Warning: on line 1183
  The attribute axis starting at an attribute node will never select anything
Warning: on line 1183
  The child axis starting at an attribute node will never select anything
```

etc.

I've used `probatron` and `xmllint`. `xmllint` failed rather spectacularly:

```
XPath error : Invalid expression
not(normalize-space(.) eq '')
                       ^
schematron.sch:18: element assert: Schemas parser error : Failed to compile test expression not(normalize-space(.) eq '')
```

**\* You will need to rename .txt to .xml or .sch, since GH doesn't like .xml extensions 

[schematron.txt](https://github.com/music-encoding/music-encoding/files/6965/schematron.txt)

**Comment by aerhard** [comment]
One way that works fine with the MEI RNGs is to use the XSLTs from the Schematron website, that is, create a validation XSLT from the RNG and then use Saxon to validate MEI files by transforming them with the generated XSLT. You can create custom output messages (using `iso_schematron_message_xslt2.xsl` from the Schematron XSLT package as a starting point), which allows you to throw XSLT errors when something's invalid
