### ISSUE TITLE
Clarifications required for pb/@func

### ISSUE THREAD

**Issue by th-we** [music-encoding/music-encoding#266]
Is my understanding correct that if `@func` is present on `<pb>`, one has to assume a folio counting scheme, if it's absent, one has to assume a page counting scheme?  The reason I ask is that we have to deal with both and have to make sure we can distinguish both situations.

In case my understanding is right, I think that should be included in the guidelines.

**Comment by th-we** [comment]
OT: I can't seem to add labels. Why is that?

**Comment by lpugin** [comment]
Now you should be able

**Comment by th-we** [comment]
@lpugin Thanks!

**Comment by pe-ro** [comment]
Another, perhaps more explicit option is to add measurement units to `<pb>`, e.g., `<pb n="1" unit="page"/>`.  The `@unit` attribute could be restricted to "page" and "folium".  In light of this change, it might be beneficial to also rename `@func` to `@folium`.  Its presence could be allowed only when `@unit = "folium"` via schematron.

**Comment by pe-ro** [comment]
Or `@func/@folium` could be dropped altogether and `@n` relied upon to carry (as it traditionally does) indication of the number and the side of the leaf, e.g., `@n="1v"` or `@n="2r"`.  This may not be quite as granular as some might like, but it fits with real, human expectations.

**Comment by th-we** [comment]
I fear dropping `@func` might lead to ambiguity. The specs explicitly state that `@n` doesn't have to be a number, and we indeed have cases where `@n` carries a number followed by a letter.  If that letter would happen to be `r`or `v`, then we'd be screwed.

Apart from that I agree that renaming `@func` to `@folium` would be more descriptive.
