### ISSUE TITLE
Add <cb> element like TEI?

### ISSUE THREAD

**Issue by th-we** [music-encoding/music-encoding#267]
We have multi-column sources like [this](http://www.ceec.uni-koeln.de/ceec-cgi/kleioc/0010/exec/pagepro/%22kkd%23ebk%23gkz915-0001_574.jpg%22):

![Drachenfels-Missale](http://www.ceec.uni-koeln.de/projekte/CEEC/manuscripts/fit/kkd%23ebk%23gkz915%2d0001/kkd%23ebk%23gkz915%2d0001%5f574%2ejpg)

A `<cb>` (column break) element [like in TEI](http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-cb.html) would be very useful here. Is this considered too atypical in music or would it be appropriate to add to MEI?

**Comment by th-we** [comment]
I guess `<cb>` might also be useful for encoding editions of songs where strophes are written in multiple columns, like [this](https://archive.org/stream/eindeutschesgei00bugoog#page/n101/mode/2up):

![strophe-columns](https://cloud.githubusercontent.com/assets/1147152/10422674/d11b3a82-70bd-11e5-97f3-d5cd9dea0119.png)

**Comment by ahankinson** [comment]
I would support this. I think it will be targeted for the next MEI release, however.

**Comment by lpugin** [comment]
This makes sense to me too.

**Comment by th-we** [comment]
As the song facsimile above shows, layout may switch between column and non-column layout.  The question is then, how does one indicate where a column layout starts and ends.

One possible solution I can think of is regarding non-column layout to actually be 1-column layout.

```
<pb n="75"/>
<cb n="1"/>
<!-- First column: "Mein leiden..." -->
<cb n="2"/>
<!-- Second column: "Dy tagweys..." -->
<cb n="1"/>
<!-- "Single column": "Die Melodie...", followed by headings and musc -->
<cb n="1"/>
<!-- First column: "Ihersalem, ..." -->
<cb n="2"/>
<!-- Second column: "Nun lauffetzw..." -->
```

One potential flaw I see with this is: When an encoded passage stops in column 1 of a 2-column layout, but the encoder wants to convey it's actually part of a 2 column layout, how would he do that? Should there be an optional `@colcount` attribute on `<cb>`? It would be sufficient to put that on the first `<cb>` of a section with columns (actually I think that should be recommended to avoid redundancy/inconsistency).

**Comment by pe-ro** [comment]
Would it be better to place `@colcount` (or `@cols`) on the preceding `<pb>`?  This would permit one to indicate that the page is layed out in columns without actually specifying where the column breaks are.  This could be beneficial for situations that require re-flowing the text.

**Comment by ahankinson** [comment]
How would you tell what text was supposed to be in which column?

**Comment by pe-ro** [comment]
You couldn't without the use of `<cb>`.  But with `<pb cols="2"/>` a renderer could break the text as it saw fit.

**Comment by pe-ro** [comment]
`@cols` says "this page is rendered in columns". The `<cb>` elements provide specific column break points.  In their absence, the rendering engine can break the columns as it wishes.

**Comment by pe-ro** [comment]
Even in their presence, the rendering engine can choose to ignore them and still render the page in columns.

**Comment by pe-ro** [comment]
Doh!  Column layout might not actually begin at a page break.  So, a different milestone, `<colLayout>` perhaps, is needed to indicate the start of column layout.  `<cb>` (column break or column begin) could still be used to specify where a new column starts.  For example --
```
<pb n="75"/>
<colLayout cols="2"/>
<!-- start of column layout -->
<cb n="1"/>
<!-- First column: "Mein leiden..." -->
<cb n="2"/>
<!-- Second column: "Dy tagweys..." -->
<colLayout cols="0"/>
<!-- "Single column": "Die Melodie...", followed by headings and music -->
<colLayout cols="2"/>
<!-- switch back to column layout -->
<cb n="1"/>
<!-- First column: "Ihersalem, ..." -->
<cb n="2"/>
<!-- Second column: "Nun lauffetzw..." -->
and so on ...
```
`<colLayout>` also provides a place to attach attributes that describe the columnar layout -- the width of each column, the gutter between the columns, etc.

Another approach to columns -- adopted by HTML -- is to allow "block" level elements to carry the attributes describing columnar layout; that is, `<div>`, `<p>`, `<quote>`, and `<seg>` (in text) as well as `<mdiv>`, `<score>`, `<ending>`, and `<section>` (in notation). We'd still need `<cb>` elements that HTML doesn't provide.  For example --
```
<pb n="75"/>
<div cols="2"/>
  <!-- start of column layout -->
  <cb n="1"/>
  <!-- First column: "Mein leiden..." -->
  <cb n="2"/>
  <!-- Second column: "Dy tagweys..." -->
</div>
<div cols="0">
  <!-- "Single column": "Die Melodie...", followed by headings -->
  <!-- @cols can explicitly say "no columns here" or the absence of @cols (as with the mdiv below) can be interpreted to mean the same thing. -->
</div>
<mdiv type="song">
  <!-- music notation -->
</mdiv>
<div cols="2">
  <!-- switch back to column layout -->
  <cb n="1"/>
  <!-- First column: "Ihersalem, ..." -->
  <cb n="2"/>
  <!-- Second column: "Nun lauffetzw..." -->
</div>
and so on ...
```
Please note that this approach requires the intermingling of `<div>` and `<mdiv>` elements, which is not currently allowed.  Doing so would take us very close to what TEI accomplishes with its `<notatedMusic>` element.

**Comment by pe-ro** [comment]
Actually, the separated lyrics can already been represented --
```
<mdiv>
  <!-- The preceding song -->
  <score>
    <scoreDef/>
    <section>
      <measure>
        <staff>
          <layer/>
        </staff>
      </measure>
    </section>
    <pb n="75"/>
    <div>
      <!-- <div cols="2"> -->
      <!-- <cb col="1"/> -->
      <lg type="verse" n="1">
        <l>Mein leiden...</l>
      </lg>
      <!-- <cb col="2"/> -->
      <lg type="verse" n="2">
        <l>Dy tagweys...</l>
      </lg>
    </div>
    <div>
      <p>Die Melodie...</p>
    </div>
  </score>
</mdiv>
```
The lyrics at the top of p. 75 are marked up as part of the song (presumed to be) on the preceding page.  The only thing that's missing is the column layout.  That could be supplied using `div/@cols` and `cb` elements.

**Comment by th-we** [comment]
I find the `<colLayout>` suggestion really convincing. I really like the milestone approach as it does not force structuring of musical content based on merely visual appearance.  Two made-up use cases where the milestonIn the hypothetical case that a song starts in one-column layout on one page and switches to two-column layout on the next in the midst of a verse, putting the verse into two `<mdiv>` just because of a change in layout doesn't feel right.

 because you could easily describe different layouts of different sources using milestones, but not

**Comment by th-we** [comment]
I find the `<colLayout>` suggestion really convincing as the milestone approach does not force structuring of musical content based merely on visual appearance.  Some made-up use cases to illustrate that:

* There are two sources, using differing numbers of columns.  The milestone approach can nicely describe both layouts while we can't have multiple `@col` attributes on `<div>` or `<mdiv>`.
* A song starts in one-column layout on one page and switches to two-column layout on the next at an arbitrary measure in the midst of the song. Splitting the song into two `<mdiv>`s just because of a change in layout would be questionable.
* Both the described scenarios combined: Two sources switch from one-column layout to two-column layout at different places. Without `<colLayout>` as a milestone, that would break the hierarchy.

**Comment by pe-ro** [comment]
Here's the ODD that adds `<colLayout>` and `<cb>` --
```
<elementSpec ident="colLayout" module="MEI.shared" mode="add">
  <desc>(column layout) – An empty formatting element that signals the start of columnar
    layout.</desc>
  <classes>
    <memberOf key="att.common"/>
    <memberOf key="att.source"/>
    <memberOf key="model.milestoneLike.music"/>
    <memberOf key="model.milestoneLike.text"/>
  </classes>
  <content>
    <rng:empty/>
  </content>
  <attList>
    <attDef ident="cols" usage="req">
      <desc>Records the number of columns.</desc>
      <datatype>
        <rng:data type="positiveInteger"/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="cb" module="MEI.shared" mode="add">
  <desc>(column break) – An empty formatting element that forces text to begin in a new
    column.</desc>
  <classes>
    <memberOf key="att.basic"/>
    <memberOf key="att.facsimile"/>
    <memberOf key="att.labelled"/>
    <memberOf key="att.linking"/>
    <memberOf key="att.source"/>
    <memberOf key="att.typed"/>
    <memberOf key="model.milestoneLike.music"/>
    <memberOf key="model.milestoneLike.text"/>
  </classes>
  <content>
    <rng:empty/>
  </content>
  <attList>
    <attDef ident="n" usage="req">
      <desc>Records the column number.</desc>
      <datatype>
        <rng:data type="positiveInteger"/>
      </datatype>
      <constraintSpec ident="check_cb" scheme="isoschematron">
        <constraint>
          <sch:rule context="mei:cb">
            <sch:let name="totalColumns" value="preceding::mei:colLayout[1]/@cols"/>
            <sch:assert test="preceding::mei:colLayout">Column break must be preceded by a
              colLayout element.</sch:assert>
            <sch:assert test="@n &lt;= $totalColumns">The value of @n should be less than or
              equal to the value of @cols (<sch:value-of select="$totalColumns"/>) of the
              preceding colLayout element.</sch:assert>
          </sch:rule>
        </constraint>
      </constraintSpec>
    </attDef>
  </attList>
  <remarks>
    <p>This element is modelled on an element in the Text Encoding Initiative (TEI)
      standard.</p>
  </remarks>
</elementSpec>
```
This will allow the new elements to occur in lots of places -- inline in text, between text components (such as paragraphs, lists, etc.), and anywhere a system break can occur.  They can also occur inside editorial and transcriptional elements (add, del, orig, reg, etc.), meaning there's a lot of rope here with which to hang one's self.

There's a Schematron rule that attempts to make sure that all `<cb>` elements are preceded by `<colLayout>` and that `cb/@n` isn't greater than the number of intended columns.

Example of use --
```
<div>
  <colLayout cols="2"/>
  <cb n="1"/>
  <lg type="verse" n="1">
    <l>Mein leiden...</l>
  </lg>
  <cb n="2"/>
  <lg type="verse" n="2">
    <l>Dy tagweys...</l>
  </lg>
</div>
```

**Comment by pe-ro** [comment]
In addition, I want to remind everyone that there's also a `@page.panels` attribute that's available on `<scoreDef>` to record the number of "panels" / "surfaces" / "areas" per page.  This is intended to be used for printed output.  For example, when `page.panels="2"` printed output should have a 2-column layout.  The idea was that this would be accomplished by rendering two logical pages on a single physical page by reducing them in size.  So, this doesn't interfere with the provision of `<colLayout>` and `<cb>`.
