### ISSUE TITLE
<accessRestrict> not available within <availability>

### ISSUE THREAD

**Issue by annplaksin** [music-encoding/music-encoding#269]
When using `<accessRestrict>` within `<availability>` I get a validation error although it should work according to the Guidelines at the website. (see http://music-encoding.org/documentation/2.1.1/availability/)
Looking into the source I saw the elementSpec of `<accessRestrict>` is defined as a member of model.availabilityPart but this class is never specified. There is only macro.availabilityPart specified.

Is this a little bug or is it wrong to use `<accessRestrict>` within `<availability>`? I'm a little bit confused...

**Comment by ahankinson** [comment]
Edit: I've added code formatting since GitHub eats XML tags if they're not formatted as code.

**Comment by pe-ro** [comment]
There's definitely a bug here.  I'll look into fixing it.

**Comment by pe-ro** [comment]
Wait.  There's no bug, you just have to use `<acqSource>` first, then you can specify access restrictions.  For example,

```
<availability>
  <acqSource>Get "it" from here</acqSource>
  <accessRestrict>Restrictions on who can get "it" go here.</accessRestrict>
  <useRestrict>Restrictions on uses of "it" go here.</useRestrict>
</availability>
```

Without an explanation of "where" to get it, access restrictions don't make sense.  But, this model may be too restrictive.  Can you provide a description of what you're trying to accomplish?

Since model.availabilityPart is never referenced, I've removed the declarations of membership in it to avoid confusion.

**Comment by annplaksin** [comment]
Thank you for clarifying this topic. So I just didn't understand the way to use this part of the header.
I was looking for a way to store links to digitised sources and information about the accessability of them, e.g. if it is free or if you need anything special to access it. Because I stored the the information about the provider elsewhere I didn't think about using `<acqSource>`.

I want(ed) to use it in this way:

```
<pubStmt>
  <distributor>
     <corpName>name of distributing institution</corpName>
     <ptr target="link-to-source">
  </distributor>
  <availability>
     <accessRestrict>free / only with login etc.</accessRestrict>
  </availability>
</pubStmt>
```

But maybe I have to improve this. Any suggestions?

PS: And thanks to Andrew for pointing to code formatting...

**Comment by pe-ro** [comment]
Move the content of `<distributor>` to `<acqSource>` --

```
<pubStmt>
  <availability>
    <acqSource>
      <corpName>name of distributing institution</corpName>
      <ptr target="link-to-source"/>
    </acqSource>
    <accessRestrict>free / only with login etc.</accessRestrict>
  </availability>
</pubStmt>
```

`<pubStmt>` needs more review at some point.  Thanks for "testing it out".  Please raise a flag if you find other weirdness.

**Comment by annplaksin** [comment]
Moving to `<acqSource>` is a good idea. Thanks for this advice!
