### ISSUE TITLE
Front doesn't allow mixes of div and pb

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#270]
I have the following markup:

```
<front>
    <div><p></p></div>
    <pb />
    <div><p></p></div>
</front>
```

The validators are saying that I'm not allowed to have the second div element following a pb. It will let me put as many div elements before the pb, but not afterwards.

@pe-ro is working on a fix. This is just filed to track this issue.

**Comment by pe-ro** [comment]
Changed content model of `<front>` to

```
<content>
  <rng:zeroOrMore>
    <rng:choice>
      <rng:ref name="model.divLike"/>
      <rng:ref name="model.frontPart"/>
      <rng:ref name="model.milestoneLike.text"/>
    </rng:choice>
  </rng:zeroOrMore>
</content>
```

This allows interleaving of any number of div, titlePage, pb and lb elements.  The prior model was too clever by half.  :-)

**Comment by ahankinson** [comment]
Perfect, thanks!

**Comment by ahankinson** [comment]
I just added a small test for this change.
