### ISSUE TITLE
new ligature elements

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#274]
Currently, MEI provides a `<ligature>` element to identify ligatures in mensural notation.  It is _not_ intended for use in the CMN repertoire where notes are marked with a so-called 'ligature' (usually rendered as a bracket) to indicate notes that were part of a ligature _in a mensural notation original document_.  The definition of the `<ligature>` element could be expanded to include CMN usage, but because these structures in CMN can cut across measure boundaries, another stand-off element, provisionally named `<ligatureSpan>`, would have to be created at the same time.

On the other hand, ligatures in mensural notation and those in CMN are _not_ the same thing.  So, it might be best to provide differently-named elements for each repertoire.  For example, `<ligature>` could be used exclusively in mensural notation, while `<lig>` and `<ligSpan>` could be used in CMN.

**Comment by lpugin** [comment]
I would vote for `ligatureSpan`, but maybe I am missing a point concerning the use of ligatures in CMN. If the primarily purpose of the element is to represent mensural ligatures in CMN transcriptions, then I would not change the name to `lig` and `ligSpan`.

**Comment by pe-ro** [comment]
I'm concerned that ligatures in Mensural notation and in CMN serve different purposes.  Since they're an integral part of the notation, ligatures in Mensural notation have an existence in the logical domain, while ligatures in CMN have a more editorial and therefore visual function.  It's a subtle difference, but the `<ligature>` element in Mensural notation indicates an alteration of rhythm, while a so-called ligature in CMN says only "this is where a ligature _used_ to be".  In addition, I don't see the need for `<ligatureSpan>` in Mensural markup simply because, without barlines, there's no hierarchy to span.

To be useful in CMN, a ligature-like element would need many of the same attributes as other so-called "control events" (`@tstamp, @tstamp2, @tstamp.ges, @dur, etc.`) and several attributes (e.g., `@lform, @lwidth`, etc.) that have to do with the way ligature indications are presented visually in CMN. The appearance of these on `<ligature>` in Mensural notation would lead to a great deal of confusion.  So, I think it would be better to clearly separate ligatures in CMN from those in Mensural notation by giving them different names.

A possible compromise would be to provide `<ligatureSpan>` only in the CMN repertoire and  `<ligature>` only in the Mensural repertoire. This would facilitate the separation of attributes mentioned above.  Confusion over the use of one or the other would not be alleviated, however, if one were using mei-all.

**Comment by lpugin** [comment]
Having `ligature` in Mensural and `ligatureSpan` in CMN sounds like a good compromise to me. The possible confusion when using mei-all exists elsewhere in significantly more serious ways, I think. For example with possible values in duration that can include "breve" and "brevis".

Also, having only a spanning ligature element in CMN (and no containing element) seems appropriate to me, but again, I am maybe missing a point about the use of ligatures in CMN.

**Comment by lpugin** [comment]
Any other comment on this? Otherwise I am going to add `ligatureSpan` as suggested by @pe-ro

**Comment by pe-ro** [comment]
Add to Verovio?  

Since we haven't yet worked out the difference between ligatures in mensural notation vs. CMN, can you delay implementation until MEI v. 4?

**Comment by lpugin** [comment]
To both MEI and Verovio. I can wait v. 4., but I would add them to develop as soon as 3.0.0 is out.

The difference seems clear to me: the typical use of ligatureSpan will be for indicating in CMN original ligatures. They will very often be spanning across several measures and cannot be represented with ligature elements.

**Comment by pe-ro** [comment]
I've already started a version 4.0 customization.  As soon as we finalize 3.0, we can start putting the things in the customization into the development version in Git.

I don't want to belabor the point, but technically CMN doesn't have ligatures -- it has indications of where ligatures occurred in the original mensural source of the transcription.  Putting `ligatureSpan` in the CMN module should help to make this distinction, but won't prevent mixing `ligature` and `ligatureSpan` if mei-all is used.  In addition, `ligatureSpan` must have visual domain attributes (such as those covering the drawing of the line/bracket) that won't be available on `ligature`.  The Mensural IG may also suggest new attributes for `ligature`.
