### ISSUE TITLE
<hairpin> throws validation error with `@layer` 

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#276]
When validating a `<hairpin>` element I get:

`element hairpin: Relax-NG validity error : Invalid attribute layer for element hairpin`

In MEI 2.1.1, `@layer` is definitely allowed. It seems like it should be allowed in 3.0.0, but I can't confirm this. Was `@layer` removed from this in 3.0.0?

**Comment by ahankinson** [comment]
I also get the same error for `<trill>`.

**Comment by pe-ro** [comment]
`@layer` is definitely available in 3.0.0 -- `<hairpin>` is a member of `att.hairpin.log`, which is a member of `att.controlevent`, which is a member of `att.layerident`, which defines `@layer`. Whew!

I have no problem validating `<hairpin form="cres" tstamp="1.25" tstamp2="0m+1" layer="3"/>` or `<trill xml:id="trill01" tstamp="1" layer="4"/>`.

What is the error message you're getting?

**Comment by pe-ro** [comment]
Didn't read your original message carefully enough.  Sorry.  What parser are you using?

**Comment by ahankinson** [comment]
I'm using xmllint.

**Comment by pe-ro** [comment]
Do you get an error from oXygen?  If you don't have it, you can mail me your markup and I'll give it a go.

Are you using a schema generated from develop-perry or something else?  Can you mail me the schema too please?

**Comment by ahankinson** [comment]
I figured out the problem with this -- the validation error was misleading. The value of `@hairpin` in the problematic files was `0`. Changing it to a value `>0` fixed it.
