### ISSUE TITLE
Add <listHead>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#281]
EAD provides a formatting element called <listHead> that could be useful for formatting lists in MEI, <eventList> in particular, though it could be applied to any list which precedes each item with a label; in other words, a "gloss" or "definition" kind of list.

**Comment by bwbohl** [comment]
I was looking how to do this in MEI just recently ;-)
I like the way [EAD](https://www.loc.gov/ead/tglib/elements/list.html) encloses label and list item in a defitem, e.g.:

```XML
<list>
    <defitem>
        <label>labeltext</label>
        <item>items stuff</item>
    </defitem>
</list>
```

as opposed to the loose association in TEI.

**Comment by pe-ro** [comment]
Closing for now due to lack of interest. 😄
