### ISSUE TITLE
several <mdiv> 

### ISSUE THREAD

**Issue by shino-funayama** [music-encoding/music-encoding#287]
In order to encode some harmonic studies from Max Reger.Alltogether there are six different (mdiv) for six different groups of tonalities, namely C-major, C sharp-major, a-minor, C flat-major, d flat-minor and a sharp-minor. Each (mdiv) has a (score) and multiple (section) as modulation examples.
In Verivio is only shown the first (mdiv). That means that we can see in Verovio only examples of C-major. Has someone an idea about how to show several (mdiv) in Verovio?

**Comment by ahankinson** [comment]
Hi Shino,

You should file any Verovio rendering issues on the Verovio GitHub repository, available here:

https://github.com/rism-ch/verovio

I will close the issues that you filed that should be directed there, but please, if you feel that this is a core MEI problem, re-open them with a justification for why you think so and we'll take it from there.
