### ISSUE TITLE
<choise> 

### ISSUE THREAD

**Issue by shino-funayama** [music-encoding/music-encoding#288]
This is about major and minor cadence in one example. We have taken (choice) here and two different variations as input. But in Verovio (choice) is not displayed. Does anyone have ideas?
![frage2](https://cloud.githubusercontent.com/assets/16317856/11854098/ee2442b0-a441-11e5-8056-8d0c0e7069ec.JPG)

**Comment by ahankinson** [comment]
Should be filed at rism-ch/verovio
