### ISSUE TITLE
 two notes side by side?

### ISSUE THREAD

**Issue by shino-funayama** [music-encoding/music-encoding#289]
It's about two different note values of two different voices which, however, have the same pitch. They appear to overlap in verovio. Is it somehow possible to display two notes side by side?
![frage3](https://cloud.githubusercontent.com/assets/16317856/11854287/346bb586-a443-11e5-98e7-42b038e21c65.JPG)

**Comment by ahankinson** [comment]
Should be filed at rism-ch/verovio
