### ISSUE TITLE
encode a clip 

### ISSUE THREAD

**Issue by shino-funayama** [music-encoding/music-encoding#291]
How can I encode a clip without (choice)?
![frage5](https://cloud.githubusercontent.com/assets/16317856/11854449/44685f60-a444-11e5-95d9-b580ac4a3c9d.JPG)

**Comment by ahankinson** [comment]
Unclear if this is a rendering issue or an encoding issue. Could you please elaborate?

**Comment by pe-ro** [comment]
The term "clip" is confusing.  Do you mean parenthesis?

To capture attributes of the accidental, it should be encoded using <accid>, not `@accid`.  For example,

```
<note pname="b" dur="4" oct="4">
  <accid accid="n" enclose="paren"/>
</note>
```

**Comment by shino-funayama** [comment]
Thank you for your answer!
I mean here parenthesis.
Excuse me please
Because I can not English well,I badly translated into English.

I think that's rendering issue.
Although we have properly coded, in Verovio is not displyed correctly.

2015-12-17 19:42 GMT+01:00 pe-ro notifications@github.com:

> The term "clip" is confusing. Do you mean parenthesis?
> 
> To capture attributes of the accidental, it should be encoded using , not
> @accid. For example,
> 
> <note pname="b" dur="4" oct="4">
>   <accid accid="n" enclose="paren"/>
> </note>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/music-encoding/music-encoding/issues/291#issuecomment-165543832
> .

## 

_Shino Funayama (舟山 詩乃)_

Post: Greiteler Gärten 14
           33102 Paderborn

Email: shino.funayama@gmail.com

Telefon: 0176 20 44 70 33
