### ISSUE TITLE
double signs at a note

### ISSUE THREAD

**Issue by shino-funayama** [music-encoding/music-encoding#292]
How can at a note  a  natural and a sharp side by side be encoded? In Verovio this is not displayed correctly.
![frage6](https://cloud.githubusercontent.com/assets/16317856/11854537/caff2298-a444-11e5-8755-d8618c38e8fe.JPG)

**Comment by ahankinson** [comment]
This looks like a Verovio issue and should be filed at rism-ch/verovio
