### ISSUE TITLE
Scaling element with att.typography

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#294]
att.typography has a fontsize attribute for specifying point size. In many cases, however, determining a point font size is not straightforward. It would probably be useful to be able to specify the size in a more general (or relative) way. Having a scale attribute for specifying a percentage would be more appropriate in many case. Values as in CSS (small, x-small, etc.) could be another option.

**Comment by th-we** [comment]
`att.typography` and [`data.TEXTRENDITION`](http://music-encoding.org/documentation/2.1.1/data.TEXTRENDITION/) are doing sort of the same thing. Maybe both should be unified?  `data.TEXTRENDITION` already covers the qualitative CSS property values, but in a rather unstructured way. Not sure whether I read the syntax declaration correctly, but it mixes both CSS property names and property values (like `line-height` plus a number value, i.e. a name-value pair, as well as just `small`, i.e. just a value without a property name).

This might be related to issue #144.

**Comment by pe-ro** [comment]
You're reading the declaration correctly.  The addition of the font-related attributes to `<rend>` causes the confusion/redundancy.  My plan is to remove the font size related values  (xx-small, x-small, small, medium, large, x-large, xx-large, smaller, and larger) from data.TEXTRENDITION and then allow them in `@fontsize`.  `@fontsize` will also be allowed to have percentage values.  It will continue to allow numeric values as well.  So, any of the following should work:

```
fontsize="12pt"
fontsize="125%"
fontsize="small"
```

Older files using `@rend="small"`, etc. can be up-converted with a stylesheet.
