### ISSUE TITLE
Add attribute to specify which piano pedal is used

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#308]
Currently there's no indication on `<pedal>` of **which pedal to use**. Most often, pedal indications are for the sustain/damper pedal, but that's not always true.  One could rely on `@type` to make this distinction, but that attribute should be reserved for _ad hoc_ extension and classification.

Adding `@func` (function) with a semi-open value list is a reasonable approach, I think.  Possible values include:
- "unacorda" (or "piano", "soft")
- "sostenuto"
- "sustain" (or "damper", "loud", "forte", "open")
- "practice" (or "half-blow")

Since there's wide variation in the text associated with pedal markings, such as "una corda", "tre corda", "sost.", etc., it will still be handled by `<dir>`.

**Comment by lpugin** [comment]
#305 also relates to pedals, just for the record

**Comment by pe-ro** [comment]
Yeah, but I thought this one was different enough and specific enough to warrant its own issue.

Out of curiosity, however, is there a way to combine/link issues (without creating a new one, of course)?
