### ISSUE TITLE
Travis build failure

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#311]
See https://travis-ci.org/music-encoding/music-encoding

**Comment by ahankinson** [comment]
I've fixed the Stylesheets build error, so it looks like now it's just that the unit tests are not passing.

**Comment by lpugin** [comment]
What do we need to do?

**Comment by rettinghaus** [comment]
Works now with 7f7f26d

**Comment by ahankinson** [comment]
Ha. Yes, it does, by completely disabling them.

**Comment by rettinghaus** [comment]
Perhaps the subject should be changed to "fix unit tests" or something?
