### ISSUE TITLE
Add support for verses split in parts

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#312]
There are cases where a verse is split in parts. The music is identical and repeated.

Possible solution: 

```
<verse n="1">
  <versePart>
    <syl>Da</syl>
  </versePart>
  <versePart>
    <syl>Der</syl>
  </versePart>
</verse>
```

That is

```
<content>
  <rng:zeroOrMore>
    <rng:choice>
      <rng:ref name="dir"/>
      <rng:ref name="dynam"/>
      <rng:ref name="tempo"/>
      <rng:ref name="space"/>
    </rng:choice>
  </rng:zeroOrMore>
  <rng:oneOrMore>
    <rng:choice>
      <rng:ref name="model.sylLike"/>
      <rng:ref name="model.appLike"/>
    </rng:choice>
  </rng:oneOrMore>
  <rng:zeroOrMore>
    <rng:ref name="model.lbLike"/>
  </rng:zeroOrMore>
</content>
```

We could also have a `@sym` on `<verse>` for the brace and a Schematron rule for checking that it is present only with `<versePart>`

Example provided by @craigsapp

![image](https://cloud.githubusercontent.com/assets/689412/16382750/6f520178-3c82-11e6-9ef8-3a185f410ce2.png)

**Comment by pe-ro** [comment]
@lpugin, @craigsapp: I think `<volta>` may be more appropriate here than `<versePart>`.  So Craig's example would be --

```
<verse n="1">
  <volta>
    <syl>Da</syl>
  </volta>
  <volta>
    <syl>Der</syl>
  </volta>
</verse>
```

I'm also thinking of creating a `<refrain>` element within which `<volta>` also works much better than `<versePart>`.  For example,

```
<refrain n="1">
  <volta>
    <syl>Do</syl>
  </volta>
  <volta>
    <syl>Di</syl>
  </volta>
</refrain>
```

`<refrain>` is intended to substitute for, and perhaps eventually replace, `<verse refrain="true">`, which is a bit of a kludge.  `<verse>` and `<refrain>` will have the same content model --

```
((dir|dynam|tempo|space)*, (syl|volta|app)+, lb*)
```

A `@symbol` attribute can be added to both elements that can take the same values as those for grouping staves -- brace, bracket, bracketsq, line, none.  However, the `@symbol` attribute for the lyric elements should be defined in its own attribute class, probably named "att.voltaGroupingSym".  This will allow it to be modified separately from att.staffGroupingSym.

My only concern is that "volta" is a fairly generic term that may be misunderstood; that is, folks may be confused by its use in this context and not for repetitions of musical content.

Thoughts?

**Comment by craigsapp** [comment]
I like `<volta>` as I associate the word with musical repetition (and don't know what it means otherwise).

**Comment by pe-ro** [comment]
I don't know that it has a meaning apart from "time" in the sense of an individual iteration of a repeated sequence, as in "3rd time".
