### ISSUE TITLE
title/languages in meiHeader 2009->2016

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#313]
Given this MEI 2009 code:

``` xml
    <fileDesc>
      <titleStmt>
        <title type="main" xml:lang="ger">Aus meines Herzens Grunde</title>
        <title type="translated" xml:lang="eng">From the Depths of My Heart</title>
      </titleStmt>
      <pubStmt/>
    </fileDesc>
    <profiledesc>
      <langusage>
        <language xml:id="eng" authority="iso639-2"/><!-- English -->
        <language xml:id="ger" authority="iso639-2"/><!-- German -->
      </langusage>
    </profiledesc>
```

What is the MEI 2016 expression?

Intended meaning:

> The original title in German is "Aus meines Herzens Grunde".
> The title translated into English is "From the Depths of My Heart".

**Comment by pe-ro** [comment]
`<profileDesc>` was eliminated in 2011 and its components moved to other locations.  Language(s) can be indicated at various levels.  

If you're only concerned with capturing the language of the titles, you can encoded this way --

```
<meiHead xmlns="http://www.music-encoding.org/ns/mei">
  <fileDesc>
    <titleStmt>
      <title type="main" xml:lang="ger">Aus meines Herzens Grunde</title>
      <title type="translated" xml:lang="eng">From the Depths of My Heart</title>
    </titleStmt>
    <pubStmt/>
  </fileDesc>
</meiHead>
```

This approach should suffice for the majority of cases.

If you want to capture the fact that the _work_ is German, then use  `<workDesc>` --

```
<meiHead xmlns="http://www.music-encoding.org/ns/mei">
  <fileDesc>
    <titleStmt>
      <title type="main" xml:lang="ger">Aus meines Herzens Grunde</title>
      <title type="translated" xml:lang="eng">From the Depths of My Heart</title>
    </titleStmt>
    <pubStmt/>
  </fileDesc>
  <workDesc>
    <work>
      <langUsage>
        <language authority="iso639-2" xml:id="ger"/>
      </langUsage>
    </work>
  </workDesc>
</meiHead>
```

This indicates that the _work_ is in German, but attaches the German and English-translated titles to the _file_. In other words, the language of the work and the language of the title(s) are independent of each other.
