### ISSUE TITLE
Make <language> member of att.canonical

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#315]
`@xml:id` can't be used to hold the coded value of `<language>` as `<language>` may be used in multiple locations, for example --

```
<meiHead xmlns="http://www.music-encoding.org/ns/mei">
  <fileDesc>
    <titleStmt>
      <title type="main" xml:lang="ger">Aus meines Herzens Grunde</title>
      <title type="translated" xml:lang="eng">From the Depths of My Heart</title>
    </titleStmt>
    <pubStmt/>
    <sourceDesc>
      <source>
        <langUsage>
          <language authority="iso639-2" xml:id="ger"/>
          <language authority="iso639-2" xml:id="eng"/>
        </langUsage>
      </source>
    </sourceDesc>
  </fileDesc>
  <workDesc>
    <work>
      <langUsage>
        <language authority="iso639-2" xml:id="ger"/>
      </langUsage>
    </work>
  </workDesc>
</meiHead>
```

Therefore, `@codedval` should be used instead --

```
<meiHead xmlns="http://www.music-encoding.org/ns/mei">
  <fileDesc>
    <titleStmt>
      <title type="main" xml:lang="ger">Aus meines Herzens Grunde</title>
      <title type="translated" xml:lang="eng">From the Depths of My Heart</title>
    </titleStmt>
    <pubStmt/>
    <sourceDesc>
      <source>
        <langUsage>
          <language authority="iso639-2" codedval="ger"/>
          <language authority="iso639-2" codedval="eng"/>
        </langUsage>
      </source>
    </sourceDesc>
  </fileDesc>
  <workDesc>
    <work>
      <langUsage>
        <language authority="iso639-2" codedval="ger"/>
      </langUsage>
    </work>
  </workDesc>
</meiHead>
```

**Comment by craigsapp** [comment]
> `@xml:id` can't be used to hold the coded value of `<language>` as `<language>` may be used in multiple locations.

You were the one who told me to do it that way :-)

Using @codedval definitely looks better, particularly trying to enforce a unique id
- Why is @xml:lang in fileDesc/titleStmt/title and the language elaboration in fileDesc/sourceDesc/source/langUsage?  
- @authuri might be good to add? Can I add any random string, such as you did for http://www.music-encoding.org/ns/mei?  For example https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt .

The MEI 3.0.0 documentation says that `@xml:lang` should be as "defined in BCP 47".

> @xml:lang (optional) Identifies the language of the element's content. The values for this attribute are language 'tags' as defined in BCP 47. All language tags that make use of private use sub-tags must be documented in a corresponding language element in the MEI header whose id attribute is the same as the language tag's value. Value of datatype language.

It would be useful to put a _hyperlink_ to BCP 47 in the documentation: https://tools.ietf.org/html/bcp47 (and to any other standards/specifications mentioned in the documentation).

ISO-639 is the starting point for BCP 47 (I will check what the difference between ISO-639 and ISO-639.2 in my next life...):

```
langtag       = language
                 ["-" script]
                 ["-" region]
                 *("-" variant)
                 *("-" extension)
                 ["-" privateuse]

 language      = 2*3ALPHA            ; shortest ISO 639 code
                 ["-" extlang]       ; sometimes followed by
                                     ; extended language subtags
               / 4ALPHA              ; or reserved for future use
               / 5*8ALPHA            ; or registered language subtag
```

So since @xml:lang is required (suggested?) to be BCP 47, perhaps the `<langUsage>` declarations are not necessary?  I will change "eng" to "en" and "ger" to "de", which is what the original encoding in Humdrum is using anyway: 

```
!!!OTL@@DE:     Aus meines Herzens Grunde
!!!OTL@EN:      From the Depths of My Heart
```

**Comment by pe-ro** [comment]
The earlier versions of MEI only allowed `<langUsage>` to occur one time, so using `@xml:id` to hold the coded value was fine.  Now that that's no longer true, we have to move to `@codedval`, which is better anyway as it's more consistent with similar markup elsewhere in MEI.

`<langUsage>` occurs in several locations -- `<work>`, `<source>`, and `<expression>` -- to accommodate situations where each of these uses different languages.  In the example I started this issue with (based on your example), the original work is in German, but the source of the work being encoded adds translated titles and probably English metatext (preface, etc.) as well.  `<langUsage>` records the use of language in general. `@xml:lang` captures the language of a given title, name, etc.

`@authority` and `@authURI` are already allowed on `<language>`. `@authURI` isn't a "random string" of course. :-)  But, yes, you can put any URI there.

I'll create another issue for adding a link to BCP 47 in the documentation, within the description of `@xml:lang` and/or somewhere in the Guidelines.

ISO 639-1 provides 2-letter codes, while ISO 639-2 uses 3-letter codes. BCP 47 adds support region, script, variant, etc.

**Comment by craigsapp** [comment]
BCP 47 is interesting in the sense that the short, harmonized German folksongs which I have been using as test encodings of Humdrum to MEI are from before German spelling reformation of 1901:

https://de.wikipedia.org/wiki/Orthographische_Konferenz_von_1901

I wonder if there is a way of specifying that information in BCP 47?  When there is a difference in orthography from modern German, I could provide both title variants.

gʋd lʌk rıˈfɔːmıŋ ˈıŋglıʃ ˈspelıŋ...

**Comment by pe-ro** [comment]
Check https://tools.ietf.org/html/bcp47#section-2.2.5 for info on constructing codes with language variants.  It specifically mentions German orthography.

You may also want to spend some time looking at http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry, which says "1901" is the subtag for "Traditional German orthography" and "1996" is the subtag for "German orthography of 1996".  But I can't find any subtag for pre-1901 German orthography.  For this you may want to use a different language code, such as "gmh" for Middle High German (ca. 1050-1500) or "gml" for Middle Low German.

You might also consider using`@translit` --

```
<title type="main" xml:lang="ger" translit="1901">title with post-1901 orthography</title>
<title type="alternative" xml:lang="ger">title with pre-1901 orthography</title>
```

This is a kludge to indicate a German-to-German "transliteration". `@type` is used to prioritize the titles -- "main" is the "official" one from the so-called "chief source of information", most often a title page (for a book, that is).  There's probably more librarian-ish detail in this kind of stuff than you really want to know.  :-)

**Comment by craigsapp** [comment]
> But I can't find any subtag for pre-1901 German orthography.

I can't find any either.  Here seems to be the full official subtag list:
http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

So I won't bother until some new standard comes along with a way to represent pre-1901 orthographic German spellings.

> For this you may want to use a different language code, such as "gmh" for Middle High German (ca. 1050-1500) or "gml" for Middle Low German

They are not that old :-)  Here is the editor of the series of three volumes (600 short harmonized songs):
https://de.wikipedia.org/wiki/Ludwig_Erk

**Comment by pe-ro** [comment]
I just added the following remarks to the att.lang class --

```
<remarks>
  <p>BCP 47 is described at <ref target="https://tools.ietf.org/html/bcp47">
  https://tools.ietf.org/html/bcp47</ref>. The IANA Subtag Registry, from 
  which BCP 47 language tags are constructed, may be found at 
  <ref target="www.iana.org/assignments/language-subtag-registry">
  www.iana.org/assignments/language-subtag-registry</ref>. A tool for 
  locating subtags and validating language tags is available at
  <ref target="https://r12a.github.io/apps/subtags">
  https://r12a.github.io/apps/subtags</ref>.</p>
</remarks>
```

Maybe one of our German-speaking friends can enlighten us regarding pre-1901 German orthography.
