### ISSUE TITLE
Add link to standard values for @role

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#317]
On pages such as http://music-encoding.org/documentation/3.0.0/att.name

The role attribute documentation mentions "standard values":

> @role (optional) Used to specify further information about the entity referenced by this name, for example, the occupation of a person or the status of a place. Use a standard value whenever possible. Value is plain text. att.name 

It would be useful to provide a link to what the standard values are.

**Comment by pe-ro** [comment]
See section 2.1.1 Title Statement in the Guidelines --

"Values from the MARC relator code list (http://www.loc.gov/marc/relators/relacode.html) or term list 
(http://www.loc.gov/marc/relators/relaterm.html) are recommended for `@role`, where applicable."

Element and attribute descriptions are used as tool tips in oXygen (and perhaps other software as well), but URLs are not click-able, so there's no good reason to put them in the description.  They can be added in the remarks section of the Data Dictionary entry (e.g. http://music-encoding.org/documentation/3.0.0/att.name), where they would be action-able, but then we'd end up with duplicated data.  Where there is more detail in the Guidelines than in the Dictionary (which should be true in most cases), then a link from the Dictionary to the Guidelines should be provided.

**Comment by craigsapp** [comment]
Even more clarification would be helpful.  What does _Values_ mean? The abbreviation code for the role, or more broadly the long name of the code?  For example: "cmp" or "Composer".

I would say that "Composer" is preferable above "cmp", as "cmp" is technical jargon to a non-librarian (Chimp, Chump, Campaigner, Campanist, Campanogist, Camper).  

Is there a way to indicate the the role is from a standardized list (or not from a standardized list)?  And which standard was used? :-)

An informal system I could use is to capitalize the the initial of the roll if it from the MARC relator codes, and lowercase otherwise.

> Element and attribute descriptions are used as tool tips in oXygen (and perhaps other software as well), but URLs are not click-able, so there's no good reason to put them in the description.

I don't use oxygen (if you haven't noticed :-), so that is not a problem for me.  I am using the website, and expect the links to referred concepts/resources when I am reading the documentation (as would anyone else reading the documentation).  How a hyperlink gets placed in the right location in the web documentation and where they are stored are not as important.  Of course, it should be up to oxygen to filter out the URLs when creating the tooltips...  Or perhaps you are supposed to do it yourself somehow with an XLST?

And not I know why the description of attributes are terse (you use them as tooltips).  In general the documentation of attributes on the website should be more verbose, most particularly with usage examples.  If you want a tooltip form, it should be perhaps given as a "summary" field in the documentation markup.

**Comment by craigsapp** [comment]
> Where there is more detail in the Guidelines than in the Dictionary (which should be true in most cases), then a link from the Dictionary to the Guidelines should be provided.

More links to the Guidelines would be great.  A problem is that there needs to be a technical description of elements/attributes which is more verbose than a dictionary and less wishy-washy than guidelines.  Guidelines are more an overview of how all the little bits and pieces should fit together.  A dictionary gives a succinct summary of the individual bits.  But there is a need of a more elaborate description of the bits, most noticeably adding usage and case examples for the bits.

Also a general problem is that the Guidelines on music-encoding.org are not searchable, so that makes them less useful for reference documentation.  A simple solution would be to provide a single-page version of the documentation, then I could use the browser's search tool.  Otherwise another possible solution would be to provide an index of terms and concepts with the guidlines (like a book index, but is harder to implement effectively for webpages).

It would also be useful to have valid content at these URLS:
    http://music-encoding.org/documentation/3.0.0/
         which would point to  http://music-encoding.org/documentation/3.0.0/chapters/
and   http://music-encoding.org/documentation
which contains a list of documentation resources (the current spec and a list of the historic specs, mei-1st tutorial, etc).

As a comparison, there is the Humdrum User Guide, and the Humdrum Reference Manual.  The Guide is for learning the basic concepts, and the reference guide for how to use the tools with detailed descriptions of all of the options which tools posses and technical descriptions of the data representations.  I read the user guide once, and now only refer to the reference manual (more or less).    Likewise, SCORE has a User Guide and Reference Manual.  And likewise, I read the guide once, and refer now to only the reference manual.

**Comment by pe-ro** [comment]
Elements that have `@role` also provide `@authority` and `@authURI`, so yes, there's a way to indicate where a value in `@role` comes from.  When both of these attributes are missing, the value in `@role` is assumed to be user-defined.

You say there's a need for 3 things -- guidelines, dictionary, and something in between -- but then you provide examples where there are only 2 parts -- user guide and reference manual.  Which is it, 2 or 3?
If it's 2, then I think we have the right approach already -- basic concepts and examples (Guidelines) + technical descriptions (Data Dictionary).  As far as I'm concerned the titles of the parts aren't important.  If 3 pieces are needed, then are you volunteering to re-write everything?   I'd be happy to relinquish my role as editor of the Guidelines.

I agree that searching on the web site is less than ideal. Perhaps @kepper can address this, but it is WordPress, after all.

**Comment by craigsapp** [comment]
> You say there's a need for 3 things -- guidelines, dictionary, and something in between -- but then you provide examples where there are only 2 parts -- user guide and reference manual. Which is it, 2 or 3?

For me it would be 2: guidelines which are a top-down form of documentation, and reference manual which is a bottom-up form of documentation.  The Data Dictionary is serving as the bottom-up documentation, but there is a need for more elaboration.  This elaboration could be interleaved or appended to the guidelines, so I am not necessarily advocating for a total different organization from the current. There is no need to get rid of the dictionary as it already exists (which is why I was saying 3).  It can be an entry in the more verbose form of the technical documentation.  For example, unix man pages have a "synopsis" section which could function as the current dictionary entries.  And the "description" entry would contain more detailed information, examples, crosslinks to the guidelines, etc.  The synopsis could be pulled out and used as tooltips in oXygen.

> If it's 2, then I think we have the right approach already -- basic concepts and examples (Guidelines) + technical descriptions (Data Dictionary).

Either a lot more hyperlinks between the data dictionary and the guidelines (particularly for usage examples), or more verbose dictionary is needed.

> then are you volunteering to re-write everything? I'd be happy to relinquish my role as editor of the Guidelines.

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAH!  I am trying to get Humdrum users to update the web documentation:  http://www.humdrum.org, but mostly this involves me doing all of the work :-).  Also more user-friendly documentation of MuseData would be nice, and also that would fall nearly completely on myself as well, so I haven't done more than an initial start of it.  And not to mention the documentation for the Dox format...  Anyway, you don't want to waste a programmer's time having them write documentation do you? :-)

> I agree that searching on the web site is less than ideal. Perhaps @kepper can address this, but it is WordPress, after all.

Not quite the same thing, but perhaps at the point of the next website redesign, the website could instead be generated by jekyll:
    https://jekyllrb.com/

Wordpress and jekyll are functionally equivalent.  The advantage of jekyll is that it was developed by the creator of github, so it is the preferred system for gh-pages:
    https://jekyllrb.com/docs/github-pages

It _might_ make me more interested in contributing to the documentation development.  It would also make it easier for other people to contribute to the website development, as you can change the files directly on github, and the static webpages that jekyll generates for the website are magically generated behind the scenes.

As another sidebar, you can see the website for my midifile parsing library:
    http://midifile.sapp.org
which is written in jekyll and hosted on github.

For the documentation of functions, I have pages listing all of them for the entire library:
     http://midifile.sapp.org/class
And individual pages for each class:
    http://midifile.sapp.org/class/MidiFile
on such pages, the functions are listed in short form, but you can click on a function to get the description of the function:

![screen shot 2016-06-29 at 9 56 22 am](https://cloud.githubusercontent.com/assets/3487289/16461107/c94a66d0-3ddf-11e6-9bdb-409e436c7b0d.png)

Expanding the first entry:

![screen shot 2016-06-29 at 9 57 07 am](https://cloud.githubusercontent.com/assets/3487289/16461128/e1362ba8-3ddf-11e6-865b-02ad1b726c3f.png)

The description contains a list of example usages at the bottom which in turn can be expanded:

![screen shot 2016-06-29 at 9 58 12 am](https://cloud.githubusercontent.com/assets/3487289/16461163/0eeb6c3e-3de0-11e6-9f67-2889aea1e8c4.png)

And I also include the source code for the function:

![screen shot 2016-06-29 at 9 58 59 am](https://cloud.githubusercontent.com/assets/3487289/16461176/26ecce22-3de0-11e6-8485-ee52b268ea5f.png)

All of the documentation originates from structured files.  I have separate documentation files describing each function:
     https://github.com/craigsapp/midifile/tree/gh-pages/class/MidiFile
such as in this case:
    https://github.com/craigsapp/midifile/blob/gh-pages/class/MidiFile/read.aton

Tutorial pages also contains documentation content extracted from the documentation files, see bottom of:
    http://midifile.sapp.org/tutorial/mirror

In theory these files could be edited by other github users, and the online documentation would be automatically updated (as the documentation content is generated dynamically on the webpages from the documentation files with JavaScript. 

(the source code is inserted automatically):

``` cpp
@@BEGIN:    FunctionDocumentation
@INDEXED:   yes
@CLASSNAME: MidiFile
@METHOD:    read
@ACCESS:    public
@RETURN:    int
@PARAMETERS:    const char* filename
@PARAMETERS:    const string& filename
@PARAMETERS:    istream& input
@FILE:      MidiFile.cpp
@LINES:     186-523
@SEEALSO:   
@SHORTDESC: Read a Standard MIDI File in binary or ASCII formats.
@LONGDESC:  Parse a Standard MIDI File from either a file or from
        an already opened input stream, and store its contents
        in the MidiFile object.  The function can also handle
        ASCII text input that describes a Stadard MIDI file in
        the binasc format (either as hex byte codes, or in
        more structured content).

@@BEGIN: EXAMPLE
@DESCRIPTION: Read a MidiFile from a file with the read() function.
@CODE:
#include "MidiFile.h"

int main(void) {
   MidiFile midifile;
   MidiFile midifile.read("test.mid");
   return 0;
}
@OUTPUT:
@@END:  EXAMPLE

@@BEGIN: EXAMPLE
@DESCRIPTION: Use the MidiFile constructor to read from a file.
@CODE:
#include "MidiFile.h"

int main(void) {
   MidiFile midifile("test.mid");
   return 0;
}
@OUTPUT:
@@END:  EXAMPLE

@SRCCODE:

//////////////////////////////
//
// MidiFile::read -- Parse a Standard MIDI File and store its contents
//      in the object.
//

int MidiFile::read(const char* filename) {
   rwstatus = 1;
   timemapvalid = 0;
   if (filename != NULL) {
      setFilename(filename);
   }

   fstream input;
   input.open(filename, ios::binary | ios::in);

   if (!input.is_open()) {
      return 0;
   }

   rwstatus = MidiFile::read(input);
   return rwstatus;
}


//
// string version of read().
//


int MidiFile::read(const string&amp; filename) {
   timemapvalid = 0;
   setFilename(filename);
   rwstatus = 1;

   fstream input;
   input.open(filename.data(), ios::binary | ios::in);

   if (!input.is_open()) {
      return 0;
   }

   rwstatus = MidiFile::read(input);
   return rwstatus;
}


//
// istream version of read().
//

int MidiFile::read(istream&amp; input) {
   rwstatus = 1;
   if (input.peek() != 'M') {
      // If the first byte in the input stream is not 'M', then presume that
      // the MIDI file is in the binasc format which is an ASCII representation
      // of the MIDI file.  Convert the binasc content into binary content and
      // then continue reading with this function.
      stringstream binarydata;
      Binasc binasc;
      binasc.writeToBinary(binarydata, input);
      binarydata.seekg(0, ios_base::beg);
      if (binarydata.peek() != 'M') {
         cerr &lt;&lt; "Bad MIDI data input" &lt;&lt; endl;
     rwstatus = 0;
         return rwstatus;
      } else {
         rwstatus = read(binarydata);
         return rwstatus;
      }
   }

   const char* filename = getFilename();

   int    character;
   // uchar  buffer[123456] = {0};
   ulong  longdata;
   ushort shortdata;


   // Read the MIDI header (4 bytes of ID, 4 byte data size,
   // anticipated 6 bytes of data.

   character = input.get();
   if (character == EOF) {
      cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'M' at first byte, but found nothing." &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   } else if (character != 'M') {
      cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'M' at first byte but got '"
           &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   }

   character = input.get();
   if (character == EOF) {
      cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'T' at first byte, but found nothing." &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   } else if (character != 'T') {
      cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'T' at first byte but got '"
           &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   }

   character = input.get();
   if (character == EOF) {
      cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'h' at first byte, but found nothing." &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   } else if (character != 'h') {
      cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'h' at first byte but got '"
           &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   }

   character = input.get();
   if (character == EOF) {
      cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'd' at first byte, but found nothing." &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   } else if (character != 'd') {
      cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
      cerr &lt;&lt; "Expecting 'd' at first byte but got '"
           &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   }

   // read header size (allow larger header size?)
   longdata = MidiFile::readLittleEndian4Bytes(input);
   if (longdata != 6) {
      cerr &lt;&lt; "File " &lt;&lt; filename
           &lt;&lt; " is not a MIDI 1.0 Standard MIDI file." &lt;&lt; endl;
      cerr &lt;&lt; "The header size is " &lt;&lt; longdata &lt;&lt; " bytes." &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   }

   // Header parameter #1: format type
   int type;
   shortdata = MidiFile::readLittleEndian2Bytes(input);
   switch (shortdata) {
      case 0:
         type = 0;
         break;
      case 1:
         type = 1;
         break;
      case 2:    // Type-2 MIDI files should probably be allowed as well.
      default:
         cerr &lt;&lt; "Error: cannot handle a type-" &lt;&lt; shortdata
              &lt;&lt; " MIDI file" &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
   }

   // Header parameter #2: track count
   int tracks;
   shortdata = MidiFile::readLittleEndian2Bytes(input);
   if (type == 0 &amp;&amp; shortdata != 1) {
      cerr &lt;&lt; "Error: Type 0 MIDI file can only contain one track" &lt;&lt; endl;
      cerr &lt;&lt; "Instead track count is: " &lt;&lt; shortdata &lt;&lt; endl;
      rwstatus = 0; return rwstatus;
   } else {
      tracks = shortdata;
   }
   clear();
   if (events[0] != NULL) {
      delete events[0];
   }
   events.resize(tracks);
   for (int z=0; z&lt;tracks; z++) {
      events[z] = new MidiEventList;
      events[z]-&gt;reserve(10000);   // Initialize with 10,000 event storage.
      events[z]-&gt;clear();
   }

   // Header parameter #3: Ticks per quarter note
   shortdata = MidiFile::readLittleEndian2Bytes(input);
   if (shortdata &gt;= 0x8000) {
      int framespersecond = ((!(shortdata &gt;&gt; 8))+1) &amp; 0x00ff;
      int resolution      = shortdata &amp; 0x00ff;
      switch (framespersecond) {
         case 232:  framespersecond = 24; break;
         case 231:  framespersecond = 25; break;
         case 227:  framespersecond = 29; break;
         case 226:  framespersecond = 30; break;
         default:
               cerr &lt;&lt; "Warning: unknown FPS: " &lt;&lt; framespersecond &lt;&lt; endl;
               framespersecond = 255 - framespersecond + 1;
               cerr &lt;&lt; "Setting FPS to " &lt;&lt; framespersecond &lt;&lt; endl;
      }
      // actually ticks per second (except for frame=29 (drop frame)):
      ticksPerQuarterNote = shortdata;

      cerr &lt;&lt; "SMPTE ticks: " &lt;&lt; ticksPerQuarterNote &lt;&lt; " ticks/sec" &lt;&lt; endl;
      cerr &lt;&lt; "SMPTE frames per second: " &lt;&lt; framespersecond &lt;&lt; endl;
      cerr &lt;&lt; "SMPTE frame resolution per frame: " &lt;&lt; resolution &lt;&lt; endl;
   }  else {
      ticksPerQuarterNote = shortdata;
   }


   //////////////////////////////////////////////////
   //
   // now read individual tracks:
   //

   uchar runningCommand;
   MidiEvent event;
   vector&lt;uchar&gt; bytes;
   int absticks;
   int xstatus;
   // int barline;

   for (int i=0; i&lt;tracks; i++) {
      runningCommand = 0;

      // cout &lt;&lt; "\nReading Track: " &lt;&lt; i + 1 &lt;&lt; flush;

      // read track header...

      character = input.get();
      if (character == EOF) {
         cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'M' at first byte in track, but found nothing."
              &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      } else if (character != 'M') {
         cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'M' at first byte in track but got '"
              &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      }

      character = input.get();
      if (character == EOF) {
         cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'T' at first byte in track, but found nothing."
              &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      } else if (character != 'T') {
         cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'T' at first byte in track but got '"
              &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      }

      character = input.get();
      if (character == EOF) {
         cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'r' at first byte in track, but found nothing."
              &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      } else if (character != 'r') {
         cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'r' at first byte in track but got '"
              &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      }

      character = input.get();
      if (character == EOF) {
         cerr &lt;&lt; "In file " &lt;&lt; filename &lt;&lt; ": unexpected end of file." &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'k' at first byte in track, but found nothing."
              &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      } else if (character != 'k') {
         cerr &lt;&lt; "File " &lt;&lt; filename &lt;&lt; " is not a MIDI file" &lt;&lt; endl;
         cerr &lt;&lt; "Expecting 'k' at first byte in track but got '"
              &lt;&lt; character &lt;&lt; "'" &lt;&lt; endl;
         rwstatus = 0; return rwstatus;
      }

      // Now read track chunk size and throw it away because it is
      // not really necessary since the track MUST end with an
      // end of track meta event, and many MIDI files found in the wild
      // do not correctly give the track size.
      longdata = MidiFile::readLittleEndian4Bytes(input);

      // set the size of the track allocation so that it might
      // approximately fit the data.
      events[i]-&gt;reserve((int)longdata/2);
      events[i]-&gt;clear();

      // process the track
      absticks = 0;
      // barline = 1;
      while (!input.eof()) {
         longdata = readVLValue(input);
         //cout &lt;&lt; "ticks = " &lt;&lt; longdata &lt;&lt; endl;
         absticks += longdata;
         xstatus = extractMidiData(input, bytes, runningCommand);
         if (xstatus == 0) {
            rwstatus = 0;  return rwstatus;
         }
         event.setMessage(bytes);
         //cout &lt;&lt; "command = " &lt;&lt; hex &lt;&lt; (int)event.data[0] &lt;&lt; dec &lt;&lt; endl;
         if (bytes[0] == 0xff &amp;&amp; (bytes[1] == 1 ||
             bytes[1] == 2 || bytes[1] == 3 || bytes[1] == 4)) {
           // mididata.push_back('\0');
           // cout &lt;&lt; '\t';
           // for (int m=0; m&lt;event.data[2]; m++) {
           //    cout &lt;&lt; event.data[m+3];
           // }
           // cout.flush();
         } else if (bytes[0] == 0xff &amp;&amp; bytes[1] == 0x2f) {
            // end of track message
            // uncomment out the following three lines if you don't want
            // to see the end of track message (which is always required,
            // and added automatically when a MIDI is written.
            event.tick = absticks;
            event.track = i;
            events[i]-&gt;push_back(event);

            break;
         }

         if (bytes[0] != 0xff &amp;&amp; bytes[0] != 0xf0) {
            event.tick = absticks;
            event.track = i;
            events[i]-&gt;push_back(event);
         } else {
            event.tick = absticks;
            event.track = i;
            events[i]-&gt;push_back(event);
         }

      }

   }

   theTimeState = TIME_STATE_ABSOLUTE;
   return 1;
}

@@END:  FunctionDocumentation
```
