### ISSUE TITLE
MEI-1st cheat sheet

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#319]
Perhaps not the best place to report it, but the MEI 1st webpage:
http://music-encoding.org/support/tutorials/mei-1st/exploring-the-mei-header
Contains a link to a PDF:
http://music-encoding.org/wp-content/uploads/2015/03/CheatSheetHeader.pdf

The schematic is great; however, the use of the asterisk symbol is poorly chosen: The asterisk typically means "0 or more"(i.e., optional) in XML DTD, while the footnote on the PDF says it means "required":

![screen shot 2016-06-29 at 7 05 08 am](https://cloud.githubusercontent.com/assets/3487289/16455052/e6d47c30-3dc7-11e6-8daf-34b3d94f8e23.png)
![screen shot 2016-06-29 at 7 12 29 am](https://cloud.githubusercontent.com/assets/3487289/16455377/ed321b04-3dc8-11e6-8e7c-b98c33f524b3.png)

It would be better to choose a different symbol for representing a mandatory element.  Perhaps a dagger (†) instead of an asterisk? — as your file will die if it does not include those elements.

It would be even more useful if it were slightly more technical and gave the standard schema symbols used for each element: \* for 0 or more, + for one or more, ? for optional, nothing for mandatory.  But that might get too complex when considering larger-scale patterns of elements.

**Comment by pe-ro** [comment]
Kristina Richts is the keeper of the MEI-1st tutorial.  I'll email her to see if/when she can address this.

**Comment by craigsapp** [comment]
OK, I will bug her if I notice problems in the tutorial :-)  I will be reading the header tutorial today...

**Comment by bwbohl** [comment]
As MEI 1st in no longer in placeI will close this issue and mark it as wontfix.
