### ISSUE TITLE
Add Schematron to disallow nesting of <ending>

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#323]
The guidelines say in section 1.1.2.3 "The ending element shares the same model as the section element. Unlike section, however, it may not be recursively nested." This makes sense. However, the schema allows `ending` within `ending`. Or is this controlled by a Schematron rule?

**Comment by pe-ro** [comment]
At the time of this part of the Guidelines, the restriction was enforced by the schema.  The restriction should be enforced by a new Schematron rule.

**Comment by pe-ro** [comment]
Another option is to modify the content model of `<ending>` from --

```
<content>
  <rng:zeroOrMore>
    <rng:ref name="expansion"/>
  </rng:zeroOrMore>
  <rng:zeroOrMore>
    <rng:choice>
      <rng:ref name="model.appLike"/>
      <rng:ref name="model.divLike"/>
      <rng:ref name="model.milestoneLike.music"/>
      <rng:ref name="model.annotLike"/>
      <rng:ref name="model.graphicPrimitiveLike"/>
      <rng:ref name="model.editLike"/>
      <rng:ref name="model.transcriptionLike"/>
      <rng:ref name="model.sectionPart"/>
    </rng:choice>
  </rng:zeroOrMore>
</content>
```

to --

```
<content>
  <rng:zeroOrMore>
    <rng:ref name="expansion"/>
  </rng:zeroOrMore>
  <rng:zeroOrMore>
    <rng:choice>
      <rng:ref name="model.appLike"/>
      <rng:ref name="model.divLike"/>
      <rng:ref name="model.milestoneLike.music"/>
      <rng:ref name="model.annotLike"/>
      <rng:ref name="model.graphicPrimitiveLike"/>
      <rng:ref name="model.editLike"/>
      <rng:ref name="model.transcriptionLike"/>
      <rng:ref name="model.scoreDefLike"/>
      <rng:ref name="model.sectionLike"/>
      <rng:ref name="model.staffDefLike"/>
      <rng:ref name="model.sectionPart.cmn"/>
      <rng:ref name="model.sectionPart.mensuralAndNeumes"/>
    </rng:choice>
  </rng:zeroOrMore>
</content>
```

That is, within `<ending>` only the non-ending members of model.sectionPart would be allowed.

This causes a bit of a hiccup when it comes to maintenance, but probably no greater than that caused by the addition of a new Schematron rule.

Comments?

**Comment by lpugin** [comment]
This looks like a good fix to me. However, I am not sure what you mean hiccup in maintenance.

**Comment by pe-ro** [comment]
Modification of the content model of `<ending>` means that it has to be treated specially -- one can't assume that changes to `model.sectionPart` will have any effect within `<ending>`.  Said another way, if any changes are made to `model.sectionPart`, then corresponding changes also have to be made in the content of `<ending>`.  It's somewhat of a hassle to remember to do this.

On the other hand, while keeping the current, generic model and creating a Schematron rule that disallows nesting of `<ending>` makes for somewhat easier maintenance of the schema, it also requires the Schematron rule.  In other words, if the Schematron rule is ignored, the restriction will never be enforced.

Although MEI isn't completely consistent, my usual M.O. is to use the schema as much as possible to enforce restrictions and use Schematron as a last resort.  I always have a twinge of apprehension/
guilt/shame when I don't.  :-)

All XML content has to be enumerated in one fashion or another.  Content model exclusion (e.g., all the members of X class "except" this or that element) was allowed in SGML, but was dropped in XML.  That's too bad 'cause it can be very useful, as in this case.

**Comment by lpugin** [comment]
@pe-ro : I leave this up to you.
