### ISSUE TITLE
Images missing from MEI 1st webpages

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#326]
Images are missing from MEI 1st tutorial pages, such as:

http://music-encoding.org/support/tutorials/mei-1st/encoding-music-notation/music-level-1

![screen shot 2016-07-19 at 11 11 53 am](https://cloud.githubusercontent.com/assets/3487289/16961285/a41cea28-4da1-11e6-91ad-98fea8de7fdb.png)

This is caused by prefixing the image URLs with `https://` rather than `http://`.

The problem is that the server for music-encoding.org does not have secure connections, so this sort of address:
https://music-encoding.org/wp-content/uploads/2015/06/Oktavenbezeichnungen.png

Returns an error page:

![screen shot 2016-07-19 at 11 09 00 am](https://cloud.githubusercontent.com/assets/3487289/16961183/45a1b5dc-4da1-11e6-8389-e24410e077db.png)

(Seems that it used to have secure connections, but certificate has expired).

Without the secure connection, the images are viewable:

http://music-encoding.org/wp-content/uploads/2015/06/Oktavenbezeichnungen.png

![screen shot 2016-07-19 at 11 10 46 am](https://cloud.githubusercontent.com/assets/3487289/16961250/81d9ec5e-4da1-11e6-94fd-729f64c6f788.png)

**Comment by pe-ro** [comment]
Appears to have been resolved

**Comment by craigsapp** [comment]
> Appears to have been resolved.

Yes, I see them now:

<img width="587" alt="screen shot 2017-01-04 at 10 23 43" src="https://cloud.githubusercontent.com/assets/3487289/21653845/0199dc56-d268-11e6-9871-6157c23690b7.png">
