### ISSUE TITLE
Written out arpeggio encoding?

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#327]
How should this musical example be encoded:

![screen shot 2016-07-19 at 10 49 22 pm](https://cloud.githubusercontent.com/assets/3487289/16976388/62db130c-4e03-11e6-9dee-09b9330d39d1.png)

**Comment by pe-ro** [comment]
@craigsapp, There's no requirement that the `@startid` and `@endid` attributes on `<tie>` be notes that are adjacent, so 
```
<tie startid="#n2" endid="#n7"/>
```
is fine (where the notes are counted left-to-right and top-to-bottom in the chord).

I'm not sure what Verovio expects, however.

**Comment by craigsapp** [comment]
Verovio can do non-adjacent ties:

<img width="443" alt="screen shot 2017-02-08 at 17 58 17" src="https://cloud.githubusercontent.com/assets/3487289/22766052/3d026e94-ee28-11e6-9ec2-eae1861b2174.png">

That is useful to know (that it works in MEI and verovio).

But, the ties in the original example are all normal.  Perhaps my question was more along the lines of the messy layers (looks like it could be up to six layers in a staff depending on what to do for the cross-staff notes).  For example this arpeggio involves 5 layers:

<img width="235" alt="screen shot 2017-02-08 at 18 11 11" src="https://cloud.githubusercontent.com/assets/3487289/22766403/1a4c8dd8-ee2a-11e6-96de-e168be0bfdde.png">

but there is only one "audible" ("gestural"?) layer.

One layer is for the 32nd notes, and one each for the superimposed notes that are keeping track of the ties.  Since this is solo piano music, each of the doubled noteheads is a single sounding note, so the extra complication is how to indicate that there are two noteheads for the start of the slur.

Probably `@plist` could indicate the double-note start to the tie?  And/or `@sameas` could be involved to indicate a single note attack across two `<note>` elements?

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-02-08T17:56:05" version="0.9.14-dev-59d795c">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000000680123850">
                        <staffGrp xml:id="staffgrp-0000001743276650">
                            <staffDef xml:id="staffdef-0000001131260529" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001916445708">
                        <measure xml:id="measure-L3" n="1" right="end">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L4F1" dur="4" oct="4" pname="e"/>
                                    <note xml:id="note-L5F1" dur="4" oct="4" pname="g"/>
                                    <chord xml:id="chord-L6F1" dur="2">
                                        <note xml:id="note-L6F1S1" oct="4" pname="e"/>
                                        <note xml:id="note-L6F1S2" oct="4" pname="g"/>
                                    </chord>
                                </layer>
                            </staff>
                            <tie xml:id="tie-L4F1-L6F1S2" startid="#note-L4F1" endid="#note-L6F1S1" />
                            <tie xml:id="tie-L5F1-L6F1S2" startid="#note-L5F1" endid="#note-L6F1S2" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by pe-ro** [comment]
A diplomatic transcription may not be practical here due to the layer complications.  I suggest encoding it as though there were only 2 layers in each staff.  The flagged notes would be missing, but the sense of the passage would be preserved. Gould advocates the same on p. 133.

**Comment by craigsapp** [comment]
That is the easy way out :-)  But I would most likely also do that in a non-diplomatic edition.  Also, that is how I encoded it in Humdrum, where I am only interested in the logical content.

For fun, here is the diplomatic version done in SCORE:

<img width="869" alt="screen shot 2017-02-09 at 10 50 38" src="https://cloud.githubusercontent.com/assets/3487289/22798190/e695cf40-eeb5-11e6-8eaa-35758e1cb516.png">

In SCORE there are two ways: (1) give the stemmed duplicate notes the correct duration as seen, (2) give the stemmed notes 32nd rhythms, but add visual dots/flags as needed (I did the second one, as that is slightly faster).

And here is the Behind Bars recommendation:

<img width="864" alt="screen shot 2017-02-09 at 10 50 49" src="https://cloud.githubusercontent.com/assets/3487289/22798224/fccb7422-eeb5-11e6-9791-5b81a37bb40b.png">

[bee.txt](https://github.com/music-encoding/music-encoding/files/764693/bee.txt)
[bee2.txt](https://github.com/music-encoding/music-encoding/files/764694/bee2.txt)

**Comment by pe-ro** [comment]
The Gould version is what I'm recommending. :-)

If necessary, `@facs` can be used to point to a graphic showing the original version.
