### ISSUE TITLE
Endings displayed on top of several staves

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#328]
It is not uncommon to have endings brackets displayed on top of several staves. A default behavior for renderers could be to display them on top of each `staffGrp`. However, this might not always be desirable and I don't think there is currently a way to specify explicitly on top of what staves ending brackets are expected to be displayed.

**Comment by pe-ro** [comment]
The `@ending.rend` attribute, available on `<scoreDef>`, is intended to record where the ending brackets appear.  Possible values are: `top` (Ending rendered only above top staff), `barred` (Ending rendered above staves that have bar lines drawn across them), and `grouped` (Endings rendered above staff groups).

**Comment by lpugin** [comment]
Great! I think you just wrote a paragraph I can add to the guidelines. Or did I overlook it?

One question: could you clarify the meaning of `barred`? I am not sure I can visualise that one.

**Comment by pe-ro** [comment]
`barred` was added in anticipation of the case where bar lines extend across staves or staff groups that aren't part of a larger, containing staff group.  You're safe in ignoring it for now as MEI doesn't yet have a way to indicate the extent of bar lines outside the context of staff groups.  We could even decide to remove this value at some point.
