### ISSUE TITLE
Triple sharps/flats symmetry in explicit/implicit accidentals

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#330]
Why are there triple sharps and flats in explicit accidentals:

http://music-encoding.org/documentation/3.0.0/data.ACCIDENTAL.EXPLICIT

xs    Triple sharp (written as a croix followed by a sharp).
sx    Triple sharp (written as a sharp followed by a croix).
ts     Triple sharp (written as 3 sharps).
tf      Triple flat.

But there are none in implicit accidentals:

http://music-encoding.org/documentation/3.0.0/data.ACCIDENTAL.IMPLICIT

**Comment by pe-ro** [comment]
Sorry to have let this question languish for so long.

So-called "explicit" accidentals are those that are written on the page, while "implicit" ones are those that are sounded.  Limiting the values of `@accid.ges` was intended to simplify conversion to MIDI.  Using these definitions, G triple-sharp can be encoded as 

`<note pname="g" accid="ts" pname.ges="a" accid.ges="n">`

(No, I don't want to go around again about requiring/implying `@accid.ges`.)

Would it help to rename data.ACCIDENTAL.EXPLICIT to data.ACCIDENTAL.WRITTEN and data.ACCIDENTAL.IMPLICIT to data.ACCIDENTAL.SOUNDED or data.ACCIDENTAL.GESTURAL?

**Comment by craigsapp** [comment]
> Would it help to rename data.ACCIDENTAL.EXPLICIT to data.ACCIDENTAL.WRITTEN and data.ACCIDENTAL.IMPLICIT to data.ACCIDENTAL.SOUNDED or data.ACCIDENTAL.GESTURAL?

Yes, that would be helpful, since "explicit/implicit" is a bit abstract as to their meaning (they are in reference to written accidentals, giving a bias to printed music).

`<note pname="g" accid="ts" pname.ges="a" accid.ges="n">`

You mean `accid.ges="s"`?

This should work for most reasonable cases (and triple sharps/flats are extremely rare, so it is a small point).  Logically it is not precise for non-equal-tempered systems, since G### is not necessarily the same frequency in Hertz as an A#.   For example in Pythagorean tuning a B# is a Pythagorean comma higher than a C.

https://en.wikipedia.org/wiki/Pythagorean_comma

But considering the `accid="ts"` attribute, a sounding A# could be differentiated from a sounding G###.

**Comment by rettinghaus** [comment]
@craigsapp 's got a point here. If you don't have _that_ possibility, having `@tune.temper` on `<scoreDef>` seems to be a bit senseless.

**Comment by pe-ro** [comment]
> You mean accid.ges="s"?

Yes.

> If you don't have _that_ possibility, having @tune.temper on `<scoreDef>` seems to be a bit senseless. 

Sometimes there's method in my madness. :-)

**Comment by craigsapp** [comment]
Most temperaments will map G### to Bb (A G### in the score will sound like a Bb in the temperament).  12-note temperaments would usually use B-flat since A# will most likely map to Bb.  So I suppose that it should be:

`<note pname="g" accid="ts" pname.ges="b" accid.ges="f">`

For a 31-note temperament,  G### would map to Bbb since they are closest to each other in frequency than G### is to Bb or A#.   In a 31-note temperament, the encoding would then probably be:

`<note pname="g" accid="ts" pname.ges="b" accid.ges="ff">`

https://en.wikipedia.org/wiki/31_equal_temperament#/media/File:31-TET_circle_of_fifths.png

It won't be possible (or at least practical without inferring cases where the written accidental is not given for a G###) to switch between these two encodings.  Not that this will ever be a problem :-)
