### ISSUE TITLE
Dynamics or hairpin to be centered between two staves

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#331]
It is currently not very clear how to encode the placement of dynamics or hairpin when they are centered between two staves. A proposal (see https://github.com/rism-ch/verovio/issues/251) is to add `"between"` as possible value to `@place` when (and only when) two staves are provided in `@staff`.

**Comment by craigsapp** [comment]
Here are the positions that are needed for piano (and other grand staff instrumental parts):

![screen shot 2016-07-21 at 9 47 40 pm](https://cloud.githubusercontent.com/assets/3487289/17046872/f5f5a38e-4f8c-11e6-92ac-82923948878f.png)

"A" is handled by `@staff="1"  @place="above"`, and B is the default of `@staff="1" @place="below"`.  These dynamics would only apply to staff 1.

"D" is handled by `@n="2"  @place="above"`, and E is the default of `@staff="2" @place="below"`. These dynamics would only apply to staff 2.

However, for piano music the most important position is "C" which would apply to both staves.  I propose that this be handled by `@staff="1 2" @place="between"` or `@staff="1 2" @place="center"`.  Using `@staff="1 2"` without `@place` would automatically select position "C".  

Less common: `@staff="1 2" @place="above"` would be "A" (but applied to both staves), and `@staff="1 2" @place="below"` would be position E (but apply to both staves).

Or perhaps better: `@staff="1 2" @place="above"` would be "B" (but applied to both staves), and `@staff="1 2" @place="below"` would be position D (but apply to both staves).

Here is some music with examples of three of the five positions:

![screen shot 2016-07-21 at 10 02 05 pm](https://cloud.githubusercontent.com/assets/3487289/17047081/e0005798-4f8e-11e6-8062-4f5fc7e79b74.png)

The first "p" should be encoded as `@staff="1"`, with an implied `@place="below"`.

The second "p" should be encoded as `@staff="2"`, also with an implied `@place="below"`.

On the second line of music the red dynamics would be encoded as `@staff="1 2"`, with an implied `@place="between"` or `@place="center"`.

**Comment by craigsapp** [comment]
Are there going to be 5 positions for placing items in piano music?  Mostly this being by adding an attribute state `@place="between"` to center between two adjacent staves?

**Comment by pe-ro** [comment]
Yes, I just added "between" as a possible value and a Schematron rule that makes sure that there are two values in `@staff` and that the values are adjacent to each other in the /development branch.

**Comment by pe-ro** [comment]
For example ---
```
<!-- place can now be "between", in which case @staff must have 2 adjacent values -->
<dynam tstamp="1" tstamp2="1m+2" val="2" val2="8" staff="1 2" place="between">cres.</dynam>
```

**Comment by kepper** [comment]
I'm not sure if we can / should enforce that values are adjacent. Staves need to be adjacent, but we have no formal requirement that staff number are consecutive, especially in case of suppressed staves. I know this won't happen in case of piano music, but I'm confident that someone can pull out an absurd example for this… At the same time, extracting the staff order from a scoreDef just to check if the two values in @staff refer to adjacent staves seems overkill. I see two possible solutions here: Either we just don't care what the values in @staff are, or we put that in a separate rule with warn level only, so that users get a hint, but their file isn't automatically invalid when they (righteously) use non-consecutive numbers…

**Comment by pe-ro** [comment]
When the need arises, I'm sure someone will file a bug report.  😄

**Comment by kepper** [comment]
Well, of course, how could I forget about this third solution ;-)

**Comment by craigsapp** [comment]
That is a good solution :-)

In theory this could happen in orchestral scores, but in general, parts on separate staves should not be sharing dynamics which would be encoded as "between".  Perhaps in modern scores (particularly for small ensembles) there might be a need the non-consecutive "between" case:

<img width="671" alt="screen shot 2017-01-10 at 14 01 04" src="https://cloud.githubusercontent.com/assets/3487289/21826672/45903e9e-d73d-11e6-94c9-803513bbd71d.png">

in this case, the big "p" should be placed between staves 1 and 3.

**Comment by pe-ro** [comment]
I'm not sure that this situation can be adequately described as a dynamic _**shared by**_ staves 1 and 3.  Who knows what this means?  A better approach would be to describe the dynamic with respect to its location on the page and let the user determine/indicate its meaning.

In any case, let's wait until someone asks for this "feature".

**Comment by craigsapp** [comment]
As the composer of that particular work, I assert that it affects both staff 1 and staff 3 :-).  And it also affect staff 2 when it comes in again :-)

**Comment by pe-ro** [comment]
@craigsapp, As the composer, you can assert anything you want to, especially in the 20th & 21st centuries. :-)  However, in MEI `@staff` does double duty; that is, it records both logical and physical associations.`<dynam staff="1">` says that the dynamic is both logically associated with/affects staff AND that it has a physical association with staff 1.  This follows the definitions of `@place` you gave before, particularly with regard to the value "between".

In the current regime, `place="between"` signals that a dynamic affects 2 staves AND that it's positioned relative to both.  An analogous statement would be "The English Channel is between France and England"; that is, both countries use its waters and it's geographically located next to them.  Your latest composition changes that definition, something along the lines of "The English Channel is between France and Iceland".  This is true in some sense, but the English Channel doesn't affect Iceland that much, in that it doesn't physically touch Iceland.  

Worse yet, "The English Channel is between France, England, and Iceland", is nearly impossible to make sense of.  Change "France" to "staff 1", "England" to "staff 2", and "Iceland" to "staff 3" and you should see the difficulty we're faced with when we claim that something is "between" 3 entities.  Limiting `@staff` to 2 values when `@place="between"` reduces complexity, and makes dealing with common situations easier.  To deal with more complex interactions, like those suggested by your example, I think we have to look to other mechanisms.

@kepper, your objection to the definition of "adjacent" staves is sound.  Continuing the analogy above, if the UK invented a way to arbitrarily and temporarily "cloak" itself (that is, make itself invisible), then the statement "The English Channel is between France and Iceland" could make more sense.  So, I suppose we need to amend the definition of "adjacent" to include *visible* staves.  A Schematron rule that accounts for invisible staves won't be easy to create.  Until we can provide it, as you suggest, we can demote the existing rule to a warning.
