### ISSUE TITLE
Vertical alignment of dynamics and hairpins

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#332]
Very often, hairpin and dynamics are aligned vertically. There is currently no dedicated way to encode positioning. Rather than trying to encode precisely the position of each of them, one idea is to provide a way to group them and then to leave the positioning to the renderer. In other words, a way to encode that a set of dynamics and hairpins constitue a sequence, or a group, and hence need to be aligned vertically.

We need to discuss if we need something like this, and if yes, what is the best way to encode it. Preliminary discussion occurred here https://github.com/rism-ch/verovio/issues/251

Some ideas are:
- add a `dynamGrp` element that would point to a first and last (or to a list) or `dynam` and `hairpin` that constitute a group.
- add a generic `@grpId` on `dynam` and `hairpin` to let them specify they are grouped together
- align `dynam` and `hairpin` that have simultaneous timestamps (for example a dynamic and a hairpin starting at the same time would mean the dynamic followed by the hairpin)

**Comment by pe-ro** [comment]
I'd like to address Laurent's suggestions in reverse order:

> - align dynam and hairpin that have simultaneous timestamps (for example a dynamic and a hairpin starting at the same time would mean the dynamic followed by the hairpin)

I think this option is (or should be) inherent in Verovio; that is, it's part of the routine to avoid collisions.  So, option 3 doesn't need further discussion.

> - add a dynamGrp element that would point to a first and last (or to a list) or dynam and hairpin that constitute a group.

This is a viable solution, but stand-off mark is easier to implement if you know the members of the group _a priori_.  This may not always be the case.

> - add a generic @grpId on dynam and hairpin to let them specify they are grouped together

So, I'd prefer to add `@grpid` on `<dynam>`, `<hairpin>`, etc.  Elements carrying the same value for `@grpid` may be vertically aligned.  Of course, the attribute can be used for other purposes as well, such as rendering the members of the group in a different font, color, etc.

**Comment by kepper** [comment]
I remember discussions about this back in Montreal. Ultimately, I wonder how this relates to a redefined @type, as discussed (and accepted) in #338. Is the proposed @grpid really so much different than just a custom @type? For me, both attributes "feel" like HTML's @class…

I see reasons for a generic grouping mechanism, but they apply to elements like <add>, <del> or <rdg> (to name just a few), but not to the situation described in this issue…

PS: Even for the elements mentioned above, I think I'd prefer to follow TEI's @excludes, maybe alongside an @includes / @requires…

.

**Comment by pe-ro** [comment]
`@grpid` is similar to `@type`. However, `@grpid` has a specialized purpose; that is, to vertically align the entities bearing the same value.  To use `@type` for this there would have to be agreement on a special value, like 'valign' and a method for addressing the particular elements to be aligned.  It would also cause confusion if this 'valign' capability were provided everywhere (as it would be if it were consigned to `@type`.)  So, I think `@grpid` is the better approach, although as I describe its purpose now, I see that it might be better to call it `@valign`.  It would still take a set of IDs as values, though.

**Comment by pe-ro** [comment]
E.g., `valign="#dynam1 #hairpin1 #dynam2"` indicates that the 3 entities referenced in `@valign` should be vertically aligned.  What happens if one or more of these carries an indication of its vertical position is application dependent.  Some thought should perhaps be given to a hierarchy/chain of processing, i.e., 
1. `@x/@y`
2. `@vo` 
3. `@dynam.dist`
4. program determination

There also has be to be program logic to deal with cases where values are different across elements; that is, `#dynam1` and `#dynam2` have conflicting values for `@y` or `@vo`.

**Comment by lpugin** [comment]
I quite like the idea of `@valign` with a list of ids. This is a good proposal to me and possible conflicts are similar to what we can have elsewhere in MEI.

The hierarchy chain also makes sense to me. However, I am not sure we can always or easily chain them because some a complementary. In particular the offset. For example, it makes sense to me to have and use both `@dynam.dist` and `@vo`. How I would understand it is "place it at at a distance of `@dynam.dist` + in the case of the current `dynam` a `@vo`." But it could also be understood as `With a @vo, do not take into account`@dynam.dist`and add`@vo` to the program determine position."

Also, what remains unclear is how `@vo` should be taken into account with program determination. See this comment about it https://github.com/music-encoding/music-encoding/issues/357
