### ISSUE TITLE
unusual accidental

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#333]
How should these accidentals be encoded with @accid?

![screen shot 2016-07-25 at 4 20 29 pm](https://cloud.githubusercontent.com/assets/3487289/17120850/f8e43bf6-5283-11e6-9fe7-90d45f976b5e.png)

http://petrucci.mus.auth.gr/imglnks/usimg/3/3c/IMSLP423660-PMLP01969-Op._10_-_12_Etudes__1833_Schlesinger__FE_.pdf

From first edition (Paris) of Chopin's ètude in C-sharp minor, Op. 10, No. 4.

**Comment by ahankinson** [comment]
What do they mean?

**Comment by craigsapp** [comment]
I thought it doesn't matter what they mean, as they are visual :-)

They mean natural, although why there are also normal natural signs in the same work, I don't know...

![screen shot 2016-07-25 at 6 17 33 pm](https://cloud.githubusercontent.com/assets/3487289/17122879/3612058e-5294-11e6-9326-20ee56ab05b5.png)

Modern style:

![screen shot 2016-07-25 at 6 18 27 pm](https://cloud.githubusercontent.com/assets/3487289/17122881/3e957d30-5294-11e6-8e2d-4af9d7129e6c.png)

**Comment by ahankinson** [comment]
I would encode them using the <accid /> element with attribute "accid='n'". If you really want to capture the symbol, find it in the SMuFL tables and encode that using the SMuFL codepoint (can't remember the attribute for that off the top of my head).

Alternatively, you could create a customization with the element `<funnySharpWithDotsInFourCornersFromSomePrinterWhoAlsoHasAFunnyForteF />`*\* and define it's behaviour, but I suspect that's probably not what you're looking for.

*\* and, of course, its corollary `<funnyForteFFromSomePrinterWhoAlsoHasFunnySharpsWithDotsInCornersToMeanNaturalSignsForSomeOddReason />` element

**Comment by craigsapp** [comment]
That is good enough for now, and when I figure out why there are two graphical types of naturals, I'll know better what I want to do...
