### ISSUE TITLE
unclear attributes on breath

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#345]
Some attributes on `<breath>` don't seem to make sense. 
`@dur`: I can't think of an example of notated music in which a breathing sign would have an actual _notated_ duration. Albeit in may have a _real_ duration (in perfomances) a `@dur.ges` is missing
`@dots`: no really, dots?
`@startid`: when connecting it to another event, e.g. a note, it is highly unlikely to be meant to be performed or printed _on_ the note. But should it mean instead _before_ or _after_ the connected event? (Guidelines are no guide in this case)
`@plist`: same as on `@startid`
`@tstamp2` and `@endid`: where is the point on having these for a single sign (with probably no duration after all)? 
`@place`: this records if the breathing sign would be printed 'above' or 'below' the staff. In most cases (at least those I can think of) it is printed _on_ the staff but by now it can't be placed via `@loc`, `@oloc`, and `@ploc`.

**Comment by pe-ro** [comment]
@rettinghaus: As a control event; that is, something that occurs at a particular time, but not directly within the stream of events (notes, rests, and chords), `<breath>` takes all the attributes of that class.  Giving it these attributes, however, was simply for convenience, a way to get started.  As you point out, some of them don't make sense.  Obviously, the duration-related attributes, like `@dur`, `@dots`, `@tstamp2`, `@endid` can be safely removed.  The intended use of `@plist` was to refer to all the events taken under one breath, probably the ones following the mark, but I can see that raises issues, so `@plist` could likely be removed as well.

Other attributes should stay.  For example, `@startid` is intended to connect a control event to an event **logically**, not necessarily **visually**.  In other words, linking a breath mark to a note says nothing about where to display the mark.  That's the job of `@place`, `@ho`, `@vo`, etc.  The Guidelines could be more clear about this with regard to CMN.

Adding `@loc`, `@ploc`, and `@oloc` is certainly do-able.
