### ISSUE TITLE
make ornam part of att.altsym

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#347]
For `<ornam>` he guidelines state: 

> The glyph of the ornament may be indicated with the @altsym attribute

but actually `<ornam>` isn't part of att.altsym. 

As `<ornam>` is equal to `<mordent>`, `<turn>`, and `<trill>` it basically should allow the same attributes.

**Comment by pe-ro** [comment]
Oops!  Will fix in the next release.
