### ISSUE TITLE
Guidelines : empty chord in an exemple (notes missing)

### ISSUE THREAD

**Issue by marie-ototoi** [music-encoding/music-encoding#348]
p.103 - screenshot attached
<img width="916" alt="capture d ecran 2016-09-28 a 16 43 22" src="https://cloud.githubusercontent.com/assets/1785024/18918422/0ba2ddb6-859b-11e6-85f2-4da6997d1fdf.png">

**Comment by ahankinson** [comment]
It is helpful if you can provide the section in which this occurs. What part of the guidelines? 

As I mentioned the other day, I believe that these notes have been omitted for clarity in this example, but I think an improvement could be to have a comment specifying this.

**Comment by marie-ototoi** [comment]
Sorry : 4.2.2 Ties, Slurs and Phrase Marks
Sure, a comment would be fine
If you want to send the image source I'm happy to do it !
