### ISSUE TITLE
Bowing marks

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#351]
Currently, bowing marks are a type of `<artic>/@artic`. However, they are not really articulations be rather instrument specific marks. In a way, they are more similar to `<finger>`. Is this something that we could want to change? Or would it become too complicated to distinct?

**Comment by pe-ro** [comment]
I think it's a good idea in this case to follow previous encoding systems, which have treated note-level performance indications as articulations.  It's technically possible to encode them separately, but it would lead to a distinction without a difference, I believe.

**Comment by lpugin** [comment]
OK, thanks
