### ISSUE TITLE
something mixed up in beatRpt

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#355]
The Guidelines say following on `<beatRpt>`:

> `@form` (required) Indicates the number of slashes required to render the appropriate beat repeat
> symbol. When a single beat is repeated, consisting of a single note or chord, it is indicated by a
> single thick, slanting slash; therefore, the value '1' should be used. The following values should
> be used when the beat is divided into even notes: 4ths or 8ths=1, 16ths=2, 32nds=3, 64ths=4,
> 128ths=5. When the beat is comprised of mixed duration values, the symbol is always
> rendered as 2 slashes and 2 dots. Value conforms to data.BEATRPT.REND

But `data.BEATRPT.REND` only allows the values 4|8|16|32|64|128

Obviously there's something odd.

**Comment by rettinghaus** [comment]
On the other hand it is stated [here](http://music-encoding.org/documentation/3.0.0/cmn/#cmnRep) that `<beatRpt>` would be using the `@rend` attribute, which actually isn't allowed.

**Comment by pe-ro** [comment]
The values for `data.BEATRPT.REND` were changed in an effort to capture the intended performance of the sign.  But, I now recognize this as an error -- the performance info should be encoded using `<orig>` and `<reg>`.  So, the Guidelines are correct and the current schema is wrong.

The `@rend` attribute was replaced by `@form` and other attributes in the last revision, but it seems the Guidelines didn't get updated to reflect this change.
