### ISSUE TITLE
Fix PDF guidelines in downloadable zip

### ISSUE THREAD

**Issue by musicus** [music-encoding/music-encoding#358]
The https://github.com/music-encoding/music-encoding/archive/v3.0.0.zip contains the ```MEI_Guidelines_2013_v2.1.1.pdf``` in the guidelines directory rather than the ```MEI_Guidelines_v3.0.0.pdf``` available at http://music-encoding.org/downloads/latest-release/.

**Comment by ahankinson** [comment]
@kepper I believe this is up to you to generate the new guidelines PDF.

**Comment by kepper** [comment]
@ahankinson I'm happy to do whatever is necessary, but I don't know what to do in my clone to downstream it correctly in the official repo. As @musicus pointed out, the correct PDF is available already, living at http://www.music-encoding.org/docs/MEI_Guidelines_v3.0.0.pdf.
