### ISSUE TITLE
How to encode sharps/flats in <harm> text?

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#359]
How should sharps and flats be encoded in the text of `<harm>`?

Should it be done with Unicode characters?  Such as

```xml
<harm>F♯</harm>
```
or as a numeric entity:

```xml
<harm>F&#x266f;</harm>
```
or in some other way, or are both of the above methods acceptable?

Links to examples on the page http://music-encoding.org/documentation/3.0.0/harm would be handy.

I see that the answer is the first case above, from the page:

http://music-encoding.org/documentation/3.0.0/harmony

In this case element examples were relatively easy to find, but in general it is not.  Crosslinks from the element references: http://music-encoding.org/documentation/3.0.0/elements to the Guidelines http://music-encoding.org/documentation/3.0.0/chapters would be handy.  Perhaps tags containing a title which are embedded in the Guidelines would be a way of doing this.  These would be compiled into HTML anchor tags, and can then be compiled into and index of links for the element references.

**Comment by pe-ro** [comment]
Either method of putting Unicode characters in text is acceptable.  The Unicode character and the character entity reference are equivalent.

One of these days we'll get around to linking the element descriptions to the Guidelines. :-)

**Comment by craigsapp** [comment]
I tried the character entity reference method, but the chord text did not resolve the entity into a unicode character when displaying with verovio.  So perhaps a bug in verovio and/or pugixml.  Is an xml parser expected to handle the conversion to unicode, or is software using the parser supposed to do it?  

@lpugin: I am using `UTF8to16()` to store text in the MEI data structure, but perhaps I need also to run it through another filter to convert entities into UTF8 first?

**Comment by pe-ro** [comment]
Entities are normally resolved by the parser -- that's why they're not "round-tripable".
