### ISSUE TITLE
Clarify horizontal spacing of notes/events

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#363]
MEI currently has a couple of attributes (`@spacing.packexp` and `@spacing.packfact`) -- borrowed from Mup, but similar to MuseScore's "spacing" and "minimum note distance" parameters -- that are intended to record information about note/event spacing. They're available in the att.spacing class. (BTW, "packexp" and "packfact" aren't set in stone; they can be changed if someone suggests better names.)

Right now, only `<scoreDef>` allows these attributes, but `<scoreDef>` can occur within `<staff>` so resetting the spacing for a particular staff is possible. Major questions arise, though -- Are these attributes adequate for describing note spacing? Are additional attributes or values necessary? Is there another set of attributes that would work better? Does changing the value of these attributes affect the entire score from that point forward or only the staff in which the change occurs? Would it be better to make `<staffDef>` (and perhaps `<measure>` too) a member of att.spacing?

I'm aware that there are various algorithms for computing "optimal" note spacing. But, is there a generic way of describing note spacing, say with an attribute with a list of values (closed or semi-open), such as "linear", "logarithmic", "proportional", etc. that could replace `@spacing.packexp` and `@spacing.packfact`?

**Comment by ahankinson** [comment]
FYI, when writing angle brackets in GitHub, you need to escape them with backticks otherwise it doesn't parse correctly.

**Comment by ahankinson** [comment]
My take on this is that, even if we do supply a closed or semi-open list of note spacing 'algorithms', not every renderer will do this correctly, and certainly won't do it consistently in every context (different screen sizes, etc.)

What does 'exp' and 'fact' mean?

**Comment by pe-ro** [comment]
> What does 'exp' and 'fact' mean?

From the Mup User's Guide (http://www.arkkra.com/doc/uguide/index.html) --

```
packexp

sets note expansion factor. This factor controls spacing of notes relative to their time 
values.  If set to 1.0, Mup will try to give a half note twice as much space as a quarter 
note, a whole note twice as much as a half note, etc. If set to 0.0, a chord's time value 
will have no impact on its placement.  Intermediate values will cause relative spacing 
between the two extremes.  Note that individual chords may get more space than 
they would theoretically "deserve" if they happen to need extra space to accommodate 
accidentals, dots, etc.

Value: a number from 0.0 to 1.0 inclusive

Default value: 0.8 
```
and 
```
packfact

specifies how tightly to pack notes together on output. The smaller the value, the 
more tightly notes are packed together.

Value: a number from 0.0 to 10.0

Default value: 1.0 
```
Another related Mup parameter --
```
pad

specifies the amount of padding to be added to notes. This can be used to control how 
tightly things are packed together. Especially if packexp and packfact are very small, 
notes can get placed very close together. This parameter can be used to always force 
a minimum amount of space between horizontally adjacent note groups. A value of 
zero means notes will be allowed to just touch. More positive values cause more space 
around notes. A negative value will let things actually overlap, so most people will 
probably never want to use a negative value, but the option is there if you want to do 
something unusual. This parameter works somewhat like the "pad" value that can be 
specified for individual note groups, except that it applies to all groups.

Value: a number of stepsizes, -5.0 to 50.0

Default value: 0.3333 
```

**Comment by rettinghaus** [comment]
I definitely think we need something like this, but don't no, what the best approach could look like. 
In LilyPond there are tons of spacing options, e.g. the `SpacingSpanner`:

> 
    average-spacing-wishes (boolean):

        #t

        If set, the spacing wishes are averaged over staves. 
    base-shortest-duration (moment):

        #<Mom 3/16>

        Spacing is based on the shortest notes in a piece. Normally, pieces are spaced as if notes at least as short as this are present. 
    common-shortest-duration (moment):

        ly:spacing-spanner::calc-common-shortest-duration

        The most common shortest note length. This is used in spacing. Enlarging this sets the score tighter. 
    shortest-duration-space (dimension, in staff space):

        2.0

        Start with this much space for the shortest duration. This is expressed in spacing-increment as unit. See also spacing-spanner-interface. 
    spacing-increment (number):

        1.2

        Add this much space for a doubled duration. Typically, the width of a note head. See also spacing-spanner-interface. 
    springs-and-rods (boolean):

        ly:spacing-spanner::set-springs

        Dummy variable for triggering spacing routines. 



http://lilypond.org/doc/v2.18/Documentation/internals/spacingspanner

**Comment by lpugin** [comment]
Not very clear, should be brought up with more context if needed.
