### ISSUE TITLE
MEI attribute(s) which can map to @class content in SVGs?

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#366]
Somewhere this was discussed, but I don't know were (perhaps in verovio issues but I can't find it at the moment).

It would be useful to have an attribute or attributes on MEI elements (particularly notes) which can map to class names in SVG elements' `@class`.

Maybe it was `note@label` that was discussed, although I thought it was something which allowed a single name token, but there was discussion about allowing multiple name tokens for the attribute.

One possibility is to add something to the MEI header which indicates that a certain attribute should/can be mapped to `@class` when converting to SVG.  

As an sample application, dissonant notes are being marked in color in this example:

http://verovio.humdrum.org/?file=jrp:Jos2501&filter=dissonant%20-cemxhm

![screen shot 2016-12-26 at 22 22 42](https://cloud.githubusercontent.com/assets/3487289/21492460/dc061cf2-cbb9-11e6-9338-e66d296434b9.png)

I am currently using `note@color` to color the dissonant notes, but this is not a semantically great way of doing the markup.  In this case the color of the notes indicates the metric strength of the note: red = accented dissonant (on a beat), green/blue = unaccented dissonance (on an offbeat).

It would be nice to be able to assign a class or classes to the dissonant notes.  Then the choice of color for the dissonance would be controllable from CSS.   In this case `note@mfunc` could be mapped to an SVG `@class` value:

http://music-encoding.org/documentation/3.0.0/data.MELODICFUNCTION

But there would be other types of markup which do not map to specific note attributes.  And in this case the labels are geared towards Renaissance music rather than functional harmony which is more the focus of `**embel`.

(Of course, I want `@class` on directly MEI notes which would automatically get passed to an SVG rendering :-)

**Comment by pe-ro** [comment]
> It would be useful to have an attribute or attributes on MEI elements (particularly notes) which can map to class names in SVG elements' `@class`.

Use `@type` -- it can take any number of single token values.

>One possibility is to add something to the MEI header which indicates that a certain attribute should/can be mapped to `@class` when converting to SVG.

Not so keen on this one.  Wouldn't it be better to add whatever attributes are needed directly on note?  We could steal, uh I mean borrow, spines from Humdrum.  For instance, `**embel` because `@embel`.

**Comment by craigsapp** [comment]
> Use @type -- it can take any number of single token values.

Yes, this was the one that was discussed.  But I don't see it in the attribute list for notes:

http://music-encoding.org/documentation/3.0.0/note

Does it have to be added to MEI first?

**Comment by pe-ro** [comment]
> Does it have to be added to MEI first?

Yes, it will be there in the next revision.

**Comment by craigsapp** [comment]
Yea!
