### ISSUE TITLE
all-note chord slurs

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#367]
How should/can the slurs on the last two chords in this measure be encoded in MEI:?

<img width="707" alt="screen shot 2016-12-28 at 18 36 21" src="https://cloud.githubusercontent.com/assets/3487289/21535645/c9c78746-cd2c-11e6-9e6a-24a08d32ccbc.png">

Are these two different styles of slurring, and can the slurs in the second half of the measure be expressed as a single logical slur?

**Comment by pe-ro** [comment]
@craigsapp, 

The slur(s) on the last 2 beats can either be handled as 2 independent, visual slurs --
```
<slur staff="1" startid="#n3" endid="#n4" curvedir="above"/>
<slur staff="1" startid="#n5" endid="#n6" curvedir="below"/>
```
or as a single, logical slur made up of 2 curves --
```
<slur staff="1" tstamp="3" tstamp2="4">
   <curve startid="#n3" endid="#n4" curvedir="above"/>
   <curve startid="#n5" endid="#n6" curvedir="below"/>
</slur>
```

I'm using `@startid/@endid` for the independent slurs and the curves to make it clear which notes the visual slur/curve should be attached to.  When `<slur>` contains `<curve>` elements, the `@tstamp/@tstamp2' pair is more appropriate.

**Comment by pe-ro** [comment]
Given
```
<staff n="1">
   <layer>
      <chord xml:id="c01">
         <note xml:id="n01" pname="a" oct="5"/>
         <note pname="a" oct="4"/>
      </chord>
      <chord xml:id="c02">
         <note xml:id="n02" pname="g" oct="5"/>
         <note pname="g" oct="4"/>
      </chord>
      <chord xml:id="c03">
         <note xml:id="n03" pname="a" oct="5"/>
         <note xml:id="slurtest5" pname="a" oct="4"/>
      </chord>
      <chord xml:id="c04">
         <note xml:id="n04" pname="g" oct="5"/>
         <note xml:id="n06" pname="g" oct="4"/>
      </chord>
   </layer>
</staff>
```
The following is also correct --
```
<slur tstamp="1" tstamp2="2"/>
<slur tstamp="3" tstamp2="4"/>
```
as is --
```
<slur startid="#chord1" endid="#chord2"/>
<slur startid="#chord3" endid="#chord4"/>
```
But both of these imply that each of the notes in the starting chord are slurred to a note in the ending chord.  This is fine at a high level of abstraction, but can't be relied on to achieve a suitable rendering in every case, since it leaves out so much detail.

**Comment by craigsapp** [comment]
That all looks good.

I am wondering about the need for `@n` when `@startid`/`@endid` are used:

```
<slur staff="1" startid="#n3" endid="#n4" curvedir="above"/>
<slur staff="1" startid="#n5" endid="#n6" curvedir="below"/>
```

What would be the meaning of `@staff="1"` if both staring and ending elements are on staff 2?

**Comment by pe-ro** [comment]
@craigsapp, Of course, it would be meaningless, if the starting and ending elements are on staff 2.  But in that case, the encoding should be 
```
<slur staff="2" startid="#n3" endid="#n4" curvedir="above"/>
```
😛 

`@staff` isn't required by the schema, but it's use is necessary to provide clarity when there's more than one staff and the same time stamps are used on different staves to "anchor" a slur.  For example,
```
<slur tstamp="1" tstamp2="2"/>
<slur tstamp="1" tstamp2="2"/>
```
is ambiguous and should be
```
<slur staff="1" tstamp="1" tstamp2="2"/>
<slur staff="2" tstamp="1" tstamp2="2"/>
```
So, I usually add it even in single-staff encodings.

We might be able to do more with Schematron rules to make it clear when to use `@staff`, but that might be over-doing it.

**Comment by craigsapp** [comment]
> @staff isn't required by the schema, but it's use is necessary to provide clarity when there's more than one staff and the same time stamps are used on different staves to "anchor" a slur. For example,

That is all ok, I am just wondering from the programming side of MEI:  when the contents of one staff is moved to another staff, a slur with `@startid + @endid` would not need altering, while a slur with `@tstamp+@staff` would need to update the contents of `@staff`.

If you want to extract parts, then having `@staff` on the slur regardless makes the extraction more convenient; otherwise, you would have to find the `@startid` element and check its `@staff`.
