### ISSUE TITLE
grace="acc" v grace="unacc"

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#368]
The following example on the page:
http://music-encoding.org/documentation/3.0.0/cmn/#cmnNotesGrace
seems to be incorrect:

<img width="513" alt="screen shot 2016-12-29 at 01 43 14" src="https://cloud.githubusercontent.com/assets/3487289/21541003/39ae2836-cd68-11e6-9c76-ad7de13e5865.png">

<img width="245" alt="screen shot 2016-12-29 at 01 43 45" src="https://cloud.githubusercontent.com/assets/3487289/21541010/4162df04-cd68-11e6-9b9c-a4a8655bd7a1.png">

These are unaccented grace notes (accacciaturas) due to the slash on the stems, but they are encoded as `@grace="acc"` instead of `@grace="unacc"`.

**Comment by pe-ro** [comment]
According to standard terminology, this example is "incorrect".  But, as I remember it, this was intended to be a "counter example"; that is, it demonstrates that the accentuation and slashed stem of a grace note are independent.  This was probably too clever by half.  It would be better to encode it "correctly", then explain the attribute independence.

**Comment by rettinghaus** [comment]
So, does @grace imply any visual representation or has a slash always be
extra encoded? (And @grace is merely a performance indicator.)

Am 29.12.2016 3:26 nachm. schrieb "pe-ro" <notifications@github.com>:

**Comment by craigsapp** [comment]
At least in a modern context (perhaps since 1800 and probably earlier), a slash means an accacciatura (short unaccented grace note).  The time to play the accacciatura is typically taken from the previous note (i.e., the onset of the next note is not altered).  Some styles will play the accaciatura with zero duration (played as a chord note which is quickly released), and possibly technically on the beat with a slight delay for the main note.

  And a single grace note without a slash is usually an appoggiatura, and it is supposed to take time away from the note which follow it.

Modern style has been minimizing the use of appoggiaturas by notating them as regular notes.  Here is an example of a c1910 edition of a Haydn keyboard sonata:

<img width="221" alt="screen shot 2016-12-29 at 08 38 05" src="https://cloud.githubusercontent.com/assets/3487289/21548627/571f177e-cda2-11e6-842d-6bb12a9329d9.png">

It could be inferred that at the time this edition was published, musicians were probably not too familiar with the performance rendering of the appoggiatura grace note, since the edition draws dashed lines to indicate where each note should be played compared to the notes in the left hand.

Here is a 1937 edition which replaces the grace note with a regular note (and an accent is given to the note as well):

<img width="284" alt="screen shot 2016-12-29 at 08 37 51" src="https://cloud.githubusercontent.com/assets/3487289/21548714/cb9ef34e-cda2-11e6-9e37-2310d0a115f1.png">

**Comment by craigsapp** [comment]
I am wondering what sort of `grace` these notes should be notated as:

<img width="275" alt="screen shot 2016-12-29 at 08 27 02" src="https://cloud.githubusercontent.com/assets/3487289/21548877/c0ecae5e-cda3-11e6-945c-ba4e838458b7.png">

Probably technically as `@grace="unacc"` since they take their time from the previous note.  But these are not accacciaturas, just the last two notes of the trill ornament.

This is also an interesting encoding case.  The trill only applies to a single note in the chord and is not a double-note trill.

**Comment by pe-ro** [comment]
@craigsapp, I concur -- these notes should use `@grace="unacc"`, but not `@slash`.  This is why `@grace` and `@slash` have to be independent of each other.

This issue with grace notes could also be handled by adding a `<gruppetto>` element, but I fear that would introduce other problems.

**Comment by lpugin** [comment]
@pe-ro I am confused. Is the counter example correct? It is a counter example of what?

> it demonstrates that the accentuation and slashed stem of a grace note are independent

Does this mean we need both?

**Comment by craigsapp** [comment]
> @craigsapp, I concur -- these notes should use @grace="unacc", but not @slash. This is why @grace and @slash have to be independent of each other.

There are two broad categories of grace notes: acciaccaturas and appoggiaturas, which map fairly closely to the categories of unaccented and accented, respectively.  The slash is used to indicate acciaccaturas, and lack of slash (on a single note) indicates and appoggiatura.  Groups of grace notes beamed together do not get a slash, but always represent acciaccaturas:

<img width="916" alt="screen shot 2016-12-29 at 10 19 47" src="https://cloud.githubusercontent.com/assets/3487289/21550642/640f1b74-cdb0-11e6-955f-f1aebb59b1bd.png">

(some 20th-century repertories will put slashes on beamed grace notes, but these are mostly from hand-written scores published without a music editor or typesetter :-), and the slash probably helps to distinguish between regular notes and grace notes in manuscript).

Here is the general visual/gestural syntax for grace notes:

(1) a slash on a single grace note is an acciaccatura (meaning "crush" in Italian) it is very short and usually occurs before the beat.  It could occur on the beat (depending on the performer/school and specific repertory), but I would still argue that it remains unaccented due to its brevity.

(2) a single grace note without a slash is an appoggiatura.  This note typically takes half the time of the duration of the note which follows it.  It occurs on the beat (if the note it is attached to is on the beat) and is a non-harmonic tone which resolves to the main note.

(3) If grace notes are beamed, then they are acciaccaturas even though they do not have a slash.  An appogiatura can only be a single note (excepting possible corner cases), so there is no ambiguity for beamed grace notes, and hence no need for the slash.


So the default behavior of `@grace="unacc"` should be to implicitly add a visual slash to the grace note (if it is not beamed).  The default behavior of `@grace="acc"` should be to not add a slash.  And if grace notes are beamed together, there are no slashes on the stems or beams of the grace notes.

Is there `@slash` for note elements?  I don't see one:
http://music-encoding.org/documentation/3.0.0/note

**Comment by pe-ro** [comment]
@craigsapp --
> (some 20th-century repertories will put slashes on beamed grace notes, but these are mostly from hand-written scores published without a music editor or typesetter :-), and the slash probably helps to distinguish between regular notes and grace notes in manuscript).

There is 20th-century notation where beamed grace notes with a slash/slashes are other performance indications, like "play these notes as fast as possible".  In those cases, however, the slash is through the beam, not the stem of the individual notes.

> (1) a slash on a single grace note is an acciaccatura (meaning "crush" in Italian) it is very short and usually occurs before the beat. It could occur on the beat (depending on the performer/school and specific repertory), but I would still argue that it remains unaccented due to its brevity.

The statement that an acciaccatura "*usually* occurs before the beat" is what "acc(ented)" and "unacc(ented)" were intended to skirt around.  A definition like this isn't precise enough.  By separating the performance indication from the visual one (the slash), the combination of the attributes can be used to reinforce or contradict the traditional definitions. So --
```
<note grace="unacc" stem.mod="1slash"/>
```
fits the traditional definition of acciaccatura.  "acc" and "unacc" were intended to convey the position of the note (falling on the beat or off the beat, respectively), not whether it is actually accentuated or not.

> (2) a single grace note without a slash is an appoggiatura. This note typically takes half the time of the duration of the note which follows it. It occurs on the beat (if the note it is attached to is on the beat) and is a non-harmonic tone which resolves to the main note.

Again, separating the performance intention from the visual representation, a traditional appoggiatura may be represented as --
```
<note grace="acc"/>
``` 
or 
```
<note grace="acc" stem.mod="none"/>
```
to be absolutely clear.  But, the atypical case in your definition may be encoded as --
```
<note grace="unacc" stem.mod="none"/>
```
In other words, the binary distinction of the terms "acciaccatura" and "appoggiatura" just isn't detailed enough. Using 2 attributes provides the level of detail required to address the "sometimes", "usually", "commonly" weasel words that creep into the definitions of these things.

> So the default behavior of @grace="unacc" should be to implicitly add a visual slash to the grace note (if it is not beamed). The default behavior of @grace="acc" should be to not add a slash.

I don't think there can be a default behavior. For un-beamed notes, both attributes are necessary.  We can add a Schematron rule (in the CMN repertoires) to make sure that `@stem.mod` is required when `@grace` is used, if that will help.

>  And if grace notes are beamed together, there are no slashes on the stems or beams of the grace notes.

Addressing this will require having a better look at Stone's _Notation in the 20th Century_. 😄 

Sorry, there is no `@slash` attribute.  I meant `@stem.mod`.

@lpugin -- Yes, both `@grace` and `@stem.mod` are needed to completely describe grace notes. No, the example in the Guidelines isn't correct according to a strict, traditionalist approach.  It was intended to demonstrate an interpretation that isn't traditional.  But there are other, better ways of encoding such an interpretation, so the example should be changed to reflect the traditional view.

**Comment by craigsapp** [comment]
> Sorry, there is no @slash attribute. I meant @stem.mod.

I do not see application of `@stem.mod` to grace note slashes mentioned in the attribute documentation...

This would mean that there are two semantic uses of `@stem.mod`: one for tremolos and one for acciaccaturas:

<img width="325" alt="screen shot 2016-12-29 at 12 41 01" src="https://cloud.githubusercontent.com/assets/3487289/21554430/51c9df30-cdc4-11e6-896f-14bf297be627.png">

In other words, you are encoding logical features using visual features.   It does not seem to be a problem, as I have not seen a grace note with a tremolo, or a regular note with a grace-note slash.  But the functions of the slashes are very different.

In the context of `@stem.mod`, these are the rules I want to see for rendering:

<img width="1257" alt="screen shot 2016-12-29 at 12 57 35" src="https://cloud.githubusercontent.com/assets/3487289/21554677/6c73efd6-cdc6-11e6-8ab1-d24a03561c0b.png">

If `@grace="unknown"` is used, then `@stem.mod="none"` or `@stem.mod="1slash"` should be a requirement in the schematron rules, as this decision should not be left up to the renderer.

**Comment by pe-ro** [comment]
> I do not see application of `@stem.mod` to grace note slashes mentioned in the attribute documentation...

'Encodes any stem "modifiers"; that is, symbols rendered on the stem, such as tremolo or Sprechstimme indicators.'

Doesn't the phrase "such as" usually indicate a list of examples that is not exhaustive?

>  you are encoding logical features using visual features

I don't think so.  A grace note can be distinguished from other notes using `@grace`.  A tremolo can be distinguished using `<bTrem>`.  In --
```
<staff>
  <layer>
    <note grace="unacc" stem.mod="1slash"/>
    <bTrem>
      <note stem.mod="1slash"/>
    </bTrem>
  </layer>
</staff>
```
`@stem.mod` records only the visual characteristic.

**Comment by craigsapp** [comment]
>> 'Encodes any stem "modifiers"; that is, symbols rendered on the stem, such as tremolo or Sprechstimme indicators.'

> Doesn't the phrase "such as" usually indicate a list of examples that is not exhaustive?

If you do not say it explicitly, then it is left up to interpretation.  And you can't complain if someone interprets it differently from the intended meaning  :-)

SCORE treats these two cases completely separately: tremolos are a type of beam placed on a stem, likewise with Sprechstimme marks which are a symbol placed on the stem.  These can be placed anywhere on the stem, given various widths and sizes, rotation, etc.  Grace note slashes are a property of the note object in SCORE and it is a boolean: there is a slash or there is not a slash.  The slash cannot be styled in anyway.  So from a SCORE point of view, `@stem.mod` is a totally separate descriptor than a gracenote slash.

>>   you are encoding logical features using visual features

> I don't think so. A grace note can be distinguished from other notes using @grace. A tremolo can be distinguished using <bTrem>. In --
```
<staff>
  <layer>
    <note grace="unacc" stem.mod="1slash"/>
    <bTrem>
      <note stem.mod="1slash"/>
    </bTrem>
  </layer>
</staff>
```
> @stem.mod records only the visual characteristic.

The funny semantics is not in identifying  grace notes versus regular notes, but what category of grace note: either acciaccatura or appoggiatura, or in MEI terminology `acc` versus `unacc`.   There is a clear visual syntax defining these two categories which should not get mixed up in the encoding.  The example in the documentation is greatly confusing the issue and should be removed/replaced.  In other words, why is a `@grace="acc"` being shown with a slash?  The default visual semantics for `acc` would be to *not* have a slash in every standard CMN repertory that I can think of, so showing `acc` with a slash is a confusing corner case (hence this discussion).  And if you want `@grace="acc"` to have a slash, then it should be required to have `@stem.mod="1slash"`.

**Comment by pe-ro** [comment]
Like I've said, fixing the example is not a problem.

> if you want `@grace="acc"` to have a slash, then it should be required to have `@stem.mod="1slash"`.

Yes, if a slash is desired, then the way to express that is with `@stem.mod="1slash"`. Conversely, with `@grace="unacc"` the way to say that a slash is present is also `@stem.mod="1slash"`.  If a slash is not desired, then the way to express that is with `@stem.mod="none"`.  In other words, `@grace` and `@stem.mod` work independently of each other.

**Comment by craigsapp** [comment]
> Like I've said, fixing the example is not a problem.
 >>   if you want @grace="acc" to have a slash, then it should be required to have @stem.mod="1slash".
>Yes, if a slash is desired, then the way to express that is with @stem.mod="1slash". Conversely, with @grace="unacc" the way to say that a slash is present is also @stem.mod="1slash". If a slash is not desired, then the way to express that is with @stem.mod="none". In other words, @grace and @stem.mod work independently of each other.

OK, so you can fix the documentation :-)

**Comment by pe-ro** [comment]
Yes, I can and yes I will. :-)
