### ISSUE TITLE
trill@accidlower

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#370]
Just show-and-tell: Here is an example of trill@accidlower (which I have not seen very often):

<img width="623" alt="screen shot 2016-12-30 at 08 53 42" src="https://cloud.githubusercontent.com/assets/3487289/21569020/fcf16dde-ce6d-11e6-99cd-5039f8900cc6.png">

**Comment by pe-ro** [comment]
Thanks for the example.
