### ISSUE TITLE
Address vertical display order of articulations, tempo marks, etc.

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#390]
See discussion at https://github.com/music-encoding/music-encoding/issues/375.

**Comment by pe-ro** [comment]
@music-encoding/core-contributors: 

A question before proceeding with adding new attributes to control rendering order of "stuff" outside the staff (as suggested in #375) -- Does adding `@aboveorder`, etc. have any effect on/relationship with `@vo`?

**Comment by pe-ro** [comment]
Here's the list of staff-related things I think of as "stackable" --

```
beam/beamSpan
bend
breath
cpMark
dir
dynam
fermata
fing
fingGrp
hairpin
harm
harpPedal
ligature/ligatureSpan
mordent
octave
ornam
pedal
reh
tempo
trill
tuplet/tupletSpan
turn
```

I intentionally left out articulations, slur & phrase marks, and ties, but we could consider those as being part of the list too, if necessary.  Please speak up if other additions/deletions are needed.

One method of proceeding would be to allow each of these things to be a possible value in the proposed attributes, for example --
```
@aboveorder="reh ornam breath"
```
indicating that rehearsal marks should occur closest to the staff, then ornam elements, with breath signs top-most.

Another way to approach it is to assign each of these things to a class --
```
@aboveorder="ornaments lines text"
```
which would indicate that those things in the ornaments class (mordent, ornam, trill, turn, etc.) would get rendered closest to the staff with line-like things (e.g., beam/beamSpan, bend, octave, pedal, etc.) next, and text-y stuff (cpMark, dir, dynam, etc.) farthest away.  This provides a quick and easy to remember entry method that's good for human encoders, but may not be specific enough in that the renderer will still have to make a decision about where to put the things that are in the same class.  For example, given `<dir>` and `<tempo>` elements needing stacking, one program may put the tempo marking above the directive, while another program does the opposite.

In the absence of `@aboveorder`, `@beloworder`, or `@betweenorder` (which is needed for things with `@place="between"`, a set of default values will have to be documented.  @craigsapp has made suggestions along these lines already.

I believe these `@.*order` attributes are necessary on `<scoreDef>`, `<staffDef>`, and `<measure>` at a minimum.  Providing info at the sub-measure level may prove more difficult.  

One possibility is to use `<scoreDef>` and `<staffDef>` within the measure.  This matches the original intent of allowing these elements inside `<measure>`.  But from #324 , it appears there's some confusion where these elements ought to be allowed.

(In my opinion, since `<clef>`, `<keySig>`, and `<meterSig>` can occur in `<layer>`, it may be best to disallow `<scoreDef>` and `<staffDef>` inside `<measure>`, and allow them only between measures. But I digress ... 😀 )

Another approach is to add an `@order` attribute on the stackable items in the measure themselves --
```
<dir order="1"/>
<tempo order="2"/>
etc. 
```
which would indicate, given a potential overlap, where to place the item (in conjunction with the values in the `@staff` and `@place` attributes, of course).

Even if we take the second approach, I'm still inclined to remove `<scoreDef>` and `<staffDef>` from `<measure>`.  But that discussion should take place over at #324.

**Comment by kepper** [comment]
I agree to remove scoreDef / staffDef inside measure
I think the @order proposal is more flexible, as sources may not be perfectly following one set of rules. The @aboveorder etc. may provide sensible defaults, though. But like you, I can't see how this might be used on slurs etc., while that seems possible with @order (actually, it might be required to have @startorder and @endorder, but that's a different story…)

**Comment by craigsapp** [comment]
Here is a very rough default stacking order of the elements:

```
=== Furthest from note/staff ===

tempo
harm
dir
reh
harpPedal
pedal
octave
breath
fermata
hairpin
dynam
slur
ligature/ligatureSpan
tuplet/tupletSpan
fingGrp
fing
trill
ornam
turn
mordent
artic
bend
tie
beam/beamSpan
cpMark

=== Nearest to note/staff ===
```

Slurs are more complicated:  placement of a slur would ignore those elements higher on the list.  But if there is a space below the slur after placing it, some of them (dynamics and hairpins) should be placed below the slur.

**Comment by pe-ro** [comment]
Would it be better to remove slurs and ties from this list and deal with collisions involving these separately; that is, entirely programmatically?

**Comment by craigsapp** [comment]
It is not unreasonable to omit slurs and ties, although they are somehow involved in stacking.

Here is a tricky case:

<img width="598" alt="screen shot 2017-01-28 at 09 37 06" src="https://cloud.githubusercontent.com/assets/3487289/22398433/6e0b98c4-e53d-11e6-83c2-6246da334031.png">

The mordent in the first measure is above the slur, and the mordent in the second measure is below the slur.  Probably the algorithm for both is that the mordent is placed first and then the slur is placed.  In the first case the slur could not be moved closer to the notehead than the mordent, so it goes above; and in the second case it was able to go below the mordent and ends up close to the notehead.

**Comment by pe-ro** [comment]
Of course slurs and ties are involved in stacking, but I was thinking of them as "wildcards" in the process that can't be totally controlled in every case, so why not just omit them?  But, this raises the issue of whether a user-supplied stacking order must be followed absolutely or whether it's simply a "hint" provided to the renderer.  I was thinking of it as absolute; that is, it's a constraint on the ability of the renderer to arrange the stackable items according to its own standards.

**Comment by pe-ro** [comment]
This chunk of ODD implements `@aboveorder`, `@beloworder`, and `@betweenorder` on `<scoreDef>` and `<staffDef>` --
```
<macroSpec ident="data.STAFFITEM.basic" module="MEI" type="dt" mode="add">
  <desc>Items in all repertoires that may be printed near a staff.</desc>
  <content>
    <valList type="closed">
      <valItem ident="accid"/>
      <valItem ident="annot"/>
      <valItem ident="artic"/>
      <valItem ident="dir"/>
      <valItem ident="dynam"/>
      <valItem ident="harm"/>
      <valItem ident="ornam"/>
      <!-- more note-attached than staff-attached? -->
      <!--<valItem ident="phrase"/>-->
      <valItem ident="sp"/>
      <valItem ident="stageDir"/>
      <valItem ident="tempo"/>
    </valList>
  </content>
</macroSpec>
<macroSpec ident="data.STAFFITEM.cmn" module="MEI.cmn" type="dt" mode="add">
  <desc>Items in the CMN repertoire that may be printed near a staff.</desc>
  <content>
    <valList type="closed">
      <valItem ident="beam"/>
      <!-- beamSpan is subsumed within "beam" -->
      <!--<valItem ident="beamSpan"/>-->
      <valItem ident="bend"/>
      <valItem ident="breath"/>
      <valItem ident="cpMark"/>
      <valItem ident="fermata"/>
      <valItem ident="fing"/>
      <!-- fingGrp is subsumed within "fing" -->
      <!--<valItem ident="fingGrp"/>-->
      <valItem ident="hairpin"/>
      <valItem ident="harpPedal"/>
      <valItem ident="ligatureSpan"/>
      <valItem ident="lv"/>
      <valItem ident="mordent"/>
      <valItem ident="octave"/>
      <valItem ident="pedal"/>
      <valItem ident="reh"/>
      <!-- more note-attached than staff-attached? -->
      <!--<valItem ident="slur"/>-->
      <valItem ident="tie"/>
      <valItem ident="trill"/>
      <valItem ident="tuplet"/>
      <!-- tupletSpan is subsumed within "tuplet" -->
      <!--<valItem ident="tupletSpan"/>-->
      <valItem ident="turn"/>
    </valList>
  </content>
</macroSpec>
<macroSpec ident="data.STAFFITEM.mensural" module="MEI.mensural" type="dt" mode="add">
  <desc>Items in the Mensural repertoire that may be printed near a staff.</desc>
  <content>
    <valList type="closed">
      <valItem ident="ligature"/>
    </valList>
  </content>
</macroSpec>
<macroSpec ident="data.STAFFITEM.neumes" module="MEI.neumes" type="dt" mode="add">
  <desc>Items in the Neume repertoire that may be printed near a staff.</desc>
</macroSpec>
<macroSpec ident="data.STAFFITEM" module="MEI" type="dt" mode="add">
  <desc>Items that may be printed above, below, or between staves.</desc>
  <content>
    <alternate>
      <macroRef key="data.STAFFITEM.basic"/>
      <macroRef key="data.STAFFITEM.cmn"/>
      <macroRef key="data.STAFFITEM.mensural"/>
      <macroRef key="data.STAFFITEM.neumes"/>
    </alternate>
  </content>
</macroSpec>
<classSpec ident="att.staffItems" module="MEI.shared" type="atts" mode="add">
  <desc>Attributes that describe items printed near (above, below, or between) staves</desc>
  <attList>
    <attDef ident="aboveorder">
      <desc>Describes vertical order of items printed above a staff, from closest to
        farthest away from the staff.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.STAFFITEM"/>
      </datatype>
    </attDef>
    <attDef ident="beloworder">
      <desc>Describes vertical order of items printed below a staff, from closest to
        farthest away from the staff.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.STAFFITEM"/>
      </datatype>
    </attDef>
    <attDef ident="betweenorder">
      <desc>Describes vertical order of items printed between staves, from top to
        bottom.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.STAFFITEM"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
<classSpec ident="att.scoreDef.vis" module="MEI.shared" type="atts" mode="replace">
  <desc>Visual domain attributes for scoreDef in the CMN repertoire.</desc>
  <classes>
    <memberOf key="att.barPlacement"/>
    <memberOf key="att.cleffing.vis"/>
    <memberOf key="att.distances"/>
    <memberOf key="att.endings"/>
    <memberOf key="att.keySigDefault.vis"/>
    <memberOf key="att.lyricStyle"/>
    <memberOf key="att.measureNumbers"/>
    <memberOf key="att.meterSigDefault.vis"/>
    <memberOf key="att.multinumMeasures"/>
    <memberOf key="att.notationStyle"/>
    <memberOf key="att.oneLineStaff"/>
    <memberOf key="att.optimization"/>
    <memberOf key="att.pages"/>
    <memberOf key="att.spacing"/>
    <memberOf key="att.staffItems"/>
    <memberOf key="att.systems"/>
    <memberOf key="att.textStyle"/>
    <memberOf key="att.scoreDef.vis.cmn"/>
    <memberOf key="att.scoreDef.vis.mensural"/>
  </classes>
  <attList>
    <attDef ident="vu.height" usage="opt">
      <desc>Defines the height of a "virtual unit" (vu) in terms of real-world units. A
        single vu is half the distance between the vertical center point of a staff line and
        that of an adjacent staff line.</desc>
      <datatype>
        <rng:data type="token">
          <!-- px and vu are *not* allowed here because they're not real-world units -->
          <rng:param name="pattern">\d+(\.\d+)?(cm|mm|in|pt|pc)</rng:param>
        </rng:data>
      </datatype>
    </attDef>
  </attList>
</classSpec>
<classSpec ident="att.staffDef.vis" module="MEI.shared" type="atts" mode="replace">
  <desc>Visual domain attributes for staffDef.</desc>
  <classes>
    <memberOf key="att.cleffing.vis"/>
    <memberOf key="att.distances"/>
    <memberOf key="att.keySigDefault.vis"/>
    <memberOf key="att.lyricStyle"/>
    <memberOf key="att.meterSigDefault.vis"/>
    <memberOf key="att.multinumMeasures"/>
    <memberOf key="att.oneLineStaff"/>
    <memberOf key="att.scalable"/>
    <memberOf key="att.staffItems"/>
    <memberOf key="att.textStyle"/>
    <memberOf key="att.visibility"/>
    <memberOf key="att.staffDef.vis.cmn"/>
    <memberOf key="att.staffDef.vis.mensural"/>
  </classes>
  <attList>
    <attDef ident="grid.show" usage="opt">
      <desc>Determines whether to display guitar chord grids.</desc>
      <datatype>
        <rng:ref name="data.BOOLEAN"/>
      </datatype>
    </attDef>
    <attDef ident="layerscheme" usage="opt">
      <desc>Indicates the number of layers and their stem directions.</desc>
      <datatype>
        <rng:ref name="data.LAYERSCHEME"/>
      </datatype>
    </attDef>
    <attDef ident="lines" usage="opt">
      <desc>Indicates the number of staff lines.</desc>
      <datatype>
        <rng:data type="positiveInteger"/>
      </datatype>
    </attDef>
    <attDef ident="lines.color" usage="opt">
      <desc>Captures the colors of the staff lines. The value is structured; that is, it
        should have the same number of space-separated RGB values as the number of lines
        indicated by the lines attribute. A line can be made invisible by assigning it the
        same RGB value as the background, usually white.</desc>
      <datatype maxOccurs="unbounded">
        <rng:ref name="data.COLOR"/>
      </datatype>
    </attDef>
    <attDef ident="lines.visible" usage="opt">
      <desc>Records whether all staff lines are visible.</desc>
      <datatype>
        <rng:ref name="data.BOOLEAN"/>
      </datatype>
    </attDef>
    <attDef ident="spacing" usage="opt">
      <desc>Records the absolute distance (as opposed to the relative distances recorded in
        <gi scheme="MEI">scoreDef</gi> elements) between this staff and the preceding one
        in the same system. This value is meaningless for the first staff in a system since
        the spacing.system attribute indicates the spacing between systems.</desc>
      <datatype>
        <rng:ref name="data.MEASUREMENTREL"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```
`data.STAFFITEM` (used by `@aboveorder`, `@beloworder` and `@betweenorder`) is comprised of more specific datatypes: `STAFFITEM.basic` (for shared values), `STAFFITEM.cmn`, `STAFFITEM.mensural`, and `STAFFITEM.neumes`. By placing these in their associated module, they'll be turned off if the module isn't used. The attributes are collected in `att.staffItems`, which is used by `<scoreDef>` and `<staffDef>`.

`@order` (actually `@vorder`) on all the elements represented in the list in `data.STAFFITEM` is still to be done.

**Comment by lpugin** [comment]
By any chance, do you have a small corresponding encoding snippet?

**Comment by pe-ro** [comment]
```
<scoreDef aboveorder="cpMark beam tie bend artic mordent turn ornam trill fing 
  tuplet ligatureSpan ligature dynam hairpin fermata breath octave pedal harpPedal
  reh dir harm tempo" beloworder="tempo harm dir reh harpPedal pedal octave breath
  fermata hairpin dynam ligature ligatureSpan tuplet fing trill ornam turn mordent
  artic bend tie beam cpMark"/>
```
The values in `@aboveorder`, `@beloworder`, and `@betweenorder` provide the _ideal stacking order_ of staff-associated items, not necessarily the way they will ultimately appear, which depends on a number of other factors, not the least of which is collisions between the things listed here and other things that appear on the staff, like notes and slurs, or things that may appear in the list but that are absolutely positioned.  If any of the possible values isn't present, then those items are assumed to be at the end of the list.  For example, if "annot" isn't listed in `@aboveorder`, then it would be positioned (in the absence of other info on the annotation itself) higher than tempo marks.

In `@aboveorder` and `@beloworder` the first item is the one closest to the staff.  This makes it possible to move a `<dir>` from above the staff to below without having to modify the values in `@aboveorder` and `@beloworder`.  For example, if
```
<dir staff="1" place="above">Foo</dir>
```
becomes
```
<dir staff="1" place="below">Foo</dir>
```
the directive will end up lower than rehearsal marks and higher than harmonic labels -- just the opposite of its positioning when it was above the staff.  This will also jibe with `@vorder`, which will take integer values.  For example, the vertical order can be overridden for a particular item by giving it a `@vorder` value different from its positional index in `@aboveorder`.  The following markup
```
<dir staff="1" place="above" vorder="1">
```
says that this directive should be placed closer to the staff than anything else without a `@vorder` attribute.  This is why I said `@aboveorder` etc. represent the _ideal_ vertical ordering.  `@vorder` provides for absolute vertical ordering.

By the way, don't hold me to this set of values.  It's all the staff-associated stuff I could come up with, but with some values combined.  For example, I couldn't justify providing both "tuplet" and "tupletSpan" when these things should be (at least to my thinking) rendered at the same height.  On the other hand, I left "ligature" and "ligatureSpan" because these entities occur in different repertoires (and therefore in different modules).  I'd be just as happy to collapse these into "ligature" as well.  I left out "slur" and "phrase" since the calculations to position these things are much more complex.  I also wonder if "beam", "lv", "tie", "tuplet" shouldn't be dropped too, since they're more "note-associated" than "staff-associated".  Lyrics aren't considered.  In short, it may be worthwhile to do some more thinking about what does and doesn't belong in the list.

We may even want to collapse the list down to a set of "classes", for example,
```
SYMBOLS
  accid
  artic
  bend
  breath
  fermata
  mordent
  ornam
  trill
  turn

LINES
  harpPedal
  ligature
  octave
  pedal

DYNAMICS
  dynam
  hairpin

REHEARSAL
  reh

HARMONY
  harm

ANNOTATIONS
  annot
  cpMark

FINGERINGS
  fing

TEXT
  dir
  sp
  stageDir
  tempo

OTHER?
```
In this approach, the classes would be "order-able" but not the items within the class.  Order of items in the same class could be determined from the encoding order in the file or even randomly.  Of course, the most deterministic way to say how items in the same class should be ordered would be to use `@vorder`.

**Comment by sonovice** [comment]
Since the issue was closed: Is there now a defined order of elements that should normally be used?

**Comment by kepper** [comment]
In MEI v4, this is handled by `@aboveorder` / `@beloworder` on `<staffDef>`. C.f. 

- https://music-encoding.org/guidelines/v4/attribute-classes/att.staffitems.html
- https://music-encoding.org/guidelines/v4/data-types/data.staffitem.html

**Comment by kepper** [comment]
which means no, there is no default order. MEI very rarely prescribes defaults – they're usually too context-dependent…
