### ISSUE TITLE
attribute list in guidelines

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#395]
At the moment the guidelines provide a list of attribute classes. This is good, but quite unintuitive if for users not into ODD modelling. An alphabetical list of attribute names (maybe with indication of the class they are part of) would be a very good addition.

**Comment by kepper** [comment]
You mean like the third row at http://music-encoding.org/documentation/3.0.0/caption/ (or any other element)?

**Comment by bwbohl** [comment]
I mean as an alternative to http://music-encoding.org/documentation/3.0.0/atts/
Which is good to have but both misleading in its name URL "…/atts/" and the link labels on music-encoding ("Attributes") but actually is (as stated in the page heading) "Attribute classes".

See for example:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/REF-ATTS.html
