### ISSUE TITLE
Naming of mordent

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#401]
The mordent/inverted mordent labels in MEI are ambiguous.  I would propose avoiding calling them "mordent" and "inverted mordent" and instead call them "upper mordent" and "lower mordent", such as this random sample from the web:

<img width="517" alt="screen shot 2017-02-02 at 01 31 30" src="https://cloud.githubusercontent.com/assets/3487289/22543958/b793bf64-e8e7-11e6-9e78-d52edaffcc9e.png">

The problem is primarily due to the fact that the lower-mordent was called a plain "mordent" in the Baroque era:

<img width="546" alt="screen shot 2017-02-02 at 01 32 43" src="https://cloud.githubusercontent.com/assets/3487289/22543996/e6897e44-e8e7-11e6-88b1-94ac1fa8a806.png">

However, in the 19th century the names switched so that the upper-mordent was the one called a plain "mordent" and the lower mordent was then called the "inverted mordent":

<img width="496" alt="screen shot 2017-02-02 at 01 30 46" src="https://cloud.githubusercontent.com/assets/3487289/22544071/24cd5086-e8e8-11e6-9806-6181494fa7d4.png">

I doubt that the term "inverted mordant" was used in the Baroque era, so using that terms would imply the modern labeling system.

Using `upper` and `lower` (or choosing one of them to be the `norm`), would be better to avoid confusion in the meaning of `mordent@form`.

See https://github.com/rism-ch/verovio/issues/464

**Comment by pe-ro** [comment]
Just to be clear, you're suggesting that `@form` use the values "upper" and "lower" instead of "norm" and "inv"?

**Comment by craigsapp** [comment]
Yes.  Or keep `norm` for the lower mordent, and use `upper` instead of `inv` (it would be clear that `norm` means `lower` in that case).

**Comment by pe-ro** [comment]
There's a symmetry to "upper" and "lower" that's appealing. 😀

**Comment by rettinghaus** [comment]
I checked several german handbooks for that matter. They were always called "Mordent" for the lower and "Pralltriller" (or "Praller") for the upper. The english Wikipedia says, following Eric Tayler, that 
> the lower mordent became known as an inverted mordent.

This seems to be nonsense (even @donbyrd wonders about that). 
A quick Google books search for "inverted mordent" shows that in 19th century this is used for the upper "Pralltriller". 

As the Guidelines are totally clear about this I recommend to stay with "norm" and "inv" as in `<turn>`.

**Comment by pe-ro** [comment]
The point is that at some point there was a complete reversal of the meaning of "normal" and "inverted".  So, I think @craigsapp is right to say that avoidance of these terms would be better.  Using "upper" and "lower" (perhaps for `<turn>` too) would remove any ambiguity by encoding the intended performance, not the sign.  The sign can be indicated using `@altsym`, `@glyphnum`, or `@glyphname`.

**Comment by rettinghaus** [comment]
I dare to contradict. This wouldn't remove any ambiguity by encoding the intended performance, as the *performance style* changed at some point (at least for "upper"). Same with trills. If you want to split up visual appearance and performed style then you would have to add an attribute for declaring the specific style. And then there's a whole bunch of new and changed attributes. 
On the other hand there's `@long` which won't go along nicely with both forms, "inv" and "norm". So to clear this up, the visual aspect should be merged into one single attribute with values "norm" (or whatever) for the short zigzag line, "stroked" and "long".

**Comment by craigsapp** [comment]
> I dare to contradict. This wouldn't remove any ambiguity by encoding the intended performance, as the performance style changed at some point (at least for "upper")

The mordent with a slash always means "lower mordent", and the mordent without a slash always means the "upper mordent".  So there is no ambiguity in the intended performance of the two symbols, only in which one to call a regular "mordent" and which to call "inverted mordent".  

`upper`/`lower` would match the accented/unaccented nomenclature used for grace notes in MEI.

**Comment by craigsapp** [comment]
Is there any case where a slashed mordent is not a lower mordent?  If that is true, then there could also be something like `@slash="true"` for drawing a line through the main squiggle; otherwise `@form="lower"` would indicate a slash through the mordent squiggle.

Also, `<mordent>` can have both `@accidlower` and `@accidupper` at the same time (that is impossible as that would sound like a turn).  There should be a schematron warning if the wrong attribute is used for the `@form` (`@accidlower` when `@form="upper"` for example).  Alternatively, `@accidlower` and `@accidupper` could be merged into `@accid`, and `@form="upper|lower"` could be the control for if it is the upper or lower accidental.

For example:

```xml
          <mordent form="lower" accid="n">
```

for the mordent:

<img width="51" alt="screen shot 2017-02-05 at 12 07 34" src="https://cloud.githubusercontent.com/assets/3487289/22629481/bf8bf0cc-eb9b-11e6-86c8-1e5ff71f1922.png">


`@accid.ges` should also be allowed on `<mordent>`.  This is important for realizing mordents in MIDI.  For example:

```xml
     <note xml:id="note1" pname="c" oct="5" dur="4">
     <mordent startid="#note1" form="lower">
```

When `@accid` is missing, then the gestural accidental is undefined, and it is complicated to calculate from the external context: It will be dependent on the key, previous accidental changes on the diatonic pitch in the measure, and even on the staff or layer that note with the mordent is in (due to cross-staff display of notes for example).

If in the key of F major, this might happen:

```xml
     <note xml:id="note1" pname="c" oct="5" dur="4">
     <mordent startid="#note1" form="lower" accid.ges="f">
```

In G major, this might happen:

```xml
     <note xml:id="note1" pname="c" oct="5" dur="4">
     <mordent startid="#note1" form="lower" accid.ges="n">
```

**Comment by donbyrd** [comment]
I've always thought a slashed mordent always involves the lower neighbor, not the upper, and my home collection of music dictionaries seem to agree. (All three also agree that the word "mordent" alone means the slashed one.) But I'd have more confidence in New Grove, or the opinion of a Baroque specialist like Eleanor Selfridge-Field!

I did learn something interesting from the dictionaries, though. It seems that the terms _upper mordent_ and _lower mordent_ are pretty widely used, i.e., your random web sample isn't so random :-) .

**Comment by craigsapp** [comment]
> I've always thought a slashed mordent always involves the lower neighbor,

Yes, that is the only way I have seen it, but who knows... :-)

"upper" and "lower" mordent seem difficult to mess up, unlike "regular" and "inverted" mordents.

The upper mordent seems to have the names pralltrifler or schneller in German (which are not used in English).   Perhaps they are reversed in English because the slash is analogous to "=" versus "≠", where the symbol without the slash is the primary form, and the one with the slash is the negative form.  

And perhaps which one is called a regular "mordent" is related to which one is more common in a given era.  In the Mozart piano sonatas, I find that about half of the sonatas contain upper mordents, and I cannot find any lower mordents.  This is the most likely the reason for the linguistic shift.

<img width="583" alt="screen shot 2017-02-05 at 23 11 17" src="https://cloud.githubusercontent.com/assets/3487289/22637724/6e654be6-ebf8-11e6-8ea3-01aa5a6c867d.png">

I also find only two Beethoven piano sonata movements with upper mordents and none with lower mordents (sonata 3 mvmt 1, and sonata 2 mvmt 4).




------------------

Here is mention of a double mordent (no symbol given):

https://books.google.com/books?id=_XYAAAAAYAAJ&pg=PA859&lpg=PA859#v=onepage&q&f=false

<img width="304" alt="screen shot 2017-02-05 at 22 53 53" src="https://cloud.githubusercontent.com/assets/3487289/22637324/1e2b8f0c-ebf6-11e6-8383-1f7429ee14dc.png">

Also:
https://www.merriam-webster.com/dictionary/double%20mordent

So in principle, there could be more than one accidental for this sort of mordent.

Image of a doppelschlag:

http://www.musikzeit.de/theorie/bilder/doppelschlag8.gif

<img width="225" alt="screen shot 2017-02-06 at 00 05 06" src="https://cloud.githubusercontent.com/assets/3487289/22638871/f2c9db2a-ebff-11e6-8753-ffb424b98492.png">

which looks a lot like a turn...

**Comment by donbyrd** [comment]
Interesting. The doppelschlag looks _exactly_ like a turn, and it does seem as if there could be two accidentals on it!

"upper" and "lower" mordent seem enormously more difficult to mess up than "regular" and "inverted" -- especially since (as you say) which is more common seems to have changed over time. So you and I agree, and no one else has commented on this issue in a few days, so I'm tempted to declare the naming issue is settled.

**Comment by rettinghaus** [comment]
The Doppelschlag looks like a turn because it *is* a turn! 
The lower mordent always carries a slash. I was just wondering if it could make sense to separate completely the visual appearance from performance. "upper" and "lower" should be sufficient for *implicitly* stating the form. One could (be forced to) rely on `@glyphnum` or `@glyphname` for an explicit statement. 

Would "upper" and "lower" on `<turn>` specify the *first* neighbor tone? 

And what about `@form` for `<trill>`? If there's a wiggly line or a plus sign instead of a *tr* do you have to use `@glyphname` / `@glyphnum` (as the *performance* is the same)?

**Comment by craigsapp** [comment]
> Would "upper" and "lower" on `<turn>` specify the first neighbor tone?

I would say yes.

Here is a good webpage on turns:

http://musicofyesterday.com/historical-music-theory/musical-ornaments-how-to-execute-a-turn

which gets messy...

**Comment by donbyrd** [comment]
I agree, "upper" and "lower" on <turn> should specify the first neighbor tone.

That webpage on turns looks good, but it brings up the question of the symbol for the "inverted" turn. It proposes the normal turn symbol rotated by 90 degrees; the alternative is just to draw the normal turn symbol backwards. I believe the latter is more common, and, like the normal turn symbol, it shows the changes of pitch graphically; on the other hand, it's much easier to confuse with the normal symbol. I just checked four or five notation books, including _Behind Bars_ and Gardner Read's; none of them says anything about the symbol for inverted turn. I also checked a couple of music dictionaries; both show both possibilities but neither recommends either one.

**Comment by craigsapp** [comment]
> It proposes the normal turn symbol rotated by 90 degrees; the alternative is just to draw the normal turn symbol backwards.

> on the other hand, it's much easier to confuse with the normal symbol.

Probably some composers/publishers rotated the turn symbol 90 degrees to make it more obvious than a reflection so that it is not confused with a regular turn.  But the "S" shape and the inverse "S" shape give a good indication of the melodic contour of the ornament to be performed, so I would also say that performers just have to learn to distinguish between those forms rather than the more obvious rotation to differentiate them.

But that would be a styling that might be useful to be able to encode in MEI, particularly if the meaning of the symbol is not clearly understood.

```xml
    <turn form="norm" rotation="90">
```

Or form could encode the function as well:

```xml
    <turn form="inv" rotation="90">
```

As long as it looks like a reverse "S" as opposed to a regular "S" in that case.

Another style for inverse turn is similar to mordents, where a slash is added to the regular turn (and might be another reason why there is confusion about the inverted mordent label):

<img width="73" alt="screen shot 2017-02-07 at 10 02 07" src="https://cloud.githubusercontent.com/assets/3487289/22704413/818b8562-ed1c-11e6-8098-27475d8f9d54.png">

So perhaps:

```xml
    <turn form="norm" slash="true">
```

SMuFL turn glyphs:

<img width="557" alt="screen shot 2017-02-07 at 10 07 08" src="https://cloud.githubusercontent.com/assets/3487289/22704660/55317f3e-ed1d-11e6-9ffe-d9f6b89d6137.png">

And what is this:

<img width="188" alt="screen shot 2017-02-07 at 10 07 33" src="https://cloud.githubusercontent.com/assets/3487289/22704667/5c35ae0e-ed1d-11e6-9091-90dca9bd3b67.png">

It looks like a handwritten ornamentTurnSlash.  Perhaps it is the same as this ornament in C.P.E. Bach:

<img width="162" alt="screen shot 2017-02-07 at 10 10 33" src="https://cloud.githubusercontent.com/assets/3487289/22704789/d4b6dfa6-ed1d-11e6-943f-e2ac6c1f5bf9.png">

which I think is a trill with a turn at the end of it (or the other way around).

**Comment by pe-ro** [comment]
I think the visual symbol vs. intended meaning conundrum can be resolved by removing any discussion of specific signs from the description of the values of `@form`.  This removes any co-dependency between `@form` and `@glyphnum/@glyphname`.  For example --
```
<attList>
  <attDef ident="form" usage="opt">
    <desc>Records semantic meaning, i.e., intended performance, of the mordent. The
        <att>altsym</att>, <att>glyphname</att>, or <att>glyphnum</att> attributes may be used to
      specify the appropriate symbol.</desc>
    <valList type="closed">
      <valItem ident="lower">
        <desc>Starts with the written note, followed by its lower neighbor, with a
          return to the written note.</desc>
      </valItem>
      <valItem ident="upper">
        <desc>Starts with the written note, followed by its upper neighbor, with a
          return to the principal note.</desc>
      </valItem>
    </valList>
  </attDef>
  <attDef ident="long" usage="opt">
    <desc>When the long attribute is set to 'true', a double or long mordent, sometimes called a
      "tremblement", consisting of 5 notes, is indicated.</desc>
    <datatype>
      <rng:ref name="data.BOOLEAN"/>
    </datatype>
  </attDef>
</attList>
```
This makes it possible, as stated in the description of `@form`, to associate either symbol (SMuFL U+E56C, ornamentMordent, or U+E56D, ornamentMordentInverted) with the value of `@form`.

This leads to several markup possibilities.
1. The encoder indicates the presence of a mordent, but not its form or sign.  Any rendition, visual or aural, is left to the rendering software.
```
<mordent tstamp="1"/>
```
2. The encoder (e.g., OMR) knows the sign, but not its interpretation.  Since `@form` is optional, it can be omitted.
```
<mordent tstamp="1" glyphnum="U+E56C"/>
```
3. The encoder is concerned with the performance info, but not the sign.  The specific sign can be supplied by the renderer (most likely based on modern practice) with the caveat that it has a 50% chance of being wrong unless there's other data in the file that could help it choose the appropriate sign.  We can discuss later what/where this info might be found.
```
<mordent tstamp="1" form="lower"/>
```
4. The encoder captures the performance info and the sign.  The sign chosen may confirm or contravene modern practice.  In either case, the intention is explicit.
```
<mordent tstamp="1" form="upper" glyphnum="U+E56C"/>
```
