### ISSUE TITLE
Allow @breaksec on rests

### ISSUE THREAD

**Issue by th-we** [music-encoding/music-encoding#402]
`<rest>`s can be under beams, which means they can also be at a place where secondary beams are interrupted, like in this example from [sibeliusblog.com](http://www.sibeliusblog.com/tutorials/beam-over-rests-with-more-control-by-using-the-keypad/) (top staff, last beam):

![secondary beam broken at a rest](http://www.sibeliusblog.com/wp-content/uploads/2013/01/03-moved-rests1-300x81@2x.png)

The shown example is artificial, but I still think that `@breaksec` is missing from `<rest>`s. Any opinions?

**Comment by pe-ro** [comment]
I think you're right. 😀
