### ISSUE TITLE
default clef position

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#404]
As `@clef.line` is optional I wonder what the default position for a clef would be if it isn't set? I assume it should mean "the center of the staff". This gets vitally important for percussion clefs on staffs with an even number of lines and has to be cleared in the documentation: 

![drums-1](https://cloud.githubusercontent.com/assets/7693447/22980680/7b70a534-f39a-11e6-9b83-3e3ec692f2bc.png)

**Comment by pe-ro** [comment]
`@clef.line` must be set when `@clef.shape` is anything other than "perc" or "TAB".  When `@clef.shape` has one of these values, `@clef.line` should be ignored, since these always appear vertically centered on the staff.
