### ISSUE TITLE
Scordatura example/unusual key signatures

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#415]
Here is some interesting notation for encoding:

<img width="947" alt="screen shot 2017-03-06 at 10 03 18 am" src="https://cloud.githubusercontent.com/assets/3487289/23622693/790ce0f0-0254-11e7-934a-782baa4e33af.png">

J.S. Bach cello suite no. 5 in C minor, BWV 1011, Breitkopf & Härtel/Klengel, *c*1900.

(http://ks.imslp.net/files/imglnks/usimg/9/97/IMSLP36902-PMLP04291-Bach-BWV1007-1012klengel.pdf)
 

The cellist can optionally tune the top string down a whole tone to play the top staff (scordatura), or use the regular tuning by reading the bottom staff.

MEI can handle this pretty well, with liberal use `@pname.ges`/`@oct.ges`/`@accid.ges`.  A tricky item is the key signature of the top staff.  How would that be encoded?  The problem is that it is a super-position of the regular key signature (C minor) and a transposed key signature (D minor) which applies only to the top string).  This results in the `@pname="a"` of the key signature having two different states: the lower A being flat for C minor, and the upper being natural for D minor.

`keySig@sig.mixed` seems close to what is needed, but it only seems to encode a horizontal sequence of accidentals, without a way to encode the accidentals vertically aligned.  Semantically it is two key signatures (3-flats and an irregular one with a-natural), so one possibility would be a way of encoding two keySig elements and instructions on how to overlap them.

This is also somewhat related to key signatures such as:

<img width="344" alt="screen shot 2017-03-06 at 10 32 07 am" src="https://cloud.githubusercontent.com/assets/3487289/23623800/36de2c94-0258-11e7-8423-a4265ad53e6e.png">

How are these encoded in MEI?

**Comment by pe-ro** [comment]
For the 'cello notation use --
```
<keySig>
  <keyAccid pname="b" oct="2" accid="f"/>
  <keyAccid pname="e" oct="3" accid="f"/>
  <keyAccid pname="a" oct="2" accid="f"/>
  <keyAccid pname="a" oct="3" accid="n"/>
</keySig>
```
The other examples work the same way.

There's no info about how to place the individual accidentals, but I'd venture to guess that accidentals on the same pitch name in different octaves should be vertically aligned.

**Comment by craigsapp** [comment]
Thank!  I'll keep that in mind for feature requests for verovio :-) . (I have some late Renaissance music which will need the octave-flat key signatures).
