### ISSUE TITLE
horizontal grouping of note@artic

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#416]
Here is another weird case for music encoding:

<img width="100" alt="screen shot 2017-03-06 at 10 44 29 am" src="https://cloud.githubusercontent.com/assets/3487289/23624358/48c36bf2-025a-11e7-8ab9-a2a2d2324b10.png">

J.S. Bach cello suite no. 5, prelude, Durand/Pollain 1918.

(http://ks.imslp.net/files/imglnks/usimg/4/47/IMSLP105620-PMLP04291-Bach_-_6_Suites_for_Cello_Solo__Pollain__Durand_1918.pdf)

There are three bowing articulation marks, with two attached to the first note, and the second one attached to an invisible grace note with a slur linking the bowing to the following note.

(1) How should the two bowings on the first note be encoded?  They need to be horizontally rendered on the note as opposed to the usual vertical alignment for articulations.  In other words the pair act as a single articulation unit.

(2) How should the last bowing mark be encoded?  Can it be encoded as a floating element, which seems the best semantic expression of it in this case? and how to place it, since `@tstamp` cannot address grace-note positions?  and there is no grace note to attach it to with `@startid`... 

The slur should not be difficult to encode, since `@startid` could refer to the floating bowing.

Alternately the three bowings could be grouped together since the last one is part of the trill ornamentation.  But if there were a wide spacing between the notes, the last bowing mark should probably be spatially attached to the next note, and a gap would be placed between the second and third bowing marks.

**Comment by craigsapp** [comment]
And unrelated, but in the following measure is another peculiarity:

<img width="253" alt="screen shot 2017-03-06 at 11 04 29 am" src="https://cloud.githubusercontent.com/assets/3487289/23625083/c9124ab0-025c-11e7-90b4-e278049dbe0b.png">

This could be encoded in MEI with no problem by attaching the second fermata to `@tstamp="2"` (or `@qstamp=1.5` :-), although this does not accurately capture the semantics of the notation (the second fermata acts as a caesura, which is often indicated as a double slash at the top of the staff, or it could behave similar to a breath mark in an instrument played by breath).

**Comment by pe-ro** [comment]
`<dir>` is the go-to work-around for almost anything placed around (instead of on) the staff.  I admit it's a little kludgey, but I'd use --

```
<dir type="caesura" tstamp="1.5">
  <symbol glyphnum="whateverTheSmuflNumberIsForFermata"/>
</dir>
```

`<dir>` provides the mechanism for placement, while its content is the thing you want to render.  I'm reluctant to allow `<symbol>` to appear where `<dir>` can occur because it will lead encoders to focus on the visual result rather than the semantic encoding, which I believe a "pause here" indication is.  There just happen to be specific elements for `<fermata>` and `<breath>` but not for `<caesura>` 'cause it's gotta stop somewhere. 😀

**Comment by pe-ro** [comment]
The bowing mark can be handled in the same way as the fermata/caesura.  You can attach it to the 16th note, but then give it a visual nudge to the left with a negative value for `@ho` --

```
<dir type="upbow" startid="#n2" ho="-1">
  <symbol glyphname="whatever"/>
</dir>
```
Of course, you can control its vertical position with `@vo`, but it should also obey any rules established by Verovio for where to put such things.

**Comment by craigsapp** [comment]
> There just happen to be specific elements for `<fermata>` and `<breath>` but not for `<caesura>` 'cause it's gotta stop somewhere

What? Limits?  :-) .  There is a standard rendering for caesuras (which was not used in this case).  Here is a random example from the web for a similar situation following a fermata:

<img width="331" alt="screen shot 2017-03-06 at 3 51 50 pm" src="https://cloud.githubusercontent.com/assets/3487289/23635458/e2f0eca2-0284-11e7-8629-4018b204d315.png">


http://forum.makemusic.com/default.aspx?f=5&m=407984
http://forum.makemusic.com/attach.aspx/25574/caesura2.png

Two slanted slashes centered on the top staff line.

And a case which could also be just as well done with a fermata over a the quarter-note rest:


<img width="404" alt="screen shot 2017-03-06 at 3 55 39 pm" src="https://cloud.githubusercontent.com/assets/3487289/23635564/611ac53a-0285-11e7-86ed-067dcebb0ac3.png">

http://dictionary.onmusic.org/terms/4795-caesura

I see several caesura styles in the Bravura font set:

http://www.smufl.org/version/1.2/range/holdsAndPauses

And the same symbol is used to increase the visibility of system breaks (but different meaning from a caesura):

<img width="637" alt="screen shot 2017-03-06 at 3 58 10 pm" src="https://cloud.githubusercontent.com/assets/3487289/23635633/b93d0106-0285-11e7-8068-a5e0617d853e.png">

**Comment by pe-ro** [comment]
So, you're advocating for the creation of `<caesura/>`?

**Comment by craigsapp** [comment]
I would say that caesura would be a good element to have, since certain repertories will use it fairly often (not piano music :-).

It would behave like most floating elements, and the rendering is fairly simple (always two slashes centered on the top line of the staff at the given time stamp) and functions similar to a rest with a fermata on it (but for caesura, there is nothing it will attached to, such as with `@startid`, just `@tstamp` or `@startid` with a horizontal offset).

There will be no `@dur`/`@dots` for a `<caesura>` as they do not posses score duration, but it would be useful to have `@dur.ges` to give a performance duration.  Then MIDI files can render the caesura with a user-assignable duration pause.

**Comment by pe-ro** [comment]
>How should the two bowings on the first note be encoded? They need to be horizontally rendered on the note as opposed to the usual vertical alignment for articulations. In other words the pair act as a single articulation unit.

I just remembered that the issue of vertical grouping of `<dynam>` and such is similar to this.  So, one possibility is to allow `@vgrp` on `<artic>` --
```
<note xml:id="n1" pname="f" oct="3" dur="8" dots="1">
  <artic artic="upbow" vgrp="1"/>
  <artic artic="dnbow" vgrp="1"/>
</note>
```
which says that both articulations belong at the same vertical height.  It would be left to the renderer to determine their horizontal positioning.  Encoding order would be significant (left-to-right when `@vgrp` is present).  Using this method or the `@tstamp` approach above would both still be valid methods of encoding.

**Comment by pe-ro** [comment]
Just to be clear -- `<caesura>` would encode the "railroad tracks" found on the staff, not the hash marks between systems.  `@form` on `<sb>` already does that.

**Comment by craigsapp** [comment]
Yes, they look similar to each other, but they are semantically different.

**Comment by craigsapp** [comment]
The wikipedia page on caesura:

https://en.wikipedia.org/wiki/Caesura

> In musical notation, a caesura is marked by a double oblique lines, similar to a pair of slashes  "//". The symbol is popularly called "tram-lines" in the UK and "railroad tracks" in the US. It can also be marked by a quarter rest with a fermata over it.[2] In choral works, a smaller apostrophe-like mark is used to denote caesurae.

This points out that a caesura is closely related to a breath mark, and also equivalent to a rest with a fermata over it.  In MEI you could either add a `<caesura>` which renders as railroad tracks, or merge it somehow with `<breath>` (it is probably less confusing to just add a separate element since it has a different name in music).  Or there could be a generalized element which merges these two elements, and then has a `@form` which specified if it is to be rendered as a breath mark or a railroad track (such as perhaps calling the hybrid element `<pause>`).  Merging a caesura/breath with a fermata+rest would be trickier to do since the caesura/breath elements do not have score duration while the fermata+rest does.

According to the SMuFL font set, there is a short caesura which is two vertical lines as opposed to the slanted lines of the normal form, so there probably should be `@form="normal|short"` for a caesura (I have never seen music with a "short" caesura).

**Comment by rettinghaus** [comment]
Why don't you use `<breath>` with `@altsym`, `@glyphname`, or `@glyphnum`?

**Comment by craigsapp** [comment]
The main reason would be readability, at least for glyphnum.

to quote @pe-ro:

```
<dir type="caesura" tstamp="1.5">
  <symbol glyphnum="whateverTheSmuflNumberIsForFermata"/>
</dir>
```

In this case the `@type` is "caesura" so not totally unreadable, but if the word "caesura" is not present in a breath element, it would be hard to figure out what the glyphnum means by reading the text.  Also typing in the data by hand (as @pe-ro like to do :-) slows down as you have to go look up the code for the caesura shape.

Also I would be nervous about using a glyphnum in the long term.  Whose glyphnum?, and what if SMuFL renumbered its glyphs for some strange reason?

And caesuras are much simpler than breath marks to render, which might be a factor. The breath mark is placed above the staff while the caesura is always centered on the top line of the staff (requiring additional space between notes if necessary).  So it is not as easy as replacing a symbol since the position must also be changed.  Breath marks can be above notes, after notes, on barlines, etc., and are positioned more similar to fermatas:

<img width="756" alt="screen shot 2017-03-07 at 11 13 50 pm" src="https://cloud.githubusercontent.com/assets/3487289/23694055/92f05054-038c-11e7-921d-5daa635fcf70.png">

**Comment by rettinghaus** [comment]
But `@type` will be available globally, so you could use: 
`<breath type="caesura"/>`
For positioning you should have a look here: #345

**Comment by pe-ro** [comment]
While `<breath>` and `<caesura>` are similar pause-like things, they're not enough alike to use the same element.  And, while it's also true that `@type` will be globally available, relying on a generic attribute like this for interoperable behavior is not a good idea.  Better to create a new `<caesura>` element.

**Comment by pe-ro** [comment]
> Also I would be nervous about using a glyphnum in the long term. Whose glyphnum?, and what if SMuFL renumbered its glyphs for some strange reason?

Whose glyphnum? can be answered using `@authority` and/or `@authURI` on `<symbol>`.

**Comment by craigsapp** [comment]
> But @type will be available globally, so you could use:
`<breath type="caesura"/>`
> For positioning you should have a look here: #345

What about using `@form`:
`<breath form="caesura"/>`
and what would be the difference compared to 
`<breath type="caesura"/>`?
i.e., when to use `@form` and when to use `@type`?

For example to distinguish between inverted and normal (soon to be upper/lower?) mordents:
`<mordent form="inv"/>`/`<mordent form="normal">`
where `@form` functions as an adjective describing two types of mordents.

But I am still preferring `<caesura>` since that is the name of the musical notation object.  Using `@form` or `@type` is more for distinguishing between sub-categories of a generalized element, but in this case caesura and breath are more like siblings rather than twins like mordents.

German has `<shoe type="foot"/>` and `<shoe type="hand"`/>'  which is amusing in English :-) where it is conceptually more like `<limb-terminal-covering type="foot" form="shoe"/>` and `<limb-terminal-covering type="hand" form="mitten"/>`.

**Comment by pe-ro** [comment]
The difference between `@form` and `@type` is that the values of the former are enumerated, while those of the latter are user-supplied, though sometimes suggestions are offered.  `<breath type="caesura">` feels a lot like `<shoe type="hand">`.  😀   So, I prefer `<caesura>`.

There might be some advantage in making `<breath>`, `<caesura>`, and `<fermata>` members of a pauseLike class, which in turn is a member of the controlEventLike class, but that will take some additional thought.  For now, we can create `<caesura>` and think about class memberships for it and its cousins later.

**Comment by craigsapp** [comment]
> There might be some advantage in making `<breath>`, `<caesura>`, and `<fermata>` members of a pauseLike class, which in turn is a member of the controlEventLike class, but that will take some additional thought. For now, we can create `<caesura>` and think about class memberships for it and its cousins later.

That sounds interesting since all three of them would be handled in a similar manner for performance rendering, such as conversion to MIDI.

**Comment by ahankinson** [comment]
Why was this closed?

**Comment by pe-ro** [comment]
Closed because the alignment question was answered and because the `<caesura>` element was created in #417.

**Comment by ahankinson** [comment]
OK, thanks!
