### ISSUE TITLE
Add @class attribute

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#420]
`@class` provides a mechanism for classifying an element according to an established, formal taxonomy.  It has a different function from `@type`, which is for ad hoc extension and restriction of the schema.  

`@class` may contain one or more URIs which denote classification terms that apply to the entity bearing this attribute. A fragment identifier (e.g., '#term01`) points to a classification term recorded in the MEI header.

A Schematron rule will ensure that the value in `@class` corresponds to the `@xml:id` attribute of a `<term>` element or is an external URL, i.e., one that matches '^([a-z]+://|\.{1,2}/)'.

`@class` will be available anywhere `@type` is.

**Comment by craigsapp** [comment]
Is this different from an HTML element `@class`?

**Comment by pe-ro** [comment]
Yes, `@class` in HTML is like MEI's `@type`.
