### ISSUE TITLE
Clarify use of <annot>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#424]
The `<annot>` element tries to be too many things, leading to confusion about its purpose and how to render it. In an attempt to fix this situation, I propose --
- `<annot>` be limited to explanatory material (text and non-text) that occurs (or has the potential to occur) **within** the musical notation.  Thus, `<annot>` may occur wherever other so-called "control events" are allowed and can be rendered similar to `<dir>`.
- `<remark>` be added to accommodate explanatory material that occurs **outside** the musical notation; i.e., marginalia, footnotes, etc. It may occur at the text phrase level as well as in `ending`, `layer`, `lem`, `measure`, `part`, `perfMedium`, `pgDesc`, `rdg`, `score`, `section`, `sp`, `staff`, `syllable`, and `symbolDef`.
- add an `@audience` attribute to `<annot>` and `<remark>` with values of "public" and "private" to distinguish those features that are intended for internal use vs. those that are for all uses.  Elements marked as "private" should not be rendered.
- the  main differences between `<annot>` and `<remark>` are  a simpler content model for `<annot>` compared to `<remark>` and the values that may be used in their `@place` attribute.  Also, `<annot>`, like `<dir>`, will be linkable to other items in the notation via its other attributes; e.g., `@plist`, `@staff`, `@tstamp`, etc.,  while `<remark>` will use `@target` to create an association with another element.
- Both digitized and born-digital material may use these elements. Depending on the purpose of the encoding, it may be wise to wrap them in other elements, `<add>`, `<del>`, `<supplied>`, etc., to fully capture their editorial nature.

**Comment by kepper** [comment]
What I learnt from Mr. Beethoven is that space is used depending on its availability. I'm aware that I'm talking about modifications to the music, while this thread is about additional information about the music. However, I have the impression that the distinction you make isn't necessarily the right / only one. Other distinctions seem equally valid to me, for instance regarding authorship (authorial vs. editorial) or content (music vs. textual annotation) or structure (a freeform sentence like 'this cadence needs to be improved' vs. an editorial annotation in a critical report). There may be other distinctions I don't have in mind right now…

Is there a way to combine all these distinctions? I know this pretty much sounds like a single element with a set of specific attributes, but maybe we can come up with something better than that, especially in order to allow a more restrictive content model…

**Comment by pe-ro** [comment]
The whole point is that combining all these things leads to a total mess. Some distinctions must be made.

Did you miss the last sentence of my proposal?  The idea is that annotations and remarks of an editorial nature would be wrapped in the appropriate editorial elements.

**Comment by kepper** [comment]
I didn't miss it, and I fully agree on your motivation to avoid the mess we're looking at. I just think that it's more important to distinguish between musical and textual annotations in the first place. Like you said, musical annotations can be addressed with <supplied>, <add> and the like – we already have much more specific markup than the generic <annot> we're looking at right now. This means <annot> is left for textual annotations, and doesn't have to include musical content.

The distinction between authorial and editorial content is actually quite complicated, and strongly depends on perspective. It's tempting to ask for a binary switch here, but how do you encode a 19th century critical edition? Does it make a difference then when you have or don't have original manuscripts? Eventually, it seems that relying on @resp and @role on the people linked from there is the most faithful solution already. All that is available right now, but maybe not properly documented and advocated. Admittedly, it also requires more processing and depends much more on project-specific conventions. There is certainly room for improvement here, but it's not easy to achieve.

A distinction between freeform annotations and structured annotations is something we've been talking about on and off for years. It's more or less like TEI's <bibl> vs. <biblStruct> – one is more database-like, the other one more text-like. It seems reasonable to me to consider splitting <annot> into <annot> and <annotStruct> (or something similar). In this process, we should also consider to not use <annot> as general fallback for all kinds of information in the header anymore.

When annotations really deal with textual content only, by definition they are not part of the music – they say something about the music. This is no statement whether they should be superimposed, rendered as a footnote or some other fancy of displaying them – it's a statement about their logical relation to the music. If they were part of the music, they could be encoded using <supplied>, <del> and the like. This logical connection can be established by all the means you mention, like @plist, @tstamp etc. What seems to be lacking is a way to specify the visual connection, that is, where the annotation should be rendered: If the annotation is transcribed, where was it in the source: At the margin, between two staves, at the end of the manuscript? If the annotation is "born digital", should it be rendered as a popup, footnote, whatever? Maybe I'm overlooking something, but I think we could improve this situation.

So, what's the conclusion here? I believe the current situation actually isn't that bad. Yes, we need to be more explicit in the documentation and elsewhere, we need to make it clearer what <annot> is about (and what it's not…), and we need to improve the possibilities to encode the visual placement of annotations. Other than that, I fail to recognise a real problem. Maybe I miss something, but I'd like to hear the arguments (again) why it's not sufficient to polish the current model. It seems to be all but trivial to come up with a new model that is at least as good as the current one in all those aspects. Until now, I prefer to clarify the current one where necessary (which is, I guess, a compliment…) ;-)


Am 24.03.2017 um 22:46 schrieb pe-ro <notifications@github.com <mailto:notifications@github.com>>:

**Comment by lpugin** [comment]
I personally would suggest to keep `<annot>` as the ones that occurs **oustide** the music notation, with the idea that an annotation comes on top of something. For the ones **inside** the notation, why not just `<text>`? It would also align with `<anchoredText>` but signifying the difference that generic `<text>` elements are not fixed.

**Comment by pe-ro** [comment]
> I personally would suggest to keep <annot> as the ones that occurs oustide the music notation, with the idea that an annotation comes on top of something.

That's too narrow a definition of annotation, I think.  And I'm not sure what you mean by **outside the music notation**.  Do you mean something added by an editor/scribe?  If so, then that puts the annotation into the editorial realm.  For instance --
```
<add place="superimposed">
  <annot tstamp="1" tstamp2="4">Blah, blah, blah</annot>
</add>
```
The fact that the annotation is "on top of" the notation can be indicated with `add/@place`, while its placement in relation to the notation is captured with attributes on `<annot>` --

However, annotations which are part of the notation itself from the outset don't need the outer editorial element --
```
<annot>Blah, blah, blah</annot>
```
They can be laid out along with/at the same time as other notation features.  In this situation, the annotation is not an addition to or a commentary on the notation; it is literally part of the notation.  Think of marking up an existing edition where the harmony was analyzed, a Bach chorale with Roman numeral chord analysis, for example.  While it is true that these symbols were added by an editor at some point, they are a feature of the edition being represented.

Even so, this kind of `<annot>` may also need to be superimposed. Since `@place` is already used for the relationship between elements and the staff; i.e., above, below, between, within, I'd add another attribute, perhaps `@fixed` as a Boolean, to indicate that the annotation isn't part of the "flow".

`<text>` as container name is way too broad.  It doesn't indicate the function of the material it contains.  It's better to have several specialized elements, even if they all end up being rendered pretty much like `<dir>`.  (You may have noticed the recent addition of `<sp>` and `<stageDir>`.)

**Comment by pe-ro** [comment]
> What seems to be lacking is a way to specify the visual connection, that is, where the annotation should be rendered: If the annotation is transcribed, where was it in the source: At the margin, between two staves, at the end of the manuscript? If the annotation is "born digital", should it be rendered as a popup, footnote, whatever? Maybe I'm overlooking something, but I think we could improve this situation.

Exactly what I'm trying to do.

**Comment by lpugin** [comment]
> And I'm not sure what you mean by outside the music notation.

You said that

**Comment by pe-ro** [comment]
@kepper, I don't want to wade into the various forms that annotations can take, i.e., structured vs. free-form, until we have a better general sense of what an annotation is.

@lpugin, I did use the terms "inside" and "outside".  But that was separate from any notion of "superimposition" vs. "part of the layout".  Joining "inside" and "superimposition" in the definition of `<annotation>` is too restrictive, I think.  MEI's `<annotation>` is very much like TEI's `<note>`.  Simply, it's explanatory text that doesn't fit into a more specific category/element.  That definition is separate from its editorial role and from its rendering.

I have tried in the last couple of days to keep `<annot>` as it is, but where I've run into trouble is in its rendering, specifically with regard to `@place` -- We need a way to record where an annotation occurs; that is, mixed in with the notation or elsewhere on the page. `<add>` (and eventually, `<supplied>`, etc.) has `@place`, but with values that declare its location with respect to the **page**, not a **staff**.  `<annot>` and other text-y bits have the opposite, `@place` says where it is with respect to a staff, but this won't work for those annotations that are in the margins, between lines of text, or in-line within text. (Think of N.B.-type notes/annotations.)

Merging the various values of `@place` into a single attribute is a recipe for confusion, and 2 different attributes on `<annot>` isn't much better, leaving only the possibility of separate elements that I took with `<remarks>` and `<annot>`.  In my attempt to resolve this, `<annot>` is simply `<remarks>` that can have a relationship to a staff.  Conversely, `<remarks>` is an `<annot>` without a staff relationship.  In every respect except placement, they are the same -- both can occur in lots of places and can be both original and editorial.

Obviously, this proposal is a non-starter for you guys.  So perhaps we should back up a step and investigate having 2 mutually exclusive attributes -- called `@place` and `@placement` for argument's sake.  The first one can express a staff relationship and the second page-related location.  Is this better?

**Comment by kepper** [comment]
Just to get this out of the way, I think we agree that _exact_ placement on the page is out of scope – we have `@facs`, `@x`, `@y` and other stuff for that. This means we're talking about the _semantic_ information that a comment has been written on the margin of the _page_, other than between the staves. However, in both cases, the comment relates to some _music_, not the page (there are certainly comments about pages, but for the sake of my life, I can't come up with a real-world example for this right now). Even if someone puts an "X" onto the music, and writes a comment together with another "X" three pages later (because there was no space available any closer than this…), the comment still relates to the music at the first X's position. 
For many elements, it is important to `@place` things above or below the staff. It's reasonable to say that this equally applies to comments located relative to a staff. However, if things are placed relative to the (or _some_) page, I wonder if it's necessary to trace that position any closer than a simple "margin", "bottom", or "elsewhere". Again, we have the attributes mentioned above to be more specific. We already have two lists of allowed values for `@place` ("above" and "below" allowed everywhere, "within" allowed only sometimes). To make a long story short, I just wonder if it's really to complicated to allow a small number of additional values for the existing `@place`, instead of coming up with another attribute, with almost similar name and purpose, which seems pretty easy to confuse… (but again, I'm not yet settled on anything)

**Comment by pe-ro** [comment]
> Just to get this out of the way, I think we agree that exact placement on the page is out of scope – we have @facs, @x, @y and other stuff for that. This means we're talking about the semantic information that a comment has been written on the margin of the page, other than between the staves. However, in both cases, the comment relates to some music, not the page (there are certainly comments about pages, but for the sake of my life, I can't come up with a real-world example for this right now). Even if someone puts an "X" onto the music, and writes a comment together with another "X" three pages later (because there was no space available any closer than this…), the comment still relates to the music at the first X's position.

We have `@plist` to capture the referents of the comment.  We ***are*** talking about exact placement on the page.

> However, if things are placed relative to the (or some) page, I wonder if it's necessary to trace that position any closer than a simple "margin", "bottom", or **"elsewhere".

"margin", "bottom", etc. is fine, but page-relative placement is different and separate from staff-relative placement!

The problem with simply expanding the values of `@place` is that for "text-y type stuff" multiple values are often necessary.  In the case of staff-related placement, they're not.  If multiple values are allowed, it opens up all kinds of silliness -- how can an annotation be "above" the staff and in the "margin" simultaneously?  To discourage this kind of crap we/I will have to perform fairly complex Schematron tricks.  It would be better if this were handled in the schema itself.

**Comment by kepper** [comment]
> The problem with simply expanding the values of `@place` is that for "text-y type stuff" multiple values are often necessary.

Could you provide an example for such a situation? Since the values we currently have are all _relative_ to something, I wonder if we can possibly put multiple values into one attribute (independent of it's name), as we would have to specify to what other element they relate in which way. But maybe I'm overcomplicating things (as so often…)

**Comment by pe-ro** [comment]
The following example, taken from http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.placement.html, indicates the addition starts on the bottom of the current page and finishes on the facing page.  MEI uses different values for `@place`, but the principle's the same.
```
<add place="bottom opposite">[An addition written at the
foot of the current page and also on the facing page]</add>
```
A similar example in MEI --
```
<annot staff="1" place="above bottom opposite">[place indicating 
attachment to staff 1 AND location is NO GOOD]</annot>
```
To remedy this problem, one of the following is necessary -- 
1. another attribute on `<annot>` (for *location* as opposed to *attachment*) or 
2. a new element with a different definition for `@place`

**Comment by kepper** [comment]
> To remedy this problem, one of the following is necessary --
> 
> 	• another attribute on <annot> (for location as opposed to attachment) or
> 	• a new element with a different definition for @place

I guess I prefer the first solution, as long as we're able to adequately describe everything that's needed in a bunch of attribute values. Is the example given by TEI really sufficient for us, or do we need a much preciser way to describe the position? If so, is the current setup of facs attributes pointing to one or more zones sufficient, or do we need something completely different? For my needs, this covers already everything I need in the foreseeable future. Accordingly, a fairly generic mechanism for location would be sufficient for me. I don't see an intuitive way to explain the use of two different elements for encoding the same thing, only separated by the question of whether information about their attachment vs. their placement is provided.

I understand your reluctance to open the list of allowed values for "place" on annot. To absolutely avoid confusion, what about completely dropping "place" on annot, and replacing it with "location" (which then takes the wider list of values)? The attachment is still handled by tstamp and the like, and regular musical symbols (like dynams) don't have the same "freedom" in placement that annotations have. Wouldn't it be sensible / comprehensible to use a different attribute for their placement in the first place, even though some possible values are shared?

**Comment by pe-ro** [comment]
I'm not sure I understand your suggestion, but substituting `@location` (with an expanded value space) for `@place` just moves the problem.  The new attribute would exhibit the same problem I described earlier --
```
<annot staff="1" aNewAttribute="above bottom opposite">[aNewAttribute indicating 
attachment to staff 1 AND location is STILL NO GOOD]</annot>
```
`@facs` doesn't help resolve the issue -- it indicates where the annotation *was* in an earlier incarnation, not where it *should be* in a rendered version of the encoding.  (I sometimes say that `@facs` describes an *input **to** the encoding*, while `@place` or the new attribute we're discussing describes an *output **from** the encoding*.)

What I was getting at by suggesting a new attribute is something like --
```
<annot staff="1" place="above">[Annotation is attached to and located 
  relative to staff 1]</annot>
```
vs.
```
<annot staff="1" location="bottom opposite">[Annotation is attached to 
 staff 1, but is located relative to the page]</annot>
```
Observations --
1. `@place` and `@location` cannot be used simultaneously.
2. We can't require either `@place` or `@location`, but annotations without one of them (such as those that occur in `<notesStmt>`) are problematic with regard to rendering.  This is why I want to use a completely different element in the header.
3. If one insists on abusing `<notesStmt>`, then `<annot>` (in the body) can be transformed into `<notes>` (in the header) by removing `@place` and `@location`.  This is preferable to creating yet another Schematron rule to contextualize `<annot>`.

**Comment by kepper** [comment]
I have the impression we're getting closer. It certainly makes sense to clearly separate an attachment relative to the music from a position relative to the page. However, what I failed to say is that even something positioned on the page (that is, utilizing `@location`, but not `@place`, might still be _logically_ attached to the music. And in fact, MEI still allows this kind of attachment through `@tstamp`, `@startid`, `@plist` or similar. I'm not saying this is a problem, and I'm not saying this isn't a problem. I'm just asking how this relates, and what positioning then really means. I think this is somewhere in the realm of document vs. text, whatever those categories may mean here. 

Looking at your observations: 

1. agreed. 

2. I agree we can't require it. I would just draw a different conclusion in leaving it to an application how to deal with this situation. I wouldn't connect this argument with the need for a different element in the header. 

3. I wouldn't call this abuse. For me, `<notesStmt>` is just a container for `<notes>` / `<annot>`s. At the same time, encoding a critical report with its editorial remarks somewhere inside `<front>` or `<back>` looks pretty "bookish" to me. There's nothing wrong with that, especially when encoding an existing (printed) edition, but I wonder if it's really adequate to perpetuate this setup in "born digital" editions. Here, I think it's much more appropriate to either put all annotations into the places they talk about (i.e., in the music), as their rendering can be controlled dynamically (other than with footnotes in books), or they can be treated as metadata and be stored in a defined spot. As I've never seen (or at least recognized as such) a website's back matter, `<notesStmt>` seems to be that place for my eyes. However, I'm not very evangelistic about this and happy to live with other models…

One more thing: Until now, I never thought about `@place` being suitable for output _only_. Everytime I used it, it was for capturing a source, and I was fine with software ignoring its value. The reason might be that there wasn't much of an output back in th days, and that I'm always more focussed on getting things into MEI rather than out, so I admittedly never thought about this…

**Comment by pe-ro** [comment]
The attached RNG -- [latest_DEV.zip](https://github.com/music-encoding/music-encoding/files/883761/latest_DEV.zip) -- contains an attempt to deal with `@place` --
1. Some existing classes are renamed to clarify their function.
2. Some new classes are added as "future-proofing". They may come in handy at some point.
3. `<annot>` is now permitted at the text phrase level.  It is also a control event, meaning it may occur within `<measure>`, `<layer>` , `<staff>`, and `<syllable>` as appropriate for the repertoire.
4. `@place` on `<add>` and `<annot>` allows a broad range of values and multiple values may be used, e.g. "facing botmar".  However, `@place` is constrained so that non-staff-related values (topmar, botmar, etc.) cannot occur simultaneously with staff-related values (above, below, between, and within).
5. Though I disagree with @kepper on its proper use, `<annot>` is allowed, unchanged, in `<notesStmt>`.

The following examples are valid:
```
<!-- In the header: -->
<notesStmt>
  <annot>This is an annotation without any attributes. How/where to render it is
    application-dependent.</annot>
</notesStmt>
```
```
<!-- In text: -->
<p>Text, text, text. <annot type="footnote" place="botmar facing">Wyze guy?</annot>
Other text, text, text.</p>
```
```
<!-- To be rendered as part of the notation: -->
<annot staff="1" place="above" tstamp="1">Rendered the same as a directive.</annot>
```
```
<!-- Associated with entities in the notation, but to be rendered outside the notation: -->
<annot plist="#n01 #n02 #n03" place="rightmar">Marginal note.</annot>
```
Since the annotation can't be *above a staff* and *in the margin* at the same time, the next example raises an error (courtesy of a Schematron rule):
```
<annot staff="1" plist="#n01 #n02 #n03" place="rightmar above">Marginal note.</annot>
```
Better?

**Comment by kepper** [comment]
I like it ;-) I wonder what @raffazizzi says to all those annot discussions, and how our considerations look from a TEI perspective. I'm not asking for compatibility here, I'm just curious…

**Comment by pe-ro** [comment]
I'm happy that you're happy. 😀

**Comment by kepper** [comment]
And I'm happy that you're happy that I'm happy. Yet still, I would be even happier if you were happy with the proposal, not just with my happiness ;-)

**Comment by pe-ro** [comment]
But I still think you're wrong about `<annot>` in the header.  😀 

Obviously, a web site doesn't have "back matter" *per se*.  However, the book-ish model of front, body, and back provides a way of separating text (body) from para-text (front & back).  Annotations transcribed from an existing edition or forming part of a born-digital edition are para-text and, therefore, belong in `<front>` or `<back>`.  Of course, `<front>` and `<back>` elements can be rendered in any fashion the editor desires.

Annotations/notes in the metadata header are a different animal and shouldn't be co-mingled or confused with para-text annotations.

**Comment by pe-ro** [comment]
I'm moderately happy with the result. :-|

**Comment by kepper** [comment]
One problem I have is that we're even failing to distinguish `<front>` and `<back>`. Where should annotations go, why there and not in the other place? What's the difference between `<front>` and `<back>` in a born-digital context? Unless we're able to have a clean distinction here, I see no reason to exclude the header from allowed places for `<annot>`. 

At the same time, in my experience with Beethovens Werkstatt, the boundaries between data and metadata are increasingly blurring. The more analytical a given information is, the more likely it'll end up in the header. The more "visible" it is in the notation, the more likely it'll stay in the body. However, I'm aware that my examples are rather extreme and shouldn't guide the general development of MEI… (hence my question to @raffazizzi…)

**Comment by kepper** [comment]
> I'm moderately happy with the result. :-|

I know… :-(
