### ISSUE TITLE
Allow <note> within <notesStmt>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#425]
It has always bothered me that `<note>` doesn't occur within `<notesStmt>` as it logically should.  Unfortunately, there's this other thing that we use `<note>` for. 😀 

One solution would be to put the kind of `<note>` that occurs within `<notesStmt>` in a different namespace.  However, to do this just for one element seems a long way to go.  Another possibility, better in my opinion, is to use something like the following ODD fragment, which creates an element called "genNote" (generic note), but then immediately renames it "note".
```
<elementSpec ident="genNote" module="MEI.shared" mode="add">
  <!-- DO NOT REMOVE <altIdent>! It is used to rename <genNote> so that its name better 
            matches its only possible parent, i.e., <notesStmt>. -->
  <altIdent>note</altIdent>
  <desc>(generic note) – Provides general information for which a specialized element has not been
    defined.</desc>
  <classes>
    <memberOf key="att.audience"/>
    <memberOf key="att.bibl"/>
    <memberOf key="att.common"/>
    <memberOf key="att.dataPointing"/>
    <memberOf key="att.lang"/>
    <memberOf key="att.source"/>
    <memberOf key="att.responsibility"/>
    <memberOf key="att.targetEval"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:text/>
        <rng:ref name="model.headLike"/>
        <rng:ref name="model.textComponentLike"/>
        <rng:ref name="model.textPhraseLike"/>
        <rng:ref name="model.editLike"/>
        <rng:ref name="model.transcriptionLike"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <constraintSpec ident="genNote_content_constraint" scheme="isoschematron">
    <constraint>
      <sch:rule context="mei:note[mei:head or mei:lg or mei:p or mei:quote or mei:table]">
        <sch:assert test="not(mei:head[preceding-sibling::*[not(local-name()='head')]])">Head
          elements can only occur at the start of a note.</sch:assert>
        <sch:assert test="not(*[../text()[normalize-space()]])">Mixed content is not allowed when
          head, lg, p, quote or table elements are used.</sch:assert>
        <sch:assert
          test="not(*[not(local-name() eq 'biblList' or local-name() eq 'castList' or local-name() eq 'head' or 
          local-name() eq 'lg' or local-name() eq 'list' or local-name() eq 'p' or local-name() eq 'quote' or 
          local-name() eq 'relationList' or local-name() eq 'table')])"
          >Unstructured text not allowed when head, lg, p, quote or table elements are
          used.</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
  <remarks>
    <p>This element is intended to be used for general notes that occur within <gi scheme="MEI"
        >notesStmt</gi>. The <att>resp</att> attribute records the editor(s) responsible for
      identifying or creating the note.</p>
  </remarks>
</elementSpec>
```
Essentially, this creates another `<note>` element, one with a different content model. Whereas the musical note looks like this in the RNG --
```
<define name="mei_note">
      <element name="note">
```
the ODD above generates --
```
<define name="mei_genNote">
      <element name="note">
```
making it possible to use mei_genNote in `<notesStmt>` and mei_note in `<layer>`.  Same name, but completely different elements as far as the RNG is concerned.

At present, the only down side I see is that oXygen displays the same tool-tip for both contexts; i.e., a concatenation of the description of both notes.

**Comment by ahankinson** [comment]
Ooooooof. There **must** be a better way. At the very least, it will make documentation very difficult, because if someone wants to look up what the 'note' element does they will get two different answers.

I think this falls firmly under the heading "consistency for consistency's sake" and will cause more problems than it will solve.

**Comment by lpugin** [comment]
I agree that this is a tweak that will have side effect problems. The documentation is indeed one but it will also quite likely be the case for code generated from the schema (e.g., class name conflicts). I would strongly suggest to just find another name for notes within `notesStmt`. What about `noteStmt`?

**Comment by pe-ro** [comment]
`<notes>`?

**Comment by kepper** [comment]
notes is certainly better than note, but probably still confusing. I wonder if this is really a real-world problem (anymore), or for whom. For the last couple of years, we told everyone that MEI relies on annot instead of note. We also had the benefit of having a striking example for explaining both the need and implementation of XML namespaces. So I would expect annot being confusing to new users of MEI more than for existing users. Those new users coming with a scholarly background should be receptive for the namespace issues, while users with a different background are probably less dependent on annotations. I believe that the rationale behind the name annot is reasonable enough to stick with it. According to various posts on this thread, there seems to be a consensus that we may need a clarification of the model, but not necessarily the name. This will already raise compatibility issues, and it could be a strategy to use a new name in order to signal a different model, but this seems like "pouring out the baby with the bath water" (not sure if this german phrase exists in english, though…).

**Comment by pe-ro** [comment]
You may have also heard "you can't make an omelet without breaking some eggs".

If the usage of `<annot>` is too confusing, the best way to fix that is to break it into several other elements, each with a simpler, more focused model/purpose.  Keeping the *status quo* (regardless of whether or not that has served adequately in the past) doesn't help us to move forward.

**Comment by pe-ro** [comment]
The *status quo* simply leaves us with one more thing that `<annot>` is called upon to do; that is, represent general textual notes within the metadata.  The goal with this proposal was to carve off that particular usage and give it a name that was more meaningful in its context.  If we don't provide this "context sensitivity" by renaming, we have to do it through Schematron rules.  We could just not do it at all, but this puts the burden of using `<annot>` appropriately in the various contexts in which it can occur entirely on the encoder.

**Comment by kepper** [comment]
Together with #424, this whole thing is really complicated, and I don't feel like there's a simple answer. When looking at your original argument about `<annot>` being a misnomer inside `<notesStmt>`, I thought about renaming `<notesStmt>` to `<annotations>`. However, this doesn't solve the problem you're looking at (and breaks compatibility with TEI once more, for rather little reason this time, I'd say…). Then, I thought about using a different annotation-like element for the header (i.e. inside `<notesStmt>`). However, it has been very convenient in the past to be able to move all annotations spread across the `<music>` into a single defined spot in the header. As long as they're attached by IDs, you don't even have touch the `<annot>` itself. I'm not sure if I'm willing to drop that possibility – it's just very close to traditional printed critical reports. However, it's particularly this use case that might benefit from a more structured approach to annotations. It's certainly legitimate to use a new element for those structured annotations (`<annotStruct>` or `<remark>`, anyone?), and not leave all that to the encoder, guided (only) by Schematron and documentation. And yes, I'm aware that this contradicts what I said just two sentences ago… Maybe we should allow both `<annot>` and `<annotStruct>` (temporary use of the word, just for clarity) in `<notesStmt>`, and leave it to projects to convert their annotations to a structured form…

To not conflate issues even more, I will add some thoughts about placement over at #424.

**Comment by pe-ro** [comment]
While it may be convenient to collect `<annotation>` elements spread throughout the file in `<notesStmt>`, creating a critical report inside the header is an abuse of `<notesStmt>`.  That kind of content belongs elsewhere, likely in the `<front>` or `<back>` matter.  That's exactly why a differently named element is required in `<notesStmt>`.
