### ISSUE TITLE
Add <lv> element

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#426]
Just as notes and chords can have a `@tie` attribute, they also can have an `@lv` attribute.  These attributes serve an analytical function.  When detailed visual information is required, an element should be used instead of / in addition to the attribute.  Unfortunately, there is currently no `<lv>` element that corresponds to `@lv`.  Since an l.v. indication has the same visual rendition as a slur or tie, a `<slur>` or `<tie>` element could be used to capture the visual characteristics of the l.v. sign  However, it is best to create an `<lv>` element so that there's no confusion about whether to choose `<slur>` or `<tie>` for l.v. signs. `<lv>` will have the same syntax as `<tie>`; i.e., it will use the same attributes and allow the same content.

**Comment by bwbohl** [comment]
In addition to having the same appearance as a tie, l.v. might have an additional text, e.g. "l.v.". Before having an dedicated `<lv/>` I would have encoded that as `<dir>` but under these new circumstances, the fact that these two graphical  phenomena are closely connected, actually part of the same logical phenomenon, should be reflected in our encoding model. This could be done:

1. using `<lv/>` and `<dir>` with `@corresp` but in fact I think this is little too loose?
2. encoding a label on `<lv/>` which only would be possible as `@label` (at least according to the 3.0.0 Documentation) and might better be implemented according to #361, i.e.
```xml
<lv>
   <label>some text</label>
</lv>
```
3. Any other possibilities?

**Comment by pe-ro** [comment]
The intention was that `<lv>` capture only the tie-like symbol, leaving the text portion to be recorded in `<dir>`.

It might be helpful to compare the model of `<gliss>` with the model of `<lv>`. `<gliss>` allows text and model.textPhraseLike elements because the glissando line and text are closely linked visually.  That is, the text "sticks to" the line.  In the case of `<lv>`, the "tie" and the "l.v." text often need to be positioned more independently of each other.

You say "too loose", I say "flexible".  😀
