### ISSUE TITLE
Revise remarks for <facsimile> to explicitly include SVG

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#427]
Given the description of `<facsimile>` --
```
Contains a representation of a written source in the form of a set of 
images rather than as transcribed or encoded text.
```
it would be helpful to add 
```
In the context of this element, "images" includes SVG (Scalable Vector Graphics).
```
to the remarks.

**Comment by pe-ro** [comment]
It might also be helpful to revise the content model to allow a single reference to a file capable of representing multi-page images such as PDF or TIFF.  In addition to the currently-allowed --
```
<facsimile>
  <surface>
    <zone>
      <graphic target="#page17" height="4" width="6"/>
    </zone>
  </surface>
</facsimile>
```
the new model would allow --
```
<facsimile>
  <graphic target="myFile.pdf"/>
</facsimile>

and

<facsimile>
  <svg:svg/>
</facsimile>
```

These options are mutually-exclusive -- one may use either a single file which represents multiple pages **or** multiple `<surface>` elements, one for each page.

This change doesn't affect how one references individual pages/surfaces in an external file --
```
<facsimile xml:base="path/to/manifest.json">
  <surface label="fol 3v">
    <graphic target="jsonpath(#page17)" type="iiif"/>
  </surface>
</facsimile>
```

**Comment by ahankinson** [comment]
I'm not sure about this. SVG, being a scalable vector graphic format doesn't have a compatible co-ordinate system with raster images. If you're expected to align a notation with bounding boxes on a vector graphic, you'll likely need to have inspected the SVG in order to tell how it's co-ordinate system is set up through the `viewport` and `viewbox` definitions.

**Comment by pe-ro** [comment]
Understood.  But this is being allowed specifically for those cases where there's no expectation of aligning the notation with bounding boxes.

**Comment by kepper** [comment]
Sorry for not being up to date, but is there a mechanism to connect zones to a specific graphic? If we have that kind of setup, it wouldn't be a problem to allow svg as well – you just wouldn't attach zones to it…

**Comment by pe-ro** [comment]
As demonstrated in the markup below, `<graphic>` already allows `<zone>`.  

The use of `graphic/zone/graphic` generates a warning: "Graphic child of zone should not have children."  But, I now wonder if this is actually necessary.  If someone wants to continue drilling down _ad infinitum_, then why should we care?  So, perhaps a re-wording of the warning is called for, something like: "Complex nesting of graphic and zone elements may be difficult to process." or we could just drop the Schematron warning.
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="latest_DEV.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="latest_DEV.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<facsimile xmlns="http://www.music-encoding.org/ns/mei">
  <surface>
    <graphic target="p1.jpg">
      <zone>
        <graphic target="p1z1.jpg">
          <zone>
            <!--<graphic></graphic>-->
          </zone>
        </graphic>
      </zone>
    </graphic>
    <graphic target="p1.png">
      <zone>
        <graphic>
          <!--<zone></zone>-->
        </graphic>
      </zone>
    </graphic>
  </surface>
</facsimile>
```

**Comment by pe-ro** [comment]
Markup example of the use case I mentioned earlier -- a multi-page graphic format that represents the entirety of the encoding.  No connections are allowed between the graphic (likely generated from the encoding) and the elements in the `<body>`. 
```
<facsimile>
  <graphic target="foo.pdf"/>
</facsimile>
```
Only a single `<graphic>` element is allowed directly in `<facsimile>` in order to avoid confusion with page-by-page encoding.  Page-by-page encoding still requires the use of `<surface>` --
```
<facsimile>
  <!-- individual pages/surfaces -->
  <surface>
    <graphic target="p1.jpg"/>
  </surface>
  <surface>
    <graphic target="p2.jpg"/>
  </surface>
</facsimile>
```
Contrary to my earlier statement, I think it's ok to allow both approaches simultaneously --
```
<facsimile>
  <!-- a multi-page graphic file -->
  <graphic target="foo.pdf"/>
  <!-- individual pages/surfaces -->
  <surface>
    <graphic target="p1.jpg"/>
  </surface>
  <surface>
    <graphic target="p2.jpg"/>
  </surface>
</facsimile>
```

**Comment by pe-ro** [comment]
Reopening for the second part of the issue -- changing the content model of `<facsimile>`.
