### ISSUE TITLE
breve unit for meterSig?

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#438]
How should a breve be represented as the `@unit` in a `<meterSig>`?

Here is the relevant definition in http://music-encoding.org/documentation/3.0.0/att.meterSig.log:

<img width="562" alt="screen shot 2017-05-26 at 12 16 43 pm" src="https://cloud.githubusercontent.com/assets/3487289/26490895/84e0620a-420d-11e7-9cd6-ab9ea50ba372.png">

What is a `decimal` type?  Does that mean integers (..., -2, -1, 0, 1, 2, ...)?  Or numbers containing decimal points (0.623, 4.0, 3.141596)?  And what would a zero or negative `@unit` mean?

Technically the unit should probably be "1/2" which is not an integer.  I often use "0" to mean a breve beat in a time signature, but I do not know how conventional that would be.

**Comment by pe-ro** [comment]
Assuming you mean a modern breve (equivalent to 2 whole notes), the value of `@unit` should be ".5".

A decimal type is any number potentially containing a decimal point.  0.623, 4.0, 3.141596, -42, etc. are all good examples.  See https://www.w3.org/TR/xmlschema11-2/#decimal for a more technical definition.

A zero or negative value for `@unit` would be meaningless, but that's not addressable just by assigning a primitive datatype.  Additional constraints can be added to exclude specific values, say less than or equal to zero.

By the way, there are weird, modern uses of beat unit values, like "one quarter plus an eighth note". This is why `@unit` is allowed to be a decimal number.

**Comment by craigsapp** [comment]
Thanks, that sounds good.
