### ISSUE TITLE
clarify usage of text.dist

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#439]
`harm` and `dynam` are textual elements. So do `@harm.dist` and `@dynam.dist` add up to `@text.dist`? Or does `@text.dist` *only* applies to textual elements that are *not* dynamic or harmonic inidications? 

I propose to drop `@text.dist` and instead introduce `@dir.dist`, `@tempo.dist`, and `@reh.dist`.

**Comment by pe-ro** [comment]
Yes, `@text.dist` is intended as a short-cut for `@harm.dist` and `@dynam.dist` and anything else we say it applies to.  Setting a value here essentially gives the same vertical position to all these things.  Then one can use `@aboveorder`, `@beloworder`, and `@betweenorder` (see #390) to be more specific about the relative positions of the individual markings.

**Comment by rettinghaus** [comment]
So setting `text.dist="4"` and `dynam.dist="2"` means *all* textual element are placed with a minimal distance of `4vu` to the staff and dynamics are push a bit further with a total of `6vu`.

**Comment by pe-ro** [comment]
No, textual elements (dir, harm, tempo, reh) are placed with a minimal distance of `4vu`, and dynamics are placed with a minimal distance of `2vu`.

**Comment by rettinghaus** [comment]
Ok! So `@harm.dist` and `@dynam.dist` (re)specify the minimal distance for `<harm>` and `<dynam>` elements, i.e. overrides the value given by `@text.dist`. 

Still think `@dir.dist`, `@tempo.dist`, and `@reh.dist` would make a valuable addition. 

Anybody volunteering to put that in the guidelines?

**Comment by lpugin** [comment]
We can add them, and then remove `@text.dist` because that one would not be needed anymore.
