### ISSUE TITLE
add dis.ges to clef

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#440]
In settings for men's choir it has been common practice (mostly in second half of 19th century but sometimes still used today) to print a standard violin clef for tenors, i.e. without the needed 8 below it. AFAIK there is no possibility to encode this in MEI, so I'd like to propose the addition of 

`@dis.ges` to `<clef>` 
resp. 
`@clef.dis.ges` to `<scoreDef>` and `<staffDef>`. 

Value should conform to 
`data.OCTAVE.DIS.gestural`
`-22|-15|-8|8|15|22`

**Comment by pe-ro** [comment]
@rettinghaus, This is a kind of transposition and can be encoded using `@trans.semi` and `@trans.diat`. 

```
<staffDef n="1" label="Tenor" lines="5" clef.line="2" clef.shape="G"
  key.sig="4f" key.mode="major" trans.semi="-12" trans.diat="0"/>
```

**Comment by rettinghaus** [comment]
I can live with that. 
Could/should we add this example to the Guidelines?

**Comment by craigsapp** [comment]
This probably should also apply to guitar music which is played an octave
lower than written without adding the 8 under the clef.

**Comment by pe-ro** [comment]
And to piccolo staves which are played an octave higher than written without an '8' over the clef.

**Comment by pe-ro** [comment]
A lot of things need to be added/revised in the Guidelines.  I'm even wondering if we should use the wiki here or github pages for the Guidelines.  Is there a reason to prefer one over the other?

**Comment by rettinghaus** [comment]
Just for curiosity: What would happen on a _basso continuo_ line, where the cellos sound like written and the double basses sound an octave lower?

**Comment by pe-ro** [comment]
That one's harder.  I think the best approach would be to create two alternative encodings -- one for display (with a single line) and one for performance (with 2 layers/staves/etc).

**Comment by bwbohl** [comment]
> A lot of things need to be added/revised in the Guidelines. I'm even wondering if we should use the wiki here or github pages for the Guidelines. Is there a reason to prefer one over the other?

I don't think a wiki is a good place for the guidelines, at least in the sense of controlled versioning and tying the guidelines to a specific schema version. Although it might be in the sense of "contribution ease".
I don't know enough about the mechanisms of GitHub pages though…

Although this might ease contribution, I think we have to maintain the guidelines with the schema and publish a PDF version.
