### ISSUE TITLE
clean up att.staffident

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#441]
Why are such elements like `mRest`, `mRpt`, `mRpt2`, `mSpace`, and `multiRest` part of `att.staffident`. It really doesn't seem to make much sense there. Could someone throw some light on this plz?

**Comment by pe-ro** [comment]
`@staff` (available within `att.staffIdent`) can be useful for tracing the path of a voice that "wanders" across staves.  Since these elements are events (the same as notes, rests, and chords), they need `@staff` too, even though the likelihood of its use on them is small.

**Comment by rettinghaus** [comment]
Thanks for clearing that up.
