### ISSUE TITLE
Work duration

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#45]
_From [a...@kb.dk](https://code.google.com/u/101822190470135414035/) on January 23, 2012 08:43:43_

Some way of encoding a work's duration; <extent> in <work>?

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=45_

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on February 21, 2012 11:50:47_

**Labels:** Milestone-Release2013

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on May 24, 2012 07:32:11_

**Owner:** pd...@virginia.edu

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on February 12, 2013 13:51:50_

> Reported by atge@kb.dk, Jan 23, 2012
> Some way of encoding a work's duration; <extent> in <work>?

<extent> is provided in the new <expression> element.

**Comment by pe-ro** [comment]
Adding `<extent>` to `<work>` is addressed in my 2015 customization.  HOWEVER, at this point I believe it's implemented entirely wrong and it's too complex.  Of course, `<extent>` may be allowed within `<work>` easily; the difficulty comes in effectively distinguishing between measurements of logical **size** and **duration** (intended and actual).  The simplest means, I now believe, is to add new `@duration` and `@quantity` attributes to extent and use schematron to disallow their simultaneous use. `@quantity` should be part of a new class (`att.quantity`) that can be re-used.  This solution can be used within `<expression>` to capture both logical size (e.g. 1 page) and intended duration (4'33") when `<extent>` is made repeatable. It can be used in the same way in `<source>` and `<item>`.
