### ISSUE TITLE
Guidelines stylesheet

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#454]
The data dictionary portion of the Guidelines contains errors that appear to be caused by the stylesheet used to generate the individual pages.  For example, http://music-encoding.org/documentation/3.0.0/model.pubStmtPart/ incorrectly lists as members of model.pubStmtPart elements that aren't actually members at all.

Possibly related issues #428, #395, and #374.

**Comment by bwbohl** [comment]
> incorrectly lists as members of model.pubStmtPart that actually members at all.

is there some information missing here or am I just incapable of understanding it right?

**Comment by pe-ro** [comment]
Sorry, brain and fingers moving at different speeds.  Fixed now.

**Comment by pe-ro** [comment]
It seems the development version of the Guidelines is fixed.
