### ISSUE TITLE
Allow members of model.transcriptionLike in <keySig>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#459]
From https://github.com/music-encoding/music-encoding/pull/458#issuecomment-326065385:

**att.transcriptionLike corrected to model.transcriptionLike**

>the content of `<keySig>` should allow members of model.transcriptionLike (add, corr, damage, etc.) These elements would also have to allow `<keyAccid>`, of course. For example,
```
<keySig>
  <keyAccid accid="s" pname="f"/>
  <supplied>
    <keyAccid accid="s" pname="c"/>
  </supplied>
</keySig>
```
>We'd also need a Schematron rule to disallow content of `<supplied>` other than `<keyAccid>`.

**Comment by lpugin** [comment]
Should this be limited to keySig? Or do we want to allow editorial markup within scoreDef in a more general manner?

**Comment by pe-ro** [comment]
This is a particularly treacherous area, so I think one-step-at-a-time is the way to go.
