### ISSUE TITLE
note@dots.ges

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#467]
An attribute `dots.ges` is needed for gestural durations.

I don't see it in the attributes for notes:
     http://music-encoding.org/documentation/3.0.0/note
so it should be added.

Example:

<img width="553" alt="screen shot 2017-10-09 at 7 08 50 pm" src="https://user-images.githubusercontent.com/3487289/31366375-680cf2be-ad25-11e7-9314-722321154e3e.png">

Verovio implements `dur`/`dur.ges`, but cannot align the second notes on each staff in the first measure because `dots.ges` is not available to give a dotted gestural duration.

Test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-10-09T18:15:59" version="2.0.0-dev-d484cb6-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001101442804" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001709012224" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-0000000774670143" clef.shape="G" clef.line="2" meter.count="6" meter.unit="8" n="1" lines="5" />
                            <staffDef xml:id="staffdef-0000002129874453" clef.shape="F" clef.line="4" meter.count="6" meter.unit="8" n="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000438874746">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F2N1" n="1">
                                <layer xml:id="layer-L3F2N1" n="1">
                                    <note xml:id="note-L5F2" dots="1" dur="4" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L6F2" dots="1" dur="4" oct="4" pname="d" accid.ges="n" />
                                </layer>
                            </staff>
                            <staff xml:id="staff-L3F1N1" n="2">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <note xml:id="note-L5F1" dur.ges="4" dots.ges="1" dur="4" oct="3" pname="c" accid.ges="n" />
                                    <note xml:id="note-L6F1" dots="1" dur="4" oct="3" pname="d" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L7" right="end" n="2">
                            <staff xml:id="staff-L7F2N1" n="1">
                                <layer xml:id="layer-L7F2N1" n="1">
                                    <note xml:id="note-L8F2" dots="1" dur="2" oct="4" pname="e" accid.ges="n" />
                                </layer>
                            </staff>
                            <staff xml:id="staff-L7F1N1" n="2">
                                <layer xml:id="layer-L7F1N1" n="1">
                                    <note xml:id="note-L8F1" dots="1" dur="2" oct="3" pname="e" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by pe-ro** [comment]
If `@dur.ges` allowed the usual power-of-two values, then `@dots.ges` would make sense.  However, `@dur.ges` can only be expressed as clicks/ticks per quarter note, Humdrum `**recip` values, etc. which *include any necessary "dots"*.  For example, in this case, `@dur.ges="3b"` works; that is, 3 beats of a 6-beat measure.

**Comment by craigsapp** [comment]
Thanks, using `@dur.ges="3b"` will work for me.  I will be checking if verovio supports it, and submit a bug report over there if it does not work :-)


But of course seeing the term "beat" be used for the eighth note in this case will trigger the commentary:  Note that the musical beat is the dotted quarter note, not the eighth note, which seems to be the "MEI beat" :-)   Maybe `@dur.ges="3u"` would be better, with `u` standing for the `@meter.unit` value of the meter.  Also, I wonder how to specify a similar thing when the meter is undefined? If a measure with such information is pulled out from a score, the `meter.unit` content from a previous point in the score would also have to be extracted as well.

**Comment by pe-ro** [comment]
I think you're right -- switching to "u" would be better.  Should we break compatibility now or later?  It's easy to do now.

If the meter is undefined, then values in pulses-per-quarter-note have to be used.  In that case, however, I wouldn't expect just one measure to have different values, but rather the entire piece to use pulses-per-quarter.  Alternatively, one could pretend the measure is in some meter and provide `@dur.ges` values that match, but then not display the meter signature.

**Comment by craigsapp** [comment]
Yes, switching to `u` to mean `meter.unit` units would get me to stop whining about that point :-).  Presumably for MEI 4 and not for MEI 3, of course.
