### ISSUE TITLE
invisible ties

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#469]
How could I encode "invisible" ties?

Here is some example music from JRP (http://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Jos0602d):

<img width="1171" alt="screen shot 2017-10-10 at 9 38 03 pm" src="https://user-images.githubusercontent.com/3487289/31422666-2fcc578e-ae04-11e7-9e85-f579784980f5.png">

The last notes in each part are "terminal longs" which function similar to fermatas in Renaissance-era music.   Behind these longs, the encoding in the musical data looks like this:

<img width="1161" alt="screen shot 2017-10-10 at 9 40 53 pm" src="https://user-images.githubusercontent.com/3487289/31422693-55896ade-ae04-11e7-9b82-3490aa6bdbb8.png">

In particular I convert the two gestural tied breves into a single visual long.  How can I do that in MEI?
`note@visible="false"` can be used to hide the second breve in the tied group, but how to not display the tie as well, since it does not have a visual attribute?

Here is a sample encoding, which has (1) the second note invisible, (2) the barline invisible, and (3) the breve visually rendered as a long:

<img width="384" alt="screen shot 2017-10-10 at 9 51 47 pm" src="https://user-images.githubusercontent.com/3487289/31422822-3f669852-ae05-11e7-9be2-917953386157.png">

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-10-10T21:50:27" version="2.0.0-dev-7f71266">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001705520885" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001762618526">
                            <staffDef xml:id="staffdef-0000001940139764" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001814356097">
                        <measure xml:id="measure-L2" right="invis" n="1">
                            <staff xml:id="staff-L2F1N1" n="1">
                                <layer xml:id="layer-L2F1N1" n="1">
                                    <note xml:id="note-L4F1" dur.ges="breve" dur="long" oct="4" pname="b" accid.ges="n" />
                                </layer>
                            </staff>
                            <tie xml:id="tie-L4F1-L6F1" startid="#note-L4F1" endid="#note-L6F1" />
                        </measure>
                        <measure xml:id="measure-L5" right="end">
                            <staff xml:id="staff-L5F1N1" n="1">
                                <layer xml:id="layer-L5F1N1" n="1">
                                    <note xml:id="note-L6F1" dur="breve" oct="4" pname="b" visible="false" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

I could not encode the tie if necessary, but then the MIDI output from verovio would be incorrect and it would re-attack the invisible breve...

**Comment by siennamw** [comment]
So in the gestural domain you need a breve tied to a breve, but in the logical (and visual) domain you need only a long.  Right?  It doesn't look like we have a way to encode a tie as purely gestural yet.  Perhaps that should be added.

**Comment by craigsapp** [comment]
Yes, although I would say that the gestural and logical domain are the same in this case, and this is how the original data is encoded for analytic purposes.  For printing, I want to transform the tied group of notes into a visual representation as found in the original edition by converting the first notehead to a long, and hiding all notes tied to that note (including the ties of course).

For now I will cheat and remove the tie when converting to MEI.  Here is what the example looks like in rendered with verovio at the moment:

http://verovio.humdrum.org/?k=e&file=jrp:Jos0602d&filter=myank%20-m85-93

<img width="876" alt="screen shot 2017-10-11 at 6 25 23 pm" src="https://user-images.githubusercontent.com/3487289/31474757-a3d279b2-aeb1-11e7-8936-3abd6a72cba0.png">

(barline after long in bottom staff I will also have to figure out how to get rid of)

And here is how the data is otherwise encoded without showing the terminal longs:

<img width="1046" alt="screen shot 2017-10-11 at 6 32 10 pm" src="https://user-images.githubusercontent.com/3487289/31474910-8a85c3f0-aeb2-11e7-94b8-71b7fd152561.png">

**Comment by pe-ro** [comment]
> I could not encode the tie if necessary, but then the MIDI output from verovio would be incorrect and it would re-attack the invisible breve...

This sounds like a MIDI conversion problem to me.  Invisible notes should be ignored, shouldn't they?

**Comment by pe-ro** [comment]
> For now I will cheat and remove the tie when converting to MEI. Here is what the example looks like in rendered with verovio at the moment:

It's not "cheating" to remove the tie.  In fact, it's anything but cheating.  It's being faithful to the different notational styles  -- ties exist in CMN, but not in mensural notation.  I say it's cheating to "warp" CMN into mensural by manipulating its visual characteristics.  That's the thing we're trying to avoid by encoding both styles.

It would be more honest to provide both encoding styles (via `<choice>`) and switch between them.

**Comment by craigsapp** [comment]
> It would be more honest to provide both encoding styles (via <choice>) and switch between them.

That is probably good, although the musical content is basically the same so a bit redundant.   So more expensive in terms of encoding as well as maintenance :-)

The terminal long has a variable duration: when a singer comes to the long note at the end of their part, then keep holding it until all other singers are holding their terminal long.  It functions similar to a fermata in CMN.  I am displaying a terminal long in full-score format which was never done in mensural music, since the music was always written out by part (when generating a part, aligning the terminal long with other parts is not a problem).

In Humdrum, I encode the score as it would be done in Finale, as that is where the scores are initially entered.  When converting them to Humdrum, I add a "terminal long" marker to the note attack of the last note for each part in the piece (and before any double barline which demarks a major section boundary).  For analysis (logical form) I use the Finale-style encoding, as well as for the gestural form (MIDI). for the visual form, I generate the visual long in the process of converting the Humdrum data to the music typesetting format (MuseData for this example):

![screen shot 2017-10-16 at 3 49 09 pm](https://user-images.githubusercontent.com/3487289/31638754-20d66398-b28a-11e7-8c07-91fe5d64e82d.png)

Here is the Humdrum data for this excerpt:

```
**kern	**kern	**kern	**kern
*clefF4	*clefGv2	*clefGv2	*clefG2
=249	=249	=249	=249
2C	2A	2E	0r
2D	2F	2F	.
2BB-	1G	2D	.
2C	.	2E	.
=250	=250	=250	=250
1AA	2r	2r	1c
.	1A	1E	.
1BB-	.	.	1d
.	2G	2D	.
=251	=251	=251	=251
2AA	2A	1E	2.c
2.C	2G	.	.
.	.	.	4B-
.	2A	2r	2c
4AA	.	.	.
2BB-	2G	2D	2d
=252	=252	=252	=252
2C	2A	2E	2c
2D	2F	2F	1f
2BB-	1G	2D	.
2C	.	2E	2e
=253	=253	=253	=253
2AA	[0Fl	2C	[0fl
2BB-	.	2D	.
2AA	.	2C	.
[2BB-	.	[2D	.
=254	=254	=254	=254
2BB-]	0F_	4D]	0f_
.	.	4BB-	.
2AA	.	2C	.
2.BB-	.	1D	.
4AA	.	.	.
=255	=255	=255	=255
0FFl	0F]	0Cl	0f]
==	==	==	==
*-	*-	*-	*-
!!!RDF**kern: l=terminal long
```

If I remove the RDF line, then the music will be printed in a more conventional modern style, which is the only format that verovio can currently handle properly:

![screen shot 2017-10-16 at 4 07 01 pm](https://user-images.githubusercontent.com/3487289/31639145-1aabce34-b28c-11e7-8cfc-77ce03df1ddc.png)

probably adding fermatas to the notes in the last measure since the original last notes were longs and not breves as in two parts.  MIDI playback is correct since this is conventional CMN.

Verovio is getting close to what I want.  Here is what happens when I add the definition of the "l" marker back into the data:

![screen shot 2017-10-16 at 4 10 36 pm](https://user-images.githubusercontent.com/3487289/31639251-a6923730-b28c-11e7-9b49-a8d044ea1305.png)

Playing the music, you will hear the invisible notes being re-struck since I removed the ties.  These invisible notes could be converted to invisible rests (a.k.a. space elements) and a `@dur.ges` added to the terminal longs, which verovio does not support (yet)).  So either MEI should add an invisible attribute to ties, which would allow verovio to generate MIDI properly from the visual form of the score in verovio as is; or verovio should add support for `note@dur.ges`.  Or both should be done, of course.

If the music is encoded with invisible notes/ties, then it would be easier to switch between the two visual formats programmatically in MEI: to convert to standard CMN, make all of the invisible notes and ties attached to the terminal long visible.  Using the `note@dur.ges`/`space` method would require swapping out the spaces for notes and adding ties, which would be a much more difficult process (and be better suited to storing both forms in `<choice>` if that is the encoding method).

Checking the MuseData conversion of this score:
      http://josquin.stanford.edu/data?a=musedata&f=Jos0602c
I see that I remove the visual ties, but I partially keep the gestural ties, the "-" after `48-`, I don't make the MIDI file from the MuseData conversion; otherwise I would fix that.  And I make the tied notes invisible (`P  C1:p1` is equivalent to `note@invis="true"` in MEI).

```
measure 249
rest  48      1
measure 250
C4    24      1 w
D4    24      1 w
measure 251
C4    18      1 h.    u
Bf3    6      1 q     u
C4    12      1 h     u
D4    12      1 h     u
measure 252
C4    12      1 h     u
F4    24      1 w
E4    12      1 h     u
measure 253
F4    48      1 L
msilent 254
F4    48-     1 B
P  C1:p1
msilent 255
F4    48      1 B
P  C1:p1
mheavy2
```

**Comment by pe-ro** [comment]
We can make more elements be members of att.visibility.  But how does this compare with using `@type` (e.g., `@type="invis"`) to hide these items during rendition?

**Comment by craigsapp** [comment]
> We can make more elements be members of att.visibility. But how does this compare with using @type (e.g., @type="invis") to hide these items during rendition?

Doing that should work for webpage interfaces.  

It would not be as easy for static SVG use -- probably accomplished by adding a style element to the SVGs after they have been generated by verovio (or other renderer).

**Comment by pe-ro** [comment]
There's a fairly lengthy list of elements whose visual domain attributes doesn't include `@visible`.  As I recall these were removed at the point at which the possibility of a style language was introduced.  I have no objection to adding them back, but I think we need to determine exactly what we mean when we say something is "invisible".  Does it mean --

1. space for the item is preserved in the layout but the item just isn't shown, or
2. no space is retained for the item and the layout is "collapsed" as though the item never existed?

I've been assuming option 1 since it would provide a way to "de-clutter" a complex rendering. (I imagine Finale-like "handles" being displayed for invisible/hidden elements.) Option 2, on the other hand, leads to more fundamental philosophical questions along the lines of "If a tie falls in the woods ...".

One way forward might be to add `@visible` to more elements now (assuming option 1), and address option 2 in a style language later.  Alternatively, we could modify `@visible` to take 3 values: show, hide, ignore, where "show" and "hide" address option 1 and "ignore" addresses option 2.

**Comment by craigsapp** [comment]
> 1. space for the item is preserved in the layout but the item just isn't shown, or
> 2. no space is retained for the item and the layout is "collapsed" as though the item never existed?

In CSS, (1) is the equivalent of `visibility:hidden`, and (2) is `display:none`, so the best behavior would be (1) for an `invis` attribute to match the behavior of CSS.  Technically I would want (2) for invisible ties, but (1) should always work just as well. 

Using `ignore` for (2) sounds good.  This would make a `<note>` behave like a `<space>`, for example.  Potentially this could be useful for controlling slurs that go off to nowhere: they could be attached to an "ignored" note that otherwise would not take up any space by itself.

`@invis` could also be used to control the visibility of things such as a "gestural" slur, or other gestural feature in the music.  Gestural items could have the default behavior `@visible="hide"`, but they could be forced visible by setting `@visibile="show"` explicitly.  Conversely, fermatas could be switched from visible to purely gestural by setting `@visible="hide"`.

**Comment by pe-ro** [comment]
> Using `ignore` for (2) sounds good. This would make a `<note>` behave like a `<space>`, for example. 

I think not, because a `<space>` occupies time and therefore has dimensions.  An ignored note (that is, taking away its dimensions) can't be equivalent to a space (which has dimensions).  Perhaps you meant to say that a slur could be attached to an invisible note (not an ignored one).

> `@invis` could also be used to control the visibility of things such as a "gestural" slur, or other gestural feature in the music.

I don't think we should equate invisibility with gestural-ness or vice versa.  These qualities should be independent of each other.

**Comment by craigsapp** [comment]
> I think not, because a `<space>` occupies time and therefore has dimensions. An ignored note (that is, taking away its dimensions) can't be equivalent to a space (which has dimensions). Perhaps you meant to say that a slur could be attached to an invisible note (not an ignored one).

Yes.  I was thinking in terms of a full score where the duration is still needed, but just for alignment.

**Comment by pe-ro** [comment]
@craigsapp, So,
1. `@visible="show"` means the entity **_should_** be rendered. This is the default for any "render-able" elements. Non-render-able elements wouldn't carry `@visible` anyway.
2. `@visible="hide"` means the entity **_should not_** be rendered, but **_should_** affect performance,
3. `@visible="ignore"` means the item **_should not_** be rendered, and **_should not_** affect performance.  In practical terms, it is simply "gone".

But, I'm still not sure how this would help deal with the Josquin example, because the possible alternatives -- one mensural, one CMN -- still have to be encoded somehow.  Even with the possibilities described above, a note, fermata, etc. can't be visible and invisible simultaneously.  The mechanism for switching between (or at least identifying) alternatives is still `<choice>`.

**Comment by craigsapp** [comment]
```
@visible="show" means the entity should be rendered. This is the default for any "render-able" elements. Non-render-able elements wouldn't carry @visible anyway.
@visible="hide" means the entity should not be rendered, but should affect performance,
@visible="ignore" means the item should not be rendered, and should not affect performance. In practical terms, it is simply "gone".
```

Yes, there would be no effect on performance, only on visual rendering.   You were suggesting that the difference between `@visible="hide"` and `@visible="ignore"` would be similar to `@visibility="hidden"` and `@display="none"` in CSS.  Visibility hidden in CSS means to make them invisible, but preserve the layout as if the object were still there.  Display none in CSS means to make them invisible and do not preserve the space that the take up  (i.e., remove them from the display).

Strictly speaking I would want to say that the invisible notes and ties that form the end of a terminal long are `@display="none"` which would map to `@visible="ignore"`.  For single-staff music, the objects could be removed.  For multi-staff music, the notes would have to be converted internally into spaces before rendering.


In Humdrum data, I would say that I am adding a "functional attribute" to the first note in the terminal long group.  I encoded in modern notation, and use modern notation for analysis, but when converting to a notation format (MuseData usually), I "compile" the data according to the functional attribute.  This would be somewhat equivalent to embedding an attribute on a note (such as with `note@type="terminal_long"`) which would then trigger an XSLT script to process the data into the visually desired form.

Fermatas are the modern equivalent of terminal longs.  Here are the two visual syntaxes:

![screen shot 2017-11-09 at 4 54 34 pm](https://user-images.githubusercontent.com/3487289/32637453-b40a5b1e-c56e-11e7-88f6-263998fb9387.png)

In the Josquin Research Project encodings, which come from Finale, the data is encoded purely in CMN.  Jesse wants to use a somewhat hybrid mensural/CMN representation that reflects the original mensural notation.  For example, the original note values are used in the notation, and in this case terminal longs are used instead of a long series of tied notes ending with a fermata sign.  When converting into MEI, I would want to keep the CMN syntax, at least for analysis and performance, but be able to adjust the visual look to do something which is not CMN.  Karen and other Renaissance/Medieval scholars would also want this sort of capability: rendering the notation in explicit rhythms and adding barlines as in CMN, but preserving other aspects of mensural music such as the mensural signs and terminal longs.  The mensural signs are important to display since they encode both meter and tempo, but the terminal long are "visual sugar".

**Comment by bwbohl** [comment]
I basically see one point of discussion with the approach to mensuralish CMN
shouldn't mensuralish CMN rather rely on `<staffLine>` than `measure`?
This would:
   - resolve the problem of meter conformity (as none can ever exist)
   - make it unnecessary to have multiple "empty" measure after the terminal longs
   - render the problem to a mere synchronisation problem with no differences between logical, gestural and visual durations, which brings me to the second point

Consequently 

> This sounds like a MIDI conversion problem to me[, too!]

N.B. The MIDI rendition by means of certain converter should not serve as model for encoding. Instead the converter should cover the logical aspects of the ›mensuralish MEI‹ (which I like, though ;-)

**Comment by craigsapp** [comment]
Has this been implemented yet?   Invisible ties are a required feature of MEI.
