### ISSUE TITLE
Make <extent> in <expression> repeatable?

### ISSUE THREAD

**Issue by axgeertinger** [music-encoding/music-encoding#471]
Is there a particular reason that `<extent>` is not repeatable when it's a child of `<expression>`? It is repeatable in other contexts such as `<physDesc>`. Since extent can be expressed by any unit of measurement, I may want to provide more than one - for instance, number of bars AND number of sections or whatever.

**Comment by pe-ro** [comment]
There's no reason in particular that it's not repeatable.  It's easily fixed.
