### ISSUE TITLE
Description of Audio and Video components within a work

### ISSUE THREAD

**Issue by BAZAK** [music-encoding/music-encoding#475]
In the current MEI header, audio and video are treated as expressions of a work, e.g., an audio recording of a symphony. However, it is currently unclear how we might catalogue a work containing audio or video as a constituent part of that work. For example, how to record the media part for a work for singer and tape. 

The use case we identified was B.A. Zimmermann’s _Requiem für einen jungen Dichter
Lingual für Sprecher, Sopran- und Baß-Solo, drei Chöre, Orchester, Jazz-Combo, Orgel und elektronische Klänge nach Texten verschiedener Dichter, Berichte und Reportagen_. This work contains excerpts from other musical recordings and speeches, which has been pre-arranged in a single recording.

Some of the recordings include:

-	Paul McCartney, Hey Jude, Ausschnitt – Englisch, Schallplattenaufnahme (Excerpt – English vinyl)
-	Jossif Wissarionowitsch Stalin, Rundfunkansprache an Volk und Armee am 3. Juli 1941, Ausschnitt – Russisch mit deutscher Ansage, Originaltonaufnahme (Broadcast to the public and army on 3 July 1941, excerpt – Russian with German introduction, Original recording)
-	Joseph Goebbels, Rede im Berliner Sportpalast am 18. Februar 1943, Ausschnitt – Deutsch, Originaltonaufnahme (Speech at Berlin Sport Palace on 18 Februarz 1943, excerpt – German, original recording)
-	Winston Churchill, Rede in der BBC, Ausschnitt – Englisch, Originaltonaufnahme (Speech in the BBC, excerpt – English, original recording)
-	Konrad Bayer, der sechste sinn, Ausschnitt – Deutsch, Studioaufnahme. (Reading of an excerpt of the book „Der sechste Sinn“, excerpt, German, Studio recording)

... and others.
This is available as a single 4-track recording with specifications for quad-channel reproduction. (“2 Einspielbänder (4-Spur, 38 cm/s) über 2 × 4 Lautsprecher“)

The guidelines do not contain examples identifying how this type of work can be described. It may be that the “perfRes” elements may need to be expanded to accommodate non-traditional instruments, or to describe components of the “instrument”.

As a first pass, it may look something like:

```xml
<perfResList>
    <perfResList recording=”http://example.com/recording.mp3” >
        <perfRes tstamp=”4m3”>McCartney, Hey Jude</perfRes>
    </perfResList>
</perfResList>
```

**Comment by pe-ro** [comment]
> It may be that the “perfRes” elements may need to be expanded to accommodate non-traditional instruments, or to describe components of the “instrument”.

The MARC Instruments and Voices Code List (and probably other lists too) already identify electronic resources, for example --
```
ea - Electronic - Synthesizer
eb - Electronic - Tape
ec - Electronic - Computer
ed - Electronic - Ondes Martinot
en - Electronic - Unspecified
eu - Electronic - Unknown
ez - Electronic - Other
```
so extending `<perfRes>` in this respect isn't necessary.  Identifying the initial use of the resource in the transcription is addressed in #476.

While there are no examples in the Guidelines, MEI already provides elements for describing electronic characteristics.  See the example below for details.

As I see it, the tape (being a physical thing) is part of a manifestation of the work.  Manifestations are treated as (potential) source material in MEI and are, therefore, marked up using `<source>` elements. The tape part of a source can be described using `<componentGrp>` containing another `<source>` element --
```
<source xmlns="http://www.music-encoding.org/ns/mei">
  <!-- containing manifestation; i.e., the requiem -->
  <componentGrp>
    <source>
      <!-- contained material; i.e., the tape -->
    </source>
  </componentGrp>
</source>
```
For a simple listing of the contents of the tape, the `<contents>` element may be employed.  Alternatively, a more detailed description of each of the contained items (in the generic sense, not the FRBR one), can be accommodated using a `<componentGrp>` element one more level down.  If another description is available for the individual components of the tape, however, then one should keep the details here minimal and reference the other description.  An example showing both approaches in the same file follows, although in  real use cases, one or the other option should be chosen.
```
<source xmlns="http://www.music-encoding.org/ns/mei">
  <titleStmt>
    <title>Requiem für einen jungen Dichter Lingual für Sprecher, Sopran- und Baß-Solo, drei Chöre,
      Orchester, Jazz-Combo, Orgel und elektronische Klänge nach Texten verschiedener Dichter,
      Berichte und Reportagen.</title>
    <composer>B.A. Zimmermann</composer>
  </titleStmt>
  <pubStmt/>
  <componentGrp>
    <source>
      <head>Tape</head>
      <physDesc>
        <dimensions><width>2"</width></dimensions>
        <playingSpeed>38 cm/s</playingSpeed>
        <trackConfig num="4">4-Spur</trackConfig>
        <soundChan num="4">2 × 4 Lautsprecher</soundChan>
      </physDesc>
      <contents>
        <contentItem>Paul McCartney, Hey Jude, Ausschnitt – Englisch, Schallplattenaufnahme (Excerpt
          – English vinyl)</contentItem>
        <contentItem>Jossif Wissarionowitsch Stalin, Rundfunkansprache an Volk und Armee am 3. Juli
          1941, Ausschnitt – Russisch mit deutscher Ansage, Originaltonaufnahme (Broadcast to the
          public and army on 3 July 1941, excerpt – Russian with German introduction, Original
          recording)</contentItem>
        <contentItem>Joseph Goebbels, Rede im Berliner Sportpalast am 18. Februar 1943, Ausschnitt –
          Deutsch, Originaltonaufnahme (Speech at Berlin Sport Palace on 18 Februarz 1943, excerpt –
          German, original recording)</contentItem>
        <contentItem>Winston Churchill, Rede in der BBC, Ausschnitt – Englisch, Originaltonaufnahme
          (Speech in the BBC, excerpt – English, original recording)</contentItem>
        <contentItem>Konrad Bayer, der sechste sinn, Ausschnitt – Deutsch, Studioaufnahme. (Reading
          of an excerpt of the book „Der sechste Sinn“, excerpt, German, Studio
          recording)</contentItem>
        <!-- etc. -->
      </contents>
      <componentGrp>
        <source>
          <titleStmt>
            <title>Hey Jude</title>
            <composer>Paul McCartney</composer>
          </titleStmt>
          <langUsage>
            <language>English</language>
          </langUsage>
        </source>
        <source>
          <titleStmt>
            <title>Rundfunkansprache an Volk und Armee am 3. Juli 1941</title>
            <author>Jossif Wissarionowitsch Stalin</author>
          </titleStmt>
          <langUsage>
            <language>Russian with German introduction</language>
          </langUsage>
        </source>
        <!-- etc. -->
      </componentGrp>
    </source>
  </componentGrp>
</source>
```
