### ISSUE TITLE
Identify in perfRes where an instrument occurs in the score

### ISSUE THREAD

**Issue by BAZAK** [music-encoding/music-encoding#476]
Related to the need to describe recorded sources as an instrument in the perfRes descriptions (See #475), it would be valuable to have guidance on how to identify in the score where a particular instrument occurs.

The use case for this is where a number of recorded “snippets” are treated as an instrument in the score. We should be able to identify where a particular speech or excerpt of a recording occurs within the score by aligning the perfRes element with time stamps or startid/endid.

**Comment by pe-ro** [comment]
Using `<surface>` as a model, `@startid` can be added to `<perfRes>` to capture the initial use of the resource.  I'm reluctant to go much beyond this simple mechanism, as anything more would begin to get us into the realm of annotation and analysis, for which there are already existing elements and attributes.

**Comment by ahankinson** [comment]
Would the startid need to be limited to a specific element? You would probably want to annotate every staff across measures.

It also assumes an existing id. In the related issue we have the case of an audio "instrument", which may have a musical tstamp, but not necessarily an element we can use as a startid.

On Nov 9, 2017, at 4:09 PM, pe-ro <notifications@github.com<mailto:notifications@github.com>> wrote:


Using <surface> as a model, @startid can be added to <perfRes> to capture the initial use of the resource. I'm reluctant to go much beyond this simple mechanism, as anything more would begin to get us into the realm of annotation and analysis, for which there are already existing elements and attributes.

**Comment by pe-ro** [comment]
>Would the startid need to be limited to a specific element? You would probably want to annotate every staff across measures.

Without a specific example, it's hard for me to parse your statement.

Are you suggesting that `<perfRes>` should point to every measure, staff, note, etc. where it is used?

It need not point to any particular kind of element, but I was thinking that `perfRes/@startid` would identify only the first occurrence of the use of the resource.  Exactly which element is pointed at depends on the detail provided by the encoding.  If the encoding is only marked up down to the measure level, then a measure could be the target.  If the encoding contains note-level markup, then the first note could be pointed to.  Neither of these is likely to be useful for works with tape, so it's more likely that the target would be an instruction; e.g., a `<dir>`, associated with the tape material.

**Comment by lpugin** [comment]
Closing because of the lack of input.
