### ISSUE TITLE
Make availability processable

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#477]
As it turns out, `<availability>` has no possibility to store *processable* information on the licence for the information the file holds. So it would be good to adopt the `<licence>` element from TEI for making interchange of information more reliable. 

See here:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-licence.html
https://github.com/TEI-Correspondence-SIG/CMIF

**Comment by pe-ro** [comment]
MEI provides 2 children in `<availability>` which address restrictions; that is, `<accessRestrict>` and `<useRestrict>`.  These are intended to provide for a more fine-grained approach than a single `<license>` element can support. 

Adding a `@target` attribute (and other attributes provided by the TEI `<license>` element) to both `<accessRestrict>` and `<useRestrict>` is easy to do.

**Comment by bwbohl** [comment]
one could alternative add `@auth`, `@auth.uri`, and `@codedval` or something similar to `<accessRestrict>` and `<useRestrict>` as a more sophisticated pointing mechanism.

**Comment by rettinghaus** [comment]
`@target` would be nice to have anyway for using it like in `TEI`:
`<useRestrict target="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0</useRestrict>`

But what should go into `<accessRestrict>` and how could that be processed?
`<accessRestrict>Behind a paywall</accessRestrict>`

**Comment by pe-ro** [comment]
Access restrictions have to do with physical access to the item, while use restrictions have to do with use of the intellectual content of an item.  For instance, a book may be physically available in a library, but its content is protected by copyright law.  Conversely, an item, such as a letter from Thomas Jefferson to Angelica Church, may be in the public domain, yet physically inaccessible in a library's archives.

`<accessRestrict>` is less machine-processable than `<useRestrict>` at present.  In archives, a collection is often said to be "open" or "closed" for research, but as far as I know, there's been no standardization effort for expressing/consuming access restrictions like that for use restrictions (see http://rightsstatements.org/page/1.0/?language=en, for example).  But, that doesn't mean there won't be in the future, so I think these elements should be treated the same "just in case".  If `accessRestrict/@target` or `accessRestrict/@auth` is available then one could record a string and a URI.

**Comment by bwbohl** [comment]
Yeah, having them modelled the same way might be a wise idea!
Nevertheless verbose referencing mechanisms to public entities will have to be accompanied by the possibility of a verbose description in prose, at least at the moment ;-)

I don't like `@target` for that purpose, though.
It works good in it's original TEI-context `<ref/>` and `<ptr/>` where it really can be seen as modelling a ›target‹ of the pointer but in the context of `<accessRestrict>` or `useRestrict` an attribute with that name would rather point tot the restricted material.

**Comment by pe-ro** [comment]
I agree with @bwbohl that `@target` is better for pointing at *content* and `@auth/@auth.uri` are better for indicating the source of a *standardized value*.
