### ISSUE TITLE
gatherings and folios

### ISSUE THREAD

**Issue by JanetteSeuffert** [music-encoding/music-encoding#480]
In the `<physDesc/>` we would wish a way (a tag / container) to describe the gatherings and their disposition in a musical manuscript  in MEI (in TEI, `<collation/>` is used for describing the arrangement of leaves / bifolios). In addition, we also recommend a describing format for individual folios (shape, count, missing folios, etc.)

**Comment by pe-ro** [comment]
Addressed by proposal to resolve #489.
