### ISSUE TITLE
Incorrectly numbered `<staff>` and `<layer>` elements

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#482]
Hand-coding can introduce a number of errors, one of which is unnumbered or non-consecutively numbered staves and layers.  @craigsapp recently raised the following issues in the sample-encodings repo:

1. https://github.com/music-encoding/sample-encodings/issues/41 and 
2. https://github.com/music-encoding/sample-encodings/issues/43

which can be handled by adding new Schematron rules to the MEI spec.

**Comment by pe-ro** [comment]
Here's the ODD --
```
<!-- Add schematron rules that:
    check measure for same number of staff elements as its predecessor,
    forces all staves to be numbered if any staves have @n, and 
    enforces uniqueness on staff/@n -->
<elementSpec ident="measure" module="MEI.cmn" mode="replace">
  <desc>Unit of musical time consisting of a fixed number of note values of a given 
    type, as determined by the prevailing meter, and delimited in musical notation by 
    bar lines.</desc>
  <classes>
    <memberOf key="att.common"/>
    <memberOf key="att.facsimile"/>
    <memberOf key="att.metadataPointing"/>
    <memberOf key="att.pointing"/>
    <memberOf key="att.measure.anl"/>
    <memberOf key="att.measure.ges"/>
    <memberOf key="att.measure.log"/>
    <memberOf key="att.measure.vis"/>
    <memberOf key="att.targetEval"/>
    <memberOf key="model.measureLike"/>
  </classes>
  <content>
    <rng:optional>
      <rng:ref name="mNum"/>
    </rng:optional>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:ref name="model.annotLike"/>
        <rng:ref name="model.appLike"/>
        <rng:ref name="model.editLike"/>
        <rng:ref name="model.graphicPrimitiveLike"/>
        <rng:ref name="model.measurePart"/>
        <rng:ref name="model.milestoneLike.music"/>
        <rng:ref name="model.relationLike"/>
        <rng:ref name="model.staffDefLike"/>
        <rng:ref name="model.transcriptionLike"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <constraintSpec ident="measure-to-measure_staff_count" scheme="isoschematron">
    <constraint>
      <sch:rule xmlns="http://www.tei-c.org/ns/1.0" xmlns:math="http://exslt.org/math"
        context="mei:measure[preceding::mei:measure][count(descendant::mei:staff) !=
        count(preceding::mei:measure[1]/descendant::mei:staff)]">
        <sch:let name="currentStaffCount" value="count(descendant::mei:staff)"/>
        <sch:let name="previousStaffCount"
          value="count(preceding::mei:measure[1]/descendant::mei:staff)"/>
        <sch:assert
          test="(generate-id(preceding::mei:scoreDef[descendant::mei:staffDef][1]) eq
          generate-id(preceding::mei:measure[1]/following::mei:scoreDef[descendant::mei:staffDef][1])) and
          preceding::mei:scoreDef[1][count(descendant::mei:staffDef) = $currentStaffCount]"
          >This measure has <sch:value-of select="$currentStaffCount"/> staves, but the previous
          measure has <sch:value-of select="$previousStaffCount"/> staves. There must be an
          intervening scoreDef element with <sch:value-of select="$currentStaffCount"/> staff
          definitions.</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
  <constraintSpec ident="Check_measure_staff_n_values" scheme="isoschematron">
    <constraint>
      <sch:rule context="mei:measure[descendant::mei:staff[@n]]">
        <sch:let name="countstaves" value="count(descendant::mei:staff)"/>
        <sch:let name="countuniqstaves" value="count(distinct-values(descendant::mei:staff/@n))"/>
        <sch:assert test="$countstaves eq $countuniqstaves">Each staff must have a unique value
          for the n attribute.</sch:assert>
      </sch:rule>
      <sch:rule context="mei:measure[descendant::mei:staff[@n]]">
        <sch:assert test="count(descendant::mei:staff[@n]) = count(descendant::mei:staff)">If any
          staves are numbered, all staves must be numbered.</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
  <remarks>
    <p>In MEI, the <gi scheme="MEI">measure</gi> element is a grouping mechanism for events and
      control events. Pointing attributes make it possible to connect this element to other
      internal or external entities, such as media objects or annotations. The <att>width</att>
      attribute may be used to capture the width of the measure for interchange with music
      printing systems that utilize this information for printing.</p>
  </remarks>
</elementSpec>
```
The rules will only work if the encoding of ossia is also modified.

**Comment by pe-ro** [comment]
These rules work well for encoding complete examples of notation intended to be rendered, but not for fragmentary or experimental encodings, like my (in)famous hand-encoded "junk.mei" file that I use for testing changes made in the /develop branch.

So, perhaps such rules should go in a new "MEI.rendering" module.  That way, they could be switched off if the encoder is not interested in rendering.  (I hesitate to call this new module "MEI.verovio" as it could eventually be used more broadly, but that's effectively what it is -- additional rules that Verovio needs to enforce on MEI encodings in order to make them render-able.)

On the other hand, we could leave them in the MEI.cmn module and if someone wants to turn them off, they'll have to use their own customization.

**Comment by bwbohl** [comment]
N.B.
in the logical domain a measure might have the same number of staves as the measure before but in the graphical domain this might be different, though.

Even if there are the same number of staves in the graphical domain, they might be tied to other staves in the logical domain.

**Comment by craigsapp** [comment]
> N.B.
> in the logical domain a measure might have the same number of staves as the measure before but in the graphical domain this might be different, though.

This would be cases where the staves of resting parts are not shown? 

JRP has a type of this case:

http://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Jos0403d

<img width="750" alt="screen shot 2017-11-20 at 8 53 54 pm" src="https://user-images.githubusercontent.com/3487289/33055551-345bb992-ce35-11e7-8154-eb49ace15f5d.png">
<img width="748" alt="screen shot 2017-11-20 at 8 58 18 pm" src="https://user-images.githubusercontent.com/3487289/33055632-941a6f18-ce35-11e7-85a8-3a4d48066553.png">


This is from the Sanctus of a Mass.  Each subsection has a different number of voices, such as 4 for the Osanna section, and 2 for the Benedictus (after the Benedictus, the Osanna is repeated at the end of the Sanctus).


In the digital score that is the source for this rendering, all voices are encoded throughout the Sanctus, with rests if they are not playing:

http://josquin.stanford.edu/cgi-bin/jrp?a=humdrum&f=Jos0403d

Here is the boundary between the Osanna and the Benedictus:
```
=136           =136           =136           =136
1AA            1A             1c             [0.el
1.C            1.E            1.e            .
2BB/           2F/            2d\            .
=137           =137           =137           =137
1GG            1G             1B             0.e_
0AA            1.C            0c             .
.              2D/            .              .
=138           =138           =138           =138
0.El           0.El           0.Bl           0.e]
!!LO:LB:i:g=z
!!LO:TX:rj:i:t=fine
=139||         =139||         =139||         =139||
*>D            *>D            *>D            *>D
*clefF4        *clefGv2       *clefGv2       *clefG2
*k[]           *k[]           *k[]           *k[]
*M2/1          *M2/1          *M2/1          *M2/1
*met(C|)       *met(C|)       *met(C|)       *met(C|)
!!section: Benedictus
!!!OMD: Benedictus
2AA/           0r             0r             0r
2BB/           .              .              .
2AA/           .              .              .
[2D\           .              .              .
=140           =140           =140           =140
2D\]           0r             0r             0r
4C/            .              .              .
4BB/           .              .              .
1AA            .              .              .
=141           =141           =141           =141
0r             2E/            0r             0r
.              2F/            .              .
.              2E/            .              .
.              [2A/           .              .
=142           =142           =142           =142
0r             2A/]           0r             0r
.              4G/            .              .
.              4F/            .              .
.              1E             .              .
=143           =143           =143           =143
```

How should invisible parts be encoded in MEI?  If the layout is expected to change, then a logical encoding would be desired since the system breaks will occur in different places, requiring measures to be hidden only if there are on a system line where the staff contains only measures with full-measure rests.  It would then be left to the rendering software to hide resting staves in a system.

This is also somewhat similar to the Tasso in Music Project, where parts are extracted dynamically from the score.  In the full score resting measures are encoded as `mRests`, but in an extract part, a sequence of rests is converted into a `multiRest`:

http://www.tassomusic.org/work/?id=Trm0047m&k=e

Full score:

<img width="949" alt="screen shot 2017-11-20 at 9 16 21 pm" src="https://user-images.githubusercontent.com/3487289/33056043-1ea02158-ce38-11e7-96a7-c631058a9bad.png">

Bass part extracted:

http://www.tassomusic.org/work/?id=Trm0047m&k=3e

<img width="949" alt="screen shot 2017-11-20 at 9 17 29 pm" src="https://user-images.githubusercontent.com/3487289/33056074-3ec37840-ce38-11e7-908f-1f5f0ac8c501.png">

**Comment by craigsapp** [comment]
>Even if there are the same number of staves in the graphical domain, they might be tied to other staves in the logical domain.

Ossia staves being an example of this?  In any case, the values of `staff@n` would be the logical numbers, not enumerations of the visible staves in the measure.

Aaron Copland's Piano Variations are also a fairly complete single-part example of this:

https://www.youtube.com/watch?v=i1-vIw_M-Qg

Opening:

<img width="694" alt="screen shot 2017-11-20 at 9 34 13 pm" src="https://user-images.githubusercontent.com/3487289/33056481-c53a9140-ce3a-11e7-8c2d-eb8795b8603e.png">

The end of variation 7 has a third staff for one measure:

<img width="716" alt="screen shot 2017-11-20 at 9 34 51 pm" src="https://user-images.githubusercontent.com/3487289/33056501-df316a74-ce3a-11e7-9741-3cb764b81aa9.png">

Here is variation 10 which starts with three staves and then goes to two staves:

<img width="717" alt="screen shot 2017-11-20 at 9 37 04 pm" src="https://user-images.githubusercontent.com/3487289/33056516-0246ec00-ce3b-11e7-9fda-d6e528f67bcc.png">

In the coda, a double grand staff is used:

<img width="717" alt="screen shot 2017-11-20 at 9 38 53 pm" src="https://user-images.githubusercontent.com/3487289/33056592-4a34ad40-ce3b-11e7-95f7-16975cdd2235.png">

How should such a score be encoded in MEI?

Then there are cases like this:

<img width="779" alt="screen shot 2017-11-20 at 9 41 49 pm" src="https://user-images.githubusercontent.com/3487289/33056649-aadd280c-ce3b-11e7-9a1d-3f1bc3a9645d.png">

**Comment by bwbohl** [comment]
@craigsapp thanks for the great examples!

**Comment by pe-ro** [comment]
Being software independent, MEI offers multiple options for encoding a score with a changing number of staves.  

One method is to declare the largest number of staves ever used in the score in the first `<scoreDef>` and set `@optimize="true"`.  On each system, the expectation is that rendering software will not display any staff that either has all rests or spaces, or has no content. This approach will be most useful for orchestral scores without ossia staves, but also works for @craigsapp 's first example.  It could also be useful for OMR applications, although it might be difficult for the program to figure out exactly which staves have/don't have content.  A post-recognition method for linking a staff in one system to a staff in the next system, as SharpEye uses, would be useful and could be implemented using `staff/@next`.

Another method is to explicitly record the number of staves at each change using `<scoreDef>`.  Variation 10 in the Copland example could be encoded this way --
```
<!-- prior to variation 10 -->
<scoreDef>
  <staffDef n="1"/>
  <staffDef n="2"/>
</scoreDef>
<!-- 1st system of variation 10 -->
<scoreDef>
  <staffDef n="1"/>
  <staffDef n="2"/>
  <staffDef n="3"/>
</scoreDef>
<!-- 2nd system of variation 10 -->
<scoreDef>
  <staffDef n="1"/>
  <staffDef n="2"/>
</scoreDef>
```
Again, the continuation of material from one staff to another can be accounted for using `staff/@next`.

The value of `@optimize` determines whether "unmentioned" staves should be displayed or not.  If it were set to `no`, then the example above should be rendered with 3 staves throughout, or at least from the 2nd scoreDef onward, with unmentioned staves rendered as though they contained `<mSpace>` elements.

Ossia may be a different beast altogether.  I say "may be" because OMR systems may not be able to recognize the relationship between the main staff and the ossia one.  In this case, the ossia staff is just an extra, smaller staff.  Therefore, ossia and cue staves can be encoded by using changes in `<scoreDef>` or by using the `<ossia>` element, changes to which are proposed in #483.

The final example is a "cut-out" score.  In the good old days, scores like this were produced by using a razor blade to literally cut out the resting measures.  For cases like this, MEI provides `@cutout` on `<mRest>` and `<mSpace>`, and, as proposed in #483, on `<space>`.  This attribute indicates that the staff lines "behind" the element it's attached to should not be displayed.  The first 2 measures of the cutout score could be encoded --
```
<measure>
  <staff n="1">
    <space cutout="true"/>
  </staff>
  <staff n="2">
    <!-- pickup note -->
  </staff>
</measure>
<measure>
  <staff n="1">
    <mSpace cutout="true"/>
  </staff>
  <staff n="2">
    <!-- 1st full bar -->
  </staff>
</measure>
```
`@cutout` might also be added to `<measure>` to indicate that the entire measure, including its left and right barlines (but perhaps not any internal ones) should not be rendered.  I'd be interested in hearing comments on this.

HTH

**Comment by pe-ro** [comment]
Not having heard a lot of support for the additional Schematron I suggested, I'm going to leave them out of the next release (4.0.0) and close this issue. We can take this up again at a later date, if need be.
