### ISSUE TITLE
Clarify use of titleStmt, revise model of work and expression

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#484]
It seems there's a lot of confusion regarding the use of `<titleStmt>` that I believe we must resolve very soon.

First, a little background --

The current model of `<titleStmt>` adheres to a library cataloging tradition as old as card catalogs, in which an agent with primary responsibility for a bibliographic entity, such as an author, composer, and sometimes an editor, was treated as an "access point" and was given their own card in the "author" part of the catalog.  Additional authors, editors (sometimes), and titles were also given a card, but were referred to as "added entries".

AACR2 (Anglo-American Cataloguing Rules, 2nd ed.) and the MARC (MAchine-Readable Cataloging) format continued this separation.  In AACR2, the title and principal creator (if there is one) come first in the "title area", followed by the "statement of responsibility".  For example, a card might read --
```
Shakespeare, William, 1564-1616.
The complete works of William Shakespeare : reprinted from the first folio / 
edited by Charlotte Porter and H.A. Clarke ; with an introd. by John Churton Collins.
```
The creator name is given in the usual way for sorting Western names, while the title and the statement of responsibility are **_transcribed from the title page_**.

TEI and MEI also follow this pattern --
```
<titleStmt>
  <title>The complete works of William Shakespeare : reprinted from the first folio</title>
  <author>Shakespeare, William (1564–1616)</author>
  <respStmt>
    <resp>edited by </resp>
    <name>Charlotte Porter</name>
    <name>H.A. Clarke </name>
  </respStmt>
  <respStmt>
    <resp>with an introd. by </resp>
    <name>John Churton Collins</name>
  </respStmt>
</titleStmt>
```
I think we must continue to follow this tradition within `<source>` and `<fileDesc>` in order to make it easy to migrate data from MARC and TEI to MEI and not confuse our library colleagues.  While it very well might be arcane, to break with it will cause trouble from here to eternity.

In `<work>` and `<expression>`, there is no "chief source of information" to transcribe.  In these elements, it makes sense to have a flatter, more database-like organization, like --
```
<work>
  <title></title>
  <composer></composer>
  <editor></editor>
  etc.
</work>
```
In other words, `<titleStmt>` can be eliminated and its children (minus `<respStmt>`) moved up a level in the hierarchy.  I'm aware that this creates inconsistency between the way similar information is handled in `<fileDesc>` and `<source>` versus `<work>` and `<expression>`.  However, inconsistency in the service of clarity is no vice. 😀 

On the other hand, we could leave things the way they are, but we must make it clear that `<respStmt>` contains a **_transcription_**.  If a database-like organization is desired, then just don't use `<respStmt>`  - nothing will be lost.  For example --
```
<fileDesc>
  <titleStmt>
    <title analog="marc:100" type="uniform" xml:lang="de">
      <titlePart analog="marc:100$a">Mozart, Wolfgang Amadeus</titlePart>
      <titlePart analog="marc:100$d">1756–1791</titlePart>
      <titlePart analog="marc:100$t">Sonaten</titlePart>
      <titlePart analog="marc:100$m">Violine</titlePart>
      <titlePart analog="marc:100$m">Klavier</titlePart>
      <titlePart analog="marc:100$n">KV 379</titlePart>
      <titlePart analog="marc:100$r">G-Dur</titlePart>
    </title>
    <title analog="marc:430" type="main">Klaviersonate G-Dur</title>
    <composer>
      <persName analog="marc:500$a" auth="GND" auth.uri="http://d-nb.info/gnd/"
codedval="118584596">Mozart, Wolfgang Amadeus</persName>
    </composer>
  </titleStmt>
</fileDesc>
```
instead of
```
<titleStmt>
  <title analog="marc:100" type="uniform" xml:lang="de">
    <titlePart analog="marc:100$a">Mozart, Wolfgang Amadeus</titlePart>
    <titlePart analog="marc:100$d">1756–1791</titlePart>
    <titlePart analog="marc:100$t">Sonaten</titlePart>
    <titlePart analog="marc:100$m">Violine</titlePart>
    <titlePart analog="marc:100$m">Klavier</titlePart>
    <titlePart analog="marc:100$n">KV 379</titlePart>
    <titlePart analog="marc:100$r">G-Dur</titlePart>
  </title>
  <title analog="marc:430" type="main">Klaviersonate G-Dur</title>
  <respStmt analog="marc:500">
    <resp analog="marc:500$4" auth="MARC List of Relator Terms" 
auth.uri="http://id.loc.gov/vocabulary/relators/" codedval="cmp"/>
    <persName analog="marc:500$a" auth="GND" auth.uri="http://d-nb.info/gnd/"
codedval="118584596">Mozart, Wolfgang Amadeus</persName>
  </respStmt>
</titleStmt>
```
For roles beyond the primary ones enumerated for `<titleStmt>`, use `<contributor>` with a `@role` attribute.  Of course, there's no need for `@role` on `<composer>` and the like, since the elements themselves map directly to the MARC List of Relator Terms.  This also simplifies the encoding.

**Comment by kepper** [comment]
I might be willing to follow that direction, but I'd like to hear some arguments about the relation of `<titlePage>` and `<resptStmt>` before that. The other thing related to this is a clarification of the use of `<source>` both in the sense of FRBR, that is, as the printed / manuscript / … thing that witnesses "a work", and in the older MEI (and TEI) sense of the material that the current encoding is based on (which is the reason why it lives in `<fileDesc>`). These things are often the same, but sometimes they're not, and I wonder if and how we should clarify this double purpose.

**Comment by pe-ro** [comment]
`<titlePage>` appears within `<front>` as part of the data of a music document.  But a title page transcription can also be part of the metadata, esp. in thematic/work catalogs, so `<titlePage>` is also allowed within the metadata header.  `<titlePage>` contains `<respStmt>`, `<title>`, and a lot of other elements that may also be present within the metadata.

`<respStmt>` holds information about those who are responsible for the creation of the intellectual content of the material being described.  It is allowed within `<titlePage>` to encode that info in the context of the title page, as well as in `<titleStmt>` to encode that info in the metadata context.

In short, the element names are the same, but the contexts (data and metadata) are different.

Indeed, a "source" and a "witness" are different things and I agree that we should think about how this difference can be encoded.  One approach is to add `<witList>` (within `<work>`), containing `<witness>` children with the same content model as `<source>`.  In addition, the `<source>` element can be modified to allow it to either 1) contain a bibliographic description (for non-FRBR uses) or 2) to point to a full description in a `<witness>` element.  This would make it possible to describe all witnesses and then mark sources as items in that set.  Alternatively, one could continue to record only the sources used by the encoding (as is current practice).  As is often the case, "mixing and matching" of these alternatives is possible, but not recommended.

**Comment by bwbohl** [comment]
# general notes

1. this ticket addresses multiple sub issues we might want to split into several issues at some point
2. I see nothing wrong with coming from the cataloguing practice, that's what brought FRBR down to us in the first place, right?

# `titlePage`

allowed in 

   **physDesc** (MEI.header) contained by `item` (frbr:item)  and `source` (frbr:manifestation vs. "chief source of information"): titlePage as metadata of a frbr:entity

 **front** (MEI.text) titlePage as content of a frbr:entity, see 1. (above)

## Some additions to the above 

1. As @pe-ro pointed out, the `titlePage` element may be child of `body/front` and this brings yet another aspect to this discussion: a potential difference in semantics of elements with respect to their context. I would like to see this moved to another issue and concentrate this issue on the `meiHead` which fairly is still too big to take on in one ;-)

2. `titlePage` does **not** allow `respStmt` as child but `titleStmt` (which then allows `respStmt` as child)

3. found a huge mistake in the tag-library v3.0.0 (http://music-encoding.org/documentation/3.0.0/titlePage/) see #485

##  `titleStmt` in `titlePage`

If I'm not mistaken `titlePage` allows all the content `titleStmt` allows, except `respStmt` (see also 2.), but adds a couple of other elements. So why not remove `titleStmt` and add `respStmt` in order to make `titlePage` an extended content model of `titleStmt`'s content model.


N.B. this is my first two cents, rest will follow…

**Comment by pe-ro** [comment]
@bwbohl, thanks for the suggestion. `<titleStmt>` is allowed in `<titlePage>` as a container for multiple titles that may appear there.  This is the same function it has in `<fileDesc>` and other locations.  Therefore, I'm inclined to leave keep it in `<titlePage>`. 

The 2nd half of your proposal is appealing, though.  `<respStmt>` can be used in `<titlePage>` the same way it functions elsewhere; that is, as a wrapper for responsibility info.  It won't exactly make the model of `<titlePage>` an extended version of `<titleStmt>` -- `<titlePage>` is already way too complex for that -- but it will move it in that direction.

**Comment by pe-ro** [comment]
Actually, it may be beneficial in the long-run to hew more closely to TEI on the matter of `<titlePage>` and disallow `<titleStmt>` and `<respStmt>` in `<titlePage>`.  This will create a clearer distinction between the metadata context (where `<titleStmt>` and `<respStmt>` should be used) and the title page transcription context (where they are not).
