### ISSUE TITLE
tag-library error concerning titlePage

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#485]
According to the tag-library v3.0.0 at http://music-encoding.org/documentation/3.0.0/titlePage/ titlePage is contained by some elements which do not list it vice versa and/or where the schema doesn't allow titlePage to appear:

**MEI.header**
 * captureMode
* carrierForm
* condition
* dimensions
* exhibHist
* fileChar
* fingerprint
* handList
* inscription
* perfDuration
* physMedium
* plateNum
* playingSpeed
* scoreFormat
* soundChan
* specRepro
* trackConfig
* treatHist
* treatSched
* watermark

**MEI.shared**
* extent
* titlePage

**MEI.text**
* back

**Comment by pe-ro** [comment]
There are a number of errors in the tag library, all caused by the style sheet that's used to create it.  Once that style sheet is corrected, all the errors of this sort should go away.

**Comment by pe-ro** [comment]
See #454

**Comment by pe-ro** [comment]
Looks like this is fixed in the development version of the Guidelines.
