### ISSUE TITLE
Add @music.size to staffDef

### ISSUE THREAD

**Issue by donbyrd** [music-encoding/music-encoding#486]
@music.size is currently available on the scoreDef element but not staffDef. It'd very likely be useful on staffDef too, e.g., for mensural notation, where different staves might have very different features, and it should be added to staffDef.

**Comment by pe-ro** [comment]
I think I see the need for this in a theoretical sense, but I'm not certain about the practicality of it.  For instance, how can the content of staves with different music font sizes be aligned horizontally?

**Comment by donbyrd** [comment]
Aligning staves with different music font sizes isn't very different from aligning staves the same font size but different space requirements because of (say) one having 16th notes while the other has quarters. In either case, the space you allocate for each Alignment (as Verovio calls them) is the maximum any staff needs; you just have to do that in units that are independent of the size of any staff or font, for example 10ths of a point or thousands of an inch.

**Comment by pe-ro** [comment]
I have no objections to your suggestion, but @lpugin, what say you?

**Comment by lpugin** [comment]
I would say that if it is on `scoreDef` it makes sense to have it on `staffDef`. However, I think we should maybe rethink all these as styling, and try to group all of them in one, more explicit, place.

I already told @donbyrd that for me it makes more sense to use another font when the size looks different, but if changing the size needs to be done without changing the font then `@music.size` seems to be the right attribute at this stage.

**Comment by pe-ro** [comment]
Yeah, eventually we'll get around to a comprehensive approach to styling.  I'll add it for now to address any use cases that arise before then.  It will also help us keep track of the various things that need to be dealt with by a styling "language".
