### ISSUE TITLE
Provide better description of manuscript material

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#489]
The attached ODD file describes a new MEI.msdesc module, as well as a few changes to existing MEI features, to better accommodate the capture of more physical details of manuscript material.  

The most significant change is in the handling of components of a resource; i.e., in the elimination of `<itemList>` and changes to the content model of `<componentGrp>` to allow it to replace `<itemList>` and handle the special relationships between manuscript components.  For example, manuscripts sometimes contain fragments of other, unrelated material.  Conversely, part of the manuscript being described may be located elsewhere.

[msDesc_PROPOSAL.odd.txt](https://github.com/music-encoding/music-encoding/files/1524945/msDesc_PROPOSAL.odd.txt)

**Comment by pe-ro** [comment]
Here's the latest version of the proposal to enhance the description of manuscripts.

[msDesc_PROPOSAL.odd.txt](https://github.com/music-encoding/music-encoding/files/1569381/msDesc_PROPOSAL.odd.txt)

Highlights:

1. Backward-compatible changes:

- New administrative elements
- New descriptive elements that may appear within physDesc and/or physMedium
- New elements that may appear inline when MEI.msdesc is activated
- Make dimensions and extent available inline with or without msDesc activation
- Make dimensions member of att.evidence
- Make fingerprint and watermark available inline when the msDesc module is activated
- Restrict use of some inline elements to the metadata header
- Modify physMedium to accommodate more detailed description (for manuscripts and other materials)
- Add an attribute class for subordinate component type that provides a "short cut" for expressing the relationship between the component and its host item
- Add an attribute class for record type
- Make source a member of att.componentType and att.recordType
- Allow creation within source
- Revise description and remarks for contents element
- Make creation, provenance, relation, and resp members of att.datable
- Extend content model of provenance
- Revise constraint on relation within a bibliographic description

2. Backward-incompatible changes:

- Move componentGrp to MEI.header module, rename it to componentList, and modify its explanatory remarks
- Modify physLoc to group historical info within <history>
- Make provenance a child of history; modify its description and comments regarding history to make clear the distinction between it and the creation element

This proposal borrows heavily from TEI, but incorporates the borrowings into the existing MEI framework.

Comments and questions eagerly sought.  😀

**Comment by axgeertinger** [comment]
Hi Perry
I do have a few comments or questions. I'm definitely not an ODD expert (though an odd expert maybe...), but if I understand the latest ODD version correctly, you are dismissing the change regarding the elimination of itemList, right? If so, I am happy :-) Otherwise we would have constructs like source/componentList/item and possibly even have `<item>` and `<source>` siblings within `<componentList>`. `<itemList>` is also needed to describe items that are not components.  What confuses me is that the description of `<componentList>` in the ODD still says "Manifestations; i.e., sources, may have either `<source>` or `<item>` components as required to accommodate composite sources (those containing multiple sources) or multi-part sources (those made up of several physical items" – but I guess that that's just a mistake.

**Comment by axgeertinger** [comment]
Considering that it breaks compatibility, I'm not sure I see the benefit of moving `<provenance>` to `<history>`. Provenance is relevant only in the context of an item (or source, if FRBR is not used), so we would need to introduce new schematron rules to prevent it from being used in work and expression contexts. The same is true with the proposed `<acquisition>` element. Why not just add `<acquisition>` to `<physLoc>`, i.e., as a sibling to `<provenance>`? 
The guidelines say that `<physLoc>` "Groups information about the current physical location of a bibliographic item, such as the repository in which it is located and its shelf mark(s), and its previous locations." Introducing `<history>` in this context might suggest that we expect users to write about the history of the libraries and archives, which is probably not what you intend. It goes without saying that provenance and acquisition are describing historical events; I don't think we need to make that explicit by adding a `<history>` wrapper.

**Comment by axgeertinger** [comment]
And a question: does the introduction of the msdesc module take into account considerations about implementing the FRBR manifestation singleton? How do these two issues relate to each other? Since I missed the Mainz workshop, I'd like to hear what @kepper and @KristinaRichts have to say about it.

**Comment by axgeertinger** [comment]
Sorry... another one: Why is it important to rename `<componentGrp>` to `<componentList>`? I remember us having a discussion about the distinction between lists and groups. Please allow me to quote a mail from you, Perry: 

> In my mind, <...List> implies a list, ordered or unordered, of *like or unlike* things, while <...Grp> means a group, ordered or unordered, of *like* things.

I'd say componentGrp is the right name from that perspective, so why not keep it? 
I see now that I happen to object against all the changes breaking compatibility, but that's actually not my primary concern; breaking it is all right if the changes are important or if they mean substantial improvements. I just don't see that need in these cases. (In practice, I don't consider moving componentGrp to the MEI.header module as breaking compatibility, though theoretically it may be)

**Comment by pe-ro** [comment]
@axgeertinger, thanks for the comments and questions.  I'll try to answer them in order.

re: `<itemList>`, it is retained.  Originally I thought that its function could be taken over by `<componentList>`, but that proved unwieldy.  The documentation is (always) lagging behind.  `<sigh/>`  I welcome any suggestions for its improvement.

re: `<componentList>`, it can contain zero-or-more work elements OR zero-or-more expression elements OR zero-or-more source elements OR zero-or-more item elements.  Also, the Schematron rule that forces work/componentList to contain only work elements and expression/componentList to contain only expression elements, and so on, has been left in place.  So, the unruly mixtures that you mention aren't possible.

re: `<history>`, I initially did just as you suggest; that is, add `<acquisition>` and `<provenance>` directly to `<source>` and `<item>`, but I settled on placing them inside `<history>` to make the description of manuscript/non-print material TEI compliant or at least minimize the changes necessary to drop a TEI conformant description into MEI.  You're right to say that `<acquisition>` and `<provenance>` are only applicable in the context of `<source>` and `<item>`, and we could control this with Schematron, but I also trust that users would be aware of this and not abuse `physLoc/history/acquisition` to write a history of histories of libraries. 😀  On the other hand, I'm not averse to allowing `<acquisition>` and `<provenance>` only inside `<source>` and `<item>`.

re: FRBR singleton, the changes in this proposal, along with those planned for #478, are intended to deal with the "mash up" of manifestation and item within `<source>`, otherwise known as a "singleton".  The creation of a new hierarchical structure, a `<singleton>` element for example, would introduce a huge amount of unnecessary complexity, IMO.  This would be detrimental with regard to the hope that non-librarian, non-cataloger users will embrace the metadata capabilities of MEI.

re: renaming `<componentGrp>` to `<componentList>`, I wouldn't say it's "important", but it would make the grouping of components consistent with the grouping of other entities.  Why `<expressionList>` and `<itemList>`, and now `<sourceList>`, but not `<componentList>`?  As for what I may have said in the past, I reserve the right to be inconsistent (tm).  And sometimes I'm wrong.  I look at this change as a correction of my previous `<sic>mistrake</sic>`. 😀  Immortalizing my error is itself an error.

Moving `<componentList>` to MEI.header is necessary for the description of composite entities, especially manuscripts and other non-print material, in FRBR and non-FRBR description "modes".

**Comment by axgeertinger** [comment]
@pe-ro, I agree that introducing a singleton alternative to the existing elements `<source>` and `<item>` would make things very complicated, not least in terms of data interchange. I am still curious to know whether this was discussed in Mainz and what conclusions were drawn, though.

**Comment by axgeertinger** [comment]
re: `<acquisition>` and `<provenance>`, I see it may be desirable to replicate the corresponding TEI structure to some degree. But the elements would have to be renamed anyway during the process, and simply moving these two from `tei:msDesc/history` to `mei:physLoc` on the way would not be problematic. My point is that the naming of elements already implies a semantic difference between TEI and MEI. `mei:physLoc` for the description of an item's location corresponds to `tei:msIdentifer`. While the name `msIdentifier` does not suggest that it should also contain the history of the item's whereabouts, `physLoc` does (to me).

**Comment by pe-ro** [comment]
Since I wasn't able to be in Mainz, I don't know what discussion took place regarding a FRBR singleton.

**Comment by pe-ro** [comment]
re: `<acquisition>` and `<provenance>`, I agree that `mei:physLoc` is more-or-less equivalent to `tei:msIdentifier`.

`<physLoc>` may contain `<history>`, which in turn contains `<div>`, and other text components.  The current proposal adds `<acquisition>` and `<provenance>` to the mix, treating them as additional block-level text components.  So, I think we're in agreement.  And I think this is better than allowing `<acquisition>` and `<provenance>` directly inside `<item>`.  The same holds true for `<source>`, especially in the case of a "singleton" described without using `<item>`.

As you've already pointed out, the presence of these elements within `<history>` in the `<work>` or `<expression>` context could be misleading.  But there are several remedies for that: 
1. Rely on encoder/cataloger judgment. It's difficult for me to see how the terms "acquisition" or "provenance" can be applied to work and expression, especially given the current definitions/descriptions of the `<acquisition>` and `<provenance>` elements;
2. Rely on enhanced best practices documentation that I hope will come out of the Cataloging IG; and
3. Provide a Schematron rule that disallows `<acquisition>` and `<provenance>` within these contexts.

**Comment by axgeertinger** [comment]
@pe-ro, I just noticed that in the ODD, the descriptions of the attributes on the new `<layout>` element are all identical. They all say 
`<desc>`Specifies the number of columns per page. A single number indicates that all
                pages have this number of columns. Two numbers mean that the number of columns per
                page varies between the values supplied.`</desc>`
 I'd be curious to know the difference between lines and staves, and ruled and written, respectively. Are lines just any non-staff lines, such as lines to guide the writing of text or graphical separators or ornaments? Does "written" mean hand-drawn without a ruler?

**Comment by pe-ro** [comment]
@axgeertinger, good catch!  The duplication is definitely an error.  The descriptions should read ---
```
<attList>
  <attDef ident="cols" usage="opt">
    <desc>Specifies the number of columns per page. A single number indicates that all pages have
      this number of columns. Two numbers mean that the number of columns per page varies between
      the values supplied.</desc>
    <datatype minOccurs="1" maxOccurs="2">
      <rng:data type="nonNegativeInteger"/>
    </datatype>
  </attDef>
  <attDef ident="ruledlines" usage="opt">
    <desc>Specifies the number of ruled text lines per column. A single number indicates that all columns have this number of ruled lines. Two numbers mean that the number of text lines per column varies between the values supplied.</desc>
    <datatype minOccurs="1" maxOccurs="2">
      <rng:data type="nonNegativeInteger"/>
    </datatype>
  </attDef>
  <attDef ident="writtenlines" usage="opt">
    <desc>Specifies the number of written text lines per column. A single number indicates that all columns have this number of written text lines. Two numbers mean that the number of text lines per column varies between the values supplied.</desc>
    <datatype minOccurs="1" maxOccurs="2">
      <rng:data type="nonNegativeInteger"/>
    </datatype>
  </attDef>
  <attDef ident="ruledstaves" usage="opt">
    <desc>Specifies the number of ruled staves per column. A single number indicates that all columns have this number of ruled staves. Two numbers mean that the number of ruled staves per column varies between the values supplied.</desc>
    <datatype minOccurs="1" maxOccurs="2">
      <rng:data type="nonNegativeInteger"/>
    </datatype>
  </attDef>
  <attDef ident="writtenstaves" usage="opt">
    <desc>Specifies the number of written staves per column. A single number indicates that all columns have this number of written staves. Two numbers mean that the number of written staves per column varies between the values supplied.</desc>
    <datatype minOccurs="1" maxOccurs="2">
      <rng:data type="nonNegativeInteger"/>
    </datatype>
  </attDef>
</attList>
```

The term "lines" was copied directly from TEI and means "lines of text". I added the attributes that refer to staves.

"Ruled lines" means guide lines for text, while "ruled staves" are for notation. "Ruled staves" includes staves hand-drawn or printed on the base medium prior to the writing of the notes, rests, etc.  "Written" in both cases means the number of lines/staves actually containing text or notation.  Different values for "ruled" and "written" indicates that not all the prepared lines/staves were actually used.

We'll probably need to describe this in more detail in a new section of the Guidelines devoted to manuscript notation.

**Comment by pe-ro** [comment]
Revised attribute descriptions [ba3e053]
