### ISSUE TITLE
<edition> in <editionStmt> as means of versioning

### ISSUE THREAD

**Issue by ndubo** [music-encoding/music-encoding#493]
Digital editions, like their printed counterparts, may have various editions (1st, 2nd, 3rd, etc.). The proper place for this kind of information seems to be the `<editionStmt>` and there specifically the `<edition>` tag. The options, however, within this tag do not really look appropriate. First of all, in the case of an electronic document, I would prefer speaking of 'version' (including a version number) rather than of a first or second edition. So at least a `<version>` as a child of `<edition>` may be desirable. In addition, the user should have the possibility to specify what kind of versioning is used (by using attributes such as `@authority` and `@authURI`, e.g. `authURI="semver.org"`). Under certain circumstances it may also be useful to be able to specify a '1st release' or an update (possibly by numeric means). 
One could argue that the place to do this is not the `<editionStmt>` but the `<revsionDesc>`. However, by what I see, the `<revisionDecs>` is not fit for the job either. And if the `<revisionDesc>`, instead of being a documentation of individual steps (`<change>`), becomes the release and version history of the file and the edition, the `<edition>` in the the `<editionStmt>` becomes obsolete.
If this issue has already been adressed or solved, you will surely let me know.

**Comment by pe-ro** [comment]
@ndubo, thanks for raising this issue.  I understand your concerns.

The description of `<edition>` is intended to "level the playing field" with regard to the terms used to describe the intellectual content of a publication: 
```
(edition designation) – A word or text phrase that indicates a difference in either 
content or form between the item being described and a related item previously 
issued by the same publisher/distributor (e.g. 2nd edition, version 2.0, etc.), or 
simultaneously issued by either the same publisher/distributor or another 
publisher/distributor (e.g. large print edition, British edition, etc.).
```
The word "version" is in the description, so I think it's pretty clear that the `<edition>` element doesn't just mean "edition".  It's simply the most convenient label for the concept of the new form of a previously- or simultaneously-released publication.  "v. 57.0.2.9.a" or "alpha release, 2017-12-15T11:32:51+01:00" are legitimate content, as is any human-readable string.

`<edition>` allows any text phrase-level element, including `<name>`, `<date>`, `<num>`, etc., but the most useful sub-element in this case is likely to be `<identifier>`, which can already take the attributes you suggest, `@auth` and `@auth.uri`:
```
<edition>
  <identifier auth.uri="samverg.org">version XYZ</identifier>
</edition>
```
I agree that `<revisionDesc>` is not the place for this kind of information.  This element is intended to be a record of modifications to the file, not its version or release history.  Changing this is a non-starter in the TEI/MEI universe.
