### ISSUE TITLE
Make <dynam> a member of att.extender, add new attribute to att.extender

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#495]
Some continuous dynamics, like "cres.", can have a (dashed) extender line.  Making `<dynam>` a member of att.extender would support markup like the following --
```
<dynam tstamp="1" tstamp2="2m+12" extender="true" lform="dashed" 
lwidth="0.75vu">cres.</dynam>
```
In addition, att.extender can be extended (pun absolutely intended) to include attributes to describe the number/frequency of dots, dashes, or waves for these types of extending lines, say `@lseg`.  A single value can be used to specify an exact number of dots, dashes, or waves, while two values can provide a range within which the renderer is free to choose a value.

**Comment by lpugin** [comment]
It would be useful to have this for `<dir>` too

**Comment by frakel** [comment]
just noticed that `@extender` is currently supported in `<dir>` only but not in `<dynam>` ?!?!
@pe-ro is this meant to be extended ;) also to `<dynam>`? ...would make the DME happy :)

**Comment by pe-ro** [comment]
@lpugin, an extender is already possible on `<dir>`.

@frakel, yes, the intention is to allow `@extender` on `<dynam>`.
