### ISSUE TITLE
Encoding a sharp meaning a natural (mensural notation)

### ISSUE THREAD

**Issue by davidrizo** [music-encoding/music-encoding#497]
Hi,

in mensural notation we usually find a sharp that cancels a previous flat, with the meaning of a natural.

E.g. in F Major key, if we find a #B it means natural flat.

Which is the correct encoding of it? I'm using:
`<note pname="b" oct="4" dur="minima">                                  
   <accid accid="s" accid.ges="n"/> 
 </note>
`
and
`<note pname="b" oct="4" dur="minima" accid="s" accid.ges="n"/>`
Thanks !!

**Comment by pe-ro** [comment]
You got it.
