### ISSUE TITLE
Visual augmentation dots

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#498]
These questions are related to issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/71

First, how would this example be encoded in MEI:

<img width="329" alt="screen shot 2018-02-12 at 6 13 42 am" src="https://user-images.githubusercontent.com/3487289/36100800-4f514488-0fbc-11e8-9048-e2ab9e83f911.png">

Representing a scribal error where the augmentation dots were omitted from the chord.  In other words, no cheating and using a `<space>`.

Related to this would be a scribal error where a single augmentation dot is missing:

<img width="337" alt="screen shot 2018-02-12 at 6 20 58 am" src="https://user-images.githubusercontent.com/3487289/36100916-b0aa3adc-0fbc-11e8-89d0-38ad0884a80f.png">

And here is the reverse problem, where augmentation dots are added when they are not needed:

<img width="334" alt="screen shot 2018-02-12 at 6 22 45 am" src="https://user-images.githubusercontent.com/3487289/36100994-f091ab62-0fbc-11e8-946b-d30acb69d65c.png">

Adding  a `<dot>` after the chord will add a single dot in verovio.  It seems a `<dot/>` child element of a `<note>` would work, but not yet implemented in verovio.

**Comment by pe-ro** [comment]
I wouldn't say it's cheating to use `<space>`, but it doesn't help to identify the error.

A scribal error is marked using `<sic>` --
```
<measure>
  <staff n="1">
    <layer>     
        <sic>
          <!-- Scribal error: missing augmentation dots -->
          <chord/>
        </sic>      
      <note/>
    </layer>
  </staff>
</measure>
```
If you want to provide a correction, use `<corr>` --
```
<measure>
  <staff n="1">
   <layer>
      <choice>
        <sic>
          <!-- Scribal error: missing augmentation dots -->
          <chord/>
        </sic>
        <corr>
          <!-- Correction: chord with augmentation dots -->
          <chord dots="1"/>
        </corr>
      </choice>
      <note/>
    </layer>
  </staff>
</measure>
```
While it isn't technically necessary, `<choice>` can be used to explicitly pair the `<sic>` and `<corr>`.  Also, you can use `<corr>` without a corresponding `<sic>` if you don't care about showing the error you're correcting.

For an augmentation dot missing on just one of the notes in a chord, move the `<sic>`/`<corr>` down to the appropriate place in the hierarchy --
```
<measure>
  <staff n="1">
    <layer>
      <chord>
        <note dur="4" dots="1"/>
        <note dur="4" dots="1"/>
        <choice>
          <sic>
            <!-- Scribal error: missing augmentation dot on single note in chord -->
            <note/>
          </sic>
          <corr>
            <note dur="4" dots="1"/>
          </corr>
        </choice>
      </chord>
    </layer>
  </staff>
</measure>
```
where the entire note is treated as an error, or --
```
<measure>
  <staff n="1">
    <layer>
      <chord>
        <note dur="4" dots="1"/>
        <note dur="4" dots="1"/>
        <note dur="4">
          <choice>
            <sic/>
            <corr>
              <dot/>
            </corr>
          </choice>
        </note>
      </chord>
    </layer>
  </staff>
</measure>
```
in which only the missing dot is considered to be an error.  In this example, it's not entirely obvious, but the empty `<sic/>` is used to mark something missing like what we've done with an empty `<rdg/>` paired with one with content to indicate that one source has material where the other doesn't.  A machine-readable indication of this use of `<sic>` can be encoded in `<tagsDecl>` like so --
```
<tagUsage name="sic" context="//mei:sic[not(child::* or text())]">
  <desc>An empty sic element indicates an omission.</desc>
</tagUsage>
```
Too many augmentation dots can be handled the same way as not enough dots --
```
<!-- Scribal error: unnecessary augmentation dots -->
<measure>
  <staff n="1">
    <layer>
      <choice>
        <sic>
          <chord dur="4" dots="1">
            <note/>
            <note/>
            <note/>
          </chord>
        </sic>
        <corr>
          <chord dur="4">
            <note/>
            <note/>
            <note/>
          </chord>
        </corr>
      </choice>
      <beam>
        <note dur="8"/>
        <note dur="8"/>
      </beam>
    </layer>
  </staff>
</measure>
```
MEI doesn't have a built-in mechanism for typing/classifying errors, but one can use `@type` (informal) and `@class` (formal) as ways to do this.

**Comment by pe-ro** [comment]
The leading slashes in the `<tagUsage>` example I gave before aren't necessary --
```
<tagUsage name="sic" context="mei:sic[not(child::* or text())]">
  <desc>An empty sic element indicates an omission.</desc>
</tagUsage>
```

```
<tagUsage name="sic" context="mei:sic[not(node())]">
  <desc>An empty sic element indicates an omission.</desc>
</tagUsage>
```
works too, but could be broken if a comment or processing instruction appeared within the `<sic>`.

**Comment by craigsapp** [comment]
Thanks!  That will be useful.
