### ISSUE TITLE
HTML code generation for documentation

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#502]
Here is a page listing accidental attributes which could use some adjustment of the HTML/CSS code:

http://music-encoding.org/documentation/3.0.0/data.ACCIDENTAL.EXPLICIT

<img width="1468" alt="screen shot 2018-02-25 at 7 03 34 pm" src="https://user-images.githubusercontent.com/3487289/36651593-7b2d1bb6-1a5e-11e8-8e0a-ab274acb15b9.png">

<img width="1468" alt="screen shot 2018-02-25 at 7 03 47 pm" src="https://user-images.githubusercontent.com/3487289/36651594-7dc88c0c-1a5e-11e8-9cb0-24fcb8be8838.png">

The "MEI Guidelines 3.0.0" navigation menu is getting mixed up with the main contents of the page.

**Comment by bwbohl** [comment]
Page moved resulting in the above link being dead. Please see: http://music-encoding.org/guidelines/v3/data-types/data.accidental.explicit.html

**Comment by lpugin** [comment]
Fixed

**Comment by lpugin** [comment]
Fixed: see http://music-encoding.org/guidelines/dev/data-types/data.accidental.written.html
