### ISSUE TITLE
Clarify meterSig sym / form and numbers

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#504]
See discussion in https://github.com/rism-ch/verovio/issues/800

Currently, the documentation says that `@sym` "Indicates the use of a meter symbol instead of a numeric meter signature". Howerver, in some cases displaying both can be desirable.

Also, `@form` deals with the visibility of the numbers, but not exclusively because the value "invis" indicates that the "Meter signature [is] not rendered" [entirely].

I would suggest to revise the description of `@sym` and remove the "instead of a numeric meter signature", and to add a value "symandnum" to `@form` for specifying that both the symbol and the numbers should be displayed. Then it remains up to the application to decide what to do if `@form` is not provided and both a symbol and some numbers are provided. I would expect it to display only the symbol but this is debatable and a Schematron rule could also be added.

**Comment by axgeertinger** [comment]
The question also applies to `@meter.rend` on `<scoreDef>` and `<staffDef>`, which is equivalent to `meterSig/@form`. This, by the way, raises a question of naming: should `@form` be renamed `@rend`? Or should `@meter.rend` be renamed `@meter.form`?

**Comment by lpugin** [comment]
I agree. Renaming `@form` to `@rend` sounds good to me. I am waiting for comments and will make a PR unless there are some objections.

**Comment by bwbohl** [comment]
I agree, that there's something at odds and with `meterSig/@meter.form` and in comparison with `scoreDef` resp. `staffDef` `@meter.rend`  it definitely should be renamed to `@meter.rend`, too!

Moreover I wonder whether `meterSig/@sym` could be `true/false` instead of `common/cut` as the type of symbol can be inferred from the actual meter? As with `@facs` and the glyph attributes the `meterSig` can point to source and intended rendition of the encoding.

**Comment by axgeertinger** [comment]
>Moreover I wonder whether `meterSig/@sym` could be `true/false` instead of `common/cut` as the type of symbol can be inferred from the actual meter?

I'm not sure I understand. How can you do that for certain? Especially if `@meter.unit` and `@meter.count` are not even provided (or only `@meter.count` for time signature like "3", for instance)?

**Comment by lpugin** [comment]
I do not think I understand either how `@meter.sym` could be changed to `true/false`.

**Comment by pe-ro** [comment]
I agree there's a naming problem with regard to `@meter.form` and `@meter.rend`.  I've been trying to move away from naming anything using "rend", since it's a loaded word, but it looks like I missed one.  So, I will rename `@meter.rend` to `@meter.form.`

With regard to the display of a (more-or-less) numeric form of the meter signature **and** a symbolic form, I think the best way forward is to use multiple `<meterSig>` elements, one for the numeric signature and one for the symbolic form --
```
<staffDef xml:id="P1" n="1" clef.shape="G" clef.line="2" lines="5">
  <label>Horns</label>
  <labelAbbr>Hns.</labelAbbr>
  <meterSig count="4" unit="4"/>
  <meterSig sym="common"/>
    ...
```
Of course, a renderer will have to decide how to display this -- significance of encoding order, spacing, etc.

**Comment by pe-ro** [comment]
@bwbohl, Like @lpugin and @axgeertinger, I don't understand how `@meter.sym` can be modified to use true/false values.

**Comment by lpugin** [comment]
I would expect a `<meterSigGrp>`. That is:
```xml
<staffDef xml:id="P1" n="1" clef.shape="G" clef.line="2" lines="5">
  <label>Horns</label>
  <labelAbbr>Hns.</labelAbbr>
  <meterSigGrp>
    <meterSig count="4" unit="4"/>
    <meterSig sym="common"/>
  </meterSigGrp>
  ...
```
Wouldn't you?

**Comment by pe-ro** [comment]
That could work too.  But, `<meterSigGrp>` requires `@func`, which currently only allows the following values:

- alternating
- interchanging
- mixed

What's the relationship between the meter signatures in this case?  Are they "duplicative"? Or "equivalent"?

**Comment by axgeertinger** [comment]
Suggesting the use of `<meterSigGrp>` was exactly my starting point for the discussion at [rism-ch/verovio#800](https://github.com/rism-ch/verovio/issues/800), so that's fine with me.  And I agree that we should add a `@func` value describing this situation. I'll leave it to the native English speakers to decide what to call it. Perhaps we even need two more values: "duplicative" or "equivalent" may be correct in the case of, say, C 4/4, where each of the the signature parts may be understood as describing the same meter. That is not the case, however, with C3 or the like, where the two parts (symbol and number)  are describing different aspects of the meter and need to be seen together as one, combined time signature.

**Comment by axgeertinger** [comment]
BTW, I notice that this issue is closed, but the initial issue is not resolved. `@meter.rend` has been renamed, but it's still not possible to encode the combined time signatures until we have suitable values for either `scoreDef/@meter.form` or `meterSigGrp/@func` or both.

**Comment by pe-ro** [comment]
I'm fine with re-opening the issue, but I think so-called "combined" time signatures will require a lot more thought and support for them should be delayed until v. 5.0.0.

**Comment by axgeertinger** [comment]
I may be naive, but how is this situation more complicated than mixed, interchanging or alternating meters? What are the problems to be thought about (other than terminology)?

**Comment by pe-ro** [comment]
```
Perhaps we even need two more values: "duplicative" or "equivalent" may be correct in 
the case of, say, C 4/4, where each of the the signature parts may be understood as 
describing the same meter. That is not the case, however, with C3 or the like, where the 
two parts (symbol and number) are describing different aspects of the meter and need 
to be seen together as one, combined time signature.
```
If by "combined time signature" you mean those cases where `<meterSigGrp>` contains multiple, *complete* meter signatures, I agree that what's required is a label for the case where the signatures are different expressions of a single concept of time.  If there are no objections, we can use the term "equivalent".

However, I don't think this extends to a mensuration sign such as "C3".  First, "C" and "3" are not complete meter signatures.  In addition, I maintain that "C3" (even taken together) is not a meter signature.  It specifies a concept of time (mensuration) that has a similar function, but is completely different from that of "metered" music notation (which has bar lines).

So far, MEI has maintained this semantic difference -- `<meterSig>` and `<meterSigGrp>` apply to barred notation, while `<mensur>` and `<proport>` apply to mensural notation -- to provide the ability to place these concepts in separate modules.  To modify this (to treat meter signatures and mensuration signs as a single concept; that is, subsume `<mensur>`, etc. within `<meterSig>`) will require significant changes to the MEI model, which in turn necessitates serious discussion.  Since there is some pressure to issue v. 4.0.0 soon, I don't think there's time to have that discussion.  Therefore, I suggest we table it until after the v. 4 release.

**Comment by rettinghaus** [comment]
>  First, "C" and "3" are not complete meter signatures.

I tend to disagree. These are *complete meter signatures*, and together they form a `<meterSigGrp>`. But in this combination they mean something different. Although they still apply to barred notation. They are *not* a mensur, they try to imitate the look of a mensur. So this is somewhat a "neomensural" notation. Perhaps a value "neomensural" for `@func` would do the trick?

**Comment by axgeertinger** [comment]
Here are some examples using both common time and numbers. The first one is from Bernardo Pasquini's "Il Lisimaco" (1681), the other one from Alessandro Scarlatti's "La principessa fedele" (1710). These are quite far from the mensural repertoire. In my collection of about 100 sinfonias from between 1680 and 1710, I found 15 instances of such meter signatures. I don't know of any pieces using the cut time symbol in this type of combination, but I have examples of the common time being used together with 3/8, 3/4, 3/2, 6/8, and 12/8 time as well as the "3" mentioned above.
![pasquini_lisimaco_1681](https://user-images.githubusercontent.com/3779074/39699264-aa65fb24-51f8-11e8-8017-c0fd98748348.png)
![scarlatti_principessa_fedele_1710](https://user-images.githubusercontent.com/3779074/39699268-adf15162-51f8-11e8-826e-961dcbd7691c.png)

**Comment by lpugin** [comment]
> I may be naive, but how is this situation more complicated than mixed, interchanging or alternating meters? What are the problems to be thought about (other than terminology)?

I think one additional issue than terminology is the clarification required with contradicting information. Usually, `meter.sym="common"` implies 4/4, which is a different `meter.count` and `meter.unit`. The later is critical because it needs to be unambiguous for timestamp calculation.

**Comment by axgeertinger** [comment]
I think a fairly consistent rule would be that `meter.sym="common"` is to be treated as 4/4 _unless_ there are `meter.count` and `meter.unit` values contradicting it, in which case the number values should be used for timestamp calculations. The simple "3" signature is tricky in any case as it does not explicitly state the meter unit. That is also true for the "C3" time signature, of course. I wonder if there is a general need to distinguish written meter (which may be ambiguous) from an interpreted meter used for calculations. Something like `meter.ges.count` and `meter.ges.unit` for values supplied for clarification, I mean.

**Comment by craigsapp** [comment]
> The later is critical because it needs to be unambiguous for timestamp calculation.

See issue #322

**Comment by pe-ro** [comment]
@axgeertinger, I have no doubt such things exist.  And perhaps there should be ways to render them.  However, we have to dig deeper and find out the intended meaning behind these particular "scribblings".  

In other words, what does the combination of "C" and "6/8" *mean*?  I suspect that in these examples the scribe wrote "C" at the start of every piece, (it does stand for "common", after all), not unlike pre-printed music paper now, but then wrote music in 6/8 or 12/8 and didn't cross out the "C".  "I don't know" is also a perfectly reasonable answer, and we can account for that if need be, but it's not an answer that can support the calculations necessary to render the notation; i.e., make layout decisions.  

In any case, before rushing into adding things like `meter.ges.count` and `meter.ges.unit` to rationalize nonsensical things, it would be better to examine what's already in place and make a few changes as possible.  I'd like to propose a few things --

1. move `@sym` and `@meter.sym` from meterSig.log and meterSigDefault.log to meterSig.vis and meterSigDefault.vis, respectively.  
2. revise `@form` and `@meter.form` (in meterSig.vis and meterSigDefault.vis, respectively) to account for more variations in how *individual* meter signatures are rendered.  For example, we may want to add "norm+sym", which would provide a way to render the combination of "6/8" and "cut-C" simultaneously.
3. revise `@func` in att.meterSigGrp.log to account for other types (including unknown) relationships between multiple time signatures.

The first change will allow us the opportunity (if we want to take it) to make `@meter.count` and `@meter.unit` required.  These values may be present the music or may be an interpretation, but in any case they encode values that are required for layout decision-making.  This won't change anything materially, only perhaps make it clearer that it's the numbers that are important, not the symbol.  While it's always been possible to write `count="6" unit="8" sym="cut"`, perhaps this will help separate the "signified" and "signifier(s)".

The second change will provide more hints regarding the rendering of various parts of a meter signature (or combinations thereof).

The third change opens up more possibilities for expressing relationships between multiple time signatures.

In practice, one could represent the combination of time signatures in your examples with something like 
`<meterSig count="6" unit="8" sym="common" form="norm+sym"/>` (or perhaps even `<meterSig count="6" unit="8" sym="common" form="sym+norm"/>` to capture the order of the meter signatures) or use 
```
<meterSigGrp func="unknown">
  <meterSig count="4" unit="4" sym="common"/>
  <meterSig count="6" unit="8"/>
</meterSigGrp>
```
(probably better).

Turning back to an earlier point in the discussion, I do not agree with @rettinghaus that "C" and "3" are different time signatures that taken together "mean something different".  The general rule in semantic modeling is, if it *means* something different, then it *is* something different.  "C" and "3" are different aspects of a *single time signature*.  "Cut-C" and "3" is a better example as it makes clear that the underlying meter (in modern terms) is "3/1" (which should go in `@count` and `@unit`), while the symbols are dealt with separately.

**Comment by pe-ro** [comment]
Based on our decisions about modern time signatures, we can undertake a similar approach to mensuration signs.

**Comment by axgeertinger** [comment]
@pe-ro, I am fine with the changes you suggest. I am as eager as you to grasp the _meaning_ of this notation, but I still don't know for sure. I am absolutely sure, however, that this use of meter symbols and numbers is not a mistake. Looking at the manuscripts, there is no doubt that these signatures are actually intended. But even though we may not be able to name their meaning, there is also no doubt as to how they should be treated computationally: The numbers always indicate the meaningful meter to be used for timestamps etc. Using this approach (giving priority to numbers over symbols) would enable software to resolve the apparent(!) conflict. 
For "C 6/8", I would prefer `<meterSig count="6" unit="8" sym="common" form="sym+norm"/>`, and using the rule of thumb that numbers are more important than symbols, rendering software can handle it safely.
Your preferred example using `<meterSigGrp>` would make it much harder for the software to decide how to treat the meter. The `count="4" unit="4"` in the description of a "C 6/8" meter only confuses things. I am pretty sure that the C (whatever it means exactly) does _not_ mean 4/4 in this case; it wouldn't make any sense. My guess is that it qualifies the 6/8 somehow as to tempo or "beats" – the "feeling" so to speak.
BTW, I guess the C standing for "common" was a joke... as far as I know it was derived from the tempus imperfectum symbol, and I also doubt that italian baroque composers knew the term "common time" ;-)

**Comment by pe-ro** [comment]
@axgeertinger, you're absolutely correct about "C" standing for "common time".  It's incredibly English-centric and anachronistic.  So, I suggest we change 
```
<macroSpec ident="data.METERSIGN" module="MEI" type="dt">
  <desc>Meter.sym attribute values for CMN.</desc>
  <content>
    <valList type="closed">
      <valItem ident="common">
        <desc>Common time; i.e. 4/4.</desc>
      </valItem>
      <valItem ident="cut">
        <desc>Cut time; i.e. 2/2.</desc>
      </valItem>
    </valList>
  </content>
</macroSpec>
```
 to 
```
<macroSpec ident="data.METERSIGN" module="MEI" type="dt">
  <desc>Meter.sym attribute values for CMN.</desc>
  <content>
    <valList type="closed">
      <valItem ident="C">
        <desc>Common time; i.e., 4/4.</desc>
      </valItem>
      <valItem ident="cut-C">
        <desc>Cut time; i.e., 2/2.</desc>
      </valItem>
    </valList>
  </content>
</macroSpec>
```
I leave it to others to replace `<desc>` in each case.

**Comment by pe-ro** [comment]
@axgeertinger, I also see your point about using `@count` and `@unit` in both `<meterSig>`  elements --
```
<meterSigGrp func="unknown">
  <meterSig count="4" unit="4" sym="common"/>
  <meterSig count="6" unit="8"/>
</meterSigGrp>
```
but this is the most descriptive method.  To indicate which `<meterSig>` element; that is, which count and unit values, is to be used for layout calculations, we could a new attribute to `<meterSigGrp>`.  For instance,
```
<meterSigGrp func="unknown" use="#preferMeter">
  <meterSig count="4" unit="4" sym="C"/>
  <meterSig count="6" unit="8" xml:id="preferMeter"/>
</meterSigGrp>
```
This makes it possible to encode the individual `<meterSig>` elements in the order in which they appear in the document and still select the "right" one.

Alternatively, we could add `@use` on `<meterSig>`, but allow it to occur only once via Schematron.  This would be valid --
```
<meterSigGrp func="unknown">
  <meterSig count="4" unit="4" sym="C"/>
  <meterSig count="6" unit="8" use="layout"/>
</meterSigGrp>
```
but this --
```
<meterSigGrp func="unknown">
  <meterSig count="4" unit="4" sym="C" use="layout"/>
  <meterSig count="6" unit="8" use="layout"/>
</meterSigGrp>
```
wouldn't be.

Another approach would be to eliminate `@sym` and rely on an internally-defined symbol (defined in <symbol> in the header) or an externally-defined taxonomy (like SMuFL) to indicate the non-preferred time signature --
```
<meterSig count="6" unit="8" altsym="myC"/>
<meterSig count="6" unit="8" glyph.auth="smufl" glyph.num="U+E08A"/>
```
Unfortunately, SMuFL doesn't provide pre-composed numeric time signatures, so it's not possible to do this the other way around using SMuFL --
```
<meterSig count="4" unit="4" glyph.auth="smufl" glyph.num="[no code point for 6/8]"/>
```
In addition, representing 2 time signatures in the document this way contradicts how one would do it for, say, alternating time signatures.  Therefore, I'm not in favor of this approach.

**Comment by lpugin** [comment]
Looking back at this discussion we actually have a [proposal](https://github.com/music-encoding/music-encoding/issues/504#issuecomment-387104919) pending. No objection have been raised, so unless there is one, I will make a PR with the suggested changes so we can finally close this issue.

**Comment by ahankinson** [comment]
No objection, but just flagging this that it might be good to examine the proposal in light of the similar discussions in the mensural group for visual / logical mensuration signs, just to see if there's an opportunity to make the behaviours consistent.

**Comment by pe-ro** [comment]
Absolutely !

**Comment by kepper** [comment]
pinging @lpugin and @pe-ro to resolve this

**Comment by ndubo** [comment]
@pe-ro  
> ... find out the intended meaning behind these particular "scribblings"

Without intention to interfer in the search for a practical solution, I just want to point out that it may be useful to have a look at Giovanni Maria Bononcini's _Musico prattico_ (1678):

![Bononcini_musico-pratico_p15extr](https://user-images.githubusercontent.com/33256891/194859169-95acae89-53f7-41d4-89d4-cf57d927c9bc.jpg)
In Bononcini's explanation that all compound meter signs use indeed mensuration signs in combination with modern time signatures. 
They all have a name (e.g. dupla sub superbiparzienteterza - a great name for a SMUFL code)
![Bononcini_musico-pratico_p26ext](https://user-images.githubusercontent.com/33256891/194861060-c765474e-cabe-4467-acfd-f3d5016f6077.jpg)

and they may have consequences for performances practice. That's why they should be retained. 
The full text is here [https://www.digitale-sammlungen.de/view/bsb10527062?page=1]

**Comment by pe-ro** [comment]
@ndubo, I believe each of the meter signatures in your example can be encoded using my proposal above. For example, the last one would be --
```
<meterSigGrp func="other">
  <meterSig count="4" unit="4" sym="C"/>
  <meterSig count="3" unit="8" use="layout"/>
</meterSigGrp>
```
Both meter signatures can be rendered -- the first using the symbol, the 2nd using numbers --  but the 2nd one is used for logical and layout purposes.  As I understand it, `@form` isn't necessary on the first `<meterSig>` to control visual display as a symbol takes precedence over the numeric values.  @lpugin may have something to add here, though. 

The `@type` attribute on `<meterSigGrp>` can be used to give a name to the group, e.g., "duplaSubSuperbiparzienteterza", if needed.  Of course, `@class` is also available if a more formal classification scheme is desired.

**Comment by lpugin** [comment]
> Both meter signatures can be rendered -- the first using the symbol, the 2nd using numbers -- but the 2nd one is used for logical and layout purposes.

Sounds good to me. I would only suggest another attribute name because the meter signature values are used not just for the visual layout. We we really want to encode is that the meter signature is the reference for time stamps. What about `@tstampRef="true"` ?

**Comment by pe-ro** [comment]
That's what the `@use` attribute is for.  Note my comment about "logical and layout purposes". In this case the name "use" is a verb.  The idea is indicate which time signature is the "real" one.  I'd be glad if you can suggest a value other than "layout". Perhaps "logical"?  This would change "use" from a verb to a noun,, which is probably a good thing.

**Comment by lpugin** [comment]
> That's what the `@use` attribute is for.

Sorry, I was not clear. Yes, I got that and was suggesting `@tstampRef` as another possible name for `@use`. `@use="logical"` is understandable, but the 'use' does not sound very MEI-like. Maybe `@role="primary"`, of simply `@reference="true"` to say that in the meter signature group, it should be used as a reference as if we would have only it?

**Comment by pe-ro** [comment]
Oh, sorry.  Your message was entirely clear.  It was I who mentally omitted the word "name" in "attribute name".

I'm not wedded to the name "use", but I like `@role` better than `@reference` or `@tstampRef`.  How about `@role="logical"`?  Alternatively, we could use `@logical` as the name but it could only ever take the value "true" or "logical".  This is a common practice in XML for attributes originally defined in SGML/HTML markup where the value wasn't necessary, just the name.

**Comment by craigsapp** [comment]
There is also complication of `<barLine>` versus `<measure>` in music from the 17th century (particularly when dealing with `@tstamps` for the ends of measures).   There can be a meter/time signature/mensuration sign, but the barlines may not always be visually present at the end of each "measure", or the barlines may even be placed in the middle of a measure (yet the meter is understood to continue such that there are multiple measures between two barlines, which could be interpreted as  `<measures>` with invisible barlines at their end, or measures with barlines in the middle of them):

From the introduction to the 1899 edition of the Fitzwilliam Virginal Book:

http://vmirror.imslp.org/files/imglnks/usimg/9/90/IMSLP178082-SIBLEY1802.18867.35cc-39087012336568vol._1.pdf#page=18
<img width="1198" alt="Screen Shot 2022-10-10 at 7 04 11 AM" src="https://user-images.githubusercontent.com/3487289/194884504-ff2049cd-b9dd-46fd-a61a-ec30e0975e91.png">

Music cited above:

https://vmirror.imslp.org/files/imglnks/usimg/8/83/IMSLP178083-SIBLEY1802.18867.c7f2-39087012336584vol._2.pdf#page=365

<img width="789" alt="Screen Shot 2022-10-10 at 7 10 09 AM" src="https://user-images.githubusercontent.com/3487289/194886047-25f01f6d-2dfd-4b9e-bd58-748570e98ea5.png">

The `2` in measure "4" is the second repetition of the ground, which is starting at the beginning of a measure, but there is no barline, and the previous barline is probably not at the start of a measure (which might be intended to be a breve duration).
