### ISSUE TITLE
Typo in note element documentation

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#505]
On the page:

http://music-encoding.org/documentation/3.0.0/note

The description of articulations discusses the `<fingering>` element:

<img width="823" alt="screen shot 2018-03-13 at 8 53 53 am" src="https://user-images.githubusercontent.com/3487289/37353000-aa3143da-269b-11e8-94dd-81915b4faa8d.png">

But this should instead be the `<fing>` element:

http://music-encoding.org/documentation/3.0.0/fing

**Comment by lpugin** [comment]
Fixed http://music-encoding.org/guidelines/dev/elements/note.html
