### ISSUE TITLE
orphaned neume data types

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#512]
If I'm not mistaken, the revision of `<ineume>` and `<uneume>` left the following data types unused: 
`data.INEUMEFORM`
`data.INEUMENAME`
`data.UNEUMEFORM`
`data.UNEUMENAME`

Refer to:
http://music-encoding.org/guidelines/dev/data-types/data.ineumeform.html
http://music-encoding.org/guidelines/dev/data-types/data.ineumename.html
http://music-encoding.org/guidelines/dev/data-types/data.uneumeform.html
http://music-encoding.org/guidelines/dev/data-types/data.uneumename.html

We should make shure, that all available data types are used somewhere!

**Comment by pe-ro** [comment]
"We should make shure, that all available data types are used somewhere!"

I'm not 100% convinced of this.  Some data types are not used currently, but are made available for use in future customizations.

**Comment by pe-ro** [comment]
Closing this for now.
