### ISSUE TITLE
Has meter.unit to be a decimal?

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#515]
The Guidelines say `@meter.unit` has to be a `Value of datatype decimal.` 
Can somebody enlighten me, please? I thought it has to be a power of 2.

**Comment by pe-ro** [comment]
"There are more things in heaven and Earth, Horatio, / Than are dreamt of in your philosophy."

Have a look at https://en.wikipedia.org/wiki/Time_signature#Irrational_meters for info on so-called "irrational" meters.  They are extremely uncommon, but if someone has used them, I think it's important that MEI make an effort to support them.

**Comment by rettinghaus** [comment]
You live and learn! But all the examples shown there have a positive integer as unit. Only exception is the strange "pi over e" example given, but not only that "e" is no decimal value, in such cases you'd probably prefer `@altsym`. 
On the other hand `@meter.count` allows additive values, but not fractional values, or even roots, as seen there.

**Comment by pe-ro** [comment]
It seems to me that there's a line somewhere (although it's difficult to be sure exactly where to draw it) between "useful" time signatures and "speculative" ones.  My definition of "useful" is something that can be used to meaningfully measure time, while "speculative" time signatures are extensions of the concept of Augenmusik -- they look nice, but can't be used for any kind of calculation.

You're right -- at some point, one must resort to `@altsym`.  The question is, how far can we go before taking that escape hatch?

As a starting point, I decided to allow decimal values in both `@meter.count` and `@meter.unit`.  Fractional values in either one must be expressed using decimal equivalents, e.g. 1/2 = .5, etc.  Of course, this makes irrational fractions, such as 1/3, difficult to deal with.  But, this is why `@meter.count` is defined using the string data type.  We could allow actual fractions by modifying the regex that defines the parameter in the definition of `@meter.count`.  Going much beyond fractions means we'd have to allow virtually any string, a process in which we lose all control.  That's going too far for very little gain, in my opinion.  This is where "official" MEI must stop and purpose-built schemas take over.

The intent is the same for `@meter.unit` -- decimal values (including fractional equivalents) and integer values (as a subset of decimal values) are "officially" supported.  Beyond that, developers are "on their own".

**Comment by craigsapp** [comment]
In the Josquin Research Project encodings, I occasionally use `@meter.unit` of a triplet whole note.

**Comment by rettinghaus** [comment]
IMHO pure MEI should allow only positive integers for `@meter.unit` and leave the rest to `@altsym` or customization.

**Comment by pe-ro** [comment]
@rettinghaus, if by "pure MEI" you mean "MEI Basic", then I agree.  I'm less certain about such restriction for mei-all.  In any case, I'm closing this for now.  It can be re-opened when necessary.
