### ISSUE TITLE
Suppressing courtesy clef/key changes at ends of systems

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#516]
In this example music:

<img width="1039" alt="screen shot 2018-05-07 at 10 29 56 am" src="https://user-images.githubusercontent.com/3487289/39715310-ba55a866-51e1-11e8-87a0-8968a58ca159.png">

I would like to suppress the courtesy time signature change at the end of the system after the double barline.

Should there be an attribute created for barline/measure that serves as a print suggestion to not print any courtesy clef/time/key change?  Should this be a style control in the MEI header? or should this be a external option provided to the rendering software?

This is a the end of a musical section (notice the terminal longs in that measure) which ends with a double barline.  The next measure is the start of a new section, so it is not necessary to warn the performer that a mensuration change is coming, since they are warned of the possibility by the double barline, and they have time to look ahead while holding the long note.

Should the sections of the music be encoded in `<section>`, and could that encoding imply to not add a courtesy time signature change?

These sections are similar to movements, but less so.  They are more like `<subsection>` rather than `<section>`.  Notice that the bar numbers do not reset to 1, for example.  Ideally these sections should end at a system break, as it does by here accidentally.

**Comment by rettinghaus** [comment]
I would structure it like 
```
<section>
  <section>
  </section>
  <section>
  </section>
</section>
```

Different movements should go into different `<mdiv>` elements. 

Didn't we had a discussion about courtesy time signatures before somewhere?

**Comment by craigsapp** [comment]
> Didn't we had a discussion about courtesy time signatures before somewhere?

I probably asked the same question a few years ago...

**Comment by pe-ro** [comment]
This is what `@meter.showchange` is intended to do; that is, display the old time signature when a new one is provided.  Unfortunately, the description of this attribute --
```Determines whether a new meter signature should be displayed when the meter signature changes.```
was garbled somewhere along the way.  It should read more like that of `@sig.showchange`; that is, 
```Determines whether the old time signature should be displayed at a change of time signature.```

**Comment by craigsapp** [comment]
In this case I want to force a display of the meter at the start of the next section even if it is the same as the previous section, so `@meter.showchange` would not work in this case, since the meter could be the same across sections (but maybe it would need to be `@mensur.showchange` here?)

Notice the redundant clefs, which I need to work on removing:

<img width="235" alt="screen shot 2018-05-07 at 11 08 28 am" src="https://user-images.githubusercontent.com/3487289/39717009-d7f39b12-51e6-11e8-99af-a8b47bfe31d3.png">

In this case I want to suppress them (which I can easily do by not adding them to the data).  But I don't see a `@clef.showchange` in the staffDef attribute list:

http://music-encoding.org/guidelines/v3/elements/staffdef.html

**Comment by pe-ro** [comment]
1. I've always assumed, perhaps incorrectly, that a meter signature or indication of mensuration, would be displayed whenever it was encoded, *even if it were the same as the previous one*.

2. You're probably right -- there ought to be a `@mensur.showchange` attribute, along with any other parallel attributes.

3. Right again, there's no `@clef.showchange`, but doesn't the same rule apply as to item 1?  That is, the act of encoding a clef means you want it displayed.  If you don't want to display it, don't include it.  :grinning:

**Comment by ahankinson** [comment]
Closing because it's marked "Won't Fix."
