### ISSUE TITLE
Harmonize key.sig et al. attributes on scoreDef, staffDef, key and keySig

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#525]
Since `staffDef@key.sig.showchange` is changing to `staffDef@keysig.showchange` in MEI 4, it is probably best to change `staffDef@key.sig` to `staffDef@keysig` for consistency.

There are `<key>` and `<keySig>` elements:

http://music-encoding.org/guidelines/v3/elements/key.html
http://music-encoding.org/guidelines/v3/elements/keysig.html

`<key>` should be used for analytical purposes, and `<keySig>` should be for print purposes, so it is best that `staffDef@key.sig.showchange` is changed to `staffDef@keysig.showChange` since it refers to the printed key signature.  Likewise `staffDef@key.sig` should change to `staffDef@keysig` for the same reason.

`<keySig>` has `@sig.showchange`.  Perhaps this should be changed to `@showchange` to also maintain a uniform style?

http://music-encoding.org/guidelines/v3/elements/keysig.html

**Comment by rettinghaus** [comment]
Do you mean to use `@keysig` `@keypname` `@keyaccid` `@keymode` etc on `staffDef`, or `@keysig.sig` `@keysig.pname` `@keysig.accid` `@keysig.mode`? 
(Only) the latter would make some sense, as they are shorthands for `keySig@pname` etc.

**Comment by ahankinson** [comment]
I've reverted the commit and re-opened this issue for discussion.

**Comment by lpugin** [comment]
I guess this change was motivated by another one, namely `@key.sig.showchange` to `@keysig.showchange` and `@key.sig.show` to `@keysig.show`. Maybe these should be reverted as well?

**Comment by craigsapp** [comment]
There are two elements to keep in mind:

(1) `<key>` "Key captures information about tonal center and mode."
http://music-encoding.org/guidelines/v3/elements/key.html
"This element is used exclusively within bibliographic descriptions. Do not confuse this element with keySig, which is used within the body of an MEI file to record this data."

(2) `<keySig>` "Written key signature."
http://music-encoding.org/guidelines/v3/elements/keysig.html

`<key>` is for bibliographic/analytic purposes, while `<keySig>` is for music-notation purposes.  In other words, they have separate purposes, and any attributes related to them should be labeled properly.  The attributes of elements that use `@key.*` and `@keysig.*` should reflect these different functions.  If the functions are confused in the attribute names, then the attribute names should be fixed (and citing backward compatibility would not be valid poorly named attributes).

For example,  `@key.sig.showchange` does not really make sense if its name is supposed to reflect an analogous element name: It is a request to show a cancellation signature for a "key signature of the key" in the music, when instead `@keysig.showchange` makes more sense since it is a request to show a cancellation signature for a "key signature" in the music.  So I would support that particular attribute name change.

> Do you mean to use `@keysig` `@keypname` `@keyaccid` `@keymode` etc on staffDef, or `@keysig.sig` `@keysig.pname` `@keysig.accid` `@keysig.mode`?
(Only) the latter would make some sense, as they are shorthands for `keySig@pname` etc.

Yes, the latter.

Although `@keysig.sig ` and `keysig@sig` are problemmatic attribute names.  These would best be called  `@keysig.fifths` and `keysig@fifths`.  They currently mean the "signature of the key signature", while "[circle-of-]fifths of the key signature" makes more sense.

**Comment by pe-ro** [comment]
Once upon a time, I tried to make this change (to *.fifths) and nearly got run out of town on a rail.  :grinning: 

The names of the key* attributes are just names, which I'm happy to change to support a more logical system of naming.  But, creating a logical system and maintaining backward compatibility are nearly diametrically opposed.

**Comment by craigsapp** [comment]
> But, creating a logical system and maintaining backward compatibility are nearly diametrically opposed.

😄 

I would expect that   `XXX@YYY.ZZZ` (attribute viewpoint), would expand to the element viewpoint as `XXX/YYY@ZZZ`.  

If the dot character (`.`) does not imply that sort of transformation, then there is no great problem with the names, since `key.` would not imply `<key>` rather than `<keysig>`.  In that case `staffDef@key.sig.showchange` should probably not be changed to `staffDef@keysig.showchange`, since there is no great need for such a change.  If it is changed, then all cases of `@key.sig.*` should be changed to `@keysig.*`, since it would be confusing to have some cases where an attribute is called `key.sig` and others where it is `keysig`.

For `note@accid` the expansion is to `note/accid@accid`, which would be a special case, but still consistent.

For `note@accid.ges`, the expansion is to `note/accid@accid.ges`.  To be systemmatic with an element/attribute equivalence, it should expand to `note/accid@ges`.

**Comment by lpugin** [comment]
(@pe-ro  If I remember correctly the change on *.fifths was another issue.)

The desired consistency helps to understand the schema. I do not see backward compatibility as a problem here because 1) we have a major version release, and we should take the opportunity to do it, and 2) they are easy upgrades. So if the changes (now reverted) trigger other ones, let's just go for them.

**Comment by pe-ro** [comment]
@lpugin, I agree that now is the time to do it, if we're going to make changes.

The naming of the key- and key signature-related attributes has grown organically, leading to some inconsistency.  `@key` was created first and `@key.sig` came after.  The latter was named to emphasize the dependency on `@key`.  At this time, though, I think it makes sense to emphasize the distinction between key and key signature; i.e., use names like 'keysig', 'keysig.show', and 'keysig.showchange' on `<scoreDef>` and `<staffDef>`, and 'sig', 'show', and 'showchange' on `<keySig>`.

The '.ges' "extension" is a slightly different animal.  Changing that would lead to other, probably worse inconsistencies.  So, I think we should leave that alone, at least for the time being.

**Comment by craigsapp** [comment]
That sounds good

**Comment by ahankinson** [comment]
OK, so next steps? Do we merge the original PR? @rettinghaus are you satisfied?

**Comment by pe-ro** [comment]
There wasn't a PR, was there?  There were only the changes I committed directly.

**Comment by ahankinson** [comment]
Ok. Let’s wait to see what @rettinghaus says before proceeding.

**Comment by craigsapp** [comment]
> The '.ges' "extension" is a slightly different animal. Changing that would lead to other, probably worse inconsistencies. So, I think we should leave that alone, at least for the time being.

An interesting potential change in the future is to rename `note@accid` to `note@accid.vis`, and this would map to the element `accid@vis`.  This would be parallel to `note@accid.ges` which could map to the element `accid@ges`.

**Comment by ahankinson** [comment]
The creation of bare vis and ges attributes is a pretty significant change with wide ranging effects. accid.ges is not the only gestural attribute on an element so you would only be able to encode a single (implicit) visual or gestural parameter.

I'm a strong -1 on that, @craigsapp

**Comment by ahankinson** [comment]
Pinging @rettinghaus

**Comment by rettinghaus** [comment]
Sorry for being late. 
As `<keySig>` has `@visible` there's basically no need for `@sig.showchange`. 
Then `@keysig.show` and `@keysig.showchange` on `staffDef` would serve a special function, which could justify a different naming, i.e. leave the rest as it is. 
However, if we want to take the step in renaming `@key.xxx` into `@keysig.xxx` we should also rename `keySig@key` into `keySig@fifths` to clear things up. (`@fifths` could even allow integer values.) 
I'm (as you may have guessed) for the latter. And to drop `keySig@sig.showchange`, too.

**Comment by ahankinson** [comment]
`@visible` and `@sig.showchange` are (I think) two different functions. The first is whether it's visible; the second is whether to show the cautionary symbol should the change happen over a system break.

**Comment by rettinghaus** [comment]
@ahankinson yes, I understand. But that applies mainly to dynamic rendering and should be an `scoreDef` or `staffDef` option like `@mnum.visible`, `@multi.number` or even `<staffDef>/<labelAbbr>`. 
I don't think it makes much sense to mark/change it on every `keySig` in a complex score.

**Comment by lpugin** [comment]
We currently have:
* on staffDef / scoreDef
```
@key.accid
@key.mode
@key.pname
@key.sig
@key.sig.mixed
@key.sig.show
@key.sig.showchange
```
* on key
```
@accid
@mode
@pname
@sig
@sig.mixed
```
* on keySig
```
@accid
@mode
@pname
@sig
@sig.mixed
@sig.showchange
```
All the ones on staffDef / scoreDef that appears in both key and keySig are ambiguous. Also, it seems that `staffDef@key.sig` is often used for `keySig@sig`

**Comment by pe-ro** [comment]
At present in v. 4, we have -- 

- on `<scoreDef>` and `<staffDef>`:
```
key.pname
key.accid
key.mode
key.sig
keysig.show
keysig.showchange
```
- on `<key>`:
```
pname
accid
mode
```
- on `<keySig>`:
```
pname
accid
mode
sig
sig.showchange
visible
```
I think our targets should be --
- on `<scoreDef>` and `<staffDef>`:
```
key.pname
key.accid
key.mode
keysig (change from 'key.sig')
keysig.show
keysig.showchange
```
- on `<key>` (no changes):
```
pname
accid
mode
```
- on `<keySig>`:
```
key.pname
key.accid
key.mode
sig
sig.showchange
sig.show (changed from 'visible')
```
This proposal
- prefaces the analytical attributes with "key." on `<scoreDef>`, `<staffDef>`, and `<keySig>`;
- groups the attributes related to the key signature with "keysig." on `<scoreDef>` and `<staffDef>`;
- groups attributes related to the key signature with "sig." on `<keySig>`. Alternatively, we could drop the "sig." prefix here and use the names "sig", "showchange", and "show";
- replaces `@key.sig.mixed` and `sig.mixed` with a value of "mixed" for `@keysig` and `@sig`. The other values for `@keysig` and `@sig` will remain the same, e.g. "0", "2f", "2s", etc., but the datatype has been renamed to "data.KEYFIFTHS".  This is still valid as the number indicates the position of the key in the circle of fifths, while "f" and "s" record the direction.  Changing to signed integers is possible, but doesn't provide any more information.

Comments appreciated.

**Comment by pe-ro** [comment]
This issue didn't get fully resolved in v. 4.0, so I'm kicking it down the road to v. 5.0.

**Comment by bwbohl** [comment]
What I really do question though how `keySig/@visible`can actually make any sense with `<keySig>`being defined as "Written key signature"

**Comment by craigsapp** [comment]
> What I really do question though [is] how `keySig/@visible` can actually make any sense with `<keySig>` being defined as "Written key signature"

While `<keySig>` is for a written aspect of the music, it also functions as a logical element of the music, for example controlling the display or hiding of note accidentals. `@visible` is a way of making a visual element of the music also function as a logical element.  In cases where elements have the possibility of being both written and logical, there needs to be a `@visible` attribute for the element.

A practical use would be to encoded a missing key signature:   It should be there, but it is not (such as a key signature change in the middle of a line of music that was accidentally omitted).  This can be indicated with `<supplied>`, but that element does not control the visual aspect of the music: either the supplied key signature:

(1) should be displayed as a regular key signature
(2) be displayed in brackets (traditional graphical rendering to indicate "supplied")
(3) or be left invisible for diplomatic rendering

So it might make sense for the `<supplied>` element to control the visibility of elements (which it currently cannot) rather than controlling the visibility directly on the supplied element.

However, there may be other reasons for using `keySig@visible` besides being supplied.  Another example would be modern jazz/pop scores where the style of the notation is to give the key signature at the start of the music and then not to repeat it at the start of every line.  Of course, this is not exactly the same case since repeated key signatures are treated as an automatic feature of notation in MEI (and hence would be a style control).  But there may be cases where a musical excerpt of such music would be desired to include the key signature as well as keeping it invisible like the original source.

A third example is for user-interface applications: there may be a reason to hide the key signature in a notation editor.  If there is no functionality for hiding the key signature in MEI, then the interface program cannot use the MEI data structure directly, so it will have to translate to another data structure or need to alter the XML structure of the MEI data either formally or informally to add that functionality.

**Comment by pe-ro** [comment]
Are there any remaining problems with my last suggestion?  If not, then the changes listed there can be implemented.  If not, please speak up.

**Comment by bwbohl** [comment]
@pe-ro, generally, I'm entirely with you in terms of harmonising the attribute names. Nevertheless, this should also bring changes to the documentation, namely:

* `<keySig>`
  >(key signature) – Written key signature.
  
  to something like:

  (key signature) – Transcribed or supplied or otherwise necessary key signature.
* `visible` / `sig.show`
  >Indicates if a feature should be rendered when the notation is presented graphically or sounded when it is presented in an aural form.
  
  Here I'm wondering whether `@sig.show` would actually control both visual and gestural aspects. Picking up the third example by @craigsapp: if it's hidden, then it should also not be considered for sound output, right? If so wouldn't it be better to have sth. like `sig.show` and `sig.sound` or probably to go closer our naming conventions: `sig.render.vis` and `sig.render.ges`?

**Comment by ahankinson** [comment]
A key signature is never really considered for sound output, since we encode the complete absolute pitch on every note.

**Comment by pe-ro** [comment]
@ahankinson, One might not want to encode absolute pitch on every note and yet want a "renderer" to attempt a sounded rendition.  In this case, the key signature should be a factor in creating reasonable aural output.

**Comment by ahankinson** [comment]
I know that's technically possible (hey, MEI is *almost* turing complete, isn't it? 😁 ) but the prevailing practice is that we encode the absolute pitch on every note. So one might **want** to omit it, but all the tooling will likely interpret the notes as being an absolute pitch, and I don't know if there's any reasonable way of signalling that this isn't the case. 

It's more likely that your aural renderer will do the opposite, and render the note as a natural when it's indicated in the key signature, but without a local accidental.

**Comment by craigsapp** [comment]
Regarding the last three posts:  That is why I always give either `@accid` or `@accid.ges` for every single note in my conversions from Humdrum to MEI.  This guarantees that I mean absolute pitch since both the diatonic pitch name and the chromatic alteration are both given. 

> One might not want to encode absolute pitch on every note and yet want a "renderer" to attempt a sounded rendition. In this case, the key signature should be a factor in creating reasonable aural output.

For music in the age of ficta where the performers decide the accidentals, then leaving out both `@accid` and `@accid.ges` is reasonable since the accidental of a note is not necessarily fixed. (and it would be up to the editor/performer or renderer to assign a specific accidental for performance).

A significant rendering problem is that if you want the key signature to be used to render `@accid.ges`, then you also have to take into account accidentals that occur previously in the measure at the same pitch as well.  This will also depend on whether or not the staff is shared by two instruments (where the accidentals in each voice are independent).  And for grand-staff music, you have to take into account cross-staff notes which interact with the accidentals/key signature of the staff they are displayed on rather than their home staff.   There are also complications related to ties across measures, as well as interactions between grace notes/ornaments and regular notes... etc.  

A significant problem occurs if you want to change the key signature (with or without transposition).   First you would have to assign absolute pitch to all of the notes by adding implied `@accid.ges`, then recalculate `@accid`.  If  the intermediate`@accid.ges` is wrong, then the final `@accid` will be wrong.

The musical data would also be almost useless for computational analysis since harmonic analyses and non-diatonic pitch analyses require the absolute pitch.  These assignments would need to be done on the fly before the analysis, which in the least would be very computational expensive (slow).   If there are a mixture of files in two different systems, that would also be very problematic (trying to assign absolute pitch to a file which is already in absolute pitch).  And there would likely be cases where the `@accid.ges` was assigned incorrectly, messing up the analysis.   This is the main difficulty with using SCORE data for analysis since the `@accid.ges` information is not explicitly encoded in the data and can only be estimated from the key and other accidentals in the music.


> One might not want to encode absolute pitch on every note and yet want a "renderer" to attempt a sounded rendition. In this case, the key signature should be a factor in creating reasonable aural output.

The only way this could be acceptable would be for the MEI file to have an encoding state flag that indicates that notes without `@accid.ges` have an undefined accidental that needs to be calculated from the key signature/previous note accidental states.   Then a user of the data could run it through a renderer first before using the data for MIDI performance or analysis (and they could prooflisten for errors in the renderer's output).

**Comment by bwbohl** [comment]
@craigsapp, thanks for the valuable addition. Those are things that should be put down in some best practice guidelines!

**Comment by lpugin** [comment]
Following the discussion on #727 and @craigsapp's proposal above I would suggest:
- on `<scoreDef>` and `<staffDef>`:
```
key.pname
key.accid
key.mode
keysig (change from 'key.sig')
keysig.visible (change from 'keysig.show')
keysig.cancel (change from 'keysig.showchange')
```
- on `<key>` (no changes):
```
pname
accid
mode
```
- on `<keySig>`:
```
key.pname
key.accid
key.mode
sig
sig.visible
sig.cancel (change from 'key.showchange)
```

**Comment by bwbohl** [comment]
I like @lpugin 's proposal, can we agree on it?

**Comment by ahankinson** [comment]
I did a review of this issue, the linked issues, and the current definition of elements. Here's a summary of what I found.

 - The sticky issue seems to be how to encode the location of the cancellation _accidentals_. In some styles they come before the new accidentals; in other styles they come after. There is also the possibility that they are shown before the barline, or not at all.
 - The existing `keysig.showchange`/`sig.showchange` is just a boolean, so it doesn't have the possibility to encode *how* to show the change. So there are diverging methods for what a renderer should do in this case.
 - MusicXML has the [`cancel-location`](https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/cancel-location/) data type which can encode the before / after / before-bar options. No indication of how not to show the cancellation at all, but maybe that's handled differently.
 - naming it to just `.cancel` seems, in my mind, to not be clear enough in its name of what it's doing. I think we can be a bit more specific.
 - It's unclear what `keysig.visible` or `<keySig visible>` control -- I'm going to say that it controls the "absolute" visibility of a key signature, and doesn't really have anything to do with what happens on a key signature change. So you could use `<staffDef keysig.visible="false">` to hide *all* key signatures, regardless of whether there is a change or not.
 - We should normalize `keysig.show` and `<keySig visible>`, since they do the same thing. @lpugin's proposal does but I would just like to note that in the summary.

So I would take @lpugin's recommendation, but change it slightly for the location of the cancellation accidentals.

- on `<scoreDef>` and `<staffDef>`:

```
key.pname
key.accid
key.mode
keysig (change from 'key.sig')
keysig.visible (change from 'keysig.show')
keysig.cancelaccid (change from 'keysig.showchange') with values "none | before | after | before-bar"
```

     - "none" would show no cautionary change (equivalent to `keysig.showchange="false"`)
     - "before" would be what's known as "standard"
     - "after" would be "old style" or "french"
     - "before-bar" would place the cancellation accidentals before the preceding barline. 

- on `<keySig>`:

```
key.pname
key.accid
key.mode
sig
visible (no change)
cancelaccid (change from 'key.showchange) with the same values as above
```

The justification for the values on `<keySig>` are that we do have a convention that, when encoding a prefixed attribute on an element of the same name, we can drop the prefix unless it's the attribute that is being "converted" into an element. I'm thinking specifically of things like `<accid accid="s">`. Since `@sig` doesn't correspond to any other prefix, and it relates directly to `<keySig>` I suggest we drop it on `visible` and `cancelaccid`, since those can easily be applied directly without the need for a prefixed attribute name.

---

A few tangential things came up during this review:

 - What does `<staffDef visible>` mean?? Can we drop this?
 - If we remove `keysig.showchange`, what do we do with `meter.showchange`? Are there similar variations?

**Comment by craigsapp** [comment]
> The sticky issue seems to be how to encode the location of the cancellation accidentals. In some styles they come before the new accidentals; in other styles they come after.

See issue https://github.com/rism-digital/verovio/issues/1803 related to this:

<img width="749" alt="Screen Shot 2022-10-13 at 7 17 38 AM" src="https://user-images.githubusercontent.com/3487289/195622160-08686ee9-79e0-4e78-9919-dce233451d12.png">

There should be only one style for the entire work, so ideally the standard style should be presumed if not told otherwise.   And preferably a way to set to a new style with one instance affecting all key signatures, such as in the first scoreDef/staffDef which applies to all future key signatures unless the style changes again for some reason.

> There is also the possibility that they are shown before the barline, or not at all.

When changing from a sharp key signature to a flat one (or vice-versa), I wonder how the cancellation-after is handled.

Not showing the cancellation key signature (other than when changing to C major/A minor) is common in modern scores.  I use this style as the default in the Humdrum-to-MEI converter.  Then if you want to see the cancellation, you have to indicate so.   

<img width="990" alt="Screen Shot 2022-10-13 at 7 33 40 AM" src="https://user-images.githubusercontent.com/3487289/195626269-cf4d04b7-c1b3-470c-a2aa-b1c69025211a.png">

<details>
<summary> Click to view MEI conversion </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-10-13T07:33:44" version="3.13.0-dev-1b525e9-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1a6yr0d">
    <score xml:id="s1ijnv1c">
     <scoreDef xml:id="s3jt8q">
      <staffGrp xml:id="sis3d30">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="cfq6od2" shape="G" line="2" />
        <keySig xml:id="keysig-L2F1" sig="3f" />
        <meterSig xml:id="metersig-L3F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" right="dbl">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="4" oct="4" pname="c" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="d" accid.ges="n" />
         <note xml:id="note-L7F1" dur="4" oct="4" pname="e" accid.ges="f" />
         <note xml:id="note-L8F1" dur="4" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <scoreDef xml:id="s1v8pc32">
       <keySig xml:id="keysig-L10F1" sig="4s" />
      </scoreDef>
      <measure xml:id="measure-L9" right="end">
       <staff xml:id="staff-L9F1N1" n="1">
        <layer xml:id="layer-L9F1N1" n="1">
         <note xml:id="note-L11F1" dur="4" oct="4" pname="e">
          <accid xml:id="accid-L11F1" accid="n" func="caution" />
         </note>
         <note xml:id="note-L12F1" dur="4" oct="4" pname="f" accid.ges="s" />
         <note xml:id="note-L13F1" dur="4" oct="4" pname="g" accid.ges="s" />
         <note xml:id="note-L14F1" dur="4" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

Forcing the cancellation key signature to display by adding `*kcancel` somewhere before the first cancellation:

<img width="1085" alt="Screen Shot 2022-10-13 at 7 35 46 AM" src="https://user-images.githubusercontent.com/3487289/195626719-4c2e5348-5bf9-4b33-8a64-0bba50cba487.png">

<details>
<summary> Click to view MEI conversion of above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-10-13T07:37:12" version="3.13.0-dev-1b525e9-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1xrr2x8">
    <score xml:id="s9n54vl">
     <scoreDef xml:id="sno31k6">
      <staffGrp xml:id="sknoib7">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="cqhzxep" shape="G" line="2" />
        <keySig xml:id="keysig-L2F1" sig="3f" />
        <meterSig xml:id="metersig-L4F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" right="dbl">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L6F1" dur="4" oct="4" pname="c" accid.ges="n" />
         <note xml:id="note-L7F1" dur="4" oct="4" pname="d" accid.ges="n" />
         <note xml:id="note-L8F1" dur="4" oct="4" pname="e" accid.ges="f" />
         <note xml:id="note-L9F1" dur="4" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <scoreDef xml:id="s12zaafi">
       <keySig xml:id="keysig-L11F1" sig="4s" sig.showchange="true" />
      </scoreDef>
      <measure xml:id="measure-L10" right="end">
       <staff xml:id="staff-L10F1N1" n="1">
        <layer xml:id="layer-L10F1N1" n="1">
         <note xml:id="note-L12F1" dur="4" oct="4" pname="e">
          <accid xml:id="accid-L12F1" accid="n" func="caution" />
         </note>
         <note xml:id="note-L13F1" dur="4" oct="4" pname="f" accid.ges="s" />
         <note xml:id="note-L14F1" dur="4" oct="4" pname="g" accid.ges="s" />
         <note xml:id="note-L15F1" dur="4" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

In this case every `<keySig>` after the first one will have `@sig.showchage="true"`:

```xml
<keySig xml:id="keysig-L11F1" sig="4s" sig.showchange="true" />
```

**Comment by bwbohl** [comment]
2023 Dev Workshop discussion sum-up: Thanks Andrew for the great summary and the implementation proposal above https://github.com/music-encoding/music-encoding/issues/525#issuecomment-1277283204

WE can move forward with implementing this
