### ISSUE TITLE
Website CSS styling

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#526]
In the list of elements:
    http://music-encoding.org/guidelines/v3/elements.html

<img width="851" alt="screen shot 2018-06-07 at 11 53 45 pm" src="https://user-images.githubusercontent.com/3487289/41143313-a7068fd4-6aad-11e8-8c2f-6aa7efdb6c9b.png">

And on element documentation pages:
    http://music-encoding.org/guidelines/v3/elements/desc.html

The alternating gray background and element tag backgrounds in the element lists are too dark to the point of being distracting and reducing the readability of the text.

It would be useful for the gray of such regions match that of the ODD sample code at the bottom of the element reference pages:

<img width="1055" alt="screen shot 2018-06-07 at 11 49 36 pm" src="https://user-images.githubusercontent.com/3487289/41143222-63be88ee-6aad-11e8-9b47-887db6be6725.png">

The gray color is currently `#e5e5e5`, but should be lightened to `#f5f5f5`.

**Comment by rettinghaus** [comment]
This is the wrong place, should be reported on https://github.com/music-encoding/music-encoding.github.io

**Comment by craigsapp** [comment]
ok
