### ISSUE TITLE
include SVG in MEI

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#53]
_From [kep...@edirom.de](https://code.google.com/u/113787537940489926112/) on March 19, 2012 08:56:42_

The inclusion of SVG in MEI needs to be addressed. Also, the inclusion of other XML-based encoding schemes (like TEI) needs to be discussed.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=53_

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on March 19, 2012 07:48:12_

This sounds like two different issues. Should we separate them? Or change this issue to "Including other XML-based encoding schemes" in general?

**Comment by ahankinson** [comment]
_From [lxpu...@gmail.com](https://code.google.com/u/115417461610980138677/) on July 17, 2012 02:34:12_

Do we want to allow SVG only at specific places only? If yes, I think it would be useful in the header in /workDesc/work/incip

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
@kepper SVG is available in MEI in the Beethoven Project. Is that a customization, or are you doing straight-up MEI?

**Comment by kepper** [comment]
It's part of a customization (we also had it in Edirom already). Look for lines 72 - 78 in https://github.com/BeethovensWerkstatt/Data-Model/blob/master/odd/bw_data.model_2014.odd

**Comment by pe-ro** [comment]
It's also covered in the 2015 customization, but commented out because it seemed like too large a topic to tackle at the time. In the customization, <svg> is a member of model.graphicLike, making it possible to use it anywhere one could previously use <graphic>. such as in <incip>.
