### ISSUE TITLE
Remove Guidelines XML

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#538]
Now that we've shifted to the Guidelines repo, we should remove the old TEI XML for the guidelines. (It will still be available in the version history). This is so contributors do not get confused where they need to make their updates.

I will do this, but would like to get approval from other members of the technical team first.

**Comment by rettinghaus** [comment]
Makes sense.

**Comment by lpugin** [comment]
(It thought this was already done.) 👍

**Comment by ahankinson** [comment]
Nope: https://github.com/music-encoding/music-encoding/tree/develop/source/guidelines

I will file a PR later today.

**Comment by kepper** [comment]
+1
