### ISSUE TITLE
Dynam + Dir

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#540]
How should the "sempre pp senza sordini" be encoded in this example:

<img width="566" alt="screen shot 2018-06-29 at 8 41 53 pm" src="https://user-images.githubusercontent.com/3487289/42121102-98ce038a-7bdc-11e8-9dba-efc2dc7c8f6f.png">

(also notice the difference in font between the text on each side of `pp`).

**Comment by pe-ro** [comment]
There are several options:
1. capture the dynamic marking only as text in a different style embedded in a directive; i.e.,
`<dir tstamp="1">sempre <rend rend="bold italic">pp</rend> senza sordini</dir>`
2. treat the whole thing as a dynamic, where the text other than "pp" is rendered differently; i.e.
`<dynam tstamp="1"><rend fontname="roman">sempre</rend> pp <rend fontname="roman">senza sordini</rend></dynam>`. The "pp" text should be rendered in the default fashion for dynamics.
3. encode each segment of the text -- "sempre", "pp", and "senza sordini" -- using separate elements; i.e., 
```
<dir tstamp="1" vgrp="1">sempre</dir>
<dynam tstamp="1" ho="8vu" vgrp="1">pp</dynam>
<dir tstamp="1" ho="12vu" vgrp="1">senza sordini</dir>
```
The horizontal placement of each segment can be recorded using `@tstamp`, `@ho` or `@to`.  The fact that all 3 segments belong at the same vertical position can be indicated with `@vgrp`.  The only advantage of this method over number 2 is that it explicit marks the "pp" text as an actionable dynamic, although I'm not convinced that the whole text isn't actionable when treated as in method 2.

It's not currently possible, but we could allow `<dir>` to contain `<dynam>`; i.e.,
`<dir tstamp="1">sempre <dynam>pp</dynam> senza sordini</dir>`, but I haven't thought about the side effects of it.

**Comment by pe-ro** [comment]
No new features being required or requested, I'm closing this one.
