### ISSUE TITLE
Chord with one augmentation dot missing

### ISSUE THREAD

**Issue by jacekiwaszko1** [music-encoding/music-encoding#542]
How should a chord missing one augmentation dot be encoded?  This question related to this example:

![one-dot-chord](https://user-images.githubusercontent.com/29225574/42811217-4df7ec18-89ba-11e8-869e-ee34544f3d3d.png)

The B-flat octaves in the first measure only have an augmentation dot on the upper B-flat and not the lower (either it was forgotten by the typesetter, or the typesetter removed it on purpose since there is the text `a Tempo.` which is in the way).

**Comment by ahankinson** [comment]
It depends on what you want to capture.

If you just want to capture the editorial intervention on the digital edition, you can use the `<supplied>` tag to record the dot.

If you want to record more information about it, you could use the `<sic>` and `<corr>` elements to record that it's a correction from the original.

**Comment by o-sapov** [comment]
You may encode it with different @dots values on `<chord>` and `<note>`s

`<chord  dur="4" dots="1" >`

`           <note pname="b" oct="5" accid.ges="f" dur="4" dots="1"/>`
`           <note  pname="c" oct="5" accid="n" dur="4" dots="0"/>`
`            <note  pname="e" oct="4" dur="4" dots="0"/>`

`</chord>`


![screenshot_2](https://user-images.githubusercontent.com/24490898/43705693-8beba74a-9963-11e8-8b5f-6c4713f2fb97.jpg)

**Comment by o-sapov** [comment]
To capture an editorial intervention or a mistake is on my opinion rather difficult here. You cannot wrap @dots in an `<supplied>` or `<sic>` and there is no `<dots>`. And if you ecode it like this:

 `<supplied>`
     `<note pname="c" oct="5" accid="n" dur="4" dots="0"/>`
`</supplied>`

it would mean that the _note_ is supplied.
The same problem is with some other attributes. For instance, @num, where the number over the tuplet was added by an editor.

**Comment by ahankinson** [comment]
There is a `<dot>` element: 

http://music-encoding.org/guidelines/v3/elements/dot.html

```
<note>
    <dot />
</note>
```

**Comment by jacekiwaszko1** [comment]
And this solution:
```xml
<chord dur="4" dots="1" >
<note pname="b" oct="5" accid.ges="f" dur="4" dots="1"/>
<note pname="c" oct="5" accid="n" dur="4" dots="0"/>
<note pname="e" oct="4" dur="4" dots="0"/>

</chord>
```
wouldn't mean that one note goes on longer than the others?

EDIT:

apparenly there's `@dots.ges` atribute in MEI now (see #499). What do you think about that?

```
<chord dur="4" dots="1" >
<note pname="b" oct="5" accid.ges="f" dur="4" dots="1"/>
<note pname="c" oct="5" accid="n" dur="4" dots="0" dots.ges="1" />
<note pname="e" oct="4" dur="4" dots="0" dots.ges="1"/>

</chord>
```

**Comment by lpugin** [comment]
`@dots` and `@dur` on the first note is not necessary in my opinion. Also, if you want to be explicit about the editorial aspect you can do:
```xml
<chord dur="4" dots="1" >
    <note pname="b" oct="5" accid.ges="f" />
    <choice>
        <sic>    
            <note pname="c" oct="5" accid="n" dots="0" dots.ges="1" />
            <note pname="e" oct="4" dots="0" dots.ges="1"/>
        </sic>
        <corr>    
            <note pname="c" oct="5" accid="n" />
            <note pname="e" oct="4" />
        </corr>
    </choice>
</chord>
```
Regarding the duplication of values, they cannot be fully avoided as long as attributes are used. When you encode the correction of the pitch of a note, the duration `@dur` is duplicated, for example. It is a question of granularity and again, the only way to avoid any duplications is to remove attributes completely, but I am not you we want to go that path.

**Comment by o-sapov** [comment]
@jacekiwaszko1: 

> And this solution:
> 
> <chord dur="4" dots="1" >
> <note pname="b" oct="5" accid.ges="f" dur="4" dots="1"/>
> <note pname="c" oct="5" accid="n" dur="4" dots="0"/>
> <note pname="e" oct="4" dur="4" dots="0"/>
> 
> </chord>
> wouldn't mean that one note goes on longer than the others?

yes, in my example I encoded notes with different durations (violin).

**Comment by pe-ro** [comment]
This support request has been answered, so I'm closing the issue.
