### ISSUE TITLE
create <namePart> element

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#56]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on March 19, 2012 17:19:09_
1. Create new <namePart> element that allows division of names into parts.
2. No longer allow name-like elements (name, persName, corpName, etc.) to nest recursively (via schematron?).

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=56_

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on June 21, 2012 05:38:32_

**Labels:** -Type-Enhancement -Priority-Medium -Milestone-Release2013 Type-Bug Priority-High Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on July 19, 2012 11:41:53_

**Labels:** -Priority-High -Milestone-ReleaseNext Priority-Medium Milestone-Release2013

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on July 23, 2012 08:51:50_

This issue is too big to tackle right now. There doesn't seem to be a way to restrict the recursive nesting as long as namePart contains phrase-level elements.  Simply adding another element to the name mix is not a good idea right now.

**Labels:** -Type-Bug Type-Enhancement

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on October 11, 2012 16:20:57_

**Labels:** -Priority-Medium Priority-Low

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on May 30, 2014 08:47:28_

**Labels:** -Milestone-ReleaseNext Milestone-ReleaseFuture

**Comment by pe-ro** [comment]
Follow TEI practice.  See attached ODD.

[nameParts.ODD.txt](https://github.com/music-encoding/music-encoding/files/42815/nameParts.ODD.txt)
