### ISSUE TITLE
<accid> in <add> not allowed when i delete MEI.mensural in MEI 4.0

### ISSUE THREAD

**Issue by aseipelt** [music-encoding/music-encoding#566]
When I customize my schema based on MEI 4.0 by deleting the MEI.mensural module, it is not allowed to nest `accid` in `add`. I think the problem is that model.layerPart.mensural, that is between these elements, is part of the MEI.mensural module (all other model classes in this case are part of MEI-shared) and I don't want to have MEI.mensural in my customization.

**Comment by pe-ro** [comment]
Oops!

I think we can remedy this in v. 4.1.0.

**Comment by musicEnfanthen** [comment]
Pinging @pe-ro and @ahankinson . Is that something that could be fixed tomorrow at the dev workshop?

**Comment by pe-ro** [comment]
Appears to have been fixed at some point.  Closing.
