### ISSUE TITLE
Allow <availability> within <imprint>

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#567]
`<availability>` was inadvertently omitted from `<imprint>` in v. 4.0.0.

**Comment by ahankinson** [comment]
Are you thinking of adding it in?

**Comment by pe-ro** [comment]
Yes, that's why I added the MEI 4.1.0 milestone.

I've also added milestones to other things I think can be fixed in 4.1 or 5.0.

**Comment by pe-ro** [comment]
`<unpub>` can be added as well.  This will make `<imprint>` the analog of `<pubStmt>` in the context of `<bibl>`.

**Comment by ahankinson** [comment]
This sounds to me like a bug and can be addressed in 4.0.2

**Comment by bwbohl** [comment]
Well, neither `<availability>` nor `<unpub>` had been allowed inside `<imprint>` in MEI v3… so actually tis would be two new features, ergo **MEI v4.1**

I think they would both make sense, though. Referencing an unpublished bibliographic item in `<source>` is common when dealing with e.g. autograph sources and being able to encode `<accessRestrict>` (child of `<availability>`) could also make sense in an imprint, couldn't it?

**Comment by kepper** [comment]
seems like this "just" needs a fix (or check if it's done already…)

**Comment by pe-ro** [comment]
Not done yet.  I think the fix is to make `<availability>` and `<unpub>` members of model.imprintPart.

**Comment by pe-ro** [comment]
Scratch that last suggestion.  Doing that would create an ambiguous content model; that is, availability (and perhaps unpub, too) would be "doubly included" in `<titlePage>`.

**Comment by pe-ro** [comment]
I believe the correct solution is to exclude `<availability>` from model.titlePagePart and include it in model.imprintPart. This will make `<availability >` a child of `<bibl>`, `<imprint>`, and `<titlePage>` (included in this case via model.imprintPart instead of model.titlePagePart.)

I don't think adding `<unpub>` to model.imprintPart has any side effects.
