### ISSUE TITLE
Add @occurs attribute on attUsage element

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/music-encoding#569]
Provides a place to store the number of times an attribute occurs in a document or corpus.  The value is contextual; that is, when `<attUsage>` is the child of `<tagUsage>`, the value will indicate how many times the attribute occurs on the element named by `<tagUsage>` and, when `<attUsage>` is the child of `<tagsDecl>`, the value is the number of times the attribute occurs in the file.  In the latter case, the `@context` attribute can be used to indicate the names of the element(s) on which the attribute is present.

**Comment by pe-ro** [comment]
An analysis of the markup for Mozart's Quartett in B für 2 Violinen, Viola und Violoncello, 1. Satz, KV 458/01:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<tagsDecl xmlns="http://www.music-encoding.org/ns/mei">
  <namespace name="http://www.music-encoding.org/ns/mei">
    <tagUsage name="abbr" occurs="1" withid="0" context="tempo">
      <attUsage name="expan" occurs="1">
        <desc>
          <seg>Allegro vivace assai</seg>
        </desc>
      </attUsage>
    </tagUsage>
    <tagUsage name="accid" occurs="25" withid="25" context="orig reg supplied">
      <attUsage name="accid" occurs="10">
        <desc>
          <seg>f</seg>
          <seg>n</seg>
        </desc>
      </attUsage>
      <attUsage name="accid.ges" occurs="15">
        <desc>
          <seg>n</seg>
          <seg>s</seg>
        </desc>
      </attUsage>
      <attUsage name="func" occurs="4">
        <desc>
          <seg>caution</seg>
        </desc>
      </attUsage>
      <attUsage name="xml:id" occurs="25">
        <desc>
          <seg>accid_10562-A</seg>
          <seg>accid_10562b-A</seg>
          <seg>accid_10823-A</seg>
          <seg>accid_10823b-A</seg>
          <seg>accid_11087-A</seg>
          <seg>accid_11087b-A</seg>
          <seg>accid_15329-A</seg>
          <seg>accid_15329b-A</seg>
          <seg>accid_24399-A</seg>
          <seg>accid_30581-A</seg>
          <seg>accid_30581b-A</seg>
          <seg>accid_30588-A</seg>
          <seg>accid_32918-A</seg>
          <seg>accid_32918b-A</seg>
          <seg>accid_32936-A</seg>
          <seg>accid_32936b-A</seg>
          <seg>accid_33203-A</seg>
          <seg>accid_33203b-A</seg>
          <seg>accid_33335-A</seg>
          <seg>accid_33335b-A</seg>
          <seg>accid_33683-A</seg>
          <seg>accid_33683b-A</seg>
          <seg>accid_46404-A</seg>
          <seg>accid_63369-A</seg>
          <seg>accid_63762-A</seg>
        </desc>
      </attUsage>
    </tagUsage>
    <!-- add'l tags described here -->
  </namespace>
  <!-- add'l namespaces described here -->
</tagsDecl>
```

**Comment by pe-ro** [comment]
The enumeration of attribute values in the preceding example is "kludgey".  It would be better to permit more-specific markup, perhaps based on TEI's `<valList>` element:

``` xml
<valList>
  <valItem value="f">
    <desc>User-supplied description or comment, not necessarily what's in the schema</desc>
  </valItem>
  <valItem value="n">
    <desc>Ditto</desc>
  </valItem>
</valList>
```
It would also be helpful to add `@occurs` on `<valItem>` to provide an indication of how many times this particular value is used.

**Comment by lpugin** [comment]
What would be the typical usage of this? It looks to me like something you can evaluate dynamically with an xpath query and not something to store statically in the file. I must be overlooking something ...

**Comment by pe-ro** [comment]
One need not store it in the file.  But the point of `<tagsDecl>` is that one *can store it* if he likes.  One might dynamically generate a `<tagsDecl>` fragment, put it in a separate file (where it can get updated periodically), and XInclude it in the MEI header upon publication.

Also, it's helpful to have a strictly-defined form for sharing the results of a dynamic query, even if one doesn't store it in the file.  For instance, we may want to share a `<tagsDecl>` fragment with each other for reporting purposes.

**Comment by pe-ro** [comment]
A `<tagsDecl>` fragment could also be part of a quality control workflow.

But, you're right, it doesn't have to be (and maybe shouldn't be) stored in the MEI file it describes.

**Comment by lpugin** [comment]
This makes sense. Thank you for the explanation

**Comment by pe-ro** [comment]
You're welcome.

**Comment by ahankinson** [comment]
> One might dynamically generate a <tagsDecl> fragment, put it in a separate file (where it can get updated periodically), and XInclude it in the MEI header upon publication.

What's the use case for this? I've been puzzling over this for a bit and can't seem to identify a case where this would be used.

The closest I can come to is that this is more like a "meta-MEI" use... data that describes the mechanics of an encoding, not necessarily the encoding itself. Is that correct?

**Comment by pe-ro** [comment]
> The closest I can come to is that this is more like a "meta-MEI" use... data that describes the mechanics of an encoding, not necessarily the encoding itself. Is that correct?

Yes.

**Comment by ahankinson** [comment]
Would that be better encapsulated as a separate specification, then?

**Comment by pe-ro** [comment]
Changed my mind --

No, it describes the encoding in a very precise and machine-processable way -- the namespaces, elements, attributes, and attribute values (if the changes proposed here are adopted) used.

**Comment by pe-ro** [comment]
Put it where you want.

**Comment by pe-ro** [comment]
Expunge it from MEI, I don't care.

**Comment by kepper** [comment]
Seems like a local need, which might be addressed using processing instructions as part of a local workflow, which are also part of XML. @pe-ro consents to close this.
