### ISSUE TITLE
Incipit letters

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#575]
How should an incipit letter be encoded in MEI, with the long-term goal of rendering such an image in an MEI notation renderer such as veorvio?  (this is a question that someone asked me that I am fowarding for discussion and later reference when implementing such a feature, so I am not the originator of the question).

Here is a random example from the web:

<img width="507" alt="screen shot 2019-01-24 at 2 08 18 pm" src="https://user-images.githubusercontent.com/3487289/51703451-5aed0c80-1fe4-11e9-905b-bcd48a6e971e.png">

from: https://en.wikipedia.org/wiki/Eton_Choirbook

How should the "O" at the start of the music be stored?  This is somewhat related to facsimiles:
    https://music-encoding.org/guidelines/v4/content/facsimiles.html
[hint: you might want to expand the guideline documention at some point :-)]
But in any case this is not quite trying to describe a facsimile, but a more hybrid system where a piece of the source document would be scanned and inserted into a computer-rendered version of the musical content.

**Comment by ahankinson** [comment]
Hi Craig, I think this would be a question better posed to the mailing list. Could you send a message out there to solicit feedback? Thanks.
