### ISSUE TITLE
Empty beam element with sameas attribute is not valid

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#578]
Validation fails with empty `<beam>` elements using `@sameas`
```xml
<staff xml:id="staff_45387" n="4">
	<layer xml:id="layer_45393a" n="1">
		<note xml:id="note_45399a" pname="b" oct="3" dur="8" accid.ges="f"/>
		<beam xml:id="beam_45405a">
			<note xml:id="note_45411a" pname="c" oct="4" dur="8" accid="s"/>
			<note xml:id="note_45417a" pname="d" oct="4" dur="8" />
		</beam>
		<beam xml:id="beam_45426a">
			<note xml:id="note_45432a" pname="a" oct="3" dur="8" />
			<note xml:id="note_45438a" pname="b" oct="3" dur="8" accid.ges="f"/>
		</beam>
		<beam xml:id="beam_45447a">
			<note xml:id="note_45453a" pname="e" oct="3" dur="8" accid="n"/>
			<note xml:id="note_45459a" pname="f" oct="3" dur="8" />
		</beam>
		<note xml:id="note_45468a" pname="d" oct="3" dur="8" artic="spicc"/>
	</layer>
	<layer xml:id="layer_45393b" n="2">
		<note xml:id="note_45399b" pname="b" oct="3" dur="8" accid.ges="f"/>
		<!-- beams with @sames -->
		<beam xml:id="beam_45426a" sameas="#beam_45405a"/>
                <beam xml:id="beam_45426b" sameas="#beam_45426a"/>
		<beam xml:id="beam_45447b" sameas="#beam_45447a"/>
		<note xml:id="note_45468b" pname="d" oct="2" dur="8" artic="spicc"/>
	</layer>
</staff>
```
![image](https://user-images.githubusercontent.com/689412/54200106-d2aac400-44ca-11e9-8fe3-0ce84807fd51.png)

**Comment by craigsapp** [comment]
The main problem is a duplicated ID:

<img width="1073" alt="Screen Shot 2019-03-12 at 10 23 53 AM" src="https://user-images.githubusercontent.com/3487289/54207559-bd28a080-44b0-11e9-9fff-124dd2193a53.png">

The id for the first sameas beam should be  `beam_45426b`.

**Comment by lpugin** [comment]
Here is a complete and shorter example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title></title>
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score xml:id="score_01">
                    <scoreDef xml:id="scoreDef_01" n="1" meter.count="4" meter.unit="4" meter.sym="common" key.sig="1f" key.pname="f" key.mode="major">
                        <staffGrp xml:id="staffGrp_02" symbol="bracket">
                            <staffDef xml:id="staffDef_P04" n="4" clef.shape="F" clef.line="4" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure xml:id="m86_k621_023" n="86">
                            <staff xml:id="staff_45387" n="4">
                                <layer xml:id="layer_45393a" n="1">
                                    <beam xml:id="beam_45405a">
                                        <note xml:id="note_45411a" pname="c" oct="4" dur="8" accid="s"/>
                                        <note xml:id="note_45417a" pname="d" oct="4" dur="8" />
                                    </beam>
                                </layer>
                                <layer xml:id="layer_45393b" n="2">
                                    <beam xml:id="beam_45426b" sameas="#beam_45405a"/>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
Validation (Schematron) triggers:
```
A beam without a copyof attribute must have at least 2 note, rest, chord, or space descendants.
```

**Comment by bwbohl** [comment]
it's valid when you use `@copyof`. Makes me wonder about the difference of these two attributes, gotta do some research on that…

my _advocatus diavoli_ asks: why do you actually want to use `@sameas` why not just encode the beam?

**Comment by lpugin** [comment]
It is used when to instruments are playing unisson. Here is an example:
![image](https://user-images.githubusercontent.com/689412/55237101-a06ec580-5231-11e9-8d94-cbdd4fa404ab.png)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
	<meiHead>
		<fileDesc>
			<titleStmt>
				<title>Sameas example</title>
			</titleStmt>
			<pubStmt>
				<date>2018-05-29</date>
			</pubStmt>
			<notesStmt>
				<annot>Verovio supports automatic stem directation with @sameas used on notes, beams or layers.</annot>
			</notesStmt>
		</fileDesc>
	</meiHead>
	<music>
		<body>
			<mdiv>
				<score xml:id="score_01">
					<scoreDef xml:id="scoreDef_01" n="1" meter.count="4" meter.unit="4" meter.sym="common" key.sig="1f" key.pname="f" key.mode="major">
						<staffGrp xml:id="staffGrp_02" symbol="bracket" barthru="true">
							<staffDef xml:id="staffDef_P04" n="4" clef.shape="F" clef.line="4" lines="5" label="Fagotto I, II" label.abbr="Fag. I, II"
							/>
						</staffGrp>
					</scoreDef>
					<section>
						<measure xml:id="m86_k621_023" n="86">
							<staff xml:id="staff_45387" n="4">
								<layer xml:id="layer_45393a" n="1">
									<note xml:id="note_45399a" pname="b" oct="3" dur="8" accid.ges="f"/>
									<beam xml:id="beam_45405a">
										<note xml:id="note_45411a" pname="c" oct="4" dur="8" accid="s"/>
										<note xml:id="note_45417a" pname="d" oct="4" dur="8" />
									</beam>
									<beam xml:id="beam_45426a">
										<note xml:id="note_45432a" pname="a" oct="3" dur="8" />
										<note xml:id="note_45438a" pname="b" oct="3" dur="8" accid.ges="f"/>
									</beam>
									<beam xml:id="beam_45447a">
										<note xml:id="note_45453a" pname="e" oct="3" dur="8" accid="n"/>
										<note xml:id="note_45459a" pname="f" oct="3" dur="8" />
									</beam>
									<note xml:id="note_45468a" pname="d" oct="3" dur="8" artic="spicc"/>
								</layer>
								<layer xml:id="layer_45393b" n="2">
									<note xml:id="note_45399b" pname="b" oct="3" dur="8" accid.ges="f"/>
									<!-- A space should not affect stem direction in layer 1 -->
									<space dur="4"/>
									<!-- A beam with @sames not affect stem direction in layer 1 -->
									<beam xml:id="beam_45426b" sameas="#beam_45426a"/>
									<beam xml:id="beam_45447b" sameas="#beam_45447a"/>
									<!-- A note should affect stem direction in layer 1 -->
									<note xml:id="note_45468b" pname="d" oct="2" dur="8" artic="spicc"/>
									<!-- <note xml:id="note_45468b" sameas="#note_45468a"/>-->
								</layer>
							</staff>
							<dir xml:id="dir_45903" staff="4" startid="#note_45411a" place="above">
								<rend fontstyle="normal" xml:id="rend_45905">a 2</rend>
							</dir>
						</measure>
						<measure xml:id="m88_k621_023" n="88">
							<staff xml:id="staff_46848" n="4">
								<layer xml:id="layer_46854" n="1">
									<rest xml:id="rest_46860" dur="8" tstamp="1"/>
									<beam xml:id="beam_46866">
										<note xml:id="note_46872" pname="c" oct="4" dur="8" tstamp="1.5" accid="s"/>
										<note xml:id="note_46878" pname="d" oct="4" dur="8" tstamp="2"/>
									</beam>
									<beam xml:id="beam_46887">
										<note xml:id="note_46893" pname="a" oct="3" dur="8" tstamp="2.5"/>
										<note xml:id="note_46899" pname="b" oct="3" dur="8" tstamp="3" accid.ges="f"/>
									</beam>
									<beam xml:id="beam_46908">
										<note xml:id="note_46914" pname="f" oct="3" dur="8" tstamp="3.5" accid="s"/>
										<note xml:id="note_46920" pname="g" oct="3" dur="8" tstamp="4"/>
									</beam>
									<note xml:id="note_46929" pname="d" oct="3" dur="8" artic="spicc" tstamp="4.5"/>
								</layer>
								<!-- a complete layer with @sameas should not affect stem direction in layer 1 -->
								<layer xml:id="staff_46948" n="2" sameas="#layer_46854"/>
							</staff>
						</measure>
					</section>
				</score>
			</mdiv>
		</body>
	</music>
</mei>
```

**Comment by bwbohl** [comment]
Ok, plausible! Although You encode visual or logical domain?
Anyway for a best practice of encoding, I'd consider wrapping this in `choice`but that might be due to my editorial background.

But the issue here is true both in v3.0.0 and v4.0.0 – same error reported. Question is: is it a bug or intentional?

**Comment by lpugin** [comment]
> Anyway for a best practice of encoding, I'd consider wrapping this in `choice` but that might be due to my editorial background.

I am not convinced, but I am OK to have `@sameas` as a second best practice. The approach is to encode the visual domain: you can see only one beam on the score - but to provide semantic information that two instruments are behind it. It also makes instrument extraction (e.g., sound) easy.

> But the issue here is true both in v3.0.0 and v4.0.0 – same error reported. Question is: is it a bug or intentional?

I would call it a bug.

**Comment by bwbohl** [comment]
ok, sorry the image didn't load as I was in a bad connection area.
In that case I'm with you and consider it a bug!

**Comment by rettinghaus** [comment]
As far as I understood the concept of `@sameas`, it was meant for visual features. I think the beams should also carry a `@copyof`, and this would make it valid. 
Just the description of these attributes should be enhanced in the guidelines.

**Comment by lpugin** [comment]
I think you misunderstood. The guidelines seem very clear: "the `@sameas` indicates that the current element represents exactly the same entity as the one referenced in `@sameas`. Use of `@sameas` is used for describing the same entity from multiple perspectives, e.g., the same event in two layers."

**Comment by kepper** [comment]
A simple `@sameas` should be sufficient, I agree. The schematron on beams is a little too strict, or at least its sibling on tuplet is – a tuplet may very well contain a `<bTrem>` with only one note in there. I think we should revise them…

**Comment by pe-ro** [comment]
1. The schematron can be relaxed to also allow a beam with `@sameas` and no children, just as it currently does with `@copyof`.
2. A tuplet should always have more than one child. A tuplet shouldn't contain a single `<bTrem>` element. Doing so mixes visual and logical encoding. While a `<bTrem>` is often used as a shorthand way of writing a tuplet, it's *not a tuplet on the page*.  If you want to capture the rendition of the `<bTrem>` as a `<tuplet>`, make them siblings and wrap them in a `<choice>` element.

**Comment by kepper** [comment]
I'm not saying a `<bTrem>` may serve to encode a tuplet – hence the need to wrap it into one. The correct encoding would then be to do something like
``` xml
<tuplet>
  <bTrem>
    <note/>
  </bTrem>
</tuplet>
```
Of course, one may (or sometimes even should?) wrap the `<bTrem>` inside a `<choice>`, but I think this is independent from the tuplet. A complete example in that sense would look like so: 
``` xml
<tuplet>
  <choice>
    <abbr>
      <bTrem>
        <note/>
      </bTrem>
    </abbr>
    <expan>
      <note/>
      <note/>
      <note/>
    </expan>
  </choice>
</tuplet>
```
I think this is the proper way to separate logical and visual domains in this situation. However, we already agreed that it makes sense to relax the schematron rule ;-)

**Comment by lpugin** [comment]
Wouldn't you (probably) expect?
```
<choice>
  <abbr>
    <bTrem>
      <note/>
    </bTrem>
  </abbr>
  <expan>
    <beam>
      <note/>
      <note/>
      <note/>
    </beam>
  </expan>
</choice>
```
And this does not have to be in a `<tuplet>`, does it?

**Comment by kepper** [comment]
Well, I may need a `<beam>` when interested in nice rendition – for pure logical information, I don't need that. Let's say I left this out for brevity ;-)
And then of course I only need a `<tuplet>` when there is one in the source material I'm trying to encode. I have nothing at hand, so excuse my hand-drawn example below:
![bTremSample](https://user-images.githubusercontent.com/2078563/80088744-37a16c00-855d-11ea-8fae-dac7e2115fc8.jpg)
The context makes it very clear, that in this case the writer was too lazy to continue writing three notes per tuplet, and so uses the bTrem as shortcut. This shortcut is independent of the tuplet. My initial argument was that the schematron on tuplets should not yell at the encoder that there is only one note if that note (or chord…) is placed inside a `<bTrem>`…

**Comment by pe-ro** [comment]
I think we agree that the best way to represent this situation is to use `<choice>` to capture the encoding alternatives; that is, the abbreviation that uses a bowed tremolo vs. the expansion which uses beamed notes (with or without enclosing them in `<tuplet>`).

The desire is to put `<bTrem>` **inside** `<tuplet>` is just **wrong** because a tuplet indicates some things (the plural here is IMPORTANT) in the same time as some other thing(s), so the schematron cries out.  As I said before, there's no tuplet on the page to capture regardless of the obviousness of the context, and wrapping the `<bTrem>` in `<tuplet>` to encode the expansion of the abbreviation shouldn't be condoned.
