### ISSUE TITLE
anyStart schema should allow @meiversion on any element

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#580]
When encoding an MEI snippet according to the anyStart schema there is no way to encode the MEI-version used. In the MEI-all specs @meiversion is allowed on all respective starting points, mei, meiCorpus, meiHead, music

**Comment by bwbohl** [comment]
follow-up: should `@meiversion` generally be allowed on any element, i.e. also in all MEI-all?

**Comment by bwbohl** [comment]
I think this should be fixed already

**Comment by musicEnfanthen** [comment]
Yes, someone named @bwbohl fixed this in 2021: https://github.com/music-encoding/music-encoding/commit/72d506f5a528c4eab187678471c0f6faae6eb4ed 👍
