### ISSUE TITLE
Create MEI 4.0.1 release

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#582]
I think we need to do a critical bugfix release to push the fix in #581 out to master.

**Comment by bwbohl** [comment]
is there anything else that might be bugfixed on the same go? Maybe we should revisit all open issues

**Comment by wergo** [comment]
May I point to #577 that I raised some time ago. It seems to be a quick fix (if I did not misunderstand). Thanks

**Comment by wergo** [comment]
May I additionally point to this discussion https://github.com/rism-ch/verovio/issues/774. 

`<pedal>` elements should be allowed to have `@vgrp` attributes, just as `<dynam>` and `<hairpin>` are.

**Comment by bwbohl** [comment]
Hi @wergo thanks for spotting this! It pretty obviously seems to be an oversight. Although we will not fix it in v4.0.1, as we want  the critical bugfix asap, we will fix this in a soon to come bugfix release.

**Comment by ahankinson** [comment]
Fixed.
