### ISSUE TITLE
data_KEYSIGNATURE vs data.KEYFIFTHS

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#592]
82e2648261eaf6afecc32e976789dd67fbab36bc seems to be part of an unfinished revision which we discussed in #525. Same with #590. 

I think we should revert these changes for 4.0.2 and (if we manage to clear things up) move them to 5.0.0.

**Comment by ahankinson** [comment]
Would reverting them break backwards compatibility?

**Comment by rettinghaus** [comment]
A complete revert wouldn't work, as there were changes afterwards. I think we just should revert the name to `data.KEYSIGNATURE` to match the revert from `@fifths` to `@sig`.

**Comment by bwbohl** [comment]
Pasting discussion from guidelines repo https://github.com/music-encoding/music-encoding/issues/1535

@lpugin :
>One question I have on this topic is the meaning of keySig@sig="mixed". This should be clarified too. When do we expect the attribute value to be used, and what does it mean?

@rettinghaus 
> @lpugin When `<keyAccid>` is used, there is no need for an additional `<keySig sig="mixed">`. Question is: do one wants/needs to say, that there *is* a mixed key without  bothering to encode the used accidentals explicitly? 
Being part of `data.KEYFIFTHS` I wonder if the value `mixed` does make sense at all …

@lpugin 
>I don't think `data.KEYFIFTHS` is really appropriate for this. I would go back to `data.KEYSIGNATURE`
https://music-encoding.org/guidelines/v3/data-types/data.keysignature.html

@rettinghaus 
>see music-encoding/music-encoding#592 and music-encoding/music-encoding#598

**Comment by bwbohl** [comment]
I'll try to revise this and get back with a n overview of the current situation, concerning backward compatibility and changes needed for a complete implementation of the intended changes

**Comment by kepper** [comment]
this will be examined more closely, but might be closed after that?!

**Comment by pe-ro** [comment]
With the whole key fifths thing off the table, I think this is now a non-issue.  I suggest closing it and dealing with the more specific issues in #525 and #727.
