### ISSUE TITLE
MEI Basic: allow @barthru on staffGrp

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#594]
Currently, MEI Basic disallows `@barthrue` on staffGrp. That should be available.

**Comment by musicEnfanthen** [comment]
Pinging @lpugin

**Comment by rettinghaus** [comment]
@musicEnfanthen the attribute is nowadays called `@bar.thru` and is allowed in MEI Basic through `att.staffGrp.vis`.
