### ISSUE TITLE
MEI Basic: allow @key.mode on <scoreDef>

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#595]
`<scoreDef>` and `<staffDef>` should allow @key.mode

**Comment by musicEnfanthen** [comment]
Pinging @lpugin

**Comment by rettinghaus** [comment]
There is a contradiction in the spec. We explicitly include `att.keySigDefault.anl` (including `@key.mode`) and then we delete it again.

https://github.com/music-encoding/music-encoding/blob/dffa5e038aa1f8a752ce789ec0b9c2496a7a9c73/customizations/mei-basic.xml#L50

https://github.com/music-encoding/music-encoding/blob/dffa5e038aa1f8a752ce789ec0b9c2496a7a9c73/customizations/mei-basic.xml#L169

https://github.com/music-encoding/music-encoding/blob/dffa5e038aa1f8a752ce789ec0b9c2496a7a9c73/customizations/mei-basic.xml#L177

**Comment by ahankinson** [comment]
May I question why we need `@key.mode` in basic? It seems to me that marking something "major" or "minor" has very little to do with the rendering or playback of the notation, and is primarily an analytical observation.

I'm not necessarily opposed to it, but I don't really see the justification for it to be included in the original issue.

**Comment by rettinghaus** [comment]
I agree with @ahankinson here. Just because it's in MusicXML, it doesn't have to be in MEI basic. 

Still, the customization should be cleaned up.

**Comment by bwbohl** [comment]
also agree with @ahankinson. @rettinghaus could you please check the current status of the customization considering your mentioned cleanup?

**Comment by rettinghaus** [comment]
@bwbohl Seems to be fine now. I guess this can be closed then, @kepper ?

**Comment by kepper** [comment]
Seems we prefer to move on without `@key.mode` ;-)
