### ISSUE TITLE
discuss attributes for <scoreDef> that should go into MEI Basic

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#596]
Some preliminary decisions have been taken to build a straw man for MEI Basic, based on the discussions in Oxford in late 2018. However, there are plenty of attributes that are still allowed in MEI Basic, and others might be missing. Here's a list of _available_ attributes:

- `@aboveorder`
- `@bar.len`
- `@bar.method`
- `@bar.place`
- `@beam.color`
- `@beam.rend`
- `@beam.slope`
- `@beloworder`
- `@betweenorder`
- `@clef.color`
- `@clef.dis`
- `@clef.dis.place`
- `@clef.line`
- `@clef.shape`
- `@clef.visible`
- `@dur.default`
- `@dynam.dist`
- `@ending.rend`
- `@grid.show`
- `@harm.dist`
- `@key.sig`
- `@keysig.show`
- `@keysig.showchange`
- `@lyric.align`
- `@lyric.fam`
- `@lyric.name`
- `@lyric.size`
- `@lyric.style`
- `@lyric.weight`
- `@meter.count`
- `@meter.form`
- `@meter.showchange`
- `@meter.unit`
- `@midi.bpm`
- `@midi.channel`
- `@midi.duty`
- `@midi.mspb`
- `@midi.port`
- `@midi.track`
- `@mm`
- `@mm.dots`
- `@mm.unit`
- `@mnum.visible`
- `@multi.number`
- `@music.name`
- `@music.size`
- `@num.default`
- `@numbase.default`
- `@oct.default`
- `@ontheline`
- `@optimize`
- `@page.botmar`
- `@page.height`
- `@page.leftmar`
- `@page.panels`
- `@page.rightmar`
- `@page.scale`
- `@page.topmar`
- `@page.width`
- `@pedal.style`
- `@ppq`
- `@reh.enclose`
- `@spacing.packexp`
- `@spacing.packfact`
- `@spacing.staff`
- `@spacing.system`
- `@system.leftline`
- `@system.leftmar`
- `@system.rightmar`
- `@system.topmar`
- `@text.dist`
- `@text.fam`
- `@text.name`
- `@text.size`
- `@text.style`
- `@text.weight`
- `@trans.diat`
- `@trans.semi`
- `@tune.Hz`
- `@tune.pname`
- `@tune.temper`
- `@vu.height`
- `@xml:id`

Of course, some of these 83 attributes can be grouped (i.e., do we want the MIDI stuff, do we want the page layout stuff, etc.), but it might be helpful to look at the full list. Eventually, it comes down to the question if we want to understand MEI Basic as a simplified form of MEI, which may accept less precision, or if we "just" want to take out the editorial / ambiguous stuff. Any opinions are highly welcome ;-)

**Comment by kepper** [comment]
I didn't want to be the first to comment, but here I go. I would recommend to restrict MEI Basic as much as possible. This means removing the MIDI module, all page / system layout, the tuning, lyrics and music font info, everything that has a ".default" in it, everything about beams, etc. I'm not so sure about the `@mm` (metronome marking) and the `@optimize` (compress system by omitting resting staves on a page).

**Comment by bwbohl** [comment]
I completely agree. I'd keep `@mm`, though but remove `@optimize`

**Comment by musicEnfanthen** [comment]
@lpugin @kepper This can be closed now?

**Comment by musicEnfanthen** [comment]
pinging @lpugin and @kepper. Can this issue be closed?

**Comment by lpugin** [comment]
Yes, it can be closed in my opinion.

**Comment by musicEnfanthen** [comment]
Thank you!
