### ISSUE TITLE
Reconsider units on graphic

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#603]
In v4, `<graphic>` has no `@unit` anymore. Instead, one has to trust that `@width` and `@height` provide a unit with values like "3000px". If no unit is provided, the default unit is "vu" (according to https://music-encoding.org/guidelines/v4/data-types/data.measurementabs.html), which makes no particular sense on `<graphic>`. When upconverting files from v3 to v4, the current XSLT does not append the unit from `@unit` to the values in `@width` and `@height`, so all such files will have to be interpreted as if they were in "vu". 

There is clearly a bug / inconsistency in here, and we need to decide where it is. We could either fix the XSLT to consider the unit. Or, we could re-allow `@unit` on `<graphic>` – I don't remember any discussion about this (#73 clearly predates this change). At this point, I would probably prefer the latter. It solves a problem ("unitless" dimensions are easier to parse), but we should then add a Schematron rule that ensures we don't have conflicts by units provided both within `@width` (which was allowed in v3 already) and `@unit` – or not at all. 

For completeness, the only other elements bearing `@width` and `@height` in a comparable way still have `@unit` (`<folium>` and `<bifolium>`, both added in v4).

Opinions?

**Comment by rettinghaus** [comment]
Maybe related to this is that something seems to be mixed up in `<dimensions>`. 
It's part of the two `model.physDescPartGroups` and `model.textPhraseLike.limited`, but as content only `macro.struc-unstrucContent` is allowed (although the `remarks` say otherwise). It seems to me `model.textPhraseLike.limited` moved to the wrong position.

**Comment by wergo** [comment]
Has a decision been made on this? 

I would quite prefer no units in `<graphic @width and @height>` and have an optional separate attribute to specify this.

Graphic element implemented in a PR for Verovio with need for clarification of this: https://github.com/rism-digital/verovio/pull/3033.

**Comment by lpugin** [comment]
Looking at it it seems that everything is fine. It is essentially an implementation issue. Please re-open if necessary.
