### ISSUE TITLE
allow <bibl> in <source> as an alternative to the structured elements

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#61]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on April 25, 2012 15:08:22_

A loosely-structured citation is often more convenient. This might also stop users from seeking "creative" markup solutions using the structured elements.  Must the structured elements be wrapped in another tag, say <biblFull>?  Doing this will raise backwards compatibility issues.

_Original issue: http://code.google.com/p/music-encoding/issues/detail?id=61_

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on July 24, 2012 08:59:32_

<bibl> should be allowed also in <work> and <relatedItem> as well as <expression> and (FRBR) <item> when/if they are added.  A typical model might be:

source ((bibl? | (identifier_, titleStmt?, macro.bibldescPart, notesStmt?, macro.workPart, classification?, incip?, contents?, relatedItem_)), item*)

<source> could then be unstructured --

<source>
  <bibl>Roland, Perry. Blah, blah, blah: And Other tales. ...</bibl>
</source>

or structured --

<source>
  <titleStmt/>
  <editionStmt/>
  <pubStmt/>
  <physDesc/>
  <seriesStmt/>
  
</source>

It might be useful to also allow <annot> wherever <bibl> occurs in these models:

(((bibl|annot)\* | (identifier_, titleStmt?, macro.bibldescPart, notesStmt?, macro.workPart, classification?, incip?, contents?)), relatedItem_, item*)

**Comment by ahankinson** [comment]
_From [andrew.hankinson](https://code.google.com/u/andrew.hankinson/) on October 17, 2012 07:52:52_

**Labels:** -Milestone-Release2013 Milestone-ReleaseNext

**Comment by ahankinson** [comment]
_From [pd...@virginia.edu](https://code.google.com/u/103686026181985548448/) on June 11, 2014 13:28:09_

**Labels:** -Priority-Medium Priority-Low

**Comment by pe-ro** [comment]
Addressed in 4c5a821
