### ISSUE TITLE
Rendering of two syllables on one note 

### ISSUE THREAD

**Issue by ndubo** [music-encoding/music-encoding#617]
In Italian, but I assume in other (Romance) languages as well, there may be two (sometimes even more) syllables on one note, one of them at the end of a word, the other one at the beginning (see third note; the full piece is found here: <https://dme.mozarteum.at/movi/navigator/621/023/01/0013>).

![wordpos_01](https://user-images.githubusercontent.com/33256891/65250866-90f07b00-daf6-11e9-8ba3-03f32a047770.jpg)

In the present case, the syllables in question are "-da" (which is wordpos="t") and "I-" (which is wordpos="i"). The correct coding therefore should be:

```
<note dur="8" oct="4" pname="f" tstamp="3" xml:id="note_7719">
	<verse xml:id="verse_7725">
		<syl con="s" wordpos="t" xml:id="syl_7731">da</syl>
		<syl con="d" wordpos="i" xml:id="syl_7732">I</syl>
	</verse>
</note>

```
(Alternatively, in the first syllable `con="t"` or `con="c"` is possible, but it should not be mandatory using these values).

The output of this code in Verovio is:

![wordpos_02](https://user-images.githubusercontent.com/33256891/65251007-d6ad4380-daf6-11e9-875f-ee3fa6a9f509.jpg)

It works correctly only with the following coding, where the syllables are combined ("-da I-") and have the attribute `wordpos="m"`, which, however, is not correct:

```
<note dur="8" oct="4" pname="f" tstamp="3" xml:id="note_7719">
	<verse xml:id="verse_7725">
		<syl con="d" wordpos="m" xml:id="syl_7731">da I</syl>
	</verse>
</note>
```
Verovio should allow two syllables on one note, each of them with their unique `wordpos` and appropriate `con`.

**Comment by craigsapp** [comment]
> Verovio should allow two syllables on one note, each of them with their unique wordpos and appropriate con.

You have submitted the issue to the wrong repository 😉

**Comment by bwbohl** [comment]
Yes, please file an issue in the verovio repository at: https://github.com/rism-ch/verovio
