### ISSUE TITLE
Neumes ODD customization incorrect

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#628]
The Neumes ODD tries to delete an `att.augmentdots` attribute class, which is actually called `att.augmentDots`. 

https://github.com/music-encoding/music-encoding/blob/77c9a599e21da43da36513f65b9ff17a30c59370/customizations/mei-Neumes.xml#L107 https://github.com/music-encoding/music-encoding/blob/77c9a599e21da43da36513f65b9ff17a30c59370/source/modules/MEI.shared.xml#L308

**Comment by kepper** [comment]
mei-Neumes.xml also references `att.duration.musical`, which doesn't exist (anymore)

**Comment by bwbohl** [comment]
@music-encoding/ig-neumes could you please elaborate a fix and test the resulting schema against your respective sample data?

**Comment by musicEnfanthen** [comment]
According to #418 `att.duration.musical` is now `att.duration.logical`
