### ISSUE TITLE
plist available twice at tempo

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#633]
`att.plist` lists `<tempo>` twice in the "Available at" list:
https://music-encoding.org/guidelines/v4/attribute-classes/att.plist.html

**Comment by rettinghaus** [comment]
@kepper is there a quick fix for this?

**Comment by kepper** [comment]
No, but an assumption: `<dynam>` is also available twice. Both `<dynam>` and `<tempo>` are referenced in the `<desc>` on `<dir>`. Other attribute classes seems to have the same problem ([att.partIdent](https://music-encoding.org/guidelines/v4/attribute-classes/att.partident.html) also lists those elements twice). Apparently, the XSLT that extracts the elements also from the desc info, and doesn't do a `distinct-values` late enough in the game… Should be an easy fix, but I won't search just now…

**Comment by rettinghaus** [comment]
put it on the list then ;)

**Comment by rettinghaus** [comment]
@kepper any news on this?

**Comment by kepper** [comment]
I was hoping to find some time this week to work on such things for MEI – it's Thursday, and I haven't found that time so far :( I still have hopes for the afternoon, though. I'll prepare this for tomorrow, promised :-)

**Comment by kepper** [comment]
it seems like the current code for generating the guidelines (dev / v5) works just fine. The problem therefore affects the v4 guidelines only. However, those are a static dump of what we had before, and they're not re-generated anymore. This means that a fix to this would have to be through a something – either a script or some manual corrections – that fixes those static files. I'll try to  find out how often the problem actually occurs to be able take a decision on this.

**Comment by kepper** [comment]
it is triggered by the inclusion of `<gi>tempo</gi>` and `<gi>dynam</gi>` in `//elementSpec[@ident = 'dir']/desc`. This is the only element in v4 that has such references in it's description (there are a couple of attribute classes with similar references, but apparently they don't cause the same issues). This is good news, because it's possible to do a simple search and replace in the right folder… I'll prepare a PR, to be discussed tomorrow.
