### ISSUE TITLE
all lists should allow subgroupings

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#636]
Some list elements (`<biblList>`, `<eventList>`) allow subgroupings while others don't, i.e. MEI allows something like
```xml
<biblList>
  <biblList/>
  <biblList/>
  <biblList>
    <biblList/>
  </biblList>
</biblList>
```
but disallows the same with `workList` or `expressionList`.

**Comment by bwbohl** [comment]
Ok lists should definitely behave in a common way to some degree. But I think to some degree `biblList` originates from a earlier stage of modelling MEI than the rather recent `workList` and `expressionList`. The latter two now are to be seen in the FRBR-context which brings up the modelling of relations and thus `relationList`. The question consequently is: what does a nested list actually mean?

1) is it just a means of grouping?
2) does it bring hierarchical implications?
3) does it imply inclusion?
4) …

In this context, I'm not really sure about the meaning of:

> ```
> <biblList>
>   <biblList/>
>   <biblList/>
>   <biblList>
>     <biblList/>
>   </biblList>
> </biblList>
> ```

Maybe we should even discourage / disallow such use?

**Comment by pe-ro** [comment]
Nesting <biblList> permits the creation of, well, nested lists like –

<biblList>
  <head>My favorites</head>
  <biblList>
   <head>Movies</head>
    …
  </biblList>
  <biblList>
    <head>Books</head>
    …
   </biblList>
</biblList>

Not necessarily useful within a simple header, but potentially very useful in explanatory text that might be found in, say, a thematic catalog.

--
p.

**Comment by pe-ro** [comment]
<worklist> and <expressionList> intentionally do not allow for hierarchical relationships between their “items”.  Those relationships can be expressed in other ways.

**Comment by bwbohl** [comment]
That’s what I was trying to say, too ;-)
Thanks for putting it simple @pe-ro

**Comment by pe-ro** [comment]
Oh, I’m definitely good at being simple. 😊

Seriously, it must be remembered that many of the elements used in both the header and in the “text-y bits” serve multiple purposes – their nature is often not just “this *or* that”, but rather “this *and* that”.  I’m aware of the inconsistency, but inconsistency and ambiguity are, like the poor, with us always.

**Comment by bwbohl** [comment]
If you'd want a hierarchical organised list of works you probably should stick with `biblList` and make the entries reference the respective `work`
