### ISSUE TITLE
Coordinating triple sharp/flats in @accid and @accid.ges

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#639]
`note@accid` now allows for triple sharps/flats, so `note@accid.ges` should be updated to allow for the same:

| accid.ges | meaning | typical accid equivalence | 
|--------|----------|-------------------|
| `sss`    | triple sharp |  `xs`, `sx`, `ts` |
| `fff`      | triple flat | `tf` |

https://music-encoding.org/guidelines/v4/data-types/data.accidental.gestural.html
https://music-encoding.org/guidelines/v4/data-types/data.accidental.written.html

**Comment by earboxer** [comment]
We may want to support additional quartertone values so we don't leave any gaps:

[SMuFL has some glyphs for "Five-quarter-tones sharp" and others](http://www.smufl.org/version/latest/range/gouldArrowQuartertoneAccidentals24Edo/)

I guess I'm proposing addition of 2 values for "Five-quarter-tones flat" (-2.5 semitones) and "Five-quarter-tones sharp" (+2.5 semitones) for `accid.ges` (`ffd` and `ssu`), as well as values for `accid` (`fdf`, `xu`) and additional written accidentals for 3 quarter-tones flat and 3 quarter-tones sharp (`ffu`, `xd`), based on the SMuFL Gould arrow quartertone accidentals.

|semitone difference|accid.ges|meaning|accid equivalence|
|-----|----------|---------|---|
|-3     |**`fff`**       |triple flat|`tf`|
|-2.5  |**`ffd`**  |Five-quarter-tones flat | **`fdf`** (U+E279)|
|-1.5|`fd`|Three quarter-tones flat. | `3qf`, `fd`, **`ffu`** (U+E278)|
|1.5|`su`|Three quarter-tones sharp. | `3qs`, `su`, **`xd`**(U+E277)|
|2.5|**`ssu`**|Five-quarter-tones sharp | **`xu`** (U+E276)|
|3| **`sss`**|triple sharp | `xs`,`sx`,`ts`|

**Comment by rettinghaus** [comment]
Triple sharps and flats were added in #844. Closing for now. Please open a new issue if the allowed values should be changed again.
