### ISSUE TITLE
`@inth` inconsistently defined on `chordMember`

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#642]
The data type for `@inth` (`data.interval.harmonic`) requires information to be specified in diatones (https://music-encoding.org/guidelines/v4/data-types/data.interval.harmonic.html), while a remark on `<chordMember>` requires information in `@inth` to be specified in semitones (https://music-encoding.org/guidelines/v4/elements/chordmember.html). This needs to be resolved. I think the data type is correct (so use diatonic information, and change the remark), but maybe @pe-ro or someone else remembers this? (possibly related to #72)

**Comment by bwbohl** [comment]
@kepper I think you're completely right; although #72 suggests another original intent, the current situation definitely is inconsistent and should be fixed. While doing so, we should probably provide some examples resolving the resulting tokens to full names of intervals.

**Comment by pe-ro** [comment]
The remark should be corrected.

**Comment by gregchapman-dev** [comment]
There is also a (longer) wrong sentence or two in "10.2.1.1. Interpreted Chord Data in scoreDef" with a wrong example (wrong == `@inth` set to integer semitones)

**Comment by bwbohl** [comment]
@kepper any chances to provide a pull request for this during the next two weeks?
