### ISSUE TITLE
pedal line vs. pedstar 

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#644]
In `<pedal>` we can use `form="pedstar"` or `form="line"` to encode the first and the last case of the following example. 
![grafik](https://user-images.githubusercontent.com/7693447/73655674-cdc8a300-468e-11ea-804c-9f7b06321f8c.png)

To encode the middle one (which is quite common in modern notation) I recommend to add the value `"mixed"` to the value list.

**Comment by rettinghaus** [comment]
Addendum: how would you encode invisible pedal directions (for MIDI output)? As `@form` belongs to the visual domain, perhaps the value `"none"` should also added …

**Comment by rettinghaus** [comment]
Another question just popped up: 
If one wants to use a single (styled) 'P' instead of the 'Ped' glyph, should always `@glyph.name` or `@glyph.num` be used, or would it make sense to have a more explicit MEI way? 
(MusicXML 3.1 added the `abbreviated` attribute to address this, which is a bit confusing, as "Pet." and "Sost." are already abbreviated.)

**Comment by lpugin** [comment]
I would suggest to have `pedline` instead of `mixed` because it would be clearer.
