### ISSUE TITLE
specify scope of system.leftline

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#649]
The guidelines say about `@system.leftline` on `<scoreDef>`:
> Indicates whether the staves are joined at the left by a continuous line. The default value is "true".

To me it's not completely clear what should happen to one-staff systems. 
Normally single staves do not have a starting bar line, yet the default value is "true". If this attribute only applies to multi-staff systems, a single staff *never* could be drawn with a line at the beginning of the system. 
We should drop the un-MEI-ish default value and better say 

> Indicates whether the system starts with a continuous line connecting all staves.

**Comment by kepper** [comment]
agreed

**Comment by bwbohl** [comment]
Agree aswell,
Maybe we should indicate that this also includes the case of a single-staff system?
