### ISSUE TITLE
Accidental contained by Syllable (Neumes Module)

### ISSUE THREAD

**Issue by timeipert** [music-encoding/music-encoding#665]
I would suggest resuming `accid` as a child element of `syllable` for neumatic notations.

In v3, `accid` could be contained by `syllable`. In v4 this is not the case. @th-we mentioned that it was intentionally dropped because it makes no sense in the context of CWN. 

However, it is not always clear which note is affected by an accidental in neumatic notation.
In many cases, it would be the best way to have an autonomous element that just indicates an occurrence of an accidental in the manuscript.

**Comment by th-we** [comment]
(Just a remark: I'm not sure it was intentionally dropped, that was just a hunch. I'd have to look at the git history to confirm that.)

**Comment by th-we** [comment]
I realized that this is still possible with the mei-all schema, so I was wrong.

**Comment by th-we** [comment]
@pe-ro Do you recall why you made `mode.noteModifierLike` a member of `model.layerPart.mensural` instead of `model.layerPart.mensuralAndNeumes` in 43dee39?

**Comment by pe-ro** [comment]
Not 100% sure now, but it probably had to do with creation of an ambiguous content model.  Ambiguous content models are fine in an RNG schema, but not in an XSD.  I think it's important to support both even though most people are using RNG (I assume).

**Comment by kepper** [comment]
this will be addressed in the context of #968, so closing this one
