### ISSUE TITLE
Restriction on graceGrp

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#673]
I have a question regarding the Schematron restriction on `<graceGrp>` that invalidates the use of a `<graceGrp>` with a single note or an single chord. I wonder if we really need this. I personally think that it would be acceptable to allow the use of  a `<graceGrp>` container around a single note / chord. Any thoughts?

**Comment by pe-ro** [comment]
The intention of the Schematron is to enforce the "group-ness" of something called "graceGrp".  😀 A group containing a single member is still a group, so I'm not completely opposed to lifting the restriction.  But, what's the reason for removing it?

**Comment by rettinghaus** [comment]
There is no real reason why single grace notes should be treated different than groups of grace notes. It would make sense, if Schematron wouldn't allow the succession of grace notes that are not within a graceGrp container.

**Comment by lpugin** [comment]
> But, what's the reason for removing it?

Simply to allow it. It is essentially a matter of clarity and consistency. I find grace notes that are given a distinct container better structured and in a way is easier to understand (at both human and machine levels). See:
```xml
<beam>
   <note dots="1" dur="8" oct="4" pname="b" />
   <note grace="acc" dur="16" oct="5" pname="c" />
   <note dur="16" oct="4" pname="b" />
</beam>
```
versus
```xml
<beam>
   <note dots="1" dur="8" oct="4" pname="b" />
   <graceGrp grace="acc">
      <note dur="16" oct="5" pname="c" />   
   </graceGrp>
   <note dur="16" oct="4" pname="b" />
</beam>
```
No other reason. They are basically the same.

**Comment by pe-ro** [comment]
They are basically the same, but I would've thought you would prefer the "one grace note = `<note>` but more than one grace note = `<graceGrp>` plan".  If the Schematron rule is removed, then there's the potential for more confusion because sometimes "one grace note = `<note>`" but in other cases "one grace note = `<graceGrp>`".  In other words, there's no way to force encoders to use your 2nd method instead of the 1st.  Verovio will still have to support both approaches.

**Comment by rettinghaus** [comment]
Verovio isn't the problem (as it supports both).

**Comment by pe-ro** [comment]
Nothing prevents one from using --
```
<note grace="acc" dur="16" oct="5" pname="c" />
<note grace="acc" dur="16" oct="5" pname="d" />
<note grace="acc" dur="16" oct="5" pname="e" />
```
This is actually the simplest way of representing single grace notes as well as groups (unless the note or group is a Nachschlag, in which case one must use `<graceGrp>`).  The point of `<graceGrp>` is to provide a "handle" for saying something about the grace notes as a group.  For example,
```
<graceGrp color="red" grace="acc">
   <note dur="16" oct="5" pname="c" />
  <note  dur="16" oct="5" pname="d" />
  <note dur="16" oct="5" pname="e" />
</graceGrp>
```
as opposed to 
```
<note grace="acc" dur="16" oct="5" pname="c"  color="red"/>
<note grace="acc" dur="16" oct="5" pname="d"  color="red"/>
<note grace="acc" dur="16" oct="5" pname="e"  color="red"/>
```
Of course most cases are possible where `<graceGrp>` contains a single note, but they make somewhat less sense.  And, like I said above, there's no way to represent a Nachschlag using the latter method.

HTH

**Comment by pe-ro** [comment]
> Verovio isn't the problem (as it supports both).

Thanks, Klaus.  I thought so.

**Comment by lpugin** [comment]
I am not convinced because I find it arbitrary to decide that having a `<graceGrp>` with one single element is invalid. Obviously allowing it would not mean that it has to be encoded like this. It is currently possible to encode groups of grace notes with or without `<graceGrp>`. How would allowing `<graceGrp>` with one single element be more confusing than this? Isn't it just two ways to encode the same thing in the same way you can encode groups in two ways?

**Comment by pe-ro** [comment]
I'm not opposed to the suggested change, just trying to understand its implications.

**Comment by kepper** [comment]
There are similar situations in MEI where we enforce a *Grp, even for a single child element. I'm thinking about `<staffGrp>`, for instance. From that perspective, I don't see a problem to have `<graceGrp>` for single graces. The thing I'm slightly concerned with is that one needs to check for both conditions when looking for grace notes, but that's the case already anyway, and so an XPath (or similar selection mechanism) wouldn't get more complicated by this change. I don't have a strong opinion on this one, as it doesn't have huge consequences. It may improve consistency, but only a bit from my perspective…

**Comment by lpugin** [comment]
@pe-ro do you think this needs further discussion? No problem if we need to, but if not I can prepare a PR

**Comment by pe-ro** [comment]
@lpugin, I'm fine with proceeding with a PR.
