### ISSUE TITLE
Update meiversion list

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#675]
The develop version of the schema restricts /mei@meiversion to 4.0.0 and 4.0.1. This is not accurate and it would probably be wise to have a way to distinct files validated against a develop version of the schema that it not version 4.0 anymore. (This is currently a problem for Verovio because it cannot make the distinction between the type of files being passed to it. However, this is probably a problem not only for Verovio, which is the reason why I am opening an issue.)

**Comment by kepper** [comment]
since we're looking at a v5 at some point, I'd recommend to allow something like a regex expressing something like `>=5.0.0-0 <5.0.0` (see https://jubianchi.github.io/semver-check/#/%3E%3D5.0.0-0%20%3C5.0.0/5.0.0-0). Eventually, this means we'd have to increment the last digit with each commit, which seems rather impractical. Not sure yet what to do…

**Comment by ahankinson** [comment]
Would it make sense to set the value of meiversion to just the major, or possibly major.minor? “5” or “5.0”?

**Comment by kepper** [comment]
I would say we should set it to something pre-5, but post-4. However, I'm not sure how where this should be validated – in the data, or in an application. Should we have only one single value in the schema for pre-5, or shall we be more specific? I think for all subsequent releases of 5, we need to be specific, but one should perhaps not expect a huge amount of consistency of an explicit dev version, right?

**Comment by lpugin** [comment]
Something like "5.0.0-dev" would be appropriate in my opinion. I don't think we can reasonably have a version number (5.0.0-0) for each commit, even though strictly speaking this would be better.

**Comment by lpugin** [comment]
Anybody opposed to "5.0.0-dev"? If not I am happy to prepare a PR for this.

**Comment by rettinghaus** [comment]
If I'm not wrong, we're still fixing bugs for a minor release. @bwbohl? @kepper?

**Comment by lpugin** [comment]
I think you are wrong. We already had several PR merged that introduced modifications (mostly additions) to the schema.

**Comment by rettinghaus** [comment]
But we have a `MEI 4.1.0` milestone and a `MEI 5.0.0` milestone.

**Comment by lpugin** [comment]
Correct. As far as I can see we have no corresponding branches, and 66 issues with no milestone. Things become quite difficult to track....

**Comment by bwbohl** [comment]
> Correct. As far as I can see we have no corresponding branches, and 66 issues with no milestone. Things become quite difficult to track....

Yeah , trying to tackle this at the moment but unfortunately time has been scarce for the last couple of weeks. Probably you're right, that separate branches could be helpful for that…

Concerning the additions: introducing them made clear that we're not talking 4.0.x anymore but 4.1.0. So I tried to put  issues and PRs either in 4.1 (if not breaking compatibility) or in 5.0 (if braking compatibility)

**Comment by lpugin** [comment]
Follow-up from the discussion during the ODD meeting:
* The proposal is to have the develop branch carrying a `-dev` version number.
* The version number itself will be the one of the next planned release (either a minor or a major one)
* Determining whether it has to be a minor or a major release depends on the changes currently in the branch
* When a schema is built from the develop branch, the SHA of the commit is added as a comment into the Schema file

Example:
* The current develop branch should have a version number `4.1.0-dev` if the changes are not breaking compatibility, or `5.0.0-dev` if they are.
* When we make the release (4.1 or 5.0), the develop branch moves to 4.2.0-dev or 5.1.0-dev

Please speak up if you have any objection to this. Otherwise it will be applied for the next release onwards.

**Comment by ahankinson** [comment]
Do you mean adding a new entry to the list available here? https://github.com/music-encoding/music-encoding/blob/develop/source/modules/MEI.shared.xml#L1853-L1869

**Comment by rettinghaus** [comment]
@lpugin isn't this solved by now?

**Comment by lpugin** [comment]
Yes https://github.com/music-encoding/music-encoding/commit/c838d80ef60d40397d40344c9e3f65af9bfe826e
