### ISSUE TITLE
Schema update via Travis or GitHub Actions

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#677]
It seems that the schema available in https://github.com/music-encoding/music-encoding/tree/develop/schemata are not up to date. Isn’t it expected to have them build / updated on every commit to develop?

**Comment by bwbohl** [comment]
thanks for spotting this, actually very critical issue!!

**Comment by bwbohl** [comment]
actually I don't find any deploy keys in this repo for travis and no corresponding deploy action in the travis config… the only thing being deployed after build is the guidelines part in the guidelines repo

**Comment by ahankinson** [comment]
I think I might need to get involved in this, since I believe it deploys with my credentials. Can this wait a couple days?

(We really should investigate moving to GitHub actions for building and deploying. Travis is a pain.)

**Comment by ahankinson** [comment]
Ah! But re-reading this I think it’s working as expected. We didn’t ever have it deploy the built schemas AFAIK...

**Comment by bwbohl** [comment]
> Ah! But re-reading this I think it’s working as expected. We didn’t ever have it deploy the built schemas AFAIK...

I think you're absolutely right Andrew, nevertheless I think it would be worthwhile changing this behaviour ;-)

**Comment by bwbohl** [comment]
> (We really should investigate moving to GitHub actions for building and deploying. Travis is a pain.)

maybe GitHub actions would be even better for doing this

**Comment by kepper** [comment]
If I remember correctly, we decided to move back to specs and guidelines in one repo, i.e. everything back to ODD. This was scheduled for November, and I started preparations for that already. Of course we can discuss how to do that, and maybe even reconsider the decision. We should just avoid that we start working in multiple directions. I'm sorry I've been so silent over the last couple of weeks. This week is [ESS](https://ess.upb.de) and after that, I'll have more time for MEI again…

**Comment by lpugin** [comment]
I am not sure having the schema built and published on commits relates to the move back to ODD, unless we move away from GitHub or change the structure of the Schema itself. But maybe I am misunderstanding something...

**Comment by kepper** [comment]
It's not necessarily a contradiction – we just need to reconfigure the whole setup, as I would mostly like to get everything in one repo. This just means we don't need cross-repo triggers. This is not to stop us from fixing it now, it's just to make sure we don't overengineer the current situation if we (still) agree that we want to get away from it. I can't judge the effort at this point, and haven't spent a lot of thought on the build setup yet…

**Comment by bwbohl** [comment]
Getting all in one Repo again, has nothing to do with pushing build artefacts to the repo
