### ISSUE TITLE
Neume schema requires that <clef> be within a <syllable>

### ISSUE THREAD

**Issue by timothydereuse** [music-encoding/music-encoding#688]
Currently, `<clef>` is marked as a member of `model.eventLike`, and in the `mei-Neumes` customization this class is forbidden from occurring within `<layer>`. Semantically, it seems off that clefs must be assigned to a syllable; is there a reason for this behavior, or could there be change to allow clefs to exist in layers alongside syllables?

@JRegimbal suggested to me that the simplest potential way of doing this would be to  add `model.layerPart` to the list of classes that `<clef> is a member of.

**Comment by kepper** [comment]
Hi @timothydereuse, please excuse the late answer. I'm not much into the concept model of the `mei-Neumes` customization, but I can happily verify that your proposed solution would solve the problem as you described. I don't know if this has been discussed with the interest group already, but I think it would be best to reach consensus there before trying to implement this. Like I said, I'm not very much into this, and can't foresee potential side effects… 
All best, jo

**Comment by kepper** [comment]
this seems to be a sub-problem of #968, so we'll be addressing this over there. Re-open if our solution is inadequate :)
