### ISSUE TITLE
Request: bracketSpan as a child of section

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/music-encoding#692]
Brackets are used in modern transcriptions to indicate where a ligature was placed in the original mensural piece. These brackets can be indicated in CMN using the `<bracketSpan>` element as a child of `<measure>`. 

When scoring up a mensural piece—this is, aligning the voices in score layout, but preserving the original mensural notation values—it is desirable to divide ligatures into the individual notes to better visualize the alignment of the notes in the different voices. So, the use of the `<bracketSpan>` would also be desired here, to show which individual notes were part of a ligature in the original source. But, because we are still in mensural notation, there are no `<measure>` elements to contain these `<bracketSpan>` elements. It would be useful for `<bracketSpan>` to be allowed as a child of `<section>` (at least for mensural notation), so that we can visualize these brackets in pieces encoded in mensural notation (with no measures) where ligatures have been separated into their individual component notes (for facilitating the visualization of the alignment of the voices and the vertical sonorities).

**Comment by lpugin** [comment]
Would it work for you to use MEI-all? In general its used should be discouraged, but for transitional statuses that clearly mix notation types, I think it makes sense to use it.

**Comment by martha-thomae** [comment]
MEI-all would indeed allow me to use `<bracketSpan>` (since it is part of MEI.cmn), that is true!
But I will still have the issue of "where" to use this element. There doesn't seem to be any good candidate for a parent of `<bracketSpan>` when encoding mensural notation (because I don't have any `<measure>` elements in my Mensural MEI file to use as parents for `<bracketSpan>`).

**Comment by martha-thomae** [comment]
I am editing the customization file for mensural notation to solve this problem. So that `<bracketSpan>` is available as a child of `<section>` just for mensural notation. It should work as usual (child of `<measure>`) if we don't use the mensural customization.

**Comment by lpugin** [comment]
Can be closed because solved differently. See #771
