### ISSUE TITLE
guidelines: documentation seems to be in conflict with valid Neume MEI file structure

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/music-encoding#694]
Even though `<neume>` elements are not valid children of `<layer>`, the documentation [here](https://music-encoding.org/guidelines/v4/elements/neume.html) says that they are. 

This documentation is based on what it is written in the schema, so I don't understand from where it is getting this information that `<neume>` may be contained in `<layer>` because when I use the current schema for neumes, I get a validation error when using `<neume>` as a direct child of `<layer>` (see file attached).

[neume_example.mei.zip](https://github.com/music-encoding/music-encoding/files/4935142/neume_example.mei.zip)

**Comment by rettinghaus** [comment]
The documentation for neume notation is outdated, e.g., `ineume` and `uneume` were removed for MEI4, yet they are still documented in https://music-encoding.org/guidelines/v4/content/neumes.html#neumesNotation (same for development version). 

Could anyone from @music-encoding/ig-neumes fix this, please?

**Comment by ahankinson** [comment]
@rettinghaus where do you see their documentation? A link to it would help in fixing it.

I don't know that tagging it on this issue is correct, though -- perhaps a new issue is needed for removing it? This issue is about figuring out if `<neume>` can/should/is allowed as part of `<layer>`.

**Comment by bwbohl** [comment]
@martha-thomae could you please double-check if this problem is still true for the dev version?

**Comment by kepper** [comment]
The problem still persists – the last paragraph in [6.3 Neume Notation and MEI](https://music-encoding.org/guidelines/dev/content/neumes.html#neumesNotation) still mentions `<ineume>` and `<uneume>`, even in weird ways. The whole order of things in chapter 6 seems odd – more like a compilation of other chapters, that needs to be sorted. At the current Charlottesville dev meeting, @pe-ro has proposed a better structure, which includes dropping some paragraphs. Pinging the @music-encoding/ig-neumes and @vigliensoni to reach out and discuss this, so we can get this fixed for the upcoming release (we're won't have time to get in all kinds of improvements, but we should avoid releasing incorrect documentation at least…)

**Comment by martha-thomae** [comment]
Hi everyone!
So the thing is that this issue became two:
1. The one I pointed out originally, which was about the schema documentation (not guidelines) where it seemed like `<neume>` could be a child of both `<layer>` and `<syllable>`, when it was only supposed to be a child of `<syllable>` and invalid as a child of `<layer>`
2. The documentation in the guidelines that still includes old elements like `<ineume>` and `<uneume>`.

Both issues persist, but talking about issue number one:

Here you can see that even though the use of `<neume>` as a child of `<layer>` is marked as **invalid** when using the schema (dev version, but also true for current version),

![Screenshot 2023-05-25 at 11 02 30 AM](https://github.com/music-encoding/music-encoding/assets/13948831/7809a494-d206-4ef9-ad73-5ea7abff35f2)


the documentation of the schema says it is supposed to be valid, as indicated in the following screenshot where it says that `<neume>` may be contained in `<layer>`

![Screenshot 2023-05-25 at 11 01 18 AM](https://github.com/music-encoding/music-encoding/assets/13948831/c8ecdf9f-83fc-47a5-955d-799a5e7ce66e)

Now that I am looking again into this, the reason why the documentation in the schema (previous screenshot) says that `<layer>` may contain `<neume>` is because it is probably the case when using **mei-all** instead of the neume customization. Indeed, that is the case, see next screenshot where I am using **mei-all** rather than **mei-Neumes**:
![Screenshot 2023-05-25 at 11 08 56 AM](https://github.com/music-encoding/music-encoding/assets/13948831/ac3c9682-3be7-4ddf-b600-6f06c09441e8)

**Comment by martha-thomae** [comment]
I raised this issue because I noticed that the documentation misguided some people when encoding neumes. They encoded them in the layer, even though they were not supposed to do it like that, and were supposed to use them within the `<syllable>` element instead.

**Comment by musicEnfanthen** [comment]
Thanks @martha-thomae for investigating. So this seems connected to have specific guidelines for customizations, cf. #1137

**Comment by fujinaga** [comment]
> The problem still persists – the last paragraph in [6.3 Neume Notation and MEI](https://music-encoding.org/guidelines/dev/content/neumes.html#neumesNotation) still mentions `<ineume>` and `<uneume>`, even in weird ways. The whole order of things in chapter 6 seems odd – more like a compilation of other chapters, that needs to be sorted. At the current Charlottesville dev meeting, @pe-ro has proposed a better structure, which includes dropping some paragraphs. Pinging the @music-encoding/ig-neumes and @vigliensoni to reach out and discuss this, so we can get this fixed for the upcoming release (we're won't have time to get in all kinds of improvements, but we should avoid releasing incorrect documentation at least…)

I'm reaching out. How should we proceed?

**Comment by vigliensoni** [comment]
Those guidelines were approved by the IG, and the pull request was
accepted and merged before the ODD Friday session in July 2020.

Upon revisiting subsection 6.3, I believe the reference to `<ineume>`
and `<uneume>` is meant for historical approaches to describe
notations (as referenced in the literature cited in that section). If
that reference causes confusion, in my opinion, you may consider
omitting it.

@fujinaga, there is a development repository for the guidelines on the
DDMAL Github. We used that repository for working and testing before
submitting the pull request.

https://ddmal.music.mcgill.ca/guidelines/v4/content/neumes.html

**Comment by musicEnfanthen** [comment]
Thank you @vigliensoni for clarification. 

Indeed, the passage about the former usage in MEI v3 with `uneume` and `ineume` caused most of the confusion. I personally like the historical reference, but others may see it different (there is the argument that the current guidelines should only describe the current encoding approaches). 

Maybe there is a way to rephrase that passage and make very clear that the elements in question are outdated (or only available in MEI v3), and now another approach is used? I guess this was already tried to address in #1105, but obviously to no avail...

**Comment by bwbohl** [comment]
I consider 1. fixed, nevertheless 2. is still a problem for the MEI neumes schema. This is because in mei-all this is valid and allowed. So actually we need customization specific specs.

**Comment by fujinaga** [comment]
We'll update the last paragraph of 6.3 in the Guideline very soon.

**Comment by bwbohl** [comment]
Please add a hint that the specs say it's possible, although it's disallowed in the customization because the specs reflect mei-all.

**Comment by pe-ro** [comment]
@bwbohl's suggestion is good.  Generally, the Guidelines describe the entirety of MEI; that is, mei-all.  Restrictions imposed by a particular module/customization should be noted.

**Comment by bwbohl** [comment]
Maybe in the future we will have customization-specific specs ;-)

**Comment by riedde** [comment]
MEI Developer Workshop 2024: Maybe a note is useful which says that this is possible in MEI All, but not in the customization MEI Neumes. Maybe as a remark at the element definition of [`<neume>`](https://music-encoding.org/guidelines/v4/elements/neume.html)? @fujinaga @vigliensoni

**Comment by bwbohl** [comment]
> MEI Developer Workshop 2024: Maybe a note is useful which says that this is possible in MEI All, but not in the customization MEI Neumes. Maybe as a remark at the element definition of [`<neume>`](https://music-encoding.org/guidelines/v4/elements/neume.html)? @fujinaga @vigliensoni

https://github.com/music-encoding/music-encoding/issues/694#issuecomment-1591162293

**Comment by fujinaga** [comment]
Can someone add a well-worded hint in the appropriate place to be not confusing? If I do this, it may cause further confusion.

**Comment by annplaksin** [comment]
Maybe something like this?
> The MEI Neumes customization restricts the use of this element. This customization disallows `<neume>` as a direct child of `<layer>`.

@bwbohl @riedde @musicEnfanthen @fujinaga

**Comment by musicEnfanthen** [comment]
@fujinaga Can you have a look at https://github.com/music-encoding/music-encoding/pull/1405 if that would be fine?

**Comment by fujinaga** [comment]
Approved.
