### ISSUE TITLE
Rossini hairpins

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#709]
Rossini used closed hairpins. It would be nice to have a proper way of encoding this. 

![Rossini-aacent](https://user-images.githubusercontent.com/7693447/93790962-e85a8700-fc33-11ea-9e32-4b0eb346f324.png)
![image-20200918-052402](https://user-images.githubusercontent.com/7693447/93790972-ebee0e00-fc33-11ea-8bba-20cd33c180d1.png)
![image-20200918-052508](https://user-images.githubusercontent.com/7693447/93790982-ee506800-fc33-11ea-8a71-fce5086daddd.png)

**Comment by craigsapp** [comment]
The simplest would be:

```
    <hairpin  staff="1" tstamp="1" tstamp2="0m+4" form="cres" closed="true"/>            
```

How does he deal with a hairpin that crosses a system break?   Are the starting/endings of at the system break closed as well?

**Comment by rettinghaus** [comment]
@craigsapp Haven't seen a case where they go over a system break. These hairpins are always rather short.
