### ISSUE TITLE
@upperaccid.ges/@loweraccid.ges

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#710]
Here is an example of a turn, where the lower-note accidental is placed above the turn:

![strange-turn-acc1](https://user-images.githubusercontent.com/29225574/94137319-87ff5b80-fe66-11ea-9a55-67057daa5cd7.png)

For visual fidelity, this accidental must be placed in `turn@accidupper`, but for gestural fidelity it should be placed in `turn@accidlower`; otherwise, rendering of this turn (such as in a MIDI conversion) will be incorrect.

Extra attributes should be added to `<turn>` to allow this case.   I think I have seen this in printed editions as well: the most common note to alter would be the lower auxiliary note, converting it into a minor second leading tone.   In this case the scribe leaves it to the performer to figure that out.

Additional attributes to distinguish between visual and gestural accidental would be useful for other corner cases.  I propose adding `@accidupper.ges` and `@accidlower.ges` which would act in a similar manner to `note@accid` and `note@accid.ges`.

So the second turn in the above example would be encoded as:

```xml
<turn staff="1" accidupper="s" accidupper.ges="n" accidlower.ges="s" form="upper" />
```

Adding `@accidupper.ges` and `@accidlower.ges` would also localize the accidentals of the auxiliary notes which would simplify conversion to MIDI, since the accidental states of the auxiliary notes would not need to be inferred from the key signature and previous accidental states of notes in the measure.  This is a non-trivial process, similar to inferring `note@accid.ges`.

This is related to issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/425.

**Comment by frakel** [comment]
Another approach would be to see this as a writing (or printing) error. We have actually very straightforward ways to encode cases like this (see "Apparent Errors" in the MEI Guidelines). The encoding would be much simpler and easier to understand and you would have all the possibilities of rendering alike.

**Comment by craigsapp** [comment]
If the scribe wrote the accidentals on the turns in an inconsistent manner, then I would call it a scribal error.  I have asked Jacek if there are other turns in the same music that have accidentals on them.  

If there happens to be more turn accidentals notated in the same way, I would less like calling them errors rather than deviations from standard modern notation practice.  This could fit into sic/corr, but seems less suited since it would be intentional by the scribe rather than unintentional.  Or perhaps you were thinking of the `<reg>` method from the [Regularization and Normalization](https://music-encoding.org/guidelines/v4/content/scholarlyediting.html#edittransReg) section below the documentation for sic/corr, since that seems better for this sort of situation.

Here is the [Apparent Errors](https://music-encoding.org/guidelines/v4/content/scholarlyediting.html#edittransErrors) section of the Guidelines.  You can add links to issues text using this Markdown construction:

```
[text for link](link)
```

Such as in this case:

```
 [Apparent Errors](https://music-encoding.org/guidelines/v4/content/scholarlyediting.html#edittransErrors)
```

------------------

Regardless, there will eventually be an issue related to the rendering of ornaments (trills, mordents, turns, etc), which verovio currently does not deal with.   So it would be wise to implement `@accidupper.ges` and similar for ornaments.   If there is no gestural information about the accidentals of auxiliary ornament notes, there will be similar difficulties as when converting `<notes>` into MIDI when `@accid.ges` is not encoded.  Note that your benefactor is obsessed with ornament realization, so you should either avoid doing it yourself, or get it right the first time...

-----------------

Humdrum has a system analogous to `<sic>`/`<corr>` that could be used:
     https://doc.verovio.humdrum.org/filter/sic
although I have not mapped it to the MEI system yet in the converter.  But for this particular case I created a parameter to switch the placement of the accidentals so that the lower accident would be displayed above the turn:

<img width="826" alt="Screen Shot 2020-09-25 at 12 28 28 PM" src="https://user-images.githubusercontent.com/3487289/94307971-9f078180-ff2a-11ea-8fdc-bfc8495b570d.png">

**Comment by frakel** [comment]
Yes, MIDI rendering seems to be a more convincing reason for implementing `@accidupper.ges` & `@accidlower.ges` than individual scribal or regional conventions which however should be marked up as _deviations_ from CMN

**Comment by craigsapp** [comment]
Here is the manuscript source:  http://bc.bdsandomierz.pl/dlibra/publication/1283/edition/1251/content

There are four cases of turns with accidentals, all of which have the same convention that the accidental which is shown above the turn is meant to be applied to the lower auxiliary note:

<img width="233" alt="Screen Shot 2020-09-28 at 2 34 41 AM" src="https://user-images.githubusercontent.com/3487289/94416094-3fc88d80-0133-11eb-8793-c462fa752dad.png">
<img width="211" alt="Screen Shot 2020-09-28 at 2 34 46 AM" src="https://user-images.githubusercontent.com/3487289/94416097-422ae780-0133-11eb-9e88-480038efb3c6.png">
<img width="239" alt="Screen Shot 2020-09-28 at 2 34 52 AM" src="https://user-images.githubusercontent.com/3487289/94416105-43f4ab00-0133-11eb-9a8e-1933baeedb32.png">
<img width="249" alt="Screen Shot 2020-09-28 at 2 34 56 AM" src="https://user-images.githubusercontent.com/3487289/94416109-45be6e80-0133-11eb-824a-a4dac0748b55.png">

And the realization of each:

<img width="933" alt="Screen Shot 2020-09-28 at 2 27 18 AM" src="https://user-images.githubusercontent.com/3487289/94416149-52db5d80-0133-11eb-882e-dd4fb039b644.png">
