### ISSUE TITLE
Add attribute to describe directives

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#712]
In many cases, directives (`<dir>`) fulfill a distinct purpose. For example, `<dir>l.v.</dir>` fulfills the role of a `<lv>`. In such cases, it would reinforce the model to have an attribute to describe them explicitly. An open list of values is probably desirable. 

Proposals for the attribute name: `@dirtype`, `@func`. Others?

**Comment by pe-ro** [comment]
We've been down this road before.  There may be others, but the options that immediately come to mind are:

- use a single attribute, such as `@type` or `@func`, across multiple elements;
- use a different attribute, like `@dirtype` or `@dirfunc`, on every element requiring such an attribute; or
- keep `@type` (with no constraints on its value) and add `@func`, `@dirtype`, etc. with a semi-closed or closed set of values.

The first option leads to multiple, context-dependent definitions of different attributes, all of which have the same name.  The second option leads to an explosion of attributes -- `@dirfunc, @chordfunc, @notefunc`, ad infinitem.  The last option creates more confusion than it resolves.

In my opinion, the best (or in some people's opinion, the least bad) option is the first one.  But, having spent a great deal of time purging multiple definitions of `@type`, it seems ironic to return to the "bad old days".

**Comment by pe-ro** [comment]
By the way, @lpugin, I think you meant "A _semi-closed_ list of values is probably desirable."

**Comment by pe-ro** [comment]
`@func` is already used multiple times in the schema -- on `<accid>`, `<curve>`, `<tempo>`, etc.  -- so adding it to `<dir>` makes sense.

**Comment by lpugin** [comment]
> In my opinion, the best (or in some people's opinion, the least bad) option is the first one. But, having spent a great deal of time purging multiple definitions of @type, it seems ironic to return to the "bad old days".

My understanding was that the goal of purging definitions of `@type` was to have that attribute never precisely defined in MEI and to leave it to be freely defined for application-specific purposes. So I would certainly not use `@type` with a semi-closed list here. I don't think using `@func` would be a return to the "bad old days", but maybe I am missing a point here. Am I?

**Comment by pe-ro** [comment]
Yes, the goal of removing the multiple definitions of `@type` was to reserve `@type` for application-specific purposes.

The major issue with adding `@func` is that the value space of `@type` and `@func` will overlap if a semi-closed list is used for the values of `@func` -- that is, when both attributes may have uncontrolled content, there's no real difference between

```@type="lv"``` and ```@func="lv"``` 

So, even though it's not always the case in the current schema, for `@func` to be most effective, it should use a controlled vocabulary; i.e., closed value list.

**Comment by lpugin** [comment]
> So, even though it's not always the case in the current schema, for @func to be most effective, it should use a controlled vocabulary; i.e., closed value list.

I would be absolutely fine with a closed list.

**Comment by bwbohl** [comment]
Why not use `@class` for that? This would allow you to either use a vocabulary defined in your meiHead or even point to an existing classification system or ontology.

MAybe on the long run it would be desirable for MEI to publish controlled vocabularies or ontologies for certain aspects. I don't know if there's anything for directives already, maybe @musicEnfanthen or @musicog know something?

**Comment by lpugin** [comment]
> Why not use @class for that? This would allow you to either use a vocabulary defined in your meiHead or even point to an existing classification system or ontology.

Of course, this is always possible. But I think we are looking here at something that can get a community acceptance and enhance interoperability. The use of `@class` or `@type` always remains possible for other cases. (In fact, you are making a good point that we should probably encourage encoders to use `@class` with a defined vocabulary instead of `@type`.)

**Comment by lpugin** [comment]
Since there is no consensus and no clear general need for this proposal I am closing this issue. As always, it can be reopen in the future as needed.
