### ISSUE TITLE
Why is @staff recommended?

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#713]
On layer elements like `note`, `space`, and `rest` the Guidelines denote the `@staff` attribute as `recommended`. 
Could this only be shown on control elements and not on layer elements?

**Comment by bwbohl** [comment]
Well actually it's never bad to supply explicit markup instead of implicit markup…
nevertheless if it's a schematron rule, yes it could be modified to only capture control events or not inline events.

Where do we want to push people?

**Comment by pe-ro** [comment]
@rettinghaus , can you point to a specific place in the Guidelines where `@staff` is recommended, please?

**Comment by rettinghaus** [comment]
@pe-ro in `MEI.shared`:

```xml
  <classSpec ident="att.staffIdent" module="MEI.shared" type="atts">
    <desc xml:lang="en">Attributes for identifying the staff associated with the current feature.</desc>
    <attList>
      <attDef ident="staff" usage="rec">
        <desc xml:lang="en">Signifies the staff on which a notated event occurs or to which a control event
          applies. Mandatory when applicable.</desc>
        <datatype maxOccurs="unbounded">
          <dataRef name="positiveInteger"/>
        </datatype>
      </attDef>
    </attList>
  </classSpec>
```

https://github.com/music-encoding/music-encoding/blob/e7afd155b6baca8535d8b3a16d51d9c041949dcd/source/modules/MEI.shared.xml#L2995

**Comment by bwbohl** [comment]
Maybe a slight modification to the descripition would clarify things? E.g.:

Signifies the staff on which a notated event occurs or to which a control event
          applies. Mandatory when applicable, e.g., in case when the association to a staff is not clear from an elements xml context.
 
Clear for `<note>`:
```xml
<staff n="1" xmlns="http://www.music-encoding.org/ns/mei">
    <layer n="1">
        <note></note>
    </layer>
</staff>
```

Unclear for `<dir>`
```xml
<measure xmlns="http://www.music-encoding.org/ns/mei">
    <staff n="1">
        <layer n="1">
            <note />
        </layer>
    </staff>
    <staff n="2">
        <layer n="1">
            <note />
        </layer>
    </staff>
    <dir tstamp="1">morendo</dir>
</measure>
```

@rettinghaus is there also a schematron rule for validating this?

**Comment by bwbohl** [comment]
same of course should apply to `@part`, `@layer`

**Comment by pe-ro** [comment]
The "mandatory when applicable" language is common in metadata circles. It just means "be explicit when necessary."  The `<attDef ident="staff" usage="rec">`
declaration doesn't actually enforce anything.  In the end, it's resolved to "optional".  But it serves a documentary purpose.

Changing the description to -- 
"Signifies the staff on which a notated event occurs or to which a control event
applies. Mandatory when applicable, e.g., in case when the association to a staff is not clear from an element's xml context." is fine.

@bwbohl is correct, the declarations of `@part` and `@layer` should have `usage="rec"` as well.

**Comment by ahankinson** [comment]
I'm kinda with @rettinghaus here -- the recommendation will always apply, regardless of the specific context of use, and `@staff` is only really applicable when you want to do cross-staff things (i.e., a very small percentage of the time in most repertoires). 

It seems misleading to recommend its usage when it's usually not applicable.

In contrast, `@pname` is only marked as `opt` -- I would think its usage is more recommended than `@staff`. 

https://github.com/music-encoding/music-encoding/blob/e7afd155b6baca8535d8b3a16d51d9c041949dcd/source/modules/MEI.shared.xml#L2497

**Comment by pe-ro** [comment]
If `usage="rec"` is confusing, remove it.  It just gets resolved to "opt" anyway.

**Comment by lpugin** [comment]
Changing to `opt` seems OK to me.

**Comment by musicEnfanthen** [comment]
Guess this should apply to https://music-encoding.org/guidelines/v5/attribute-classes/att.origin.staffIdent.html then as well?

**Comment by rettinghaus** [comment]
No, this is a different case.

**Comment by bwbohl** [comment]
I agree with @rettinghaus that this is a different case. Nevertheless, we also should consider the wording in the element descriptions and the constraintSpecs in the contexts of some elements that can bear these attributes. But that seems to me like another issue. We should then probably modify these attributes in the contexts of the respective element declarations, to be "rec" again ;-)
