### ISSUE TITLE
Necessity of @beam.with?

### ISSUE THREAD

**Issue by MirijamBeier** [music-encoding/music-encoding#714]
In different contexts the question about the use of `@beam.with` came up (see below). We (the Digital Interactive Mozart Edition) are currently working on Mozart piano sonatas, in which the notes for both hands often have to be displayed in one staff. An example:
![image](https://user-images.githubusercontent.com/49152441/95863380-62c68480-0d64-11eb-98ac-cbe9fc5db12a.png)
To achieve a good rendering result, you have to add `@beam.with` in `<beam>`, otherwise you get rendering like this (or similar) in Verovio:
![image](https://user-images.githubusercontent.com/49152441/95863792-e54f4400-0d64-11eb-8077-8f47a6bb8c16.png)
Shouldn't rendering software like Verovio automatically place the beams correctly? What is the attribute `@beam.with` needed for, except rendering? Just to understand why we're adding it...
Questions about the necessity of the attribute were also asked by @rettinghaus (for the case of `tupletSpan` with unbeamed cross-staff tuplets, issue #689) and @craigsapp ([rism-ch/verovio #1732](https://github.com/rism-digital/verovio/issues/1732)).

**Comment by pe-ro** [comment]
Along with @MirijamBeier, I don't understand why `@beam.with` is necessary to achieve a satisfactory display here.  Seems to me to be a problem not with MEI, but with Verovio.

Closing for now.

**Comment by bwbohl** [comment]
Copied from https://github.com/music-encoding/music-encoding/issues/689#issuecomment-1268851557

>The fundamental problem here is that the placement of beams is relative to the placement of the notes, rests, chords under the beam while the placement of tuplet brackets is specified relative to the staves the events are on.  However, "fixing" the placement of tuplets and their accompanying brackets and numbers by making their placement the same as those of beams may introduce a backwards compatibility problem.  More input from @lpugin regarding Verovio's handling of these things is required.

**Comment by bwbohl** [comment]
AS this is more of a general question an not (yet) an issue with MEI schemata and guidelines I'm moving this to discussions
