### ISSUE TITLE
keySig@sig.showchange update

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#727]
Issue https://github.com/rism-ch/verovio/issues/1803 discusses two different styles of showing cancellation key signatures: either the cancellation can go before the new key signature, or it can go afterwards.

However the ordering of the cancellations cannot be controlled currently in MEI, since key-signature cancellations are controlled by `keySig@sig.showchange` which is a boolean, such as:

```xml
<keySig sig="4f" sig.showchange="true" />
```

Perhaps MEI should change this to allow three values:

(1) `@sig.showchange="none"` :: modern style (default if attribute not given)

(2) `@sig.showchange="before"` :: standard style

(3) `@sig.showchange="after"` :: old/French style

**Comment by ahankinson** [comment]
“Show” seems like a “yes/no” question: “Should I show this? “Showchange=none” would seem to me to be hiding the change, rather than giving the default behaviour.

what about “sig.changestyle” with values of before/after, with “before” being the default if not specified?

**Comment by craigsapp** [comment]
That sounds good.  It would be useful to avoid backwards compatible problems by using different values in `@sig.showchange`.   But it would be very verbose to include both `@sig.showchange` and `@sig.changestyle` always.  In general `@sig.changestyle` would be the same for all key signatures in the score, so perhaps it would best be added to `staffDef` and `scoreDef` rather than to `keySig`.

**Comment by craigsapp** [comment]
Another though: `@sig.showchange` is a bit confusing: the key *change* is always shown, rather it is the cancellation naturals placement that is being controlled.  Better would be `@sig.showcancellation`, or since that is too long, `@sig.cancellation`, or shorter `@sig.cancel`.   Without the "show" it becomes more non-boolean, so the options could be:

(1) @sig.cancel="none" :: modern style (default if attribute not given).  This would be equivalent to current `@sig.showchange="false"`.

(2) @sig.cancel="before" :: standard style, equivalent to `@sig.showchange="true"`, selecting the standard style.

(3) @sig.cancel="after" :: old/French style, equivalent to `@sig.showchange="true"`, selecting the old/French style.

**Comment by rettinghaus** [comment]
Should we have another option to place the cancellation before the bar line?

(MusicXML allows the values `left`, `right`, `before-barline`:
https://w3c.github.io/musicxml/musicxml-reference/data-types/cancel-location/)

**Comment by craigsapp** [comment]
> Should we have another option to place the cancellation before the bar line?

Related to this, it would be useful to have something like `keySig@cautionary` or `keySig@caution` to control display of a key signature at the end of the previous line if the change starts at the beginning of the next system.   The default would be true, and it would be useful to allow `keySig@caution="false"` to suppress it when needed.

This would also apply to time signature changes and clef changes.

**Comment by pe-ro** [comment]
The original intention of `@sig.showchange` was to indicate whether cancellation accidentals were to be shown or not.  The display location of the key signature wasn't taken into consideration.  Trying to keep the number of changes (in MEI) to a minimum, it seems to me keeping `@sig.showchange` (but perhaps renaming it) and adding another attribute to indicate where the key signature is to be displayed, would be best.  I have no preference about the naming.

**Comment by pe-ro** [comment]
How about, as @craigsapp suggests, renaming `@sig.showchange` to `@sig.cancel`,  but with the values "modern", "standard", "historical" instead of "none", "before", and "after"?

Adding `@keysig.caution" with Boolean values sounds good to me.

**Comment by pe-ro** [comment]
Are you satisfied, @ahankinson ?

**Comment by ahankinson** [comment]
"modern", "standard" and "historical" seem to be values that would need definition, and are an additional layer of abstraction, whereas "before" and "after" (or something similar) would simply indicate placement and would need no term definition.

Like, I don't know if I want "modern" changes or not, I just want the change to appear before the barline. Or "I have historical music, I'll use historical key signatures" regardless of what they actually do, or if they're valid.

I'm not really a fan.

**Comment by ahankinson** [comment]
If it's specifically for placement of changes, would `@sig.changeloc="before | after"` work? I'm thinking that something with "cancel" in it is a yes/no question (i.e., "should this be cancelled") but if we specify "loc" (MEI shorthand for "location") that's clearer.

**Comment by pe-ro** [comment]
'@sig.changeloc="before | after"' doesn't allow one to indicate that no changes should be displayed.

**Comment by ahankinson** [comment]
`@sig.changeloc="none | before | after"` (basically @craigsapp suggestion https://github.com/music-encoding/music-encoding/issues/727#issuecomment-872260275) "no location" seems like a reasonable approximation of "don't show"?

Or `@sig.changeloc="hidden | before | after"`?

**Comment by lpugin** [comment]
> "modern", "standard" and "historical" seem to be values that would need definition, and are an additional layer of abstraction, whereas "before" and "after" (or something similar) would simply indicate placement and would need no term definition.

"before" and "after" is actually the case only for flats and not for sharps because cancellation for those would always be before. So I would suggest

`@sig.cancel="none | before | cycleOfFifths"`

**Comment by bwbohl** [comment]
How is this related to #1170 ?

**Comment by musicEnfanthen** [comment]
@craigsapp @ahankinson @lpugin This can be closed since it was fixed in #1170, right? (`keySig@sig.showchange` is now `keySig@cancelaccid` and possible values, as requested here, are declared in to `data.CANCELACCID`)
