### ISSUE TITLE
Angled hairpins

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#733]
Currently it is not possible to encode (programmatically-determined) angled hairpins, because `@startvo` and `@endvo` by description record "a vertical adjustment of a feature's programmatically-determined" point. 

![lily-fa2a919d](https://user-images.githubusercontent.com/7693447/98963933-836f2f00-2508-11eb-95bb-8449ff3195e8.png)

It would be good to add an attribute for encoding the rotation here, something like `@angle`?

**Comment by kepper** [comment]
what about `@rotate`? I believe this name has been used already, but haven't looked…

**Comment by rettinghaus** [comment]
@kepper You'll find it here: https://music-encoding.org/guidelines/dev/attribute-classes/att.coordinated.html
But I thought that the description wouldn't match this case.

**Comment by craigsapp** [comment]
Something that allows an automatic layout system to angle the hairpin would be useful as an intermediate step towards `@startvo` and `@endvo`.  This would allow the hairpin to be positioned using the slur layout mechanism.   This could be in addition to a specific angle which would be an intermediate representation between allowing any angle and specific vertical offsets of each endpoing.

**Comment by kepper** [comment]
Well, `@rotate` seems on spot, but the rest in that class may be not. If we'd agree on that, it would mean that we'd have to separate out rotate, and make att.coordinated plus something else member of that class. The "something else" is to be determined, of course… (probably it's not just `<hairpin>`…)

**Comment by lpugin** [comment]
Aren't we looking at something like `@ploc/@oloc` and `@ploc2/@oloc2`? `@rotate` will work in some cases but not if you want to allow the horizontal spacing to change dynamically.

**Comment by kepper** [comment]
It seems we need both `@rotate` and something like `@ploc/@oloc(2)`, because there are cases that are really rotated, and sometimes the open ends are still on one vertical line. We also decided that this needs proper documentation, especially cor the combination with `@opening`. @rettinghaus has volunteered himself to prepare something for the next ODD meeting 👍 – thanks for that

**Comment by Dr-MAH** [comment]
high quality comment: I do not like angled hairpins ... ;-) Do we really need it?

**Comment by kepper** [comment]
Discussed on ODD Friday again. We need to clarify the relations between things like `@angle`, `@rotation`, `@rotate`. There are also questions about the rotation origin, skewing, and whether rotation (for instance) is applied before offsets / layout or after. All in all, this isn't fully thought through yet…

**Comment by bwbohl** [comment]
ODD meeting notes:

* definitely there seems to be a need to provide such rendition information
* more examples would be appreciated in order to thoroughly discuss the relation of the different attributes mentioned above

**Comment by rettinghaus** [comment]
We could "borrow" `@slope` from `att.beam.vis`. In combination with `@startvo` and `@endvo` we're on a pretty good way I think.

**Comment by rettinghaus** [comment]
We probably need this for even more objects:
![Sloped multi-measure rest](https://user-images.githubusercontent.com/7693447/163217952-53a81b18-143d-4514-8462-0eeeec4a9c0d.png)

**Comment by bwbohl** [comment]
> Well, `@rotate` seems on spot, but the rest in that class may be not. If we'd agree on that, it would mean that we'd have to separate out rotate, and make att.coordinated plus something else member of that class. The "something else" is to be determined, of course… (probably it's not just `<hairpin>`…)

this would be much easier in so-called pure ODD:

```xml
<elementSpec ident="hairpin">
    <attList>
        <attRef class="att.coordinated" name="rotate"/>
    </attList>
</elementSpec>
```

For me, a general question concerning `@rotate` is: what is the rotation point (any combinations of top, middle, bottom, left, centre, right)?

Nevertheless, I'm still not decided whether we do need hairpin rotation:

1. Is the intention behind this for transcriptional purposes or born-digital documents?
2. Even though it appears in some documents, isn't that something one wouldn't usually do?
3. Wouldn't it be sufficient to have this information on a `zone` that one can point to using `@facs`?

**Comment by craigsapp** [comment]
For this one:

![Screen Shot 2022-04-28 at 2 10 41 PM](https://user-images.githubusercontent.com/3487289/165846470-9c762a30-7900-4ee9-8bf3-a539f8269c67.png)

A better control would be to have `@loc` and `@loc2 for the starting and ending of the quasi multi-bar rest.

A problem with `@rotate` or `@slope` is that the endpoints remain vertical lines.

**Comment by pe-ro** [comment]
`<hairpin>` already has `@startvo` and `@endvo` attributes, so I don't see how `@rotate`, `@angle`, etc. are necessary.  As I imagine it, a hairpin has an imaginary line connecting its starting and ending points, where the starting pointing (for a crescendo mark) is where the lines converge and the ending point is mid-way between the lines at the open end.  For a "normal" hairpin, this line is parallel to the staff lines.  Adjusting the vertical offset of the end points of this imaginary line should result in a "tilt" of the hairpin. How much the visible lines of the hairpin diverge from this imaginary line is controlled by the `@opening` attribute, which is the length of another imaginary line.  This line usually remains vertical.  Adding an attribute to control the tilt of this line would allow the "arms" of the hairpin not to be vertically aligned.  That is, they could be different lengths.

The same attributes could be permitted on measure and multi-measure rests.

 (Please excuse the crude drawing.)

![hairpin](https://user-images.githubusercontent.com/5712877/165953637-8ca9d9a5-d396-4ac9-bcab-72a993179873.png)

**Comment by lpugin** [comment]
Here is a proposal that we discussed with @pe-ro, @kepper and @fujinaga:
* We add a `@optimize.angle` boolean attribute that indicates that the slope for the haipin can be adjusted to follow the content in order to optimize the spacing
* We add a `@opening.vertical` boolean attribute that indicates if the opening points have to be aligned vertically, including when the hairpin is angled (with `@optimize.angle` but that would work with `@endvo` too)

**Comment by ahankinson** [comment]
Perhaps `@angle.optimize` would indicate that the boolean true/false is for the optimization, not the angle. `@optimize.angle` might suggest that the attribute takes an angle. 

Did you discuss and reject `@opening="vertical | angled"`? Seems like that would be a bit more declarative, with `angled` being the default if nothing was specified.

**Comment by lpugin** [comment]
`@angle.optimize` is better

Because we already have an`@opening` attribute we went for `@opening.vertical`

**Comment by ahankinson** [comment]
OK
