### ISSUE TITLE
search is broken

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#749]
On our new static guidelines pages, the search function is broken. The old setup uses tipue search (https://github.com/michael-milette/Tipue-Search), which is a bit dated (last update on that Git repo was 4 years ago, but I'm not even sure it is this version that has been used), and also  introduces a dependency on jQuery. Apparently, tipue search is / was easy to set up with Jekyll (correct, @lpugin?). However, as those pages aren't built with Jekyll anymore, that's less of an argument now. It is certainly doable to reintroduce tipue search, but we may consider our options first. What we want is a client-side search function that takes a pre-generated index and lists guidelines pages which match. After some research, I see two other options for us: 

- Lunr.js (https://lunrjs.com/docs/index.html)
- Fuse.js (https://fusejs.io/)

The latter seems the more powerful, as it also brings fuzzy search. For both libraries, it should be fairly easy to adjust the index we currently generate. However, both options don't generate HTML to display search results – that's something we would have to rewrite. My guess is that it's a bit more work to integrate either Lunr.js or Fuse.js, but not by much. Personally, I don't like jQuery and would be willing to invest that extra time just to remove that dependency. With Fuse.js, we would get fuzziness, which could be nice, whereas with Lunr.js it seems pretty easy to set up different categories – searching for things like `annot`, we could prioritize the corresponding spec page before listing all chapters referencing the element and eventually bringing up all mentions of those characters somewhere in the text. Maybe this is also possible with Fuse.js (or tipue!), but I haven't seen a way there yet. 

I have no strong opinion on this, and actually going back to tipue would be perfectly fine with me. However, there might be an option to improve the user experience, so I'm wondering what others (@music-encoding/core-contributors and beyond) think about this? I would like to fix search soon, as this is the biggest remaining issue with the Guidelines…

**Comment by lpugin** [comment]
I don't see any reasons to stick with tipuesearch. It is not supported anymore, so you much better invest your time in something else.
