### ISSUE TITLE
Verovio examples in guidelines (version 5.0.0-dev)

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/music-encoding#752]
There are two issues with the examples in the `source/examples/verovio/` directory:
- the complete code is being rendered rather than just the desired segment
- the svg is not rendered

Here is one of such examples:
In **Section 2.2.4.3**, the [first encoding example](https://github.com/music-encoding/music-encoding/blob/develop/source/docs/02-shared.xml#L448-L451) is shown in its entirety (from the `<mei>` root element) rather than just the [part within the `<?edit-start?>` and `<?edit-end?>` tags](https://github.com/music-encoding/music-encoding/blob/develop/source/examples/verovio/accid-03.mei#L45-L63). Same happens in **Section 2.2.5.2** and **Section 4.3.5.5**. And there are several other examples of this in **Chapter 5**. In all of them, the images are not rendered in the website.

**Comment by lpugin** [comment]
This is one of the sections @martha-thomae is referring to https://music-encoding.org/guidelines/dev/content/shared.html#sharedAccidentalsArticulations

**Comment by martha-thomae** [comment]
@kepper, could you take a look at this? Are there any plans to get the Verovio SVG images back in?

**Comment by kepper** [comment]
I will have a look. Of course we want this back. Can't say how easy this will be, though.

**Comment by martha-thomae** [comment]
Thank you, @kepper! :)

**Comment by musicEnfanthen** [comment]
As of May 2023, the issue has been fixed (automagically) 🎉

**Comment by bwbohl** [comment]
@martha-thomae please turn the placeholder for missing images into XML comments to avoid them being rendered in the published version

**Comment by martha-thomae** [comment]
Yes, I will do that and check quickly that all the examples are understandable. Thanks!
