### ISSUE TITLE
Get rid of beamSpan and tupletSpan

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#756]
As mentioned at the end if issue https://github.com/music-encoding/music-encoding/issues/755, it would be good to get rid of `beamSpan` and `tupletSpan`.  Instead something like `beamSpan@sameas` should be implemented that merges two or more `<beam>` groups into a single beam.  Likewise, `tupletSpan@sameas` should be implemented to merge two or more `<tuplet>` groups into a single tuplet that crosses the tree hierarchy.

Both `beamSpan` and `tupletSpan` promote notes/rests that are independent children of `<layer>` into a meta tuplet or beam that crosses the `<measure>/<staff>/<layer>` hierarchy.  And knowledge of this promotion is delayed for notes in a layer until all of the floating elements have been parsed for a measure.  Placing the elements that will be spanned into groups that will be linked into a meta group seems more aligned with the MEI aesthetic without the use of promotions.   This system should also work when tuplets/beams cross each others hierarchies (you can provide counter examples to prove otherwise :-).

`tupletSpan` is particularly offensive because the actual duration of a layer cannot be known until parsing all floating elements at the measures level.  This greatly complicates calculating layout positions for generating graphical music notation, since notes within a tuplet span are useless for such layout until the tupletSpans have been applied to them.  It also greatly complicates computational analysis of such data for the same reason.

**Comment by lpugin** [comment]
I can certainly see the point, especially for `tupletSpan` that does allow for simple (on-pass) data analysis when durations are involved.

Maybe there are some less drastic options than getting rid of them, though. One idea that came to my mind and that - I think - works out of the box without any changes in MEI is it use `beamSpan` to regroup `beam` elements. There seem to be no assumption in the MEI Schema that a `beamSpan` needs to point to notes, chords or rest. It seems to me that it would make perfectly sense to make it point to beams (parts) that are meant to be grouped as a single one. 

So something like 
![image](https://user-images.githubusercontent.com/689412/105033046-e07ee800-5a57-11eb-9fd8-10cf4a202be2.png)
can be encoded with:
```xml
<measure n="1">
   <staff n="1">
      <layer n="1">
         <rest dur="2" />
         <rest dur="4" />
         <beam xml:id="b1">
            <note dur="8" oct="5" pname="c" />
            <note dur="8" oct="5" pname="d" />
         </beam>
      </layer>
   </staff>
   <beamSpan startid="#b1" endid="#b2"/>
</measure>
<measure n="2">
   <staff n="1">
      <layer n="1">
         <beam xml:id="b2">
            <note dur="8" oct="5" pname="e" />
            <note dur="8" oct="5" pname="f" />
         </beam>
         <rest dur="4" />
         <rest dur="2" />
      </layer>
   </staff>
</measure>
```
which is perfectly valid MEI. It also have the advantage that an application that would be ignoring the `beamSpan` would still preserve the underlying beam parts, which could be better than nothing in many cases.

I think the same approach would work equally well with tupletSpan, even though dealing with tuplet number display might require additional thoughts.

**Comment by craigsapp** [comment]
Yes, that is good since it organizes the elements to be spanned into more manageable groups.  And the role of the span is diminished to linking elements rather than also grouping sibling elements before doing that.

One consideration would be how to beamSpan more than two such beams together, such as when the beam goes across multiple measures?  Probably with `beamSpan@plist`?

**Comment by lpugin** [comment]
> One consideration would be how to beamSpan more than two such beams together, such as when the beam goes across multiple measures? Probably with beamSpan@plist?

Yes, I think that would work.

**Comment by craigsapp** [comment]
There will still be cases where the current beamSpan is needed, but I am still trying to think of a case where the traditional tupletSpan is necessary...
