### ISSUE TITLE
Development RNG version of the Schema fails to validate

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#757]
This file https://music-encoding.org/schema/dev/mei-all.rng raises the error `duplicate attribute "fermata"`.

**Comment by martha-thomae** [comment]
Will be fixed in this PR https://github.com/music-encoding/music-encoding/pull/753

**Comment by lpugin** [comment]
Thanks!

**Comment by martha-thomae** [comment]
Would you mind taking a look at it to see if everything is in order with that PR? I think it is, but it will be great to get a second pair of eyes. Thanks for raising the issue!

**Comment by lpugin** [comment]
I leave this to @kepper and @bwbohl

**Comment by bwbohl** [comment]
I merged #753 and tested using the https://music-encoding.org/schema/dev/mei-all.rng schema to validate a local file, the `duplicate attribute "fermata"` error was not raised.

**Comment by martha-thomae** [comment]
Thank you, @bwbohl!
