### ISSUE TITLE
Add documentation for building the guidelines locally

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#763]

**Comment by martha-thomae** [comment]
And also for using the XSLT to convert the ODD to HTML. Both things would be very useful.
Thanks, @bwbohl!

**Comment by bwbohl** [comment]
some interim notes:

Prerequisites
java-8
Apache ANT

checkout recursively or init submodules

Submodules
git submodule init
git submodule update

ant init
ant -lib lib/saxon/saxon9he.jar -Dcustomization.path=[PATH/TO/YOUR/CUSTOMIZATION] build-rng

ant init
ant -lib lib/saxon/saxon9he.jar build-guidelines-html
