### ISSUE TITLE
PR labeled fails on PRs from fork

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#766]

**Comment by musicEnfanthen** [comment]
Seems to be an issue with the action's permissions that would need to adjust the action's target .

`on: -pull_request` --> `on: -pull_request_target` . 

Cf. here: https://github.com/actions/labeler/issues/121 
and here: https://github.com/actions/labeler/issues/12#issuecomment-670967607

**Comment by lpugin** [comment]
@musicEnfanthen `pull_request_target` works, but it yields security issues because the PR can contain modifications that send the secret keys. We had that on verovio and had to disable it. You can try but be prepared to receive emails from GitHub and from users scanning for these...

**Comment by musicEnfanthen** [comment]
Thanks @lpugin for this insight. Never tried `pull_request_target` myself. Those security issues sound serious, so changing to `pull_request_target` seems not to be a real option.... Sorry, should have checked better up-front. Found this post with some more background info: https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by musicEnfanthen** [comment]
In short, the post says that 

> combining `pull_request_target` workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise.

 At the same time it mentions: 

> If your workflow scenario simply requires commenting on the PR, but does not require a check out of the modified code, using `pull_request_target` is a logical shortcut.

**Comment by musicEnfanthen** [comment]
Related issues on the action upstream:

https://github.com/actions/labeler/issues/36
https://github.com/actions/labeler/issues/121

**Comment by ahankinson** [comment]
`pull_request_target` is the officially recommended way of running this now:

https://github.com/actions/labeler/blob/main/README.md#create-workflow

I'll make the change and submit a PR.
