### ISSUE TITLE
@tstamp2 is missing in metaMark

### ISSUE THREAD

**Issue by krHERO** [music-encoding/music-encoding#767]
while `@tstamp` is allowed, `@tstamp2` is missing in `metaMark` .
btw: since `@startid` and `@endid` are allowed, `@tstamp2` should also be added.
https://music-encoding.org/guidelines/v4/elements/metamark.html

**Comment by rettinghaus** [comment]
In latest develop `@tstamp2` is available (though `@tstamp2.ges` and `@tstamp2.real` are not). 
What needs to be done here?

**Comment by kepper** [comment]
has been solved in the past. If someone needs `@tstamp2.ges` or `@tstamp2.real` in the future, this can be opened again.
