### ISSUE TITLE
Guidelines: Content from v4 not reflected in dev

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#769]
Some content from the guidelines v4 is not reflected in the dev version. Especially the Linking Data chapter is only a rudiment of itself in dev:

https://music-encoding.org/guidelines/v4/content/linkingdata.html

vs.

https://music-encoding.org/guidelines/dev/content/linkingdata.html

Did not check another chapter so far, but would be good to automatically check (at least once) that dev uses the v4 status as starting point.

**Comment by musicEnfanthen** [comment]
@bwbohl Could you add this issue to project dashboard please?

**Comment by bwbohl** [comment]
to which one? guidelines or ODD meetings? Am I right to assume this means you're not able to add it yourself?

**Comment by musicEnfanthen** [comment]
To ODD meetings, please. (Or maybe both?)

Yes, you are right. Can't assign myself, that's why I am asking ;)

**Comment by kepper** [comment]
it seems that for some reason, the sub-chapters 13.2.1 and 13.2.2 haven't been copied over. That's strange, as this worked in other chapters, and it ran through the same process. I'll re-include that asap.
