### ISSUE TITLE
TEI Stylesheets and Saxon 10

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/music-encoding#783]
I noticed that the TEI Stylesheets have switched to Saxon 10 for their build. We should confirm that this will or won't cause problems for our build process.

See: https://github.com/TEIC/Stylesheets/pull/498

**Comment by bwbohl** [comment]
thanks for bringing this up! Where did you find the info (just curious)?

**Comment by ahankinson** [comment]
Sorry -- I didn't see your response! I follow the TEIC/Stylesheets repo, and noticed the PR.
