### ISSUE TITLE
Thick double bar lines

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#787]
Currently it is not possible to encode a double bar line consisting of two thick lines which can be found in several older prints.
![image](https://user-images.githubusercontent.com/7693447/114868730-88f1dd80-9df6-11eb-8f88-fb84fac37bdf.png)
Example from: _Leroy, Eugène: Méthode de Trompette_

Could we add another value to `data.BARRENDITION`?

**Comment by kepper** [comment]
sure. quite apparently, it's necessary :-)

**Comment by craigsapp** [comment]
A variant of this style would be for repeats:

https://github.com/craigsapp/haydn-piano-sonatas/blob/master/reference-edition/sonata12-2.pdf

<img width="275" alt="Screen Shot 2021-04-15 at 12 15 34 PM" src="https://user-images.githubusercontent.com/3487289/114925807-69ea5000-9de4-11eb-9b3f-80b98dedcac5.png">

**Comment by rettinghaus** [comment]
Also in older prints repeat bar lines usually have four dots (on each side) instead of two. 
![image](https://user-images.githubusercontent.com/7693447/140763866-aef0b14c-72f1-4f3b-a44e-bd6fbf2d591e.png)
(Beethoven's Bagatelles Op. 119)

**Comment by rettinghaus** [comment]
Obviously there are so many variations that I don't see the point in trying to catch every possibility in a hard-coded list. 
Would there be a way to encode these notation styles in general in MEI?

**Comment by kepper** [comment]
Styling needs to be addressed in the future anyway. Semantically, this is still a double barline, so this can be encoded in some way already. We will come back to this later in a different context.
