### ISSUE TITLE
Schematron rule for att.coordinated attributes

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/music-encoding#801]
Should we include a schematron rule for verifying that the upper-left (`@ulx`, `@uly`) and lower-right (`@lrx`, `@lry`) coordinates of a bounding box have the correct values?

Right now, the schema only complains when these attributes have negative values. But I was wondering if we should also enforce the following:

- `@ulx < lrx` (because in terms of `x` coordinate, the upper-**left** corner has a smaller value than the lower-**right** corner),
- `@uly > lry` (because in terms of the `y` coordinate, the **upper**-left corner has a higher value than the **lower**-right corner).

Checking this with the schema, will make it easier for the users to make sure that they have encoded their corners coordinates correctly (e.g., verify that they didn't accidentally encode an upper-right corner instead).

**Comment by ahankinson** [comment]
AFAIK there is an unwritten assumption in MEI that these values correspond to a co-ordinate system with origin in the upper-left. If we introduce this rule we should also make that a written assumption. Otherwise, given an origin of 0,0 in the centre of a surface, or even bottom-right, then these schematron rules would not be universal.

**Comment by martha-thomae** [comment]
Oh, this was me thinking as if the page was on quadrant I of a Cartesian plane. Sorry, my bad. Thank you for the clarification, @ahankinson. Ok, I will see where this clarification of the top-left corner being at the coordinate `(0,0)` can be included in the documentation to avoid confusion.

Ok, then based on this, the coordinates `x` and `y` of the `ul` corner will always be smaller than their counterparts in the `lr` corner. Got it! Thanks again :)

**Comment by ahankinson** [comment]
Ah, so you thought the origin was in the bottom left? Yet another reason to make the origin explicit. [We talked about this a long time ago](https://lists.uni-paderborn.de/pipermail/mei-l/2011/thread.html#302), and there wasn't really consensus about origin. It's probably worthwhile to look through this discussion to see if there is anything relevant.

There is also the question of the units. On raster images, the co-ordinates are likely pixel values, but on vector images then pixel-based units are not useful. Perry makes a comment to that effect in the thread linked above, I believe.

**Comment by martha-thomae** [comment]
Yes, that is exactly what I thought.

Thank you for sharing, I will look into that discussion.

**Comment by ahankinson** [comment]
@martha-thomae should we keep this issue open?

**Comment by martha-thomae** [comment]
You are right, we can close it. I just think that we could clarify things in the documentation about this. But yes, I will close it.

**Comment by bwbohl** [comment]
has anyone created an issue for updating the documentation accordingly?

**Comment by martha-thomae** [comment]
Not really. I quickly went through the discussion, but I saw there is no consensus. I will look into the discussion in more detail and raise a documentation issue if appropriate. Thanks, @bwbohl!
