### ISSUE TITLE
Images not properly loaded in Neume Notation Documentation

### ISSUE THREAD

**Issue by carrieeex** [music-encoding/music-encoding#810]
Most images are not loaded in the [Documentation of Neume Notation](https://music-encoding.org/guidelines/v4/content/neumes.html), like this:
<img width="693" alt="MEI website - Neume Notation" src="https://user-images.githubusercontent.com/59303880/120512313-d3a6d380-c3fd-11eb-90b8-a4f5fff89a42.png">

**Comment by carrieeex** [comment]
We think the problem is due to the images in the [guidelines repo](https://github.com/music-encoding/guidelines/tree/master/v4/images/modules/neumes) are not fully uploaded to the main [music-encoding repo](https://github.com/music-encoding/music-encoding/tree/develop/source/images/modules/neumes).

**Comment by ahankinson** [comment]
The images are available in the Guidelines, they're just not showing up in the documentation:

https://music-encoding.org/guidelines/v4/images/modules/neumes/NEUME-con.png

The guidelines have the image URL as this (you can right click on the image that is not loading and say "Copy image address")

`src="/guidelines/images/v4/modules/neumes/NEUME-con.png"`

It looks like the correct address should be `v4/images`, not `images/v4`

**Comment by carrieeex** [comment]
Ahh I see. Yes you're right. Thanks for looking into this @ahankinson !

**Comment by ahankinson** [comment]
I believe this has been addressed now.
