### ISSUE TITLE
Cannot Add Accidentals in Neume Notation

### ISSUE THREAD

**Issue by yinanazhou** [music-encoding/music-encoding#816]
Hi, we are currently processing the manuscript _Salzinnes_, and we noticed that there are flats in the manuscript. But MEI encoding in neume notation seems not to provide accidentals for neume components. It would be nicer if it is allowed to insert accidentals since there are accidentals in neume notation.
![accid_image](https://user-images.githubusercontent.com/74484576/122110519-a2120d00-cdec-11eb-933e-df7a54af53b3.png)

**Comment by pe-ro** [comment]
In neume and mensural notation accidentals are not attached to neume components because they're often written well before the component/note that they modify.  In these kinds of notation, `<accid>` and other members of the noteModifierLike class (`<artic>` & `<dot>`) are allowed directly within `<staff>`.  I hope this helps.

**Comment by martha-thomae** [comment]
Thanks for the clarification, @pe-ro!
So the intended use for `<accid>` in neume notation is to include it within the `<layer>`, and maybe use a `@corresp` attribute to relate it to the neume component `<nc>` (the note) it is affecting?

The examples we have found so far in this manuscripts (the Salzinnes Antiphonal) seem to only be next to the affected note. However, I cannot assume that this is the common practice (neumes are far from my notation of choice).

**Comment by ahankinson** [comment]
<img width="192" alt="image" src="https://user-images.githubusercontent.com/163183/122120485-c68cda00-ce2a-11eb-8adf-83666be123b1.png">

Here's an example from the Salzinnes -- the flat symbol is written before the 'f', even though it affects the 'b'. 

https://cantus.simssa.ca/manuscript/133/?folio=002v&chant=5&search%5Btype%5D=volpiano&search%5Bquery%5D=ib#v=d&z=4&n=5&p=4&y=2023&x=915

**Comment by ahankinson** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/163183/122121663-30f24a00-ce2c-11eb-94f6-d54ba92f6728.png">

Here is another example, where there are four 'b's that are flattened -- or so my resident musicologist tells me. :-D

(If they are, then maybe the Volpiano transcription is incorrect?)

https://cantus.simssa.ca/manuscript/133/?folio=004r&search%5Btype%5D=volpiano&search%5Bquery%5D=ib

**Comment by martha-thomae** [comment]
Thanks, @ahankinson!

**Comment by pe-ro** [comment]
@martha-thomae, yes, `@corresp` is the way to associate the accidental and the note it affects.

**Comment by martha-thomae** [comment]
Thanks, @pe-ro!

**Comment by ahankinson** [comment]
@yinanazhou @martha-thomae if you're happy with the solution provided, please close this issue. Thanks!
