### ISSUE TITLE
[GUIDELINES] Tabs in Specs not working in dev version

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#823]
The tabs next to `attributes`, `Members`, `Contained by` or `May Contain` in the HTML view of the specs do not work in the dev version of the Guidelines. That applies to all entities (elements, attributes, model classes, macros, data types).

![tabs](https://user-images.githubusercontent.com/21059419/122560457-eb5a9a80-d040-11eb-9a04-3c95fc961366.PNG)

**Comment by kepper** [comment]
Hm, that's an error that I've seen (and solved?) in the past already. If I remember correctly, the problem was some Javascript error that prevented the page from loading correctly. I won't be able to investigate today, but I'll put it on my list…

**Comment by kepper** [comment]
I just looked this up with a variety of browsers, and can't reproduce anywhere. I suspect it was something with broken JS that is now functional again. Probably good to keep an eye on, but nothing to do right now. Thanks for reporting, though.

**Comment by musicEnfanthen** [comment]
Hmmm, for me it is still broken (both on FF and Chrome). Did you check the dev-version?

**Comment by kepper** [comment]
Yes, see screenshot attached. Cleared my cache, used a completely new browser – looking good for me… Haven't checked with different OS, though?! 

<img width="1248" alt="grafik" src="https://user-images.githubusercontent.com/2078563/123850616-89404600-d91a-11eb-8b68-97b050d304df.png">

**Comment by musicEnfanthen** [comment]
Yes, I see. Checked on a different device, and can confirm your observation (working there). Not sure what's happening here that it does not work on any browser.

**Comment by kepper** [comment]
Could you give the browser / OS combination that is _not_ working, so we can verify?

**Comment by ahankinson** [comment]
It doesn't seem to be working for me on Safari / Latest macOs. 

I see this in the console:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/163183/123915573-f1297780-d980-11eb-93e2-4866b53692b2.png">

Similar error in latest Chrome / latest macOs:

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/163183/123915761-22a24300-d981-11eb-8198-9a4b9df33303.png">

**Comment by ahankinson** [comment]
It looks like it's trying to find an element with the `id` of `compact_tab`, but the actual `id` value is `containedBy_compact`


<img width="781" alt="image" src="https://user-images.githubusercontent.com/163183/123916262-bd9b1d00-d981-11eb-9eb8-307cb87d8fbb.png">

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/163183/123916398-e58a8080-d981-11eb-9eda-1b52a875a086.png">

Changing 

`const newTab = document.getElementById(style + '_tab');`

to

`const newTab = document.getElementById(facetId + '_' + style);`

should fix it?

**Comment by musicEnfanthen** [comment]
Thanks @ahankinson for the digging. Thanks to your hint, I recognized that these things are written to Local Storage. After deletion of the Local Storage entries it worked for me again, i.e. displayed the tab contents correctly.

**Comment by kepper** [comment]
Ok, that explains the problem. I was desparately looking for differences, because the very browsers than @ahankinson mentioned are working for me. Question is now how we can make this more robust…?

**Comment by ahankinson** [comment]
Don’t use JavaScript? :-D

**Comment by kepper** [comment]
If you're willing to stick with the first tab, you can safely turn off JavaScript ;-)
