### ISSUE TITLE
[GUIDELINES] Data type specs not displayed correctly in dev version

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/music-encoding#824]
For "Used by" and "Remarks" entries in the data types section of the guidelines (dev version) only the row header is displayed. Other entries, like "Allowed values", are not displayed at all. It is working in MEI4 version. 

<details>
<summary>Screenshot dev version</summary>
<br>

![datatype](https://user-images.githubusercontent.com/21059419/122561639-63759000-d042-11eb-8349-e8e0aa5e4fa1.PNG)
</details>

<details>
<summary>Screenshot MEI4 version</summary>
<br>

![datatype_4](https://user-images.githubusercontent.com/21059419/122561642-64a6bd00-d042-11eb-98f3-3cc19b769e4c.PNG)
</details>

**Comment by kepper** [comment]
I'll look this up together with #823 (even though it's probably unrelated).
