### ISSUE TITLE
All images not showing when using Oxygen to build html

### ISSUE THREAD

**Issue by yinanazhou** [music-encoding/music-encoding#830]
We were trying to fix the [neume-image-not-showing issue](https://github.com/music-encoding/music-encoding/issues/810) in the [development version of the guidelines](https://music-encoding.org/guidelines/dev/content/neumes.html). But we noticed that when using Oxygen to build HTML file, all the images will not show (not just neume notation). The thing is when using command lines to build HTML file, the images are showing.

**Comment by ahankinson** [comment]
This seems related to Discussion #829 -- can we follow it up there?

**Comment by yinanazhou** [comment]
yeah, sure, thank you!

**Comment by ahankinson** [comment]
Ok, I will close this.
