### ISSUE TITLE
MarkDown artifacts in Neumes Chapter

### ISSUE THREAD

**Issue by kepper** [music-encoding/music-encoding#840]
@fujinaga has spotted a number of MarkDown remnants like the following:

https://github.com/music-encoding/music-encoding/blob/96166b37a2911d2a97911ede87e1ad20c581875f/source/docs/06-neumes.xml#L180

There are some more things to be italicized in this chapter.

**Comment by musicEnfanthen** [comment]
Fixed in  #1014
