### ISSUE TITLE
Simplify att.numberPlacement

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#852]
Do we need to have the attribute `@num.visible` in addition to `@num.place`? Shouldn't it be enough to say `@num.place="none"`?

**Comment by rettinghaus** [comment]
Why is `att.numberPlacement` actually in `MEI.cmn` and not in `MEI.visual`?

**Comment by bwbohl** [comment]
ODD meeting notes:

* we think you're totally right, either it is placed or not, if not, then location is irrelevant if above or below it can't be invisible ;-)
* Could you please file a PR?

**Comment by ahankinson** [comment]
Sometimes it's useful to be able to show/hide a number, even if it has a place. I'm not generally a fan of mixing data types and implicit behaviours. A staff placement and a visibility flag are two different types of data.

You couldn't, for example, toggle the visibility of a number while also keeping the encoded placement of it; you would need to overwrite the placement with a value of `none`, at which point the original value would be lost.

So I'm +1 to keeping both.
