### ISSUE TITLE
Add a `data.COURSETUNING` data type

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#856]
In the tablature customization, we currently have a list of possible values directly in `att.tuning.log`
https://github.com/music-encoding/music-encoding/blob/059ea54e71a590feace606d1e81b336253254570/source/modules/MEI.shared.xml#L3482-L3504
It would be better to make the list a `data.COURSETUNING` data type.

**Comment by rettinghaus** [comment]
Does a semi.open list in combination with a data type make sense? 

And where are the different tunings for the ukuleles and/or balalaikas? 
https://en.wikipedia.org/wiki/Ukulele
https://en.wikipedia.org/wiki/Balalaika
Also I'm missing the Oud. 

Maybe it would be good to massively extend the list and split it up into `data.COURSETUNING.guitar`, `data.COURSETUNING.lute` etc.

**Comment by lpugin** [comment]
> Does a semi.open list in combination with a data type make sense?

Why not? We already have this https://music-encoding.org/guidelines/dev/data-types/data.MODE.extended.html

I leave the other questions to tablature experts.

**Comment by lpugin** [comment]
It is done in the tablature customization
