### ISSUE TITLE
Signum congruentiae

### ISSUE THREAD

**Issue by davidrizo** [music-encoding/music-encoding#863]
![](https://upload.wikimedia.org/wikipedia/commons/4/4c/Signum_congruentiae_%28Bravura%29.png)

Currently, I've not found any way to encode the *Signum Congruentiae* other than the use of the ``dir`` element as suggested for the *segno* symbols in #520.

It can be encoded as a child of ``staff``, however, we cannot use the ``@tsamp`` attribute.
Show we encode it the same way or should we create a new element similar to the ``custos``?

**Comment by pe-ro** [comment]
@davidrizo, `<dir>` is permitted within `<staff>`.  Will this not accommodate the encoding of signum congruentiae in mensural notation?

**Comment by davidrizo** [comment]
@pe-ro I'm sorry, I've added the issue and I've later edited it because I've seen what you mention.  The problem is that ``dir`` uses measure relative information to be set (e.g.,``@tstamp``) and in mensural notation we may have a correct encoding without any ``measure`` element. This is why I proposed to use something similar to the ``custos`` approach

**Comment by pe-ro** [comment]
@davidrizo , When `dir/@tstamp` isn't appropriate (as in mensural notation), you can use `@startid` to associate the `<dir>` element with another element, such as a particular note.

**Comment by davidrizo** [comment]
@pe-ro You're right, I'll use this way of encoding it. Thanks !!
