### ISSUE TITLE
Add source description in Guideline files

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#877]
Although it is common practice to leave the mandatory `sourceDesc` element in the TEI header empty it could be filled with some real content. 
It needs to be discussed whether and what actually should go in there.

**Comment by musicEnfanthen** [comment]
Besides leaving it empty as is, another very basic option would be to just indicate the intention in a comment:
`<!-- intentionally left empty -->`

Other options to be found in the TEI examples for `sourceDesc`: https://tei-c.org/release/doc/tei-p5-doc/en/html/examples-sourceDesc.html:

```
<sourceDesc>
    <p>No source: This is an original work.</p>
</sourceDesc>
```


```
<sourceDesc>
    <p>Born digital: No previous source exists.</p>
</sourceDesc>
```
(Original examples with lower case after the colon.)

**Comment by ahankinson** [comment]
I'm partial to the comment option, if we do want to fill it out.

Should we address this before merging #875 ?

**Comment by kepper** [comment]
I would perhaps include a slightly longer statement in the comment, but then the comment seems to be a good approach…

**Comment by bwbohl** [comment]
I'm pro:

```xml
<sourceDesc>
    <p>Born digital: No previous source exists.</p>
</sourceDesc>
```

**Comment by pe-ro** [comment]
Also pro:

```
<sourceDesc>
    <p>Born digital: No previous source exists.</p>
</sourceDesc>
```
