### ISSUE TITLE
Removing <fingerprint>

### ISSUE THREAD

**Issue by riedde** [music-encoding/music-encoding#885]
Proposal of @music-encoding/ig-metadata 
Short summary: We noticed the existence of the element `<fingerprint>` when updating the mei guidelines (chapter 3 Metadata). Our call to the community about usage, need, examples and description for the guidelines remained without result.
Two facts:
- This element is not described anywhere in the Guidelines (only the element definiton exists).
- comment in the encoding-tool [mei2010to2012.xsl](https://github.com/music-encoding/encoding-tools/blob/cb6bb19a75b983617f56cb4aad4eaaf9cb8558a5/mei2010To2012/mei2010To2012.xsl#L216): "use of mei:fingerprint deprecated"

The metadata ig will not include the element in the guidelines (chapter 3) and proposes to remove it.

This topic was discussed in the [Issue on fingerprint](https://github.com/music-encoding/metadata-ig/issues/13) at the metadata-ig repo.

**Comment by musicEnfanthen** [comment]
@bwbohl Is this actually breaking backward compatibility when the element was removed already in 2012? (Not sure how it survived or found its way back anyhow)
