### ISSUE TITLE
provide description and documentation for `manifestation/@singleton`

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#906]
Neither the specs nor the guidelines seem to contain any information on `manifestation/@singleton`

**Comment by doerners** [comment]
Discussed it on 2022-10-01 during dev meeting in Berlin with @riedde and @mss2221. Metadata-IG will take care of this.

Quick question though: We noticed that `<availability>` is available for `<item>` but not for `<manifestation>`. If `@singleton` = TRUE `<availability>` should probably also be available on `<manifestation>`, right?

If there are no arguments against it, I can implement that.
