### ISSUE TITLE
Update build process to Saxon 11

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#907]
Just now after we've updated the build process to Saxon 10 they released the new version. 

Should we update?

**Comment by bwbohl** [comment]
could you please check if TEI-C already switched? As we're using their Stylesheets we should stick to whatever they use

**Comment by rettinghaus** [comment]
No. It was just released, so I think we still have some time. This ticket is just a precautionary measure.

**Comment by bwbohl** [comment]
closed with add49a736eafb2ea2904328220ae0c74f867633b in #1057
