### ISSUE TITLE
Images from SMuFL browser don't work

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#908]
Images in the Guidelines from the SMuFL-browser don't work, because they're pre-fixed with `../` making it a wrong relative URL.
See: https://music-encoding.org/guidelines/dev/content/cmn.html#cmnFermata

Should we switch to a SMuFL text font in general?

**Comment by kepper** [comment]
should be fairly simple to test for a `http` at the start of a link to avoid the `../` here. We would need an additional class though, to make the symbols a bit smaller / fit them to line height. I'm not opposed to a SMuFL text font, but in my experience, they cause (other) problems as well… (their fontsize often doesn't fit too well)

**Comment by rettinghaus** [comment]
The problem is, that there is a test already, but in the end for the html it adds `../` to all urls.

**Comment by kepper** [comment]
fixing the prefix just now (just to avoid duplicate work on your end)

**Comment by rettinghaus** [comment]
@kepper did already, please check #909

**Comment by kepper** [comment]
you're too quick for me ;-)
