### ISSUE TITLE
Missing documentation on linking attributes

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#915]
[Chapter 13](https://music-encoding.org/guidelines/dev/content/linkingdata.html#ptrrefModule) and [Chapter 10](https://music-encoding.org/guidelines/dev/content/analysisharm.html#analysisDescribingRelationships) of the Guidelines should contain some information and examples on `@corresp`.

**Comment by riedde** [comment]
Also `@facs` and other ways of pointing.

**Comment by bwbohl** [comment]
`@data`

**Comment by bwbohl** [comment]
cf. #1054
