### ISSUE TITLE
re-conceptualise encoding of font-properties inthe context of smufl

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#922]
There have been some discussions about how to encode smufl fonts in MEI. From a `<smufl>`element to using `@fontfam` or `@fontname`. Moreover discussion was on deprecating one of the attributes.
A sound concept should be developed for this, taking into account #716

**Comment by ahankinson** [comment]
Definitely -1 to a “smufl” element; it ties the encoding to a specific technology, and makes it harder to support non-smufl fonts.

**Comment by th-we** [comment]
A little summary:

One encoding that [has been proposed](https://github.com/music-encoding/music-encoding/pull/704#issuecomment-802800705):

```xml
<dynam>
   <rend glyph.auth="smufl">&#xE522;&#xE525;&#xE520;</rend>
</dynam>
```

Or [without `<rend>`](https://github.com/music-encoding/music-encoding/pull/704#issuecomment-832653453):

```xml
<dynam glyph.auth="smufl">&#xE522;&#xE525;&#xE520;</dynam>
```

[CSS-like fallbacks](https://github.com/music-encoding/music-encoding/issues/716#issuecomment-1024179509) (e.g. `fontfam="Leipzig,Bravura,smufl"`) might work, too, though there were [objections](https://github.com/music-encoding/music-encoding/pull/704#issuecomment-802307164).

**Comment by bwbohl** [comment]
@th-we thanks for the summary!

**Comment by lpugin** [comment]
As it stands, we can use `<rend fontfam="smufl">`. That seems to be enough. Re-open if necessary.
