### ISSUE TITLE
att.note.vis vs. att.note.vis.cmn

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#928]
What is the (intended) difference between [att.note.vis](https://music-encoding.org/guidelines/dev/attribute-classes/att.note.vis.html) and [att.note.vis.cmn](https://music-encoding.org/guidelines/dev/attribute-classes/att.note.vis.cmn.html)?

**Comment by ahankinson** [comment]
Probably so that you can remove the `@breaksec` attribute from non-cmn `<note>`s in customizations while still keeping the other visual attributes.

**Comment by rettinghaus** [comment]
Oh, yes. I was confused because of the `@stem.with` only in `att.note.vis`, but that's coming from `att.stems`.
