### ISSUE TITLE
Custos after staff

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#944]
Sometimes a custom is not printed/written (completely) on the lines of the staff.  
<img width="317" alt="image" src="https://user-images.githubusercontent.com/7693447/163979479-88943533-d779-40fa-ad64-7dfcbb620985.png">

Is there a possibility to encode this? 
@music-encoding/ig-mensural Would it make sense and be sufficient if we add the `@onstaff` attribute here, or is there a finer method needed, that allows saying something like "80% off the staff"? 

(Example taken from [Petrucci's _Frottole libro 3_](https://www.digitale-sammlungen.de/de/view/bsb00082309))

**Comment by ahankinson** [comment]
Perhaps x/y offsets need to be added to `custos` to support a different rendered placement of the symbol.

**Comment by rettinghaus** [comment]
@ahankinson That would probably make sense, but I'm not completely sure if this will be enough if you want to reconstruct the look with tools like Verovio. The specific given example needs more like `@cutout` from `mRest`.

**Comment by ahankinson** [comment]
I’m not sure I follow. This looks like a pretty standard custos, just horizontally offset. Why would we need something like `@cutout`?

**Comment by rettinghaus** [comment]
Actually it's not offset, the notation stops and after the staff lines it is printed. If you just say to a renderer "shift it horizontally" it would still reserve space on the staff lines for the symbol.

This is what Verovio produces:
![custos-onset](https://user-images.githubusercontent.com/7693447/163991032-d83ab5d8-ab75-476d-8b87-7b9374e4ceda.png)

This is what you get if you only move the custos: 
![custos-offset](https://user-images.githubusercontent.com/7693447/163991070-f7063172-71b4-44c8-9633-efa6954e9b30.png)

If you remove the "offset" in the original example it would be printed above the last two semibreves.

**Comment by DILewis** [comment]
I agree that this isn't an offset – it's not positioning something to the right of where it would normally go. Rather, it's applying a (common) layout rule that says that a _custos_ is a marginal addition and shouldn't be within the staff area. Often it applies globally or fairly globally, but if we wanted to encode it, we'd need to be able to do it on a per-symbol basis too.
I don't know `@onstaff`, so can't comment on its applicability.

**Comment by ahankinson** [comment]
Gotcha. 

`@onstaff` seems to be pretty generic, so it could probably work -- making `att.custos.vis` a member of `att.placementOnStaff`. 

There's a lot of overlap in other "placement" attributes, it seems -- `data.STAFFREL` (both `basic` and `extended` flavours), `data.PLACEMENT`, `data.NONSTAFFPLACE`. I would avoid any of those, though, since it might lead to unintended consequences. (like allowing a value of `above` for a custos placement, which of course makes very little sense.)

**Comment by kepper** [comment]
We do have a value of `rightmar` in [data.NONSTAFFPLACE](https://music-encoding.org/guidelines/dev/data-types/data.NONSTAFFPLACE.html), which seems quite appropriate. However, that it's not really accessible in this situation, as it's bringing too much other stuff. I therefore agree that [att.placementOnStaff](https://music-encoding.org/guidelines/dev/attribute-classes/att.placementOnStaff.html) seems much more appropriate. However, as it is rather generic, I would recommend to explicitly explain how it is used in conjunction with a `custos` in an example / remark within the documentation of that element.

**Comment by ahankinson** [comment]
Yeah, I saw that but thought that having a custos with a possible placement value of "facing" would be all kinds of weird. 😆

**Comment by kepper** [comment]
A potential way around this could be to split up data.NONSTAFFPLACE into multiple data types, but we would probably end up having another attribute named `place`, with yet another set of allowed values, and a lot of complexity added to the internal setup of MEI, so `@onstaff` really seems like the way to go…

**Comment by kepper** [comment]
will close this, according to the arguments given in #951
