### ISSUE TITLE
<neume> not valid as child of <rdg>

### ISSUE THREAD

**Issue by pfefferniels** [music-encoding/music-encoding#957]
With [this commit](https://github.com/music-encoding/music-encoding/commit/796ccf65ef57e0e0b2038683866051be6ea3bd11), `model.rdgPart.critapp` has been renamed to `model.rdgPart.music`. It seems, that [it has been forgotten in the mei-Neumes customization](https://github.com/music-encoding/music-encoding/blob/develop/customizations/mei-Neumes.xml#L127), which leads to `<neume>` not being a valid child of `<rdg>`.

**Comment by ahankinson** [comment]
Good catch. Would you be willing to submit a PR against the neumes customization to fix this?
