### ISSUE TITLE
Make barline with serpent available

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#969]
Currently it not easy/possible to encode a `segno` serpent. 

![](https://smufl-browser.edirom.de/E04B.png)

How about adding a `dblsegno` value to `data.BARRENDITION`?

**Comment by musicEnfanthen** [comment]
Thank you @rettinghaus .

Short question: Is the segno serpent always used with a double barline? There seems to be another standalone version in SMuFL: https://w3c.github.io/smufl/latest/tables/repeats.html

**Comment by musicEnfanthen** [comment]
Just for the record, some discussion about that sign in the Steinberg Forum (with links to lilypond approach): https://forums.steinberg.net/t/serpent-segno/127943

**Comment by lpugin** [comment]
We can add `segno` and `dblsegno` to match SMuFL.

**Comment by rettinghaus** [comment]
Solved with #1004
