### ISSUE TITLE
Nested meterSigGrps

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#970]
Currently it is not possible to nest `meterSigGrp` within `meterSigGrp`. 

Take this example from the _Fitzwilliam Virginal Book_ edition from 1899:

![image](https://user-images.githubusercontent.com/7693447/171677606-fcdca5e6-6f57-4615-b9a5-ebee7a386e4c.png)

One way to encode this (visually) would be

```xml
<meterSigGrp>
   <meterSig sym="cut" />
   <meterSigGrp enclose="brack">
      <meterSig sym="cut" />
      <meterSig count="3" form="num" />
   </meterSigGrp>
</meterSigGrp>
```

Making it part of `att.enclosingChars` would also allow us to place brackets around a complete `meterSigGrp`. 

Probably then the func attribute shouldn’t be necessary (or should allow a value like “unknown”). 

Although it works a bit different than `staffGrp` it seems to make sense to allow nesting of `meterSigGrp`s accordingly.

**Comment by lpugin** [comment]
I think this would be better encoded with a `<choice>` than nested `meterSigGrp`. But I am aware this is very later so we can keep it allowed for people who know what to do with it - Personally I do not.

**Comment by bwbohl** [comment]
@kepper pointed us to the content model of `meterSigGrp` and asked whether referencing `model.meterSigLike` would be more adequate than direct element references.

The current model in dev is:
https://github.com/music-encoding/music-encoding/blob/1404440bfc3345b09c891df1962b57856bc622e9/source/modules/MEI.cmn.xml#L1865-L1876

So, I guess something like:

```xml
<content>
    <rng:ref name="model.meterSigLike"/>
    <rng:oneOrMore>
        <rng:ref name="model.meterSigLike"/>
    </rng:oneOrMore>
</content>
```

Opinions?

**Comment by bwbohl** [comment]
When creating the schema from the above proposal @musicEnfanthen and I realised, that the current model also allows an empty `meterSigGrp`…

**Comment by musicEnfanthen** [comment]
We should think of a refactoring/simplification for v6.

**Comment by rettinghaus** [comment]
@bwbohl @musicEnfanthen How could `meterSigGrp` be empty? There no way this could be allowed.

**Comment by musicEnfanthen** [comment]
@rettinghaus Yes, this should not be allowed, but somehow it is. 

It seems that the class membership of `meterSigGrp` in `model.meterSigLike` (automatically?) adds an empty branch to the model?(When you remove the membership, the empty branch is gone. But that's of course no solution.)

**Comment by rettinghaus** [comment]
I would like to understand how you test this. I tried different approaches and an empty meterSigGrp won't validate for me.
If you're correct, basically everything would be allowed to be empty.

**Comment by rettinghaus** [comment]
@musicEnfanthen Investigated this further. Empty `meterSigGrp` doesn't validate against development versions (online and local) but does in fact validates against MEI 5.0. So actually this seems to be fixed already in the development version.

**Comment by lpugin** [comment]
As pointed [here](https://github.com/music-encoding/music-encoding/pull/1558#issuecomment-2513951771) empty `meterSigGrp` should remain valid with `@sameas` - at least.
