### ISSUE TITLE
Allowed values in att.transposition

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#972]
Maybe I'm missing something, but why are the allowed values for `@trans.diat` and `@trans.semi` decimal values? 
Corresponding features in other formats allow integers for those, which should be sufficient.

**Comment by ahankinson** [comment]
Probably to support quarter tones?

**Comment by rettinghaus** [comment]
I thought about this, but is there something like that in existence? And then, why isn't there a `@trans.quarter`? 
And why do we need `@trans.semi`, when it is possible to have `@trans.diat="1,500002"`. Does the latter then mean it's an slightly detuned instrument in e flat or d sharp?

**Comment by craigsapp** [comment]
There will be need for transposition of quarter tone pitches, but the transposition intervals themselves will not need quarter tone (for creating sounding/written orchestral scores/parts).

There is one exception that I can think of: a piece for two pianos tuned a quarter tone apart by Charles Ives that will have one part transposed by a quarter tone:   https://www.youtube.com/watch?v=wwj8mTiZi8o

**Comment by rettinghaus** [comment]
No, piano is not a transposing instrument. For that you have the tuning attributes available.

**Comment by craigsapp** [comment]
In this case it is a transposing instrument: all notes are a quarter-tone flat, but all notes are still equal tempered (creating a 24ET octave between the two pianos).  But if the tuning specification can handle this then that seems to mean that quarter tone transpositions can be ignored for this case.

**Comment by rettinghaus** [comment]
Just had a look at the score. Ives said "Piano I to be tuned a 1/4 tone higher".

**Comment by bwbohl** [comment]
Except for the "piano becoming a transposing instrument" (a point of view I can understand well), I think integer is the better choice. Not to be nitpicking but why is integer better than int?
@rettinghaus which tuning attributes are you referring to?

**Comment by rettinghaus** [comment]
@bwbohl `integer` was the nearest option to `decimal`. But then, why `int` and not `short`? 
Even `byte` should be pretty sufficient as it would allow transpositions up to ten and a half octave. But many users wouldn't probably know what "byte" means.
(See http://books.xmlschemata.org/relaxng/relax-CHP-8-SECT-1.html#relax-CHP-8-SECT-1.1.5)

I was referring to the attributes in #973.

**Comment by bwbohl** [comment]
thanks for the clarification and your argument for integer instead of a less known other datatype is a good one! So I'm completely convinced.
