### ISSUE TITLE
Some links in "Shared Concepts" documentation are broken

### ISSUE THREAD

**Issue by apacha** [music-encoding/music-encoding#979]
The three links generated by the `<ident type="class">...</ident>` element inside the Shared Concepts documentation don't work. The respective lines in the source code are:

https://github.com/music-encoding/music-encoding/blob/a81ac1d2a359242f871e5cac3f0160b40c3c7401/source/docs/02-shared.xml#L253
https://github.com/music-encoding/music-encoding/blob/a81ac1d2a359242f871e5cac3f0160b40c3c7401/source/docs/02-shared.xml#L688
https://github.com/music-encoding/music-encoding/blob/a81ac1d2a359242f871e5cac3f0160b40c3c7401/source/docs/02-shared.xml#L689

When clicking on any of the generated links (e.g., [model.graphicprimitiveLike](https://music-encoding.org/guidelines/v4/elements/model.graphicprimitivelike.html) in https://music-encoding.org/guidelines/v4/content/shared.html#usersymbolsOverview), I'm getting a 404 error. Not sure what the correct solution would be here. If I can help fixing it, I will gladly open a PR for that.

**Comment by bwbohl** [comment]
Many thanks for reporting this, will check on it and come back to you:wink:

**Comment by rettinghaus** [comment]
The code is ok, it's a problem in the static versions of the guidelines (v3/4).

**Comment by rettinghaus** [comment]
A fix is ready in https://github.com/music-encoding/guidelines/pull/205
