### ISSUE TITLE
Submodels are not shown in the guidelines

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#988]
I noticed that models that are part of another model are not shown in the latter, e.g., `meterSig` and `meterSigGrp` are grouped in the `model.meterSigLike` which is part of `model.eventLike`, yet both are not shown in `model.eventLike`. 
And top model classes like `model.layerPart` don't show any member elements (nor models).

**Comment by bwbohl** [comment]
Good catch, definitely something we should fix the get clearer information on dependencies!

**Comment by pe-ro** [comment]
There seems to be another (related?) problem with model and class membership.  Currently, only the compact view is available.  Clicking "by class" or "by module" does nothing.
